### ISSUE TITLE
Why "Don't enable virtual network service endpoints by default on all subnets."

### ISSUE THREAD

**Issue by cpinotossi** [MicrosoftDocs/cloud-adoption-framework#1004]
Could we get more details about the following recommendation "Don't enable virtual network service endpoints by default on all subnets.".
Would be great to understand why it would be a bad idea to turn on service endpoint by default?
thanks
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 188d9f77-7e00-31de-ff3b-9dcbd51a1363
* Version Independent ID: e109069b-918d-f33d-4d22-a75229e2a198
* Content: [Connectivity to Azure PaaS services - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/connectivity-to-azure-paas-services#design-recommendations)
* Content Source: [docs/ready/azure-best-practices/connectivity-to-azure-paas-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/connectivity-to-azure-paas-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi @cpinotossi

Sorry for the delay. 

The sentence “Don't enable virtual network service endpoints by default on all subnets.
”
The key world is “all”. It is recommended not to enable it in “all” subnets. 

It is recommended to keep as little as possible, you should enable only when it is  needed to be used.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
