### ISSUE TITLE
MCA buy link broken

### ISSUE THREAD

**Issue by bartlannoeye** [MicrosoftDocs/cloud-adoption-framework#1006]
The link at the top of the article to https://www.microsoft.com/licensing/how-to-buy/microsoft-customer-agreement no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b86c85ad-5136-d9f0-75d6-c5d085d81b7d
* Version Independent ID: b86c85ad-5136-d9f0-75d6-c5d085d81b7d
* Content: [Microsoft customer agreement and Azure Active Directory tenants - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/azure-billing-microsoft-customer-agreement)
* Content Source: [docs/ready/landing-zone/design-area/azure-billing-microsoft-customer-agreement.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/azure-billing-microsoft-customer-agreement.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by jtracey93** [comment]
Hey @bartlannoeye,

Seems to be working for me: 
![image](https://user-images.githubusercontent.com/41163455/202466013-b1b28021-02e8-4f51-bb8a-155299500e24.png)

**Comment by bartlannoeye** [comment]
Hey @jtracey93, I'm being redirected to: https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=lhvnll8AUEq1dIL1.0.3.0
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5115577/202466731-2b8be72f-b767-416a-802e-28c46752b3f1.png">

I wonder if this might be a regional problem (currently trying from Belgium).

**Comment by v-fearam** [comment]
Hi @bartlannoeye 
Sorry for the delay. 
It works today for me too. 
![image](https://user-images.githubusercontent.com/62260324/222690751-45c08098-d49e-4dcf-ba97-356224bc4b46.png)
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
