### ISSUE TITLE
Spove VNET Architecture using custom DNS

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/cloud-adoption-framework#1009]
Hi there,

Can more clarification please be give on this section. In the scanrio where you have both a private DNS resolver in the hub VNET and also Active Directory Domain servers in an Azure VNET, what custom DNS servers should be set on a spoke VNET that has domain joined virtual machines in it? Should it be the IP's of the ADDS\DNS servers or the IP address(es) of the outbound endpoints for the private DNS resolver.

If the DNS servers 10.100.2.4 and 10.100.2.5 aren't authoritative for customer's corporate domains (for example, Active Directory domain names), they should have conditional forwarders for the customer's corporate domains, pointing to the on-premises DNS Servers (172.16.1.10 and 172.16.1.11) or DNS servers deployed in Azure that are authoritative for such zones.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi @gerrynicol 

Sorry for the delay. 



The spoke Vms must use the DNS servers hosted in the hub VNet (10.100.2.4 and 10.100.2.5) as the primary and secondary DNS servers. (All Azure VNets must use them)


[Here information about how Private DNS Resolver works](https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-overview#how-does-it-work). Azure DNS Private Resolver is a new service that enables you to query Azure DNS private zones from an on-premises environment and vice versa without deploying VM based DNS servers. [Here how to resolve on-premises domains](https://learn.microsoft.com/en-us/azure/dns/private-resolver-hybrid-dns). It is done by configuring [DNS forwarding result sets](https://learn.microsoft.com/en-us/azure/dns/private-resolver-endpoints-rulesets#dns-forwarding-rulesets) and you will need to [link the forwarding ruleset to your VNET](https://learn.microsoft.com/en-us/azure/dns/private-resolver-endpoints-rulesets#ruleset-links)

Then,  the on-premises DNS Servers (172.16.1.10 and 172.16.1.11) will resolve customer's corporate domains.



I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
