### ISSUE TITLE
Azure Synapse Analytics Diagram

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#1010]
The diagram on this page seems quite out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3945ff8-e7dc-fcc5-d084-63e0e14827cc
* Version Independent ID: 8c68108e-07f3-07f4-91c8-ad7c58870ba9
* Content: [Azure Synapse Analytics solutions - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/analytics-solutions-overview)
* Content Source: [docs/migrate/azure-best-practices/analytics/analytics-solutions-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/analytics/analytics-solutions-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @v-hanki
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  This article has been deprecated.

**Comment by skabou** [comment]
#please-close
