### ISSUE TITLE
Guidance on DNS for VMs being replicated through Azure Migrate

### ISSUE THREAD

**Issue by Mahesh-MSFT** [MicrosoftDocs/cloud-adoption-framework#1011]
Azure Migrate has a "Test Migration" feature which allows customers to test their VMs which are being replicated to Azure. However, this functionality needs an isolated VNet. This limits the scenarios customers/partners can test. Common scenarios, such as some VMs are being replicated to Azure but some still running on-premises or replicated VMs needing to use Azure Firewall running in hub Vnet, can't be tested with isolated VNet. 

This limits customer/partner's ability to drive migrations at a faster speed. 

It appears that need for an isolated Vnet for testing is because DNS resolution in Azure and in on-premise environment is to be kept isolated. VMs which are being replicated to Azure from on-premise has same name, SID, etc. as the VM running on-premise. Putting them under DC replica in Azure which has connectivity to on-premises environment will result in conflicting DNS resolution due to another DC replica running from on-premises.

Guidance on running DNS services which allow replicated VMs to interact with on-premises as well as other services in Azure will help customer/partner handle this scenario effectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3947c417-5f06-7631-8ae5-002c9deff4fb
* Version Independent ID: 2a10b6e1-3b93-c2bc-6234-779b0d36695a
* Content: [DNS for on-premises and Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/dns-for-on-premises-and-azure-resources)
* Content Source: [docs/ready/azure-best-practices/dns-for-on-premises-and-azure-resources.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/dns-for-on-premises-and-azure-resources.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @sitarant
* Microsoft Alias: **sitarant**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62787 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
