### ISSUE TITLE
Phase 2: Onboarding Azure server management services

### ISSUE THREAD

**Issue by georgeollis** [MicrosoftDocs/cloud-adoption-framework#1015]
Should this document be updated to reflect new services like Azure Automanage? 

Current sections in the CAF: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-server-management/onboarding-overview 

The article is all about onboarding services to Azure server management services. But perhaps having a section on Automanage would help our customers? It would help onboarding at scale. Especially this section: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-server-management/onboard-at-scale 

- Intelligently onboard virtual machines to select best practices Azure services
- Automatically configures each service per Azure best practices
- Supports customization of best practice services
- Monitors for drift and corrects for it when detected
- Provides a simple experience (point, click, set, forget)

![image](https://user-images.githubusercontent.com/76496924/205037239-00aae83c-7cf8-4522-ad94-46592de78e45.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0749b85-6ecc-aa33-21e9-03cb3b76e2a2
* Version Independent ID: 53e94ec4-ef8d-eee7-b104-2ffa771be59c
* Content: [Onboard Azure server management services - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-server-management/onboarding-overview)
* Content Source: [docs/manage/azure-server-management/onboarding-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/manage/azure-server-management/onboarding-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
#please-close
