### ISSUE TITLE
Key vault in Identity Subscription

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/cloud-adoption-framework#1016]
Can you please provide use cases for the key vault in the Identiy Subscription. Apart from possibly storing secrets for ADDS servers, what other types of scenario could it be used in a Platform Landing Zone?
Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/landing-zone/#azure-landing-zone-conceptual-architecture)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by SteveBurkettNZ** [comment]
CMK encryption keys for the VM disks?

**Comment by stephen-sumner** [comment]
@gerrynicol - I'm going to close this issue. Please let us know if you have any questions. We really appreciate your feedback!
