### ISSUE TITLE
Gen2 VPN GWs support up to 10 Gbps

### ISSUE THREAD

**Issue by zeinab-mk** [MicrosoftDocs/cloud-adoption-framework#102]
Please update the decision matrix based on current VPN GWs capabilities: 
https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63badde4-b985-a969-fc40-140da14ef383
* Version Independent ID: 8f5cf934-82ca-8f8a-fcbd-801bacdfa583
* Content: [Review your network options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/networking-options#feedback)
* Content Source: [docs/ready/considerations/networking-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/networking-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#176402

**Comment by JanetCThomas** [comment]
If we send you the graphic would you mind updating the visio source file?

**Comment by JanetCThomas** [comment]
@zeinab-mk If we send you the graphic would you mind updating the visio source file?

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
