### ISSUE TITLE
PrivateLink Integration at scale only works for new Endpoints

### ISSUE THREAD

**Issue by Tbohunek** [MicrosoftDocs/cloud-adoption-framework#1020]
Hi, this policy only works for **new** Private Endpoints.
If _somebody_ goes and (accidentally or intentionally) deletes the Endpoint's DNS config, the policy still sees the Endpoint as compliant and doesn't trigger redeployment of the DNS config.
What am I missing here?

![image](https://user-images.githubusercontent.com/16520646/206134116-61f8a277-9567-4381-b7ac-7253d1ef298e.png)

![image](https://user-images.githubusercontent.com/16520646/206133543-f32ce36f-2f00-453b-8da3-41d5563a4f84.png)

The Policy validates `"type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",`, however that isn't visible as a resource in the Portal, not even with `az resource list` and `get-azresource`. I believe it represents the "DNS configuration" Settings option in portal, but apparently the hidden resource isn't properly deleted when the DNS config is deleted.

What I noticed in the Endpoint's properties is that when DNS config is created, the following property is emptied, and when the DNS config is deleted, the property is filled again.

```
{
  "customDnsConfigs": [
    {
      "fqdn": "dz106tcmk.blob.core.windows.net",
      "ipAddresses": [
        "10.104.4.11"
      ]
    }
  ],
  ...
  "type": "Microsoft.Network/privateEndpoints"
}
```

Perhaps an `existenceCondition` is required to keep an eye on this `customDnsConfigs`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **martinek**

**Comment by cveld** [comment]
Exactly my idea! I have made a screenshot from Azure Resource Explorer where you can see that the private dns zone group is still there but empty after you have clicked the delete button in Azure Portal.

![image](https://user-images.githubusercontent.com/6196260/216571030-40b531cc-2a87-4bf6-8b6c-5fad0de9fa4c.png)

**Comment by v-fearam** [comment]
Hi @Tbohunek 

Sorry for the delay. 


This channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.


Sorry, but I’m not able to figure out why it was not working in your environment.

Here some documentation about [deployifnotexists policy](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effects#deployifnotexists). It seems that something is not correctly deleted and never accomplish the condition. Please, also take into account that the policy execution is not immediate, [step 8 says](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#application-owner-experience): “After a few minutes, the DeployIfNotExists policy triggers”


I recommend leveraging the support options available in the Azure DevOps portal if you are still facing this issue.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
