### ISSUE TITLE
Abbreviation for Update Management Center

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/cloud-adoption-framework#1022]
There is no abbreviation for [Update Management Center](https://learn.microsoft.com/en-us/azure/update-center/overview).

May I suggest `umc`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@o-l-a-v : Thanks for the suggestion. I've never used the update management center, but I currently don't see where you would need to name an instance of it? Can you clarify your request?

**Comment by o-l-a-v** [comment]
> @o-l-a-v : Thanks for the suggestion. I've never used the update management center, but I currently don't see where you would need to name an instance of it? Can you clarify your request?

I probably done goofed again, like I did with Sentinel. I haven't used it either. If one can't choose the name of an instance of it, theres no point with an abbrevation.

**Comment by stephen-sumner** [comment]
@o-l-a-v - All good! Thanks for the input as always! Have a good one!
