### ISSUE TITLE
No abbreviation for Azure Sentinel

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/cloud-adoption-framework#1023]
There is no abbrevation for Azure Sentinel.

May I suggest `sent`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@o-l-a-v : Thank you for the feedback! To my knowledge, there's no way to "name" an instance of Sentinel. You add it to a Log Analytics workspace, and there's an abbreviation for the Log Analytics Workspace on this page. 

Is there something I'm missing? Could you be more specific about what you'd like to use the abbreviation for?

**Comment by o-l-a-v** [comment]
You're right, I done goofed. Tried planning all names before starting deployments, long time since I added Sentinel.

**Comment by stephen-sumner** [comment]
@o-l-a-v. I appreciate your input. Just wanted to get it right! I'll close this one. Have a great day!
