### ISSUE TITLE
There is no abbreviation for alert rules

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/cloud-adoption-framework#1024]
There is no abbreviation for Alert Rules.

This Icon in the Azure portal:
![Alert rules](https://user-images.githubusercontent.com/6450056/206443180-3dc3809a-a2b9-4437-be41-2ff9e58c371c.svg)

May I suggest `aru`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@o-l-a-v - Thank you for another great suggestion! We are going to take this one into consideration too. At the moment, I'm not seeing the need for this abbreviation. In the portal, it's always very clear when you're looking at an alert rule. For my experience, it would be more useful to give a descriptive name to the rule, rather than an abbreviation.

**Comment by o-l-a-v** [comment]
@stephen-sumner 

The Azure portal ain't the only place to view resources though. There is also the ARM API (and Az PowerShell), or resources.azure.com for instance.

**Comment by stephen-sumner** [comment]
@o-l-a-v : great point! Sorry for the overly simplistic perspective. Even more reason for us to take a look at including this abbreviation. Thank you again! Happy New Year!
