### ISSUE TITLE
Should a "regional hub" be considered?

### ISSUE THREAD

**Issue by waynehoggett** [MicrosoftDocs/cloud-adoption-framework#1025]
Just a query around domain controllers and workloads deployed to multiple regions using Hub and Spoke. The documentation states:

"Establish Virtual Network Peering back to the hub Virtual Network in the connectivity subscription"

If the company utilizes two regions, both with domain controllers, should they consider having a regional hub to reduce latency between domain controllers and the workloads in each region and peer the regional hubs with each other? Or if they have this requirement, should they move to virtual WAN?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72345a49-0a6f-78aa-7419-94c733f99a51
* Version Independent ID: 5ddffa14-9feb-59da-fa1a-939113bc3a02
* Content: [Azure landing zone frequently asked questions (FAQ) - Cloud Adoption Framework](https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/enterprise-scale/faq#feedback)
* Content Source: [docs/ready/enterprise-scale/faq.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/enterprise-scale/faq.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **martinek**

**Comment by jtracey93** [comment]
Hi @waynehoggett,

Great question/call out. 

I think this is a simple fix by just adding the phrase "...newly created regional hub..." in that statement. Do you want to submit a PR for that and get your face on the contributors list? 

If not, thats cool let me know and I'll sort 👍

**Comment by waynehoggett** [comment]
Thanks @jtracey93, I gave it a go here: https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/1026

**Comment by skabou** [comment]
This appears to have been resolved. If you are still experiencing an issue, please re-open with additional information.
