### ISSUE TITLE
No abbreviation for `On-premises Data Gateway`

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/cloud-adoption-framework#1028]
For following doc:

* https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

There is currently no abbreviation for `On-premises Data Gateway`.

May I suggest `odgw`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@o-l-a-v -- Thanks for the suggestion! We will take this into consideration as we update our guidance. Thanks again!
