### ISSUE TITLE
Incorrect table values

### ISSUE THREAD

**Issue by hazaq** [MicrosoftDocs/cloud-adoption-framework#1030]
[Enter feedback here]
Please review table under "Determine identity integration requirements" I think the 'Yes' value is incorrectly placed for line item 4: "Do your workloads depend on legacy authentication mechanisms, such as Kerberos or NTLM?"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d53df27-59c8-359c-0976-e586d9374d64
* Version Independent ID: 1692111e-37ee-bb7f-5b5c-4c3a1acec7fe
* Content: [Identity decision guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/identity/)
* Content Source: [docs/decision-guides/identity/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/decision-guides/identity/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by hallihan** [comment]
@hazaq Can you provide more context for why AD FS isn't appropriate for this scenario?

**Comment by hallihan** [comment]
Feel free to reopen is you are able to provide more context. #please-close
