### ISSUE TITLE
Title in A1 <> sheet name in Naming and tagging conventions tracking template

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/cloud-adoption-framework#1032]
Excel sheet **[Naming and tagging conventions tracking template](https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/naming-and-tagging-conventions-tracking-template.xlsx)** accidentally has title **Tagging conventions** in cell A1 in sheet **Naming conventions**. Please change to **Naming conventions**.

Regards, inge

![image](https://user-images.githubusercontent.com/40343254/208885309-b0709b58-0293-4727-879c-931c5db7d7b8.png)

**Comment by stephen-sumner** [comment]
@ingebeumer - Great catch! Thank you for your input. I have a PR to make that update.

**Comment by stephen-sumner** [comment]
#please-close
