### ISSUE TITLE
Naming - Simple changes to enhance readability

### ISSUE THREAD

**Issue by mikerains** [MicrosoftDocs/cloud-adoption-framework#1033]
1. Padding
The explanation of padding is important, however it assumes the reader understands what 'padding' is and why a number is in the name.  
 - The Naming Components do not indicate a number component, so explain why you might need a number component
 - Understanding that padding means formatting the numbers to a set number of digits that accommodates the total number of resources with the same name, and using zeros to fill out the digits. 
 - An example

2. Example names
Some of the examples use dashes to separate name components, some do not.  Some have number component, some not.
 - Explain why a number component is not used in examples that don't have one
 - Explain why no dashes in some examples.  Is this example here showing that some businesses have an existing convention?   Isn't there downside to readability and parseability that should be explained here?

Thanks, hope that makes sense.  Your documentation is great, I don't mean to complain.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@mikerains - Thank you for your feedback. I know it's been over a year. 

On padding, it's an optional component. There's a lengthy note on padding in this article that basically states to do what's best for your org. You might add a number component to multiples of the same resource (e.g. VMs) or as an org id for global resources that need to be globally unique. 

On dashes, some resources don't allow you to add dashes (such as Azure Storage).

**Comment by stephen-sumner** [comment]
#please-close
