### ISSUE TITLE
Error in private-endpoint approval script for SQL Server

### ISSUE THREAD

**Issue by janerikohmanKnowit** [MicrosoftDocs/cloud-adoption-framework#1036]
Hi
the code under "Option 2: Run the following scripts in Azure Cloud Shell in Bash mode to approve all access requests to the required private endpoints at once." has one error - the code to approve the SQL Server private endpoint should be changed from **--type Microsoft.Storage/storageAccounts** => **--type Microsoft.Sql/servers** as in the change below:

 SQL Database managed private endpoint approval
resourceGroupName=$(az group list -o tsv  --query "[?contains(@.name, '-dev-dp001')==\`true\`].name")
sqlServerName=$(az sql server list -g $resourceGroupName -o tsv  --query "[?contains(@.name, 'sqlserver001')==\`true\`].name")
endPointConnectionName=$(az network private-endpoint-connection list -g $resourceGroupName -n $sqlServerName --type Microsoft.Sql/servers -o tsv --query "[?contains(@.properties.privateLinkServiceConnectionState.status, 'Pending')==\`true\`].name")
az network private-endpoint-connection approve -g $resourceGroupName -n $endPointConnectionName --resource-name $sqlServerName **--type Microsoft.Storage/storageAccounts** --description "Approved"

to:

 SQL Database managed private endpoint approval
resourceGroupName=$(az group list -o tsv  --query "[?contains(@.name, '-dev-dp001')==\`true\`].name")
sqlServerName=$(az sql server list -g $resourceGroupName -o tsv  --query "[?contains(@.name, 'sqlserver001')==\`true\`].name")
endPointConnectionName=$(az network private-endpoint-connection list -g $resourceGroupName -n $sqlServerName --type Microsoft.Sql/servers -o tsv --query "[?contains(@.properties.privateLinkServiceConnectionState.status, 'Pending')==\`true\`].name")
az network private-endpoint-connection approve -g $resourceGroupName -n $endPointConnectionName --resource-name $sqlServerName **--type Microsoft.Sql/servers**--description "Approved"

Best Regards,
Jan-Erik

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d08426fe-400d-60f6-7c0c-d245adb64a31
* Version Independent ID: d08426fe-400d-60f6-7c0c-d245adb64a31
* Content: [Tutorial - Set up a data product batch - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/tutorials/tutorial-set-up-data-product-batch)
* Content Source: [docs/scenarios/cloud-scale-analytics/tutorials/tutorial-set-up-data-product-batch.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/tutorials/tutorial-set-up-data-product-batch.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @abdale
* Microsoft Alias: **hamoodaleem**

**Comment by v-fearam** [comment]
#please-close
