### ISSUE TITLE
Cloud-build

### ISSUE THREAD

**Issue by 16CentAstrology** [MicrosoftDocs/cloud-adoption-framework#1037]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06f7abf1-fbaf-82dc-16a7-0e977675f624
* Version Independent ID: 111a77e0-d565-355f-3ee0-425f61912e75
* Content: [Azure enterprise scaffold is now the Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/resources/azure-scaffold?source=recommendations)
* Content Source: [docs/resources/azure-scaffold.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/resources/azure-scaffold.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @rdendtler
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
@16CentAstrology - can you please elaborate on what feedback you're providing?
