### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by Aknc34** [MicrosoftDocs/cloud-adoption-framework#1038]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
@Aknc34 -- please reopen with more information if there is something we can help you with.  As this issue is now, there isn't any information in here to act on.
