### ISSUE TITLE
Local vs Global?

### ISSUE THREAD

**Issue by SaschaProdware** [MicrosoftDocs/cloud-adoption-framework#1041]
What is the difference between Local and Global Azure Clouds
https://dynamics.microsoft.com/de-de/availability-reports/georeport/
Are there any restrictions regarding Power BI, Synapse, Dynamics (FO, HR, CE, BC).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b660c4be-7ac5-4d77-06e4-22fae18724ba
* Version Independent ID: b5db2093-d8dc-3a60-d1ca-553f085aa00e
* Content: [Azure regions decision guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/multiple-regions)
* Content Source: [docs/migrate/azure-best-practices/multiple-regions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/multiple-regions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @doodlemania2
* Microsoft Alias: **dermar**

**Comment by jocontr** [comment]
@SaschaProdware I would recommend reviewing:

- https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/
