### ISSUE TITLE
Adding Best Practices for Azure self-hosted deployment agents in LZ

### ISSUE THREAD

**Issue by Nicwalle** [MicrosoftDocs/cloud-adoption-framework#1042]
As many LZ architectures involve private services, there is often a need to deploy self-hosted agents (Azure DevOps) to deploy applications privately in the Azure LZ. Those agents can be containerized or VMs, not really to be discussed here but the "where" to put those agents could be a recommendation or at least a discussion to add here. 

Should those deployment agents be put in the app subscription, in a different subscription or somewhere else? This design discussion often occurs and recommendations would be valuable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80372ed1-947b-64e4-5e6f-5a3eee9bf03d
* Version Independent ID: 80372ed1-947b-64e4-5e6f-5a3eee9bf03d
* Content: [DevOps security considerations overview - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/security-considerations-overview)
* Content Source: [docs/ready/considerations/security-considerations-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/security-considerations-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @SimonaKovatcheva
* Microsoft Alias: **sikovatc**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62763 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
