### ISSUE TITLE
missing resource abbreviation for Web PubSub Service

### ISSUE THREAD

**Issue by rybal06** [MicrosoftDocs/cloud-adoption-framework#1049]
Is there a preferred Microsoft resource abbreviation for the Web PubSub Service? If so, could it be added to the table of resource abbreviations?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by rybal06** [comment]
It looks like at least one team at Microsoft has adopted this pattern:

```json
web pub sub service = ps
web pub sub service hub = pshub
```

Source: <https://github.com/aztfmod/terraform-provider-azurecaf/blob/main/resourceDefinition.json#L3659>

**Comment by stephen-sumner** [comment]
@rybal06 - Thank you for your feedback! It's much appreciated. This is potentially a good candidate for inclusion. Let me look into this further and get back with you. 

Thank you!

**Comment by stephen-sumner** [comment]
@rybal06 - We added an abbreviation for Azure WebPubSub: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#developer-tools

Thank you for your suggestion!
