### ISSUE TITLE
Add the example to use AzGovViz - Azure Governance Visualizer

### ISSUE THREAD

**Issue by rkuehfus** [MicrosoftDocs/cloud-adoption-framework#1055]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Include this tool for visualizing your policy - AzGovViz - Azure Governance Visualizer

link - https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47afee0a-1492-66b6-77ab-b8530e08eb9e
* Version Independent ID: 47afee0a-1492-66b6-77ab-b8530e08eb9e
* Content: [Policy visibility in the deployment process - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/deployment-acceleration/policy-visibility-in-deployment?branch=pr-en-us-3941)
* Content Source: [docs/govern/deployment-acceleration/policy-visibility-in-deployment.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/deployment-acceleration/policy-visibility-in-deployment.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
@rkuehfus it looks like this feedback was provided from an internal review branch.  If this request is still valid, contact me on Teams and I can provide next steps.  #please-close
