### ISSUE TITLE
External identify access

### ISSUE THREAD

**Issue by rkuehfus** [MicrosoftDocs/cloud-adoption-framework#1056]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Should we also provide guidance on partner access guidance? Guest access or the use of Lighthouse for example.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9a321ba-e040-10a2-e3cd-ac6681f517aa
* Version Independent ID: 0f80273a-f2d7-8cda-2339-dccbeac459a3
* Content: [Identity Baseline discipline overview - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/identity-baseline/?branch=pr-en-us-3960)
* Content Source: [docs/govern/identity-baseline/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/identity-baseline/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
@rkuehfus Looks like this feedback was related to a review branch that has since been merged. Please reach out to Rob on Teams if this needs to be added to the article. #please-close
