### ISSUE TITLE
Missing abbreviation for Communications and Email Communications Service

### ISSUE THREAD

**Issue by dsdilpreet** [MicrosoftDocs/cloud-adoption-framework#1059]
Hi team,

Is there any recommended abbreviation for [Communications and Email Communications Service](https://learn.microsoft.com/en-us/azure/communication-services/concepts/email/email-overview)?

Cheers for having a look 😄 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@dsdilpreet thank you for the question! I'm going to review this suggestion and get back to you ASAP. Thanks so much!

**Comment by dsdilpreet** [comment]
@stephen-sumner Hi, wondering if you have had a chance to review this?

**Comment by stephen-sumner** [comment]
@dsdilpreet - Thank you for your patience. We're still reviewing. My apologies for the delay.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/4353

**Comment by dsdilpreet** [comment]
Thank you @stephen-sumner , I think the pr maybe private? I am seeing 404

**Comment by stephen-sumner** [comment]
@dsdilpreet - you should soon see an abbreviation for Azure Communication Services come through on the abbreviation page as "acs". 

This is the abbreviation the Azure Communication Services documentation uses in the [scripts](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/create-communication-resource?tabs=windows&pivots=platform-azp#access-your-connection-strings-and-service-endpoints-using-azure-cli).

We have decided to only add an abbreviation for the overarching product, Azure Communication Services, and not for any subservice, such as Email Communication Service.

Thanks for your input!

**Comment by dsdilpreet** [comment]
@stephen-sumner - sounds good, thanks again!
