### ISSUE TITLE
Abbreviation for Service Fabric Managed Clusters

### ISSUE THREAD

**Issue by isakengstrom** [MicrosoftDocs/cloud-adoption-framework#1061]
I'm looking for an abbreviation for a Service Fabric Manged Cluster. However, there are only abbreviations for other managed resources, such as managed AKS clusters, or abbreviations for non-managed SF clusters. Is there a consensus on how to abbreviate a managed SF cluster, that can be added to the list? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations?source=recommendations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@isakengstrom - Thank you so much for you feedback. We've added this to the page. You should see an update shortly!
