### ISSUE TITLE
More perscriptive guidance on Resource orginization of Arc resources

### ISSUE THREAD

**Issue by reduards** [MicrosoftDocs/cloud-adoption-framework#1063]
Hello,

I would like to see more perscriptive guidance on Arc enabled resources. Its intersting since the use case is usually different for Azure Arc resources, where they usually act as management scope for patch management and defender etc.

Some examples:

- One or many subscriptions for your Azure Arc resources
- Under what management scope?
- Centrally managed Azure Arc resources vs Decentralized structure

Best Regards,
Rasmus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f020f-ed24-bba6-e7dc-96b6e1f2664d
* Version Independent ID: 0b3f020f-ed24-bba6-e7dc-96b6e1f2664d
* Content: [Resource organization for Azure Arc-enabled servers - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/hybrid/arc-enabled-servers/eslz-resource-organization)
* Content Source: [docs/scenarios/hybrid/arc-enabled-servers/eslz-resource-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/hybrid/arc-enabled-servers/eslz-resource-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @lanicolas
* Microsoft Alias: **matgri**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 62732 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
