### ISSUE TITLE
Private DNS Resolver

### ISSUE THREAD

**Issue by faheemgani** [MicrosoftDocs/cloud-adoption-framework#1069]
Hi,

Just noticed that there isn't a resource abbreviation for [DNS Private Resolver](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/networking/azure-dns-private-resolver) yet. Is this something you'll be adding to the document soon?

Thanks

**Comment by v-fearam** [comment]
It would be great if you could add a link to the documentation you are taking a look? This would help us to understand. Thanks!!

**Comment by v-fearam** [comment]
Closing because the document where the improvement was proposed it is not identified. 
#please-close

**Comment by ckittel** [comment]
DNS Private Resolver is now on the abbreviations list - I added it a few weeks ago - thanks for pointing it out!

cc: @v-fearam
