### ISSUE TITLE
The navigation panel of this page is incorrect

### ISSUE THREAD

**Issue by ToMakeSense** [MicrosoftDocs/cloud-adoption-framework#107]
This page is one of the sub theme of [Architectural decision guides](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/), however it doesn't have a placeholder in the navigation panel. and navigation panel of this page is incorrect if I open this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5666e96c-01c4-bb6d-f27c-6d98c4a1435b
* Version Independent ID: 92408d48-1fd0-822a-73cf-7aa9250e1482
* Content: [Regions decision guide - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/regions/#feedback)
* Content Source: [docs/decision-guides/regions/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/decision-guides/regions/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @doodlemania2
* Microsoft Alias: **dermar**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#180238

**Comment by JanetCThomas** [comment]
This has been fixed.

**Comment by ToMakeSense** [comment]
@JanetCThomas @alexbuckgit  could you explain it a lit bit, I can't found the documentation with link(https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/regions/) any more(404).

**Comment by ToMakeSense** [comment]
Update, I Got it, the article [docs/decision-guides/regions/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/decision-guides/regions/index.md) is moved to [docs/migrate/azure-best-practices/multiple-regions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/multiple-regions.md) in commit [TOC updates and link fixes (#300)](https://github.com/MicrosoftDocs/cloud-adoption-framework/commit/a008a8f0b0b52eaaef9f0d93e38f518d4fd4f86e#diff-c7a16b972df9dff051fec090949210ec). thanks!
![image](https://user-images.githubusercontent.com/6244148/77731710-66035880-703e-11ea-9fd6-2c6ef988a9e4.png)
