### ISSUE TITLE
Include Private Endpoints

### ISSUE THREAD

**Issue by JohnPoetzinger** [MicrosoftDocs/cloud-adoption-framework#1074]
Please Include Private Endpoints in the Landing Zone Subscription next to VNets UDRs and NSGs as they are owned by application owners and not in the connectivity subscription. This is currently unclear in our docs.

Jopoetzi@Microsoft.com for any internal questions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4076bdcf-f7d9-f0e8-7bae-af95c89f4e29
* Version Independent ID: e4fbc734-a00c-b06b-f5e9-620e6d42af0c
* Content: [Traditional Azure networking topology - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology)
* Content Source: [docs/ready/azure-best-practices/traditional-azure-networking-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/traditional-azure-networking-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @sitarant
* Microsoft Alias: **sitarant**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 70539 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
