### ISSUE TITLE
Dealing with global uniqueness

### ISSUE THREAD

**Issue by hecflores** [MicrosoftDocs/cloud-adoption-framework#108]
The documentation does not address global uniqueness. In the case of storage accounts or key vaults, it simply suggest the resource type prefix, name, and instance number... I have seen organization use there org prefix and/or product prefix in the name of the resources to address this. What is the best practice for addressing these scenarios 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#feedback)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#181415

**Comment by sgryphon** [comment]
This is definitely needed for the naming standard to be followed it needs to include a recommendation, for names with global scope, to include an organisation (or subscription) abbreviation to make items unique.

e.g. It would not be unreasonable to expect more than one organisation to have an app called `navigator` or `accountlookup`, which would make `app-navigator-prod-001.azurewebsites.net` and `app-accountlookup-dev-001.azurewebsites.net` not unique in the global scope.

If the intention was for subsequent people to use a different numeric suffix that would be weird and inconsistent.

Adding a unique infix for the organisation (OrgId) would provide a better chance of uniqueness, but is only required for global items.

By specifying it in the standards, it would only need to be specified for the relevant items, and not clutter up others.

Example: For a **Web App** the standard naming (global scope) should be:

_app-&lt;app name>-&lt;org id>-&lt;environment>-&lt;###>.azurewebsites.net_

- `app-navigator-fabr-prod-001.azurewebsites.net`
- `app-accountlookup-adwk-dev-001.azurewebsites.net`

**Comment by sgryphon** [comment]
In particular I personally find this an issue with sample applications / demos, where it would be good to use the naming standards, but that ends up with collisions naming the global resources. 

The solution I have is to basically use the naming standards except add a unique identifier based on the subscription (only for global resources).

This means if there was an example deployment script for Fabrikam to create a navigator service, scripts can be written to use a hex number with the first four characters of the subscription as the Org Id, e.g.

- `app-navigator-0xacc5-prod-001.azurewebsites.net`

This means the same script can be run for every user, with limited chance of collision. (Ensuring you always provide a `remove-infrastructure.ps1` script along with the `deploy-infrastructure.ps1` script is also useful to help users clean up afterwards.)

Choosing to place the Org Id after the app name I think is useful; you want the unique (withing your org) app name earlier, to be easily distinguishable (and just after the resource type); and you want the environment and instance numbers at the end for consistency.

So, inserting in the middle I think makes the most sense (effectively as a suffix of the app name).

**Comment by skabou** [comment]
#please-close
