### ISSUE TITLE
Are ASG/NSG Blocking DNS and Active Directory Communication?

### ISSUE THREAD

**Issue by gfaleiro** [MicrosoftDocs/cloud-adoption-framework#1080]
[ASGs groups some servers and link them to NSG rules are allowing 80, 443 and 1433 ports. how Active Directory will provide DNS, GPO, KDC... since there is no explicit rule is declared at that NSG rule? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097a8a15-21c5-619d-05f6-8722da3c0d7c
* Version Independent ID: 7cc4e4f3-fa5d-dd6c-5462-7f587e708d5e
* Content: [Deploy a migration infrastructure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure?source=docs)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @deltadan
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
Hi @gfaleiro

Sorry for the delay. 


The NSG present is not exhaustive. 

The document is defining [Custom DNS](https://learn.microsoft.com/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure?source=docs#set-up-dns)

 NSGs act as firewalls for your DNS resolver endpoints. You should modify or override your NSG security rules to allow access for UDP Port 53 (and optionally TCP Port 53) to your DNS listener endpoints. Once custom DNS servers are set on a network, then the traffic through port 53 will bypass the NSG's of the subnet.

[Name resolution for resources in Azure virtual networks](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances)


I will close the ticket, but feel free to open a new one if you still have concerns.

#please-close
