### ISSUE TITLE
Two perimeter networks?

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/cloud-adoption-framework#1081]
I'm confused by the text and diagram on this page.

At the link https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/perimeter-networks#perimeter-network-topology, the document says "The following diagram shows an example [hub and spoke network](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology) with __two perimeter networks__ that enforce access to the internet and to an on-premises network."

But the diagram at https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/_images/azure-best-practices/network-high-level-perimeter-networks.png only has **one** perimeter network as far as can see.

Can you help / reconcile?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d40b10fc-3c76-0f45-6139-5e406d23cbec
* Version Independent ID: 3a4eb3db-94be-72ed-922b-48b4d87903f5
* Content: [Perimeter networks - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/perimeter-networks)
* Content Source: [docs/ready/azure-best-practices/perimeter-networks.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/perimeter-networks.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tracsman
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
Hi @larryclaman

Sorry for the delay. 

I think this image will help to understand the two-perimeter concept

![image](https://user-images.githubusercontent.com/62260324/234680810-15a7b279-4212-4d32-9877-15100d3fc0e7.png)


It was taken from [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/resources/networking-vdc#components)

That is why the paragraph below the image start with “Both perimeter networks are in the DMZ hub”


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by larryclaman** [comment]
Hi @v-fearam.  Respectfully, I think this article still needs clarification.

I do see two perimeter networks referenced in the diagram you referenced; however, that diagram is NOT in the article at all.  So how is a reader supposed to understand that is what you are referring to?
Suggest you add this diagram to the article.
