### ISSUE TITLE
there should be no difference in policies applied between "dev/test/production"?

### ISSUE THREAD

**Issue by sujitks** [MicrosoftDocs/cloud-adoption-framework#1083]
[Enter feedback here]
Regarding this statement 'To summarize, there should be no difference in policies applied between "dev/test/production" environments if you develop and build them to production standard from the start. There's little value in changing the configuration of a workload as it's promoted through the different environments. Constant change results in a poor development experience for landing zone users and owners.'

Are you suggesting that policies should be just deployed once for all the environments? 
Are you also implying the continuously changing in the configuration will not give any value?

We have experience a lots of changes in the policies due to continuous changes in the underlying infrastructure of Azure. Azure resources and management of these resources keeps changing regularly for further improvement and in some cases, some of the policy could be out of sync. For example, there are changes in the diagnostics settings for storage account. For example new resources could become available. There are so many reasons where policies would needs redeployment and IMHO **must** be tested before rolling out to other environments where outage could impact more.

Another example, you can put a naming policy to enforce standard naming convention, however some of the internal resources which gets deployed along with other resources might not known and it would start failing. Just troubleshooting of these errors takes time which could be avoided by engineering process to test policy in lower environment before promoting. 

Another suggestion in this article is to assign policies at subscription level, why don't you assign it at management group level and leave the management/maintenance to central team. Policies are usually consistent in enterprise and managed by the central team. Subscription owner should not be able to change/update policies assignments without appropriate approval/authorisation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72345a49-0a6f-78aa-7419-94c733f99a51
* Version Independent ID: 5ddffa14-9feb-59da-fa1a-939113bc3a02
* Content: [Azure landing zone frequently asked questions (FAQ) - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-handle-devtestproduction-workload-landing-zones-in-azure-landing-zone-architecture)
* Content Source: [docs/ready/enterprise-scale/faq.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/enterprise-scale/faq.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 70533 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
