### ISSUE TITLE
Why organization is not part of global resource names?

### ISSUE THREAD

**Issue by salmipa** [MicrosoftDocs/cloud-adoption-framework#1090]
[Enter feedback here]
Since the name of the global resource names must be, as the name implies, global, I don't understand why the examples (as well as Azure Name Tool) don't use organization as part of the name. Could you please tell me what I'm missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **ssumner**

**Comment by jamasten** [comment]
Hi @salmipa. I know internally we had discussed this exact topic for the Azure Naming Tool but somehow wasn't included in our backlog. We'll be sure to include the org component by default in any global resources in an upcoming release.  However, this is an easy fix in the Azure Naming Tool; remove the excluded or optional check boxes for the org component on any global resource types. There are 42 global resources so it may be easier to update JSON file instead but still, an easy fix. Thank you for your feedback!

**Comment by salmipa** [comment]
Hi,

And thanks for your response.

I already fixed some of these and added new resource types (like Azure
Container Apps) by editing the JSON file. That (ca and cae) would also be
on my wish list for the upcoming versions.

BR, Paci

su 12. maalisk. 2023 klo 23.56 Jason Masten ***@***.***)
kirjoitti:
