### ISSUE TITLE
Containability as a responsible AI principal.

### ISSUE THREAD

**Issue by andyg2** [MicrosoftDocs/cloud-adoption-framework#1094]
I recommend adding the containability to the implementation guidelines. In a decade or two, powerful AI will be ubiquitous and we don't want reward functions decentralizing for efficiency, control needs to be a top priority.

## Responsible AI principles

As you implement AI solutions, consider the following principles in your solution:

 - Fairness: AI systems should treat all people fairly.
 - Reliability and safety: AI systems should perform reliably and safely.
 - Privacy and security: AI systems should be secure and respect privacy.
 - Inclusiveness: AI systems should empower everyone and engage people.
 - Transparency: AI systems should be understandable.
 - Accountability: People should be accountable for AI systems.
 - `Containability: AI resources should be limited to the essential.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f90f6cea-98d6-d360-0f15-f9843d54a434
* Version Independent ID: 3c03d1a4-4cba-189d-2920-eb05d67a89b8
* Content: [Responsible AI - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/responsible-ai?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fbread%2Ftoc.json)
* Content Source: [docs/strategy/responsible-ai.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/responsible-ai.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @v-hanki
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
@jasallen

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 72725 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
