### ISSUE TITLE
Please provide some example ARM templates on how to implement the naming standards in this document in a scaleable way.

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/cloud-adoption-framework#11]
Please provide some example ARM templates on how to implement the naming standards in this document in a scaleable way.

**Comment by BrianBlanchard** [comment]
The following Azure Policy can provide the desired enforcement. https://docs.microsoft.com/en-us/azure/governance/policy/samples/enforce-like-pattern

To be added to the article in a coming release.
