### ISSUE TITLE
Why padded numbers are part of naming convention?

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/cloud-adoption-framework#110]
What is a reason behind advising customers to pad numbers with 00s for resource numbers? What exactly it accomplishes except complicates any sort of scripts which usually can just rely on enumeration to iterate through objects `$++` but makes it more complicated with padding added. So wondering what is being accomplished with padding. And why exactly there are 2 padding zeros and not 2 or 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#184260

**Comment by nguyenlamlll** [comment]
Personally, I support that we don't use padding. Scripting will be much easier without padding 0's.

**Comment by BrianBlanchard** [comment]
Added a note to reflect the intent of padding and the customer decision. MSFT FTEs can preview the change at https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging?branch=pr-en-us-849

As a preview for all other audiences see the below note: 
The example names above and elsewhere in this document reference a three digit padding (<###>). I.E. mktg-prod-001

Padding aids in human readability and sorting of assets when those assets are managed in a configuration management databases (CMDBs), IT Asset Management tool, or traditional accounting tools. When the deployed asset is managed centrally as part of a larger inventory or portfolio of IT assets, the padding approach aligns with the interfaces those systems use to manage inventory naming.

Unfortunately, the traditional asset padding approach can prove problematic in infrastructure-as-code approaches which may iterate through assets based on a non-padded number. This approach is common during deployment or automated configuration management tasks. Those scripts would have to routinely strip the padding and convert the padded number to a real number, which slows script development and run time.

Which approach you choose to implement is a personal decision. The padding in this article is meant to illustrate the importance of using a consistent approach to inventory numbering, not which approach is superior. Before deciding on a number schema (with or without padding) evaluate which will have a bigger impact on long term operations: CMDB/asset management solutions or code-based inventory management. Then consistently follow the padding option that best fits your operational needs.
