### ISSUE TITLE
Missing Objects

### ISSUE THREAD

**Issue by psinnathurai** [MicrosoftDocs/cloud-adoption-framework#1100]
[Enter feedback here]
The following Objects are missing:
- Microsoft.Insights/dataCollectionRules
- microsoft.maintenance/maintenanceconfigurations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@psinnathurai - Thank you so much for you feedback. We've added this to the page. You should see an update shortly!
