### ISSUE TITLE
The DINE policy for DNS record creation does not work for RSV where region code is part of DNS zone name

### ISSUE THREAD

**Issue by norregaard** [MicrosoftDocs/cloud-adoption-framework#1103]
If using RSV for Azure Backup in multiple regions, there is no check to ensure that the DNS records is created in the correct Private DNS zone. If two or more policies are assigned using the same SubResource/GroupId then DNS records will be created randomly in the different private DNS zones, e.g. in privatelink.we.backup.windowsazure.com and in privatelink.sdc.backup.windowsazure.com.

If an additional check is added on location for the private endpoint itself in the policy, then it works. See example here:
https://github.com/norregaard/Azure/blob/main/Policy/Auto-create-DNS-record-private-DNS-zone.json 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 72717 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
