### ISSUE TITLE
Page description is "learn more about asdf"

### ISSUE THREAD

**Issue by adamkadzban** [MicrosoftDocs/cloud-adoption-framework#1104]
The description should be updated to not have "asdf" as a placeholder

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0c44a7-d979-a06e-ba8a-44eaa2480100
* Version Independent ID: 0e0c44a7-d979-a06e-ba8a-44eaa2480100
* Content: [Brownfield landing zone considerations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/brownfield-considerations?source=recommendations)
* Content Source: [docs/ready/landing-zone/brownfield-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/brownfield-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @timwarner-msft
* Microsoft Alias: **timwarner**

**Comment by timwarner-msft** [comment]
#please-close
