### ISSUE TITLE
Visio download is not for the image shown

### ISSUE THREAD

**Issue by kiwishawn** [MicrosoftDocs/cloud-adoption-framework#1105]
Hi, when you download the Visio file, from the link below the imagefor the Landing Zone image it is not a Visio of the image shown.

Regards,

Nigel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
The visio that you download contains a lot of diagrams, the one shown on the page is indeed included in the file.  The page is called "ALZ Hub & Spoke."

I'm going to go ahead and close this, but if you need more assistance, please let us know.

#please-cloase
