### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by anthonyonazure** [MicrosoftDocs/cloud-adoption-framework#111]
These links are broken on the page.

[Resource Consistency]../../govern/resource-consistency/template.md)
should be: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/complex/resource-consistency-improvement

[Identity Baseline]../../govern/identity-baseline/template.md)
should be: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/complex/identity-baseline-improvement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b16fa6-f4b5-3b9b-dcd5-9664d6a4242c
* Version Independent ID: e8d3633f-79ec-3fbe-b2bf-881c912f661d
* Content: [Governance or compliance strategy - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/expanded-scope/governance-or-compliance#feedback)
* Content Source: [docs/migrate/expanded-scope/governance-or-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/expanded-scope/governance-or-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#184338

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
