### ISSUE TITLE
Introductory wording

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#1114]
The 1st sentence of this article is:

> An effective naming convention consists of resource names from important information about each resource.

I am not sure what this means. Are there some words missing in this sentence? Can it be reworded?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@VitalyMCT - We've updated that page. Is the update more clear?

**Comment by VitalyMCT** [comment]
@stephen-sumner Yes, it looks great now. Thanks for making the change!
