### ISSUE TITLE
APOGEE GAMING

### ISSUE THREAD

**Issue by AGAP79** [MicrosoftDocs/cloud-adoption-framework#1118]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5f8ca20-8273-625d-bfa8-f87a3c6f6992
* Version Independent ID: 7573139a-efce-c33b-ce87-1e91cbe48e2c
* Content: [Create your initial Azure subscriptions - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions)
* Content Source: [docs/ready/azure-best-practices/initial-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/initial-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
It is unclear what the issue is.  If assistance is still needed, please re-open with additional information.
