### ISSUE TITLE
Possible Mixup between East US and Central Architecture?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/cloud-adoption-framework#112]
In the part of the article shown in quotes below, why is a reference being made to the East US 2 Hub, when there is in fact a Hub VNet with a gateway subnet in the secondary Central US location too per the Central US diagram?
If East US2 is being referred to as the central point of connectivity to on-premises, why is there a gateway subnet in Central US Hub VNet? Will both Azure VPN Gateways have connections to on-premises VPN Devices?

"Virtual networks in Central US (secondary region)
Central US is Contoso's secondary region. Here's how Contoso will architect networks within it:
Hub: The hub VNet in East US 2 is the central point of connectivity to the on-premises datacenter, and the spoke VNets in East US 2 can be used to isolate workloads if required, managed separately from other spokes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097a8a15-21c5-619d-05f6-8722da3c0d7c
* Version Independent ID: 7cc4e4f3-fa5d-dd6c-5462-7f587e708d5e
* Content: [Deploy a migration infrastructure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure#feedback)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#184475

**Comment by SB-o-matic** [comment]
Any update on this?

**Comment by deltadan** [comment]
this should be fixed with the lates update.

**Comment by deltadan** [comment]
@alexbuckgit I worked on this issue with the last update.
