### ISSUE TITLE
Azure Policy Guest Configuration > Azure Automanage Machine Configuration

### ISSUE THREAD

**Issue by ROSMITHJ-MSFT** [MicrosoftDocs/cloud-adoption-framework#1121]
Hello, 

Azure Policy Guest Configuration is now called Azure Automanage Machine Configuration. Just wanted to get the verbiage consistent across the pages. 

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7d487b9-820c-a831-e881-617989a048dc
* Version Independent ID: f7d487b9-820c-a831-e881-617989a048dc
* Content: [Operational compliance considerations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/management-operational-compliance)
* Content Source: [docs/ready/landing-zone/design-area/management-operational-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/management-operational-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by BryanLa** [comment]
@ROSMITHJ-MSFT - thanks very much for your contribution.
@lukemurraynz - thanks for your PR and contribution in resolving this issue.

This issue is now resolved.
#please-close
