### ISSUE TITLE
What about Microsoft Sentinel

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#1122]
Is there a reason that Sentinel was not included in this architecture? Please add it. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/#azure-landing-zone-conceptual-architecture)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by stephen-sumner** [comment]
@DeanGross - Great question! Let me look into this. Thanks for the feedback!

**Comment by jtracey93** [comment]
Hey @DeanGross,

Sentinel is indeed recommend in this architecture and is deployed as part of the accelerators (it's just a solution on the log analytics workspace 👍) 

https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-area/security#security-in-the-azure-landing-zone-accelerator

We are also looking at recommending folks look to then use the Sentinel All In One Accelerator to bootstrap the sentinel initialization even further https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Sentinel-All-In-One

Hope that helps

Thanks

Jack

cc: @stephen-sumner

**Comment by stephen-sumner** [comment]
@DeanGross - I'm going to close this issue. Please let us know if you have any questions. We really appreciate your feedback!

**Comment by DeanGross** [comment]
Just because Sentinel is implemented as solution on top of a Log Analytics workspace does not seem to be a very compelling reason to leave this incredibly important product off of a high level diagram like this. Defender for Cloud is shown and I think that the fact that it is now explicitly shown may cause some organization to miss out on the opportunity to get Sentinel included in a project plan

**Comment by stephen-sumner** [comment]
@jtracey93 thoughts on showing in diagram?

**Comment by jtracey93** [comment]
I have no issues showing it on the diagram if we want to add it. On top of the log analytic workspace as a solution

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 84809 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
