### ISSUE TITLE
Feedback: Provide Visio Diagram Download for Reference

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/cloud-adoption-framework#1126]
Hey Team!  Is it possible to provide a public download link of the AVD Architecture Visio Diagram in this page for AVD Enterprise at Scale?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60ebd567-bf69-afa9-625e-38eb81dccfba
* Version Independent ID: ef4ee644-1df3-433b-b11e-cb32dc58bad1
* Content: [Enterprise-scale support for Azure Virtual Desktop - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/enterprise-scale-landing-zone#architecture)
* Content Source: [docs/scenarios/wvd/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @wahidsaleemi
* Microsoft Alias: **tozimmergren**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @brmcmill. Great catch!
I'll start investigating the missing Visio download internally and get back with an update here once I have more clarity.

**Comment by v-fearam** [comment]
#please-close
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/4535
