### ISSUE TITLE
Clarification on folder structure

### ISSUE THREAD

**Issue by Siglangf** [MicrosoftDocs/cloud-adoption-framework#1132]
Hello. I am reviewing the recommended folder structure hierarchy in cloud adoption framework/cloud scale analytics.
The example below shows the recommended folder structure layout for the landing container in the storage account. In the Log and Telemetry folders, it is recommended to include a folder per "Application Name" and "Application". It is a litle bit unclear what it is ment by application in this context. Does it map to one for each source aligned ingestion data application? Or what is the right interpretation? Please provide some examples:)

<img width="416" alt="image" src="https://user-images.githubusercontent.com/47598564/234780288-9b6b045c-b5c4-427d-832e-4f00d24a046a.png">

**Comment by Siglangf** [comment]
Cloud scale analytics documentation found here: 

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/best-practices/data-lake-zones

**Comment by v-fearam** [comment]
#assign:mboswell

**Comment by mboswell** [comment]
@Siglangf The internal application or ingestion name is what we are point to here. For example, you could have a SAP General Ledger Import - we would use this as a the application name OR you could have a SAP Purchase Transformation. 

Use what makes sense to you as a company but make sure that it is something that your data engineering can understand,

**Comment by v-fearam** [comment]
#please-close
