### ISSUE TITLE
Additional Scenario - MSFT Partners providing CSP

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#1133]
Please add another common scenario to describe when a Microsoft Partner is providing services to clients through the Cloud Solution Providers program. This results in multiple AAD tenants 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7922d1bc-f0f3-3155-8a88-ff861e779c6e
* Version Independent ID: 7922d1bc-f0f3-3155-8a88-ff861e779c6e
* Content: [Scenarios for multiple Azure Active Directory tenants - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/multi-tenant/scenarios)
* Content Source: [docs/ready/landing-zone/design-area/multi-tenant/scenarios.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/multi-tenant/scenarios.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by Zimmergren** [comment]
Hi Dean, thank you for suggesting this. 
I'll lift this suggestion internally and put it on the backlog to review. Closing the GH ticket.

Thanks!
