### ISSUE TITLE
Swapped definition of Modular and Scalable?

### ISSUE THREAD

**Issue by quekmc** [MicrosoftDocs/cloud-adoption-framework#1137]
[Enter feedback here]
Are the definitions for Modular and Scalable swapped?
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/#scalable-and-modular
![Landing Zone Scalable vs Modular definition](https://user-images.githubusercontent.com/89065520/236628682-9b1cb5c4-b45e-49ae-b5b9-7b85ef030d07.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by stephen-sumner** [comment]
@quekmc - Thank you for the feedback. We value your input highly. We've made some updates that hopefully address this lack of clarity. Thank you so much!
