### ISSUE TITLE
the picture on the page does not look good in dark theme

### ISSUE THREAD

**Issue by slavizh** [MicrosoftDocs/cloud-adoption-framework#114]
the picture on the page does not look good in dark theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac4de131-ab01-a43b-4093-736554df38b5
* Version Independent ID: 48c74463-78e7-b914-9e85-b4baef78950f
* Content: [Innovation tools for device interaction - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/devices)
* Content Source: [docs/innovate/best-practices/devices.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/best-practices/devices.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#184685

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
