### ISSUE TITLE
Non-Production Development Environment? 

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/cloud-adoption-framework#1146]
After reading this page, I wonder how development and changes to the data lake are typically made.  Would there be a completely separate logical lake or some other folder structure? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5307b585-f48a-c46d-bdc5-56ec5dad0112
* Version Independent ID: 5307b585-f48a-c46d-bdc5-56ec5dad0112
* Content: [Data lake zones and containers - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/best-practices/data-lake-zones)
* Content Source: [docs/scenarios/cloud-scale-analytics/best-practices/data-lake-zones.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/best-practices/data-lake-zones.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by v-fearam** [comment]
Hi @propellor

Here's something we can share on this:
![image](https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/62260324/a4acb35c-6558-4dd3-9f6c-6370f9b64c87)
![image](https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/62260324/2e564334-8c6a-4528-b353-80337b9b86e0)
![image](https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/62260324/25e4550c-8317-42ed-b817-7cb2e8c7c430)
This is not “MS official” guidance at the current point in time, but hopefully it helps. 
#please-close
