### ISSUE TITLE
Please add Forms Recognizer and other Applied AI services to this list

### ISSUE THREAD

**Issue by pgbfnf** [MicrosoftDocs/cloud-adoption-framework#1149]
I could not find Forms Recognizer or other Applied AI services in this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@pgbfnf - good suggestion! I'll get you those abbreviations asap. Sorry for the delay! Thanks so much!

As you probably know by now, Forms Recognizer is now Azure AI Document Intelligence: https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-form-recognizer-is-now-azure-ai-document-intelligence-with/ba-p/3875765
