### ISSUE TITLE
Clarity on private DNS zone resource ID and Policy assignment

### ISSUE THREAD

**Issue by dirkslab** [MicrosoftDocs/cloud-adoption-framework#1152]
Please advise: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale
Documenation states "and links it to the private DNS zone resource ID that's specified as the parameter. In the example, the private DNS zone resource ID is:

/subscriptions/<subscription-id>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net". 

Which parameter is this in the example. Is it  below?

"parameters": {
    "privateDnsZoneId": {
      "type": "String",
      "metadata": {
        "displayName": "privateDnsZoneId",
        "strongType": "Microsoft.Network/privateDnsZones"
      }
    }

When assigning the policy and going through the parameters step 'privateDnsZoneId' you get a drop down of Private DNS zone names:
privatelink.blob.core.windows.net
privatelink.azuresynapse.net
privatelink.table.core.windows.net
...

How are you suppose to specify the resource ID of the dns zone?
/subscriptions/<subscription-id>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net". 
![2023-05-26_20-35-48](https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/20906463/3f11e255-6c26-4f56-ad0b-dd2c744a2fcc)

**Comment by v-fearam** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/4621#issuecomment-1711967914

actually selecting the correct DNS zone from that drop down will specify the resource ID as the input on the policy, its just the portal helping and hiding that.

#please-close
