### ISSUE TITLE
Your deployment failed

### ISSUE THREAD

**Issue by Aman123mishra** [MicrosoftDocs/cloud-adoption-framework#1154]
[Enter feedback here]

These all templates are not working getting error in the scaleSetTemplate resource.
Please check this error message i have received and i also take support from azure technical team but they said it will be template related issue not a resource issue please contact author or contributor of this template.

error which i have received - 

The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)

VM has reported a failure when processing extension 'setup_moodle'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1
[stdout]
### Script Start Thu Jun  1 07:21:56 UTC 2023###
Invalid fileServerType () given. Only 'gluster', 'azurefiles', 'nfs', 'nfs-ha' or 'nfs-byo' are allowed. Exiting

[stderr]
IpExportPath":"","nfsHaLbIP":"172.31.2.100","nfsHaExportPath":"/drbd/data","fileServerDiskSize":1024},"phpProfile":{"phpVersion":"7.4"}}'
/usr/bin/jq: line 1: syntax error near unexpected token `newline'
/usr/bin/jq: line 1: `<!DOCTYPE html>'
+ export fileServerDiskSize=
+ fileServerDiskSize=
++ jq -r .phpProfile.phpVersion
++ echo '{"siteProfile":{"siteURL":"lb-7mjpwz.westeurope.cloudapp.azure.com","httpsTermination":"VMSS","thumbprintSslCert":"None","thumbprintCaCert":"None"},"moodleProfile":e++ jq -r .moodleProfile.isMigration
/usr/bin/jq: line 1: syntax error near unexpected token `newline'
/usr/bin/jq: line 1: `<!DOCTYPE html>'
+ export isMigration=
+ isMigration=
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ echo
+ check_fileServerType_param
+ local fileServerType=
+ '[' '' '!=' gluster -a '' '!=' azurefiles -a '' '!=' nfs -a '' '!=' nfs-ha -a '' '!=' nfs-byo ']'
+ echo 'Invalid fileServerType () given. Only '\''gluster'\'', '\''azurefiles'\'', '\''nfs'\'', '\''nfs-ha'\'' or '\''nfs-byo'\'' are allowed. Exiting'
+ exit 1
"

More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot  (Code: VMExtensionProvisioningError, Target: 0)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88e83333-252a-853d-79ad-614ad6f0df43
* Version Independent ID: 52b8043f-079f-e526-7368-a99da4e922eb
* Content: [Moodle migration architecture and templates - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/lamp/moodle/migration-arch)
* Content Source: [docs/scenarios/lamp/moodle/migration-arch.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/lamp/moodle/migration-arch.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @UmakanthOS
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
we've passed your feedback to the proper team

https://github.com/Azure/Moodle/issues/290

#please-close
