### ISSUE TITLE
Images are not labeled with figure numbers, making it confusing sometimes to track which figure (image) the text is referring to.

### ISSUE THREAD

**Issue by husamhilal** [MicrosoftDocs/cloud-adoption-framework#1155]
Images are not labeled with figure numbers, making it confusing sometimes to track which figure (image) the text is referring to.

@prasad3017 @sblair01 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2d5b45b-03d2-14b4-8ba5-b1fb59c69a8a
* Version Independent ID: c2d5b45b-03d2-14b4-8ba5-b1fb59c69a8a
* Content: [Network considerations for Azure VMware Solution dual-region deployments - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-dual-region-network-topology#internet-connectivity)
* Content Source: [docs/scenarios/azure-vmware/eslz-dual-region-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-dual-region-network-topology.md)
* Service: **caf**
* Sub-service: **caf-scenario-vmware**
* GitHub Login: @fguerri
* Microsoft Alias: **fguerri**

**Comment by sblair01** [comment]
@husamhilal thank you for the feedback. When I hover over the image, I do see that they are labeled. I also see that usually the image matches what's referenced in the paragraph. Do you mean specifically when they are embedded in the paragraph or do you want the references in the link to be paragraphs? Are you looking for alt text? There are many ways to address this depending on the desired outcome. 

Do you mind forking a repo and sharing an example of the fix you would like to see via pull request?

Thanks, 

Sabine

**Comment by husamhilal** [comment]
> @husamhilal thank you for the feedback. When I hover over the image, I do see that they are labeled. I also see that usually the image matches what's referenced in the paragraph. Do you mean specifically when they are embedded in the paragraph or do you want the references in the link to be paragraphs? Are you looking for alt text or labeling of the images? There are many ways to address this depending on the desired outcome.
> 
> Do you mind forking a repo and sharing an example of the fix you would like to see via pull request?
> 
> Thanks,
> 
> Sabine

Thanks a lot @sblair01 

I see in markdown that complex image was used with long description which identified the figure number. However, this is hidden and not visible to readers. Please notice that explained here: https://learn.microsoft.com/en-us/contribute/markdown-reference#complex-images-with-long-descriptions

This is how I see one of the figures for example (notice no figure description) 
<img width="885" alt="image" src="https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/11361105/15e1a653-2698-4f87-aa0b-63dfdb2be010">

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 97804 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
