### ISSUE TITLE
Missing word? "Personal needs to be secured"

### ISSUE THREAD

**Issue by ssmItera** [MicrosoftDocs/cloud-adoption-framework#1157]
[Enter feedback here]
"Personal needs to be secured" is the word "data" missing between Personal and needs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 130e32b0-bca6-d185-1988-07baed84e77d
* Version Independent ID: 95eb87fc-fb45-06ae-70c6-f4e4109ae96f
* Content: [Responsible and trusted AI - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/trusted-ai)
* Content Source: [docs/innovate/best-practices/trusted-ai.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/innovate/best-practices/trusted-ai.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @msteller-Ai
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  This has been addressed.  If you are still experiencing an issue, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
