### ISSUE TITLE
What does user-assigned managed identity have to do with downtime?

### ISSUE THREAD

**Issue by TWolversonReply** [MicrosoftDocs/cloud-adoption-framework#1158]
Please explain this recommendation:

> Use a [user-assigned managed identity](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-use-managed-service-identity) for API Management to prevent downtime during redeployment from ARM templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e23c1c08-f1cb-dd08-83fb-59771268bd6d
* Version Independent ID: e23c1c08-f1cb-dd08-83fb-59771268bd6d
* Content: [Operations management considerations for Azure API Management - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/api-management/management)
* Content Source: [docs/scenarios/app-platform/api-management/management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/api-management/management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by v-fearam** [comment]
#please-close
