### ISSUE TITLE
Incorrect catagory?

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/cloud-adoption-framework#117]
Why is "Reductions in capital expenses" categorized under "Critical Business Events"? I would think the category "Migration Motivations" would be a better fit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Begin a cloud migration journey in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/migrate#feedback)
* Content Source: [docs/getting-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#187015

**Comment by JanetCThomas** [comment]
User testing was used to evaluate how these were put together. Our users most often related to this as a critical business event.
