### ISSUE TITLE
Redundant items

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/cloud-adoption-framework#118]
Both these are listed under "Migration Motivations": "Scale to meet market demands" and "Scale to meet geographic or market demands". The last one covers the first one, so I think "Scale to meet market demands" should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Begin a cloud migration journey in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/migrate#feedback)
* Content Source: [docs/getting-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#187017

**Comment by JanetCThomas** [comment]
User testing was used to evaluate how these were put together.
