### ISSUE TITLE
migration approach

### ISSUE THREAD

**Issue by hemas2022** [MicrosoftDocs/cloud-adoption-framework#1186]
[Enter feedback here]
Hello, am working on drafting the migration approach from spring boot applications (on prem, vms, pcf) to Azure spring apps. but am not able to find a visio reference architecture to support this and arrive at a migration approach. could you guide me here please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 283f3632-9707-d345-6f95-e68ff711411c
* Version Independent ID: 283f3632-9707-d345-6f95-e68ff711411c
* Content: [Azure Spring Apps landing zone accelerator - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/spring-apps/landing-zone-accelerator)
* Content Source: [docs/scenarios/app-platform/spring-apps/landing-zone-accelerator.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/spring-apps/landing-zone-accelerator.md)
* Service: **caf**
* Sub-service: **caf-scenario-spring-apps**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by stephen-sumner** [comment]
@hemas2022 - I hope you found what you needed. The diagram on the page you indicated shows the architecture for the application landing zone. The GitHub repo for the landing zone accelerator shows a fuller architecture: https://github.com/Azure/azure-spring-apps-landing-zone-accelerator#enterprise-scale-reference-implementation.

**Comment by stephen-sumner** [comment]
#please-close
