### ISSUE TITLE
Wrong statement about claims

### ISSUE THREAD

**Issue by hardygg** [MicrosoftDocs/cloud-adoption-framework#1187]
[Enter feedback here]
This statement does not appear correct and based on the context looks like it should refer to Internet based authentication protocols
'Your workloads depend on claims-based authentication using protocols like Kerberos or NTLM.'
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d53df27-59c8-359c-0976-e586d9374d64
* Version Independent ID: 1692111e-37ee-bb7f-5b5c-4c3a1acec7fe
* Content: [Identity decision guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/identity/)
* Content Source: [docs/decision-guides/identity/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/decision-guides/identity/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 143254 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
