### ISSUE TITLE
Assessment line is missing the name of the tool

### ISSUE THREAD

**Issue by richredgrave** [MicrosoftDocs/cloud-adoption-framework#1196]
In the section Step 2: Assess the current RDS on-premises environment, the wording below doesn't make sense and seems to be missing the name of the tool used:

" it is recommended to run an assessment of the RDS on-premises environment, to achieve this Contoso its tool of preference."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 177be313-669c-b534-575c-27eaa49b76b8
* Version Independent ID: 33169923-9568-077a-7f12-19554a9dbb94
* Content: [Move on-premises Remote Desktop Services to Azure Virtual Desktop - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rds-to-wvd)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @benstegink
* Microsoft Alias: **martinek**

**Comment by stephen-sumner** [comment]
@richredgrave - Thank you for your feedback! I know it's been a while, but you should see an update to this section shortly.

**Comment by stephen-sumner** [comment]
#please-close
