### ISSUE TITLE
Microsoft Cloud Adoption Framework for Azure needs updated

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#120]
You've added the word Organize on this and other pages, plus you've added a chapter for Organize, but the graphic called Microsoft Cloud Adoption Framework for Azure does not show Organize, which is the last step after Manage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Begin a cloud migration journey in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/migrate#feedback)
* Content Source: [docs/getting-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190305

**Comment by whynotm** [comment]
hi,
i think that's can be in the same square with Manage : "Manage & Organize", that concern People and It Operations
thks

**Comment by JanetCThomas** [comment]
This issue has been addressed.  Thanks!
