### ISSUE TITLE
Azure Cosmos DB naming confusion

### ISSUE THREAD

**Issue by thomasvdb** [MicrosoftDocs/cloud-adoption-framework#1200]
When looking at the naming conventions for databases and more specifically Azure Cosmos DB, there is some confusion due to the use of terminology.

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#example-names-databases

The document states the naming for the "Azure Cosmos DB database" but shouldn't this be the "Azure Cosmos DB account"?
The database within an "Azure Cosmos DB account" doesn't has a "Global" scope as far as I know.

It also seems weird to add an environment suffix at the end for a database name within an account?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **ssumner**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 143250 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
