### ISSUE TITLE
Missing Abbreviation for Microsoft.Cdn/Profiles/AfdEndpoints/Routes

### ISSUE THREAD

**Issue by jacobspack** [MicrosoftDocs/cloud-adoption-framework#1202]
I am using fdr for the time being.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@jacobspack - Thank you so much for the suggestion! Sorry for the delay getting back to you. 

This is a good suggestion. I normally don't provide abbreviations for resources that embedded (3rd child resource). I'd recommend using a descriptive name as the documentation suggests: https://learn.microsoft.com/en-us/azure/frontdoor/create-front-door-bicep?tabs=CLI
