### ISSUE TITLE
Missing resource types

### ISSUE THREAD

**Issue by leekester** [MicrosoftDocs/cloud-adoption-framework#1205]
Hi,

Looks to be missing abbreviations for a couple of resource types:

- Microsoft.VideoIndexer/accounts ("via" maybe)
- Microsoft.Media/mediaservices/streamingendpoints ("media" maybe. Service end-of-life in June 2024 though)

Thanks,

Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@leekester I'm going to add `avi` for AI Video Indexer. I won't be adding the streaming endpoints abbreviation due to the end of life on the Azure Media Services (AMS). Feel free to use whatever works for you.
