### ISSUE TITLE
Links need improved

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#121]
The Next link at the bottom of the Cloud Adoption Framework page takes you to Begin a migration journey page.  This page links to Strategy, Plan, Ready, Migrate, Innovate, Govern, Manage and Organize as next steps.  People will totally miss the Understand the innovation journey and the Enable successful cloud adoption pages, which are next in the outline shown to the left of this page but is not shown as a Next step.

I suggest that the Cloud Adoption Framework links to a new page which has more explanation about these 3 options and a Next step of linking to:  Begin a migration journey, Understand the innovation journey, and Enable successful cloud adoption.  Maybe.  This is just one possible option for linking, which may not be optimal.

However, on Cloud Adoption Framework page, based on your table, it seems to me the 3 options are:  Critical Business Events, Migration, and Innovation.  So I'm a bit confused why two of your pages match, but Critical Business Events is missing and you've added the Enable successful cloud adoption in it's place, and they are in a different order than the table.  So I suggest more thought on possibly making the table and pages match, either adding to one or the other.  Maybe.  This is just one possible option and may not be optimal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Begin a cloud migration journey in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/migrate)
* Content Source: [docs/getting-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190309

**Comment by JanetCThomas** [comment]
This has been resolved.
