### ISSUE TITLE
Document doesn't actually advise how to create subscriptions

### ISSUE THREAD

**Issue by ml4** [MicrosoftDocs/cloud-adoption-framework#1213]
The document suggests it is about creating subscriptions, but doesn't actually list the steps to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5f8ca20-8273-625d-bfa8-f87a3c6f6992
* Version Independent ID: 7573139a-efce-c33b-ce87-1e91cbe48e2c
* Content: [Create your initial Azure subscriptions - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions)
* Content Source: [docs/ready/azure-best-practices/initial-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/initial-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
That is correct and good observation, the Cloud Adoption Framework tends not to repeat product usage instructions found elsewhere.  To see how to create a subscription, please check out a product doc such as this one called [Create a Microsoft Customer Agreement subscription](https://learn.microsoft.com/azure/cost-management-billing/manage/create-subscription#create-a-subscription) or this one called [Create an Enterprise Agreement subscription](https://learn.microsoft.com/azure/cost-management-billing/manage/create-enterprise-subscription) as appropriate.

#please-close
