### ISSUE TITLE
Business vocabulary should be established and maintained.

### ISSUE THREAD

**Issue by ecormaksin** [MicrosoftDocs/cloud-adoption-framework#1214]
I have an idea about the [Process](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/govern#process) section.
At the `Fully governed` column, it says that `Common business vocabulary complete`.
However, I think that business processes have no finished state.
So, I think that `Common business vocabulary complete` should be `Common business vocabulary established and maintaind` as a next step for `Common business vocabulary established` (at `Stage 2`).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebc90107-5f71-51f9-8c7a-3c8ce1f221d2
* Version Independent ID: 7b46c90c-d251-d709-6046-591fbcc11e3e
* Content: [Data governance overview - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/govern)
* Content Source: [docs/scenarios/cloud-scale-analytics/govern.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/govern.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by skabou** [comment]
Thank you for your feedback.  This has been addressed.  If you are still experiencing an issue, please re-open with additional information.

**Comment by skabou** [comment]
#please-close
