### ISSUE TITLE
CAF tool is unavailable

### ISSUE THREAD

**Issue by DimaRazb** [MicrosoftDocs/cloud-adoption-framework#1215]
cafbaseline.com
Hey MS,
Please fix a certificate issue.

**Comment by ckittel** [comment]
The CAF assessment has been moved for a while now to <https://aka.ms/adopt/governassessment> on the [Microsoft Assessments](https://learn.microsoft.com/assessments) platform. -- the <https://cafbaseline.com> site has been shut down and is in a state of transition to being fully removed (hence the weird cert error you are seeing right now).
