### ISSUE TITLE
Please add an abbreviation for the object type "ExpressRoute Gateway"

### ISSUE THREAD

**Issue by pgbfnf** [MicrosoftDocs/cloud-adoption-framework#1217]
Please add an abbreviation for the object type "ExpressRoute Gateway"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by v-fearam** [comment]
#assign-reviewer:stephen-sumner

**Comment by stephen-sumner** [comment]
Thank @pgbfnf. Sorry for the delay. We're working on adding this now.
