### ISSUE TITLE
Feedback is not enabled for Enable successful cloud adoption; and links in wrong category

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#122]
There is no Feedback block on the bottom of Enable successful cloud adoption page (so I used this page to submit feedback).

On the Enable successful cloud adoption page you link to business outcomes, digital estate plan, adoption backlogs:

Plan: Establishing clear business outcomes, a clearly defined digital estate plan, and well-understood adoption backlogs.

You show these in Plan, however the link for business outcomes goes to a Strategy page, and the link for adoption backlogs also goes to a non-Plan page.    I didn't check the other links, you probably should check these also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909bcd2f-c3cd-6a51-7929-89181fe63188
* Version Independent ID: af62a7e3-3f59-090d-5ac4-377748ac2ca2
* Content: [Innovate through cloud adoption - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/innovate)
* Content Source: [docs/getting-started/innovate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/innovate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190319

**Comment by JanetCThomas** [comment]
The Getting started section will be revised and released this summer. This issue will be resolved in that release.

**Comment by JanetCThomas** [comment]
This topic has been updated.  Thanks!
