### ISSUE TITLE
Small environments  missmatch

### ISSUE THREAD

**Issue by Vrolir** [MicrosoftDocs/cloud-adoption-framework#1224]
The information in this page doesn't match with other parts of the documentation when looking for information on smaller environments. for example:
https://github.com/Azure/Enterprise-Scale/
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md

on these pages the platform subscriptions are merged into one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54688c3b-0c16-6490-97c6-d92446d2553c
* Version Independent ID: 54688c3b-0c16-6490-97c6-d92446d2553c
* Content: [Subscription considerations and recommendations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-subscriptions)
* Content Source: [docs/ready/landing-zone/design-area/resource-org-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/resource-org-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
@jtracey93 - anything to add to this page about the pros/cons of highly compressed platform implementations?  I assume we wouldn't ever recommend it which is why it's not listed here.  But would like to get your take on @Vrolir's observation.

@Vrolir, do you have any more clarity on the type of guidance you're looking for?  Knowing there is a perceived mismatch is fine, but what information would you be looking for to help you make a decision?

**Comment by jtracey93** [comment]
100% correct @ckittel, we really dont advise single platform subscriptions as migrating out of them later is difficult. For example you cannot migrate an ExpressRoute circuit to another subscription, you must re-provision a new ExpressRoute entirely; hence splitting out from the start is the best approach, and it doesnt cost anything extra.

We explain this in our principles under [Subscription Democratization](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-principles#subscription-democratization) 

Also recommend a watch of the YouTube Video on this topic here: https://youtu.be/R-5oeguxFpo?si=Ptq4dDUrwFqzd0sI

**Comment by ckittel** [comment]
Thank you, Jack.

@Vrolir I'm going to mark this question resolved. If you'd like to see some more warnings on the Trey research implemention, feel free to open up an issue on that repo.

#please-close
