### ISSUE TITLE
Self Hosted Integration Run Time on Virtual Machine Scale Sets

### ISSUE THREAD

**Issue by Joguz** [MicrosoftDocs/cloud-adoption-framework#1226]
[Enter feedback here]
Can it be clarified if Self Hosted Integration Runt Time is supported on Virtual Machine Scale Sets. 
In the section: Shared Integration Runtime. It implies it is:
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-landing-zone#shared-integration-runtimes

However, if you go to the following link https://feedback.azure.com/d365community/idea/426122a4-6d26-ec11-b6e6-000d3a4f032c
this functionality was declined 4 years ago.

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a913402-aa8d-3ae7-2589-81d7bee16c09
* Version Independent ID: 5857fc40-82a4-18e2-e152-67841ca03f51
* Content: [Data landing zones - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-landing-zone)
* Content Source: [docs/scenarios/cloud-scale-analytics/architectures/data-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/architectures/data-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
@joguz - thank you and we will change this whilst reflecting the guidance for scale out [here]( https://learn.microsoft.com/en-us/azure/data-factory/create-self-hosted-integration-runtime?tabs=data-factory#scale-considerations)

#assign:@mboswell
#pri1

**Comment by mboswell** [comment]
#assign:mboswell
