### ISSUE TITLE
Some topics already are part of Cloud Adoption Framework

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#123]
On the Enable successful cloud adoption page (which doesn't have a feedback block) it says
In addition to the Cloud Adoption Framework,…   and then the blocks link to other Microsoft docs.
However, Cloud Governance, and Technical Skills Building blocks are already part of the Cloud Adoption Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909bcd2f-c3cd-6a51-7929-89181fe63188
* Version Independent ID: af62a7e3-3f59-090d-5ac4-377748ac2ca2
* Content: [Innovate through cloud adoption - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/innovate)
* Content Source: [docs/getting-started/innovate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/getting-started/innovate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190321

**Comment by JanetCThomas** [comment]
This topic has been updated.  Thanks!
