### ISSUE TITLE
Link to wrong deployment template

### ISSUE THREAD

**Issue by MGodfrey50** [MicrosoftDocs/cloud-adoption-framework#1233]
Deploy Azure VMware Solution and dependencies with a connection to Azure - this links to the green field lite -  it looks like it should be connected to the Green Field deployment
https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/AVS-Landing-Zone/GreenField

The second section is connected to the Green Field Lite - this looks correct.

Any question - ping Mark Godfrey magodfre@microsoft.com

**Comment by ckittel** [comment]
Hey there Mark, can you please include what pages you saw the bad link on, that'll help us direct this to the content maintainer for this article.

**Comment by josevarela** [comment]
Searched for the link description and found it at: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/enterprise-scale-landing-zone. 

Validated the page was already updated to point to the correct version of the scripts as suggested by @MGodfrey50. The change was made by this commit: https://github.com/MicrosoftDocs/cloud-adoption-framework/commit/ad08874930cc39710a43c149e3f4204505ed125b

#please-close
