### ISSUE TITLE
Unclear very ambiguous info 

### ISSUE THREAD

**Issue by sreedharsingaraju** [MicrosoftDocs/cloud-adoption-framework#1236]
[Enter feedback here]
The details are very ambiguous, It has no clarity on what and where is the outcome to be documented. Just looks like put a dump of garbage on whatever came to the authr mind. completely useless

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd96490e-31a0-9178-4259-43d7ddc1cfe7
* Version Independent ID: 02c48fd8-5962-b73a-2b7e-d452df5fee0c
* Content: [Build a digital transformation timeline - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/digital-transformation-timeline)
* Content Source: [docs/strategy/digital-transformation-timeline.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/digital-transformation-timeline.md)
* Service: **caf**
* Sub-service: **caf-methodology-strategy**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 177472 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
