### ISSUE TITLE
Why was Software Defined Networking and related documentation removed

### ISSUE THREAD

**Issue by jbrianmoss** [MicrosoftDocs/cloud-adoption-framework#1238]
Why was docs/decision-guides/software-defined-network/index.md and all files underneath removed?
I can't find any information in a commit, nor can I find it anywhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c249a426-07c2-9b47-4b52-1e81cafaf9b1
* Version Independent ID: 306b8e88-2d56-6168-f8ed-a934a26474f3
* Content: [Architectural decision guides - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/)
* Content Source: [docs/decision-guides/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/decision-guides/index.md)
* Service: **caf**
* Sub-service: **caf-general**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 177470 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
