### ISSUE TITLE
Why are the lists different?

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#124]
You have basically the same list, but different, on two different pages:

On this page for innovation you have:
Increasing business agility.
Preparing for new technical capabilities.
Building new technical capabilities.
Scaling to meet market demands.
Scaling to meet geographic demands.
Improving customer experiences and engagements.
Transforming products or services.

Yet on the Getting Started &gt; Understand the innovation journey you have:
•	Prepare for new technical capabilities.
•	Scale to meet market demands.
•	Scale to meet geographic demands.
•	Build new technical capabilities.
•	Improve customer experiences and engagements.
•	Transform products or services.
•	Disrupt the market with new products or services.

If docs are like programming, you may not want the same information in two different areas.  I have the same comment for more than this page, but didn't list it in feedback before.  You might want to reduce redundancy.  It really is ok, in my opinion, for summary pages not to have the detail, and therefore not the redundancy, and therefore not so boring.  But I could be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e48aaf-b0c5-ea0e-2d5d-af0f53affd3a
* Version Independent ID: 73399b00-c2a0-2aca-929f-f19e97ddab94
* Content: [Why are we moving to the cloud? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/motivations)
* Content Source: [docs/strategy/motivations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/motivations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190331

**Comment by JanetCThomas** [comment]
This issue has been addresssed.  Thanks!
