### ISSUE TITLE
DREAD Threat Model methodology is discontinued

### ISSUE THREAD

**Issue by FokkoVeegens** [MicrosoftDocs/cloud-adoption-framework#1240]
Why mention the DREAD Threat Model methodology, as it was discontinued in 2008? It could be replaced by an active methodology, like P.A.S.T.A.?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf6fc3b-2d91-463f-fdc9-19d3ba1ea965
* Version Independent ID: 0d4788a7-da1d-0619-0443-bdfb9c3c97da
* Content: [DevSecOps controls - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/devsecops-controls)
* Content Source: [docs/secure/devsecops-controls.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/secure/devsecops-controls.md)
* Service: **caf**
* Sub-service: **caf-methodology-secure**
* GitHub Login: @texnokot
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your suggestion.  It appears this has been addressed.  If you are still experiencing an issue, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
