### ISSUE TITLE
Azure virtual machines cost estimator Power BI is not working

### ISSUE THREAD

**Issue by jainaparna** [MicrosoftDocs/cloud-adoption-framework#1242]
The Azure virtual machines cost estimator Power BI is not working and throwing following error. 

DataSource.Error: AzureBlobs failed to get the response: 'The remote name could not be resolved: 'cloudpricing.blob.core.windows.net''.
Details:
    DataSourceKind=AzureBlobs
    DataSourcePath=https://cloudpricing.blob.core.windows.net/azurespecs
    Url=https://cloudpricing.blob.core.windows.net/azurespecs/APIData/ResourceSkus.json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42f8649e-4a66-2667-b4c7-88698cf5183f
* Version Independent ID: ce9e86a7-423d-7177-685d-ed9f426940b5
* Content: [Create a business case for cloud migration - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/cloud-migration-business-case#tools?WT.mc_id=azureenablement-ch9-cxa&WT.mc_id=azenable-60)
* Content Source: [docs/strategy/cloud-migration-business-case.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/cloud-migration-business-case.md)
* Service: **caf**
* Sub-service: **caf-methodology-strategy**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by SKhan012** [comment]
Hi, I have the same error

**Comment by Zimmergren** [comment]
Thank you for confirming, @SKhan012 - we'll open an internal request to mitigate!
