### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by Galihfirdaus** [MicrosoftDocs/cloud-adoption-framework#1246]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016c7c26-85f0-9c5d-3c8f-7d27010a1d9d
* Version Independent ID: 016c7c26-85f0-9c5d-3c8f-7d27010a1d9d
* Content: [Understand the roles and responsibilities for cloud-scale analytics in Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/organize-roles-responsibilities)
* Content Source: [docs/scenarios/cloud-scale-analytics/organize-roles-responsibilities.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/organize-roles-responsibilities.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by Galihfirdaus** [comment]
Y

**Comment by Galihfirdaus** [comment]
Galigfirdaus

**Comment by mboswell** [comment]
No content

#please-close
