### ISSUE TITLE
Update the diagram - rg to sub

### ISSUE THREAD

**Issue by nekdima** [MicrosoftDocs/cloud-adoption-framework#1248]
Hey Team, 

I think there is a small adjustment required to the diagram. RG should become a Subscription which connects to another HUB (connectivity) subscription via peering. Once update it would be in sync with our Enterprise-Scale framework. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: decccd7a-cdad-6352-8a6f-ff735fb6bd9e
* Version Independent ID: decccd7a-cdad-6352-8a6f-ff735fb6bd9e
* Content: [Azure Integration Services landing zone accelerator - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/integration-services/landing-zone-accelerator)
* Content Source: [docs/scenarios/app-platform/integration-services/landing-zone-accelerator.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/integration-services/landing-zone-accelerator.md)
* Service: **caf**
* Sub-service: **caf-scenario-app-plat**
* GitHub Login: @claytonsiemens77
* Microsoft Alias: **csiemens**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 177464 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
