### ISSUE TITLE
Why the link?

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#125]
You have a business outcome framework link that goes back to the Strategy Overview page.  Why?  The paragraph states to use these samples.  But there are no samples there that I can see.  Suggest removing the link.
The paragraph I am referring to:
Speaking in business outcomes can feel like a foreign language to many technically minded individuals. To help ease translation, Microsoft curates a set of business outcome examples in the business outcome framework. Use these samples to help inspire and demonstrate business outcomes that are based on actual transformation journeys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7093db-70a7-3ea2-28c7-ed88e5926188
* Version Independent ID: 5e67d5f1-6e5f-af8d-e74d-cdaff9a49300
* Content: [Business outcomes from transformation journeys - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/)
* Content Source: [docs/strategy/business-outcomes/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/business-outcomes/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190333

**Comment by JanetCThomas** [comment]
This issue has been resolved. see https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/374.  Changes should be live shortly.  Thanks!
