### ISSUE TITLE
File Server for FSLogix (not FSLogic) is not modern

### ISSUE THREAD

**Issue by 42uhybrider** [MicrosoftDocs/cloud-adoption-framework#1250]
I would approach with the usage of Azure Blog Storage when building into Azure Cloud, and not use a traditional File Server with Compute overhead, whilst utilizing FSLogix Containers.

Just saying :)

//Karsten

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26f8c27e-77a0-1ca8-4749-d0d3f075fba3
* Version Independent ID: fca6a9b5-2b70-52fe-1e5f-0aa4c432f3e4
* Content: [Strategic benefits of Azure Virtual Desktop - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/strategy)
* Content Source: [docs/scenarios/wvd/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/strategy.md)
* Service: **caf**
* Sub-service: **caf-scenario-virtual-desktop**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177462 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
