### ISSUE TITLE
Azure DDoS protection not supported in a VWAN architecture

### ISSUE THREAD

**Issue by dfendit** [MicrosoftDocs/cloud-adoption-framework#1253]
To my information, Azure DDoS Protection Standard is not supported in a VWAN architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3f50d-5fc4-32d7-400a-4876b83a1535
* Version Independent ID: e159e485-d2db-10a0-2615-73e78f3733f3
* Content: [Virtual WAN network topology - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/virtual-wan-network-topology)
* Content Source: [docs/ready/azure-best-practices/virtual-wan-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/virtual-wan-network-topology.md)
* Service: **caf**
* Sub-service: **caf-methodology-ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 177458 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
