### ISSUE TITLE
Update guidance to leverage Azure update manager

### ISSUE THREAD

**Issue by igorjnzl** [MicrosoftDocs/cloud-adoption-framework#1256]
With the Azure Update manager solution going GA and the legacy solution being deprecated in Aug 2024, can we update our CAF guidance accordingly.

https://learn.microsoft.com/en-us/azure/update-manager/overview?tabs=azure-vms

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7d487b9-820c-a831-e881-617989a048dc
* Version Independent ID: f7d487b9-820c-a831-e881-617989a048dc
* Content: [Operational compliance considerations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/management-operational-compliance)
* Content Source: [docs/ready/landing-zone/design-area/management-operational-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/management-operational-compliance.md)
* Service: **caf**
* Sub-service: **caf-alz**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 177456 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
