### ISSUE TITLE
Clarification for page content

### ISSUE THREAD

**Issue by TarekNabeel** [MicrosoftDocs/cloud-adoption-framework#1258]
Dears,

I find it hard to understand the information provided in this page and what actually benefit I can gain from it from planning perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4b9ed32-e3d4-109a-130b-f6cb12f9cbfb
* Version Independent ID: ab9abc48-1f0f-330e-0153-27205cffca88
* Content: [Approaches to digital estate planning - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/digital-estate/approach)
* Content Source: [docs/digital-estate/approach.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/digital-estate/approach.md)
* Service: **caf**
* Sub-service: **caf-methodology-plan**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Can you provide additional context?  If you still require assistance, please re-open with additional context.
