### ISSUE TITLE
Links to TechNet which is deprecated

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#126]
overview of Microsoft Azure compliance link goes to technet.  Where should it go to?  I'd like to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d0527e-5052-219c-d11f-6c0aeb034488
* Version Independent ID: 6c15662d-87d4-aadf-4b5c-28ee7c50aabe
* Content: [Examples of global reach outcomes - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/reach-outcomes)
* Content Source: [docs/strategy/business-outcomes/reach-outcomes.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/business-outcomes/reach-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190535

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
