### ISSUE TITLE
Common Customer Journeys

### ISSUE THREAD

**Issue by sriram08854** [MicrosoftDocs/cloud-adoption-framework#1263]
Dear Authors, 
I was going through the Cloud-Scale Analytics and realized that in your Customer Journey section - https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/#common-customer-journeys - the main step of Strategy is missed out. This can cause a ton of confusion, because the way I see it, Plan should come after Strategy is defined. 
Please let me know if you guys think otherwise. It might cause confusion and belittle the importance of Strategy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Cloud-scale analytics - Microsoft Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/)
* Content Source: [docs/scenarios/cloud-scale-analytics/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/index.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 196675 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
