### ISSUE TITLE
Other Design Considerations section

### ISSUE THREAD

**Issue by sriram08854** [MicrosoftDocs/cloud-adoption-framework#1267]
Dear Sir/Madam, the links in the above mentioned Design considerations are pointing to Modern Application Platform scenario. 
Please check and rectify

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c297777-3d19-9c15-b14b-3492ed3c928b
* Version Independent ID: 4973b799-c6bf-dae0-854d-c467631b4d1e
* Content: [Review your environment for Azure landing zones for cloud-scale analytics - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/ready)
* Content Source: [docs/scenarios/cloud-scale-analytics/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/ready.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by skabou** [comment]
Thank you for your suggestion.  It is unclear what content/links you are referring to.  If you are still experiencing an issue, please re-open with additional information.
