### ISSUE TITLE
Add Octopus Deploy to the Continuous Delivery list.

### ISSUE THREAD

**Issue by colinbowern** [MicrosoftDocs/cloud-adoption-framework#1269]
We're a GitHub and Microsoft partner, doing complex deployments with customers running in Azure. :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd1a394-d159-5ea1-b206-9912ac3afe20
* Version Independent ID: 8bd1a394-d159-5ea1-b206-9912ac3afe20
* Content: [DevOps considerations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/devops-principles-and-practices)
* Content Source: [docs/ready/considerations/devops-principles-and-practices.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/devops-principles-and-practices.md)
* Service: **caf**
* Sub-service: **caf-methodology-ready**
* GitHub Login: @alguadam
* Microsoft Alias: **alguadam**

**Comment by ckittel** [comment]
Hey there @colinbowern, I'll be pushing a change soon that will be including OD.  Thanks for the great software you folks write.

This issue will auto close once that PR is merged, after that, the change will be live within a couple of business days.
