### ISSUE TITLE
Pricing Calculator Estimates

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/cloud-adoption-framework#127]
[Under "Cost Management"](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/#cost-management) - It should be a best-practice to use the [azure.com/calculator](https://azure.com/calculator) to estimate your cost up-front. **Cost Management** should be considered throughout - just like security, not just at the end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca59ce2d-4eac-f0c4-6a86-e33a46574975
* Version Independent ID: 0cf30682-6247-7715-69d5-10d8abce29e0
* Content: [Best practices for Azure readiness - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/#cost-management)
* Content Source: [docs/ready/azure-best-practices/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190631

**Comment by BrianBlanchard** [comment]
We are revamping the view of financial analysis within CAF and other content sources to follow this type of holistic cost management focus. 

@alohaninja We are also working on a PR for a view of enterprise cost optimization and management. I'd be very interested in your feedback on this PR: https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/manage-costs?branch=release%2Fcaf-journey

That link is only accessible to MSFT employees. If you can't access that link, please contact @JanetCThomas, @alexbuckgit , or @BrianBlanchard for access.
