### ISSUE TITLE
Update guidance for Template Specs and Deployment Stacks

### ISSUE THREAD

**Issue by cloudappsguy** [MicrosoftDocs/cloud-adoption-framework#1270]
Current documentation demonstrates how to deploy a landing zone via an Azure Blueprint, which is not the go-forward process.

1. Blueprints are deprecated, with full expiry July 11, 2026.  Guidance/demonstration should be updated to reflect the go-forward capability of [Template Specs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/template-specs) and [Deployment Stacks](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks)
2. [Blueprint documentation](https://learn.microsoft.com/en-us/azure/governance/blueprints/overview) continues to state the capability is in 'preview', though it is being deprecated.

Recommend the page be retired/replaced by new content and demonstration instructions using template specs and deployment stacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 019fcb5a-b1ae-f264-d2d4-e26323d9b93c
* Version Independent ID: 75ab35b8-71d4-e97f-c93f-df715e7359f0
* Content: [Deploy a migration landing zone in Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone)
* Content Source: [docs/ready/landing-zone/migrate-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/migrate-landing-zone.md)
* Service: **caf**
* Sub-service: **caf-alz**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196669 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
