### ISSUE TITLE
Considerations paragraph does not include cold access tier

### ISSUE THREAD

**Issue by nielsvdc** [MicrosoftDocs/cloud-adoption-framework#1272]
In the paragraph containing the considerations under the line "Consider the following information when using access tiers:" the cold tier is not mentioned.

Also the name of the link in the line "For more information, see [Hot, Cool and Archive access tiers for blob data](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview)." needs to be changed to [Access tiers for blob data](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview).

And maybe the considerations can also include the definition of frequently/infrequently? When I have a data lake and the files are read once per day, is that frequently or infrequently? Is it then better to use hot tier or cool/cold?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef64508f-c861-4eed-0fa5-67b2655f0b37
* Version Independent ID: ec6447bb-4173-45e3-df8e-31448bfdae99
* Content: [Key considerations for Azure Data Lake Storage - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/best-practices/data-lake-key-considerations)
* Content Source: [docs/scenarios/cloud-scale-analytics/best-practices/data-lake-key-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/best-practices/data-lake-key-considerations.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by skabou** [comment]
This has been addressed and will be published on the next build.

**Comment by skabou** [comment]
#please-close
