### ISSUE TITLE
Take Unity Catalog into account as the metastore 

### ISSUE THREAD

**Issue by villepuntanen** [MicrosoftDocs/cloud-adoption-framework#1276]
The document would be more useful if it would take a stand on how to integrate and provision workloads when Unity Catalog is enabled on for the workspaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c6fd165-8d7e-0c58-81cf-21e9ef8cc3f7
* Version Independent ID: 87bea59c-c786-ab9d-4513-c57680c11b44
* Content: [Use Azure Databricks within cloud-scale analytics in Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/best-practices/azure-databricks-implementation)
* Content Source: [docs/scenarios/cloud-scale-analytics/best-practices/azure-databricks-implementation.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/best-practices/azure-databricks-implementation.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196663 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
