### ISSUE TITLE
Data breach

### ISSUE THREAD

**Issue by Heatherladue1** [MicrosoftDocs/cloud-adoption-framework#1277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8b75090-7a24-34f0-8892-257962285ac8
* Version Independent ID: 0e6ec4fc-9b50-efa7-4d0a-a554a64c4446
* Content: [Strategy for Azure VMware Solution adoption - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/strategy)
* Content Source: [docs/scenarios/azure-vmware/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/strategy.md)
* Service: **caf**
* Sub-service: **caf-scenario-vmware**
* GitHub Login: @mhenry
* Microsoft Alias: **jaalmond**

**Comment by ckittel** [comment]
Closing. If you would like to report a Cloud Adoption Framework documentation issue to the team, please open a new issue and include relevant information/repro steps in the Comment section.
