### ISSUE TITLE
Please update this page managed virtual network is now GA

### ISSUE THREAD

**Issue by kiritbhamre** [MicrosoftDocs/cloud-adoption-framework#1278]
Hello, 

This page is referencing 'managed virtual network' in 'preview' state...However, this service now in GA state, see below link

https://azure.microsoft.com/en-us/updates/azure-machine-learning-general-availability-for-october/

-Kirit 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf71dd3a-2b00-ffea-4d7d-e48a15da88c6
* Version Independent ID: 41ff90f9-75ef-db2e-64ef-9e5c5f77f6b8
* Content: [Machine learning enterprise security - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/ai-machine-learning-enterprise-security?source=docs)
* Content Source: [docs/ready/azure-best-practices/ai-machine-learning-enterprise-security.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/ai-machine-learning-enterprise-security.md)
* Service: **caf**
* Sub-service: **caf-methodology-ready**
* GitHub Login: @jhirono
* Microsoft Alias: **jhirono**

**Comment by skabou** [comment]
Thank you for your feedback.  I have made an update to the page, which will be reflected after the next build.
