### ISSUE TITLE
Need clarification on last para

### ISSUE THREAD

**Issue by vinaylaad07** [MicrosoftDocs/cloud-adoption-framework#1279]
Are we talking about 'workflow access' or 'workload access', is this typo here on last para of the document mentioned or I am misunderstanding this here completely ? Please clarify

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79eade2a-910d-f8f5-c531-229db0c90b79
* Version Independent ID: 79eade2a-910d-f8f5-c531-229db0c90b79
* Content: [Azure identity services and platform access - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/identity-access-platform-access)
* Content Source: [docs/ready/landing-zone/design-area/identity-access-platform-access.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/identity-access-platform-access.md)
* Service: **caf**
* Sub-service: **caf-alz**
* GitHub Login: @anlucen
* Microsoft Alias: **anlucena**

**Comment by skabou** [comment]
Thank you for your feedback.  I have made an update to the page which will be reflected after the next build.
