### ISSUE TITLE
Guidance Conflict - Application Gateway Deployments

### ISSUE THREAD

**Issue by MohawkAlexMS** [MicrosoftDocs/cloud-adoption-framework#1280]
There appears to be a conflict in advice regarding deployment of application gateways. This needs to be clarified or the older update removed so that it's not confusing for customers
 
Conflicting Recommendation 1 = Application Gateways should be used in perimeter networks (the hub): [Perimeter networks - Cloud Adoption Framework | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/perimeter-networks#perimeter-network-topology) - from the GitHub repo, looks like this has been here since 2019 so it's the older one.
 
Conflicting Recommendation 2 = "Treat the Application Gateway as an application component and deploy it in a spoke virtual network not as a shared resource in the hub": [Plan for application delivery - Cloud Adoption Framework | Microsoft Learn](https://learn.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-app-delivery)

In my experience, there are cases for both and for various reasons. However, at present it's not called out why you would pick one over the other, so without additional context this is conflicting and confusing for customers.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 196675 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by MohawkAlexMS** [comment]
What was the resolution for this?

Kind regards,

Alex Rose (he/him)
Senior Cloud Solutions Architect Engineer (Azure Core)
Customer Success Unit
***@***.******@***.***>

Follow me on Linkedin<https://www.linkedin.com/in/alexander-rose-networks-and-cloud/>

***@***.***
   ***@***.***
Microsoft Azure<https://azure.microsoft.com/en-us/overview/what-is-azure/>


***@***.***<https://twitter.com/microsoft>   ***@***.*** <https://www.facebook.com/Microsoft>    ***@***.*** <https://www.linkedin.com/company/microsoft>    ***@***.*** <https://www.youtube.com/user/Microsoft>    ***@***.*** <https://www.yammer.com/>



This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.
Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG.

**Comment by skabou** [comment]
Hey @MohawkAlexMS , The issue you opened is in our backlog and has not been addressed yet.  We are transitioning to another feedback system and retiring GitHub Issues.
