### ISSUE TITLE
cloud 50

### ISSUE THREAD

**Issue by SWCurragh** [MicrosoftDocs/cloud-adoption-framework#1281]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31a40001-def3-bb19-78a9-97f0405b0838
* Version Independent ID: f6c57b1d-d527-1b51-092a-a8d6098b506b
* Content: [Using cloud economics to develop a cloud adoption strategy - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/)
* Content Source: [docs/strategy/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/index.md)
* Service: **caf**
* Sub-service: **caf-methodology-strategy**
* GitHub Login: @mpvenables
* Microsoft Alias: **martinek**
```[tasklist]
### Tasks
```

**Comment by ckittel** [comment]
Closing. If you would like to report a Cloud Adoption Framework documentation issue to the team, please open a new issue and include relevant information/repro steps in the Comment section.
