### ISSUE TITLE
Code fragment to create service principal does not work

### ISSUE THREAD

**Issue by lloydlimmsft** [MicrosoftDocs/cloud-adoption-framework#1282]
[Enter feedback here]

This line of code does not work:
There was a breaking change in az which requires the use of --scopes and --role together.

az ad sp create-for-rbac -n "http://AzureArcServers" --role contributor

Corrected code should look like:
az ad sp create-for-rbac -n "http://AzureArcServers" --role contributor --scopes "/subscriptions/your subscription Id XXX/resourceGroups/your Resourcegroupname XXXX"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec71b71e-a01c-d90d-9e73-a91b3784f73c
* Version Independent ID: abac4976-7413-c92c-e53f-658ed03266b4
* Content: [Connect an existing Linux server to Azure Arc - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/onboard-server-linux)
* Content Source: [docs/manage/hybrid/server/best-practices/onboard-server-linux.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/manage/hybrid/server/best-practices/onboard-server-linux.md)
* Service: **caf**
* Sub-service: **caf-methodology-manage**
* GitHub Login: @likamrat
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thank you.  We've fixed this on this page and about 12 others in the content.  Should be live within two business days.
