### ISSUE TITLE
The  [Sentara Healthcare]  link doesn't work

### ISSUE THREAD

**Issue by lubuffa** [MicrosoftDocs/cloud-adoption-framework#1284]
[Enter feedback here]
The  [Sentara Healthcare]  link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dccac5ff-6be1-d183-e720-9c1d184d0813
* Version Independent ID: f6a6fccf-56db-cf2c-fa1e-cb4cca38430d
* Content: [Examples of fiscal outcomes - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/fiscal-outcomes)
* Content Source: [docs/strategy/business-outcomes/fiscal-outcomes.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/strategy/business-outcomes/fiscal-outcomes.md)
* Service: **caf**
* Sub-service: **caf-methodology-strategy**
* GitHub Login: @mpvenables
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  I have made an update to the page which will be reflected after the next build.
