### ISSUE TITLE
Azure Blueprints (Preview) would never go into GA - 

### ISSUE THREAD

**Issue by mailtogurvindersingh** [MicrosoftDocs/cloud-adoption-framework#1286]
[Enter feedback here]

Azure Blueprints (Preview) would never go into GA - so you should not recommend anything using this in your docs. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b579d9-16cf-ca34-0242-8a5a3740ef03
* Version Independent ID: 64c2e0a8-a179-56fc-bd13-344ae175a7db
* Content: [Standard enterprise governance guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/)
* Content Source: [docs/govern/guides/standard/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/guides/standard/index.md)
* Service: **caf**
* Sub-service: **caf-methodology-govern**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by Zimmergren** [comment]
Thank you for submitting this issue and suggestion, @mailtogurvindersingh, and you're right!

We've got this on our roadmap and backlog to address in the new year.

#please-close
