### ISSUE TITLE
Change URL from WVD to AVD

### ISSUE THREAD

**Issue by phwill1204** [MicrosoftDocs/cloud-adoption-framework#1288]
[Enter feedback here]

The link for this page reads:

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/

Is it not about time we replaced the "WVD" with "AVD"?

So it would read:

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/avd/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b549226d-3d3a-4b4e-0047-7eb0047b5773
* Version Independent ID: 4a972907-db5c-5966-bc09-e67f9e2dda50
* Content: [Migrate end-user desktops to Azure Virtual Desktop - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/)
* Content Source: [docs/scenarios/wvd/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/index.md)
* Service: **caf**
* Sub-service: **caf-scenario-virtual-desktop**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by hallihan** [comment]
Thanks for the feedback. The update for this content is live now.

#please-close
