### ISSUE TITLE
What would be the desired abbrevation for kubernetes node pools?

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/cloud-adoption-framework#1289]
What would be the desired abbrevation for kubernetes node pools?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **caf**
* Sub-service: **caf-methodology-ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
@ckittel - I see `np` in the AKS documentation. What are your thoughts?

**Comment by ckittel** [comment]
`np` is what we use in the [AKS baseline](https://learn.microsoft.com/azure/architecture/reference-architectures/containers/aks/baseline-aks) as well, and is what I would recommend.

**Comment by stephen-sumner** [comment]
@cveld - Thanks for you question. We recommend `np` as the abbreviation for node pools in Azure Kubernetes Service. You'll see that add to the CAF documentation in a day or so. Thanks!
