### ISSUE TITLE
Next step skips many steps

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#129]
Develop an Azure foundation is the next step on this page.  It skips many pages shown on the left in the outline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ae3556-ea43-75a6-f369-085e11d7471d
* Version Independent ID: 8cf010c0-f2fd-382e-96e3-4a61aec400df
* Content: [What is cloud accounting? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/cloud-accounting)
* Content Source: [docs/strategy/cloud-accounting.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/cloud-accounting.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190714

**Comment by alexbuckgit** [comment]
This particular issue has been addressed. We're evaluating broader changes with regard to Next Steps and navigating through the framework.

**Comment by alexbuckgit** [comment]
We've added the request for better consistency in Next Steps to our backlog for prioritization. Thanks for the feedback!
