### ISSUE TITLE
Readiness checklist link is broken

### ISSUE THREAD

**Issue by warnerchavescdp** [MicrosoftDocs/cloud-adoption-framework#1290]
The readiness checklist link is broken, comes back with a 404 not found

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82d6acd7-52c2-0fcd-77ad-a30e96ecbf45
* Version Independent ID: af35206e-2b05-0ae7-8ca9-6e43330e96e6
* Content: [Tools and templates - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/resources/tools-templates)
* Content Source: [docs/resources/tools-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/resources/tools-templates.md)
* Service: **caf**
* Sub-service: **caf-general**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Good catch. That file actually only contained the content:

> The readiness checklist Microsoft Word document has been replaced by an entire [Ready guide](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/). The Ready guide is a series of articles that helps you prepare your Azure environment for cloud adoption through actionable guidance.

Meaning, that file was deprecated, and recently removed because it had been deprecated for a while.  I'll remove the link from the page.
