### ISSUE TITLE
“enterprise-scale-architecture-sap” [Visio file] This link is not working. Please repair, thank you!

### ISSUE THREAD

**Issue by ngelll** [MicrosoftDocs/cloud-adoption-framework#1291]
This link is not working. Please repair, thank you!
https://github.com/microsoft/CloudAdoptionFramework/raw/master/ready/enterprise-scale-architecture-sap.vsdx

"
The following diagram is a conceptual reference architecture that shows the critical design areas in an SAP on Azure landing zone accelerator:
Download a [Visio file](https://github.com/microsoft/CloudAdoptionFramework/raw/master/ready/enterprise-scale-architecture-sap.vsdx) of this architecture.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f1fff-2485-a841-1b26-aa9601d2a121
* Version Independent ID: d8f114ec-93c2-f30b-6ac8-bfa47160813b
* Content: [SAP on Azure landing zone accelerator - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone)
* Content Source: [docs/scenarios/sap/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/sap/enterprise-scale-landing-zone.md)
* Service: **caf**
* Sub-service: **caf-scenario-sap**
* GitHub Login: @PmeshramPM
* Microsoft Alias: **pameshra**

**Comment by ckittel** [comment]
This has been resolved, thanks for letting us know.  I broke it when I did a `master` to `main` branch rename on that repo.

#please-close
