### ISSUE TITLE
Additional suggested tag

### ISSUE THREAD

**Issue by mcsiki** [MicrosoftDocs/cloud-adoption-framework#1296]
Nowadays, most deployments are done with pipelines. For convenience, I recommend adding the git repository URL name-value pair (e.g., 'repositoryURL'). Based on my experience, it greatly reduces the time required to alter the deployments.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7230a9-5b65-919f-1ed7-e4c3647cdc55
* Version Independent ID: 705b4355-78aa-b573-c833-de558da2a958
* Content: [Define your tagging strategy - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-tagging)
* Content Source: [docs/ready/azure-best-practices/resource-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-tagging.md)
* Service: **caf**
* Sub-service: **caf-methodology-ready**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 206037 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
