### ISSUE TITLE
ASR

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/cloud-adoption-framework#1298]
There doesnt seem to be any guidance for ASR in the ALZ model with regards to Subscription placement. So, where would you put ASR in the Azure Landing Zone Architecture. i.e. in the scenario where ASR is either used for DR from on-prem or in Azure  Would this be best placed in an Application Landing Zone under the Corp Subscription?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 206035 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
