### ISSUE TITLE
cloud strategy

### ISSUE THREAD

**Issue by snknchrist** [MicrosoftDocs/cloud-adoption-framework#1299]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c652070d-faad-99b3-b296-d21a37ef7a6a
* Version Independent ID: 6ac12265-53f0-76a3-848d-647bd90eebf5
* Content: [Get started: Manage cloud costs - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/manage-costs#step-1-optimize-enterprise-costs)
* Content Source: [docs/get-started/manage-costs.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/get-started/manage-costs.md)
* Service: **caf**
* Sub-service: **caf-get-started**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
#please-close

@snknchrist closing because this content issue doesn't have any details in it.  Please open a new issue with your content feedback if you have a suggestion for the Cloud Adoption Framework content team.
