### ISSUE TITLE
Inconsistencies.

### ISSUE THREAD

**Issue by nezoic** [MicrosoftDocs/cloud-adoption-framework#13]
I haven't gone through everything but why does it list Azure Storage Accounts to use a prefix of "stor" and then the examples prefix with "st"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/naming-and-tagging#feedback)
* Content Source: [docs/ready/considerations/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by jlorich** [comment]
Similarly - some resources use the A in Azure for an abbreviation and some don’t. In my opinion none should, but at the best least they should be consistent.

“aih” is not intuitive at all when “iot” would make perfect sense. Conversely we have “df” for Azure Data Factory (something people actually call ADF). It should be one way or the other.

**Comment by jlorich** [comment]
Ahh some even use az (like app services). This document is all over the place for no rhyme or reason. There’s no way I can recommend this level of inconsistency to our customers. We should fix it ASAP.
