### ISSUE TITLE
The next step skips several steps

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#130]
The Next step is to Build your cloud adoption plan, but this skips the additional considerations and the Skills relevant to strategy, as shown in the outline on the left of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7842e7a6-a58f-2ec2-1873-da5a3f68f472
* Version Independent ID: b204986b-9463-24e6-7327-eb0c0071401b
* Content: [First cloud adoption project - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/first-adoption-project)
* Content Source: [docs/strategy/first-adoption-project.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/first-adoption-project.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190719

**Comment by alexbuckgit** [comment]
This particular issue has been addressed. We're evaluating broader changes with regard to Next Steps and navigating through the framework.
