### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by jeanphilt** [MicrosoftDocs/cloud-adoption-framework#1300]
[Enter feedback here]
broken links .. error 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e75432e1-7ac1-1f9a-1f9e-7132445c4232
* Version Independent ID: 2b10147a-3aa1-f6ef-dcc9-16eb089f1664
* Content: [Azure Virtual Datacenter - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/resources/vdc)
* Content Source: [docs/resources/vdc.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/resources/vdc.md)
* Service: **caf**
* Sub-service: **caf-general**
* GitHub Login: @tracsman
* Microsoft Alias: **martinek**

**Comment by ckittel** [comment]
Thank you for bringing this to our attention.  That material has been archived for a while and no longer supported, but looks like we still have some legacy references to it in CAF.  I'll see what I can do to remove this page as the backing material was no longer relevant.
