### ISSUE TITLE
"There's a direct correlation between the number of partitions with SHIR cores and Azure IR nodes"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#1301]
Can you please clarify the meaning of this sentence in the text? 

For example, we are seeing 200 partitions created by the CDC source. The number of cores within the SHIR VM and the number of nodes within the Azure IR is much smaller. We are trying to understand the implications and performance improvement avenues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41dcab4d-5c8f-e83e-7436-6554d330e474
* Version Independent ID: 41dcab4d-5c8f-e83e-7436-6554d330e474
* Content: [Performance and troubleshooting for SAP data extraction - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/sap-lza-data-extraction-performance-troubleshooting)
* Content Source: [docs/scenarios/sap/sap-lza-data-extraction-performance-troubleshooting.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/sap/sap-lza-data-extraction-performance-troubleshooting.md)
* Service: **caf**
* Sub-service: **caf-scenario-sap**
* GitHub Login: @PmeshramPM
* Microsoft Alias: **pameshra**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 209000 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
