### ISSUE TITLE
Recommendation for "Require the following tags on all resources" does not work with all resource types

### ISSUE THREAD

**Issue by rybal06** [MicrosoftDocs/cloud-adoption-framework#1305]
It may be good to revisit the recommendation to require tags on all resources. The word require seems to imply using a deny assignment; which breaks the provisioning of certain Azure resource types:

Examples:
1. **Network Intent Policies**: While using the portal, it is not possible to provide tags while deploying a network intent policy. You can provide them post-deployment only. It is not possible to deploy network intent policies using the Azure Portal if this recommendation is followed.
2. **Azure DataBricks**: Azure databricks automatically deploys an additional resource group. Most of the resources deployed by the Azure platform do correctly obtain tags; but not all of them do. Additionally, the network intent policy Databricks creates while utilizing private networking for the underlying compute does not inherit or obtain tags.
3. **Azure SQL**: The Azure SQL platform itself creates a Microsoft.Sql/servers/databases resource named "master" internally. This does not inherit tags from the Azure SQL server resource. Implementing this recommendation makes it impossible to deploy an Azure SQL instance.
4. **App Insights Dashboards**: Deploying a dashboard from within app insights creates a new Azure resource without tags. You can assign tags post-creation; but not during creation. The recommended policy makes it impossible to create App Insight dashboards using the Azure Portal.

I apologize, my notes are a bit dated on these issues so some of these may be resolved now; but I wanted to bring this to the attention of others to avoid other customers facing the same challenges we are.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b579d9-16cf-ca34-0242-8a5a3740ef03
* Version Independent ID: 64c2e0a8-a179-56fc-bd13-344ae175a7db
* Content: [Standard enterprise governance guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/)
* Content Source: [docs/govern/guides/standard/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/guides/standard/index.md)
* Service: **caf**
* Sub-service: **caf-methodology-govern**
* GitHub Login: @martinekuan
* Microsoft Alias: **martinek**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 212840 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
