### ISSUE TITLE
Sania

### ISSUE THREAD

**Issue by nsania96** [MicrosoftDocs/cloud-adoption-framework#1307]
[Enter feedback here]
Good for decision

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 016c7c26-85f0-9c5d-3c8f-7d27010a1d9d
* Version Independent ID: 016c7c26-85f0-9c5d-3c8f-7d27010a1d9d
* Content: [Understand the roles and responsibilities for cloud-scale analytics in Azure - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/organize-roles-responsibilities)
* Content Source: [docs/scenarios/cloud-scale-analytics/organize-roles-responsibilities.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/organize-roles-responsibilities.md)
* Service: **caf**
* Sub-service: **caf-scenario-analytics**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
No action.

##close-off

**Comment by skabou** [comment]
It is unclear what the issue is.  If you are still experiencing an issue, please re-open with additional information.
