### ISSUE TITLE
rooted, not routed

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#131]
Misspelled work in second sentence on this page.  Should be rooted, not routed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8127d5cd-51a6-0aef-d5ce-4476ce4dd46a
* Version Independent ID: 6d9bedd0-092a-bde6-2e0b-32e292a9211b
* Content: [Balance competing priorities - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/balance-competing-priorities)
* Content Source: [docs/strategy/balance-competing-priorities.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/balance-competing-priorities.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190720

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
