### ISSUE TITLE
Azure Monitor alert processing rule abbreviation missing

### ISSUE THREAD

**Issue by khaliddermoumi** [MicrosoftDocs/cloud-adoption-framework#1311]
The abbreviation for Azure Monitor alert processing rules is missing. I propose "apr" as an abbreviation:

| Resource Type | Resource Provider Namespace | Abbreviation |
|---------------|-----------------------------|--------------|
| Azure Monitor alert processing rules | `Microsoft.AlertsManagement/actionRules` | apr |

This issue relates to the [list on the naming guide abbreviations page](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)

**Comment by stephen-sumner** [comment]
@khaliddermoumi - Thanks for your suggestion! We've added the abbreviation as you recommended. You should see it shortly.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/5407

**Comment by stephen-sumner** [comment]
#please-close
