### ISSUE TITLE
Landing Zone diagram - VPN P25

### ISSUE THREAD

**Issue by ak-1111** [MicrosoftDocs/cloud-adoption-framework#1316]
On the diagram the VPN should be P2S instead of P25. Point to Site = P2S.

**Comment by skabou** [comment]
Hey there @ak-1111 , thank you for your feedback.  What article is this comment in regard to?

**Comment by ak-1111** [comment]
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/

Figure 1: Azure landing zone conceptual architecture.

**Comment by skabou** [comment]
Nice catch!  I'll make sure this gets addressed.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/5536

**Comment by skabou** [comment]
Thanks for your feedback. This has been addressed and will go live during the next build/publish.

**Comment by skabou** [comment]
#please-close
