### ISSUE TITLE
management group example is not aligned with CAF landing zone guidance

### ISSUE THREAD

**Issue by kewalaka** [MicrosoftDocs/cloud-adoption-framework#1318]
The feedback in this section mentioned organising management groups by environments:

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/organize-subscriptions#example-use-cases

This seems to contradict general guidance that management groups should be organised by archetypes rather than environments:

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/management-application-environments#environment-based-management-group-challenges

**Comment by stephen-sumner** [comment]
@kewalaka - Thanks for bring that to our attention. We're working on clarifying this guidance. Thank you for your feedback!

**Comment by stephen-sumner** [comment]
#please-close
