### ISSUE TITLE
Next steps skips a step

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#132]
Next step goes to Prioritize and define workloads, but the outline on the left shows the next step as Deploy the tempalte to Azure DevOps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8598a1-1be6-8707-4175-3f98449dae3a
* Version Independent ID: 35d33d80-2533-3b02-ad69-21e8de761941
* Content: [Prerequisites for a cloud adoption plan - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/prerequisites)
* Content Source: [docs/plan/prerequisites.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/plan/prerequisites.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#190761

**Comment by alexbuckgit** [comment]
This particular issue has been addressed. We're evaluating broader changes with regard to Next Steps and navigating through the framework.
