### ISSUE TITLE
There is no Introduction to Azure Setup

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#133]
This page says:
 Go to the Azure Quickstart Center in the Azure portal, select Introduction to Azure Setup, and then follow the step-by-step instructions.
When I click the link to Azure Quickstart Center I do not see an Introduction to Azure Setup.  
Please indicate the correct steps to find it or change the wording to indicate where to start within the Azure Quickstart Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccae000a-e695-350b-e765-e7ae9b9dd67f
* Version Independent ID: bae3228c-33d9-a9e4-9c26-840756d0f75e
* Content: [Azure setup guide: Before you start - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/)
* Content Source: [docs/ready/azure-setup-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @timleyden
* Microsoft Alias: **kfollis**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191178

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
