### ISSUE TITLE
Azure landing zone design areas - Numbers vs. letters in references / legend

### ISSUE THREAD

**Issue by paraenggu** [MicrosoftDocs/cloud-adoption-framework#1331]
The [Azure landing zone design areas and conceptual architecture](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas) page includes the [diagram of the Azure landing zone architecture](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/media/ns-arch-cust-expanded.svg) which uses numbers for each design area.

<img src="https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/1186157/b2ccebcf-6856-41d5-8870-8ac1ea9ea583" width=50% height=50%>

The [Environment design areas](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas#environment-design-areas) paragraph however, mentions letters instead as references:

> The design areas are indicated with the **letters "A" through "I"** to illustrate the hierarchy of resource organization in the conceptual architecture

While inspecting the [ns-arch-cust-expanded.svg](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/media/ns-arch-cust-expanded.svg) SVG, it seems that the numbers where added on top of the (hidden) letters.

<img src="https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/1186157/7cbe1009-362d-463a-8b29-ab479ed81722" width=50% height=50%>

It would be great to have matching references between the diagram and the legend.

**Comment by skabou** [comment]
Thanks for your feedback.  This has been addressed and will go live during the next build/publish.

**Comment by skabou** [comment]
#please-close
