### ISSUE TITLE
Tenant-wide Reader permissions for Landing Zone Admins (Prevent Log Analytics Data Query Access)

### ISSUE THREAD

**Issue by RobertPaulson90** [MicrosoftDocs/cloud-adoption-framework#1334]
Hi,

We recently discovered that the default `Reader` role in Azure grants access to query data in Log Analytics workspaces. This was unexpected, as our initial understanding was that the Reader role only provided access to control plane metadata.

Could you please clarify:

Is this the intended behavior of the Reader role?

Have there been any recent changes to the Reader role's permissions related to Log Analytics data?

What is Microsoft's recommended approach to providing read access to control plane metadata without granting access to customer data?

To address this, we tested a custom role with the following configuration, which did not work as intended.

```json
{
    "properties": {
        "roleName": "Custom Reader",
        "description": "Testing... Azure RBAC Custom role",
        "assignableScopes": [],
        "permissions": [
            {
                "actions": [
                    "*/read"
                ],
                "notActions": [
                    "Microsoft.OperationalInsights/workspaces/*"
                ],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}

```

The only solution we can currently imagine involves creating a new custom reader role containg every single service except Log Analytics, which would be difficult to maintain.

How can our landing zone operations team have secure access to controlplane metadata without being able to query any LA data.

Thank you.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 260822 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by RobertPaulson90** [comment]
Thanks @skabou. Will you respond back here when there is information about ticket 260822 or how can I be kept in the loop?
