### ISSUE TITLE
What resources?

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#134]
Seems to me that in Plan you figure out where you are at and what you want to do.  And in Ready you are saying to organize the resources.  But I'm not sure where you decided what resources you should be using to meet the Plan.  Like which database structure, whether you are using a VM and how much management of it you want to do vs Microsoft managing it, etc.  Just seems to me like you are missing a whole section.  Did you even previously point to the services page that explains each service available from Microsoft?  Or explain about the case study examples?  etc.  Maybe I missed this part previously in the Cloud Adoption Framework?  Seems to me like you need a whole other section between Plan and Ready for us Innovators.  I know, because this is the part I am currently stuck on deciding.  I know there's a page someplace where I can ask Microsoft for advice, but I can't find it.  Maybe put a link to that.

I believe you previously point to where to get training for each service.  But where in your Cloud Adoption Framework are you helping us to quickly and easily decide which services we need?  Now you are telling us to Organize our resources.  Hold on there, WHAT resources???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3604b57a-0baa-577d-529e-e36eeb8396d2
* Version Independent ID: b43d934b-49ac-3c0f-295c-334259d65826
* Content: [Organize Azure resources effectively - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/organize-resources?tabs=AzureManagmentGroupsAndHierarchy)
* Content Source: [docs/ready/azure-setup-guide/organize-resources.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/organize-resources.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @laraaleite
* Microsoft Alias: **kfollis**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191181

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
