### ISSUE TITLE
No feedback section available for Adopt-Innovate-Overview page

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#135]
No feedback section available for Adopt-Innovate-Overview page
Add one.

So this comment is for the Innovate &gt; Overview page.  You have 4 areas on this page: Business value concerns, Azure innovation guide, Best practices, and Feedback loops.  They link to other areas.  However, the links do not have a different color or underline so you don't know they are links unless you happen to mouse over them.  This same comment applies to other Overview pages in other section, although I didn't leave feedback about it previously.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba58e1d5-e74a-fc36-ea0c-d236714c19de
* Version Independent ID: 6acb3ed9-00e0-655d-f7bf-98f62398bb21
* Content: [Azure innovation: Before you start - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/)
* Content Source: [docs/innovate/innovation-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @Matticusau
* Microsoft Alias: **mlavery**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191184

**Comment by alexbuckgit** [comment]
The current tab behavior is by design.
