### ISSUE TITLE
The 4 tabs are links but need color or underline to indicate they are links

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#136]
Quantitative feedback for web apps, quantitative feedback for APIs, Qualitative feedback and Close the loop with pipeline tabs are links but need color and/or underline to indicate that they are links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2db3add-d6fc-5b87-1419-7fa2437dfaa1
* Version Independent ID: 1ab86823-5220-325d-fbe5-56484344273d
* Content: [Azure innovation: Prepare for feedback - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/adoption?tabs=Quantitative-Apps)
* Content Source: [docs/innovate/innovation-guide/adoption.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/adoption.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191185

**Comment by alexbuckgit** [comment]
Current tab behavior is by design.
