### ISSUE TITLE
Open source on Azure

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#137]
You talk about 80 to 90 percent of new application development begins with open-source code but that's not what Open source on Azure link actually talks when you go to it.    

And BTW, (not talking about the Cloud Adoption Framework) that's the problem with C# in general compared to Python, from what I can find.  There are no good open source repositories for application development code other than the .NET Framework, but there are for Python.  Sure there are Visual Studio add-ons, and Azure Marketplace.  But these aren't really about the 80 to 90% open-source code that you talk about.  Wish you'd bring this to the attention of others.  I really think this is needed for C# to keep market share.

To summarize concerning this page, you make an excellent point that developers use 80 to 90 % open source code for new apps, but I think you need additional links for this statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dc745-f2dd-406b-2a9b-016775c9b7ed
* Version Independent ID: c0d94094-2598-acb4-5d9f-71262cc7feb2
* Content: [Azure innovation: Empower adoption - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/ci-cd?tabs=Collaboration)
* Content Source: [docs/innovate/innovation-guide/ci-cd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/ci-cd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @absheik
* Microsoft Alias: **absheik**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191209

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
