### ISSUE TITLE
tabs are links but do not indicate it through color or underline

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#138]
tabs (developer productivity, innovate collaboratively, innovation characteristics, liveops innovation) are links but do not indicate it through color or underline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dc745-f2dd-406b-2a9b-016775c9b7ed
* Version Independent ID: c0d94094-2598-acb4-5d9f-71262cc7feb2
* Content: [Azure innovation: Empower adoption - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/ci-cd?tabs=Collaboration)
* Content Source: [docs/innovate/innovation-guide/ci-cd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/ci-cd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @absheik
* Microsoft Alias: **absheik**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191210

**Comment by alexbuckgit** [comment]
The tab appearance is by design. The open tab is highlighted.
