### ISSUE TITLE
IoT Hub and Device Provisioning Services go to same location

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#141]
IoT Hub and Device Provisioning Services go to same document, so why have both, one below the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e34a149-c1f6-191c-d3f2-54fdae1cf6ab
* Version Independent ID: 4533a56f-d154-8239-6f3a-c935a0a4a5a6
* Content: [Azure innovation: Interact via devices - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/devices?tabs=IoTHub)
* Content Source: [docs/innovate/innovation-guide/devices.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/devices.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @UmarMohamedUsman
* Microsoft Alias: **umarm**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191215

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
