### ISSUE TITLE
make each of the toolchain elements a link

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#142]
I don't know all of these.  Please make each a link to the correct document

Power BI
Azure Data Catalog
Azure SQL Data Warehouse
Azure Cosmos DB
Azure Database for PostgreSQL
Azure Database for MySQL
Azure Database for MariaDB
Azure Database for PostgreSQL Hyperscale
Azure Data Lake
Azure Database Migration Service
Azure SQL Database, with or without managed instances
Azure Data Factory
Azure Stream Analytics
SQL Server Integration Services
Azure Stack
SQL Server Stretch Database
Microsoft Azure StorSimple
Azure Files
Azure File Sync
PolyBase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4e9b66-e21e-9b0b-4fb8-131646d7540f
* Version Independent ID: 8efc6c81-9d7f-fa77-ebfd-ad983f77ab2a
* Content: [Innovation tools to democratize data - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/data)
* Content Source: [docs/innovate/best-practices/data.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/best-practices/data.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191324

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
