### ISSUE TITLE
Next Steps - consider removing

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#143]
Not just for this page, consider removing Next steps section since frequently you miss a lot of the steps in the outline if you use the Next steps guidance.  For example, this page's Next Step skips many steps in the Adopt section and goes to the Govern section instead.

If you don't remove the Next steps section, you might want to rename it and not make it a big blue button so people don't miss important docs by skipping to another doc further because it is recommended as the next step.

At minimum, as I suggested in another Feedback item, if you go to a Next step that is not the next item in the outline to the left of the page, then at least open it in a new browser tab so people can get back to the original document to continue on with the next item in the outline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa05effd-f29a-18d2-7418-781eaae59210
* Version Independent ID: 5f09aec6-30fb-9573-a38b-8d8c16936306
* Content: [What is data classification? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/policy-compliance/data-classification)
* Content Source: [docs/govern/policy-compliance/data-classification.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/policy-compliance/data-classification.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191340

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
