### ISSUE TITLE
Provide links to the toolchain

### ISSUE THREAD

**Issue by homeworryfree** [MicrosoftDocs/cloud-adoption-framework#144]
Add the links for these:
Azure Machine Learning
Azure HDInsight
Hadoop R ScaleR
Azure SQL Data Warehouse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fa3836-822d-0235-1ebf-bc05d217f3f0
* Version Independent ID: 823083a4-4f1e-a040-7b9b-14be0ebe0304
* Content: [Innovation tools to predict and influence - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/predict?view=azure-bot-service-4.0)
* Content Source: [docs/innovate/best-practices/predict.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/best-practices/predict.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#191538

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
