### ISSUE TITLE
Phrase repeated

### ISSUE THREAD

**Issue by anthonyonazure** [MicrosoftDocs/cloud-adoption-framework#149]
"to define" is repeated in this sentence.
A minimum viable product is commonly used to define to define the smallest unit of something that can produce tangible value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287b62-25ba-d5d1-e01e-c3c140dad610
* Version Independent ID: 2eb2edd6-51e7-85a1-baa8-9eb43f855778
* Content: [Understand business risk during cloud migration - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/policy-compliance/business-risk#what-is-a-business-risk-mvp)
* Content Source: [docs/govern/policy-compliance/business-risk.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/policy-compliance/business-risk.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#194590

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
