### ISSUE TITLE
update text related to Azure VPN bandwidth from 1.25 Gbps to 10 Gbps.

### ISSUE THREAD

**Issue by zeinab-mk** [MicrosoftDocs/cloud-adoption-framework#151]
Azure VPN Gateway has a maximum bandwidth of 10 Gbps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63badde4-b985-a969-fc40-140da14ef383
* Version Independent ID: 8f5cf934-82ca-8f8a-fcbd-801bacdfa583
* Content: [Review your network options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/networking-options#feedback)
* Content Source: [docs/ready/considerations/networking-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/networking-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#194677

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
