### ISSUE TITLE
I have an enterprise NAS (such as NetApp Filers or Dell-EMC Isilon).

### ISSUE THREAD

**Issue by shawnweisfeld** [MicrosoftDocs/cloud-adoption-framework#156]
is "Filers" correct? should it be "Files" in "I have an enterprise NAS (such as NetApp Filers or Dell-EMC Isilon)."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acd2fd4-b22c-5c11-e891-cc4993d9891e
* Version Independent ID: 1acbff98-4a94-53f5-dd45-8f22637602b4
* Content: [Review your storage options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/storage-options#feedback)
* Content Source: [docs/ready/considerations/storage-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/storage-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#199047

**Comment by JanetCThomas** [comment]
This issue has been fixed.  Thanks!
