### ISSUE TITLE
Formatting issue with the note

### ISSUE THREAD

**Issue by deltadan** [MicrosoftDocs/cloud-adoption-framework#170]
There is a note with formating issues in this article.  

&gt; [!NOTE]
&gt; Assessments shouldn't just be limited to using tooling to discover information about your environment. You should also schedule time to speak to business owners, end users, and other members of the IT department to fully understand of what is happening in the environment and understand factors that tooling cannot tell you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c298c45-227e-6791-0959-c9ec79584f10
* Version Independent ID: 888192df-1dda-d757-46c5-2884b7f50591
* Content: [Assess on-premises workloads for Azure migration - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/contoso-migration-assessment)
* Content Source: [docs/plan/contoso-migration-assessment.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/plan/contoso-migration-assessment.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#205907

**Comment by JanetCThomas** [comment]
This issue has been fixed.  Thanks!
