### ISSUE TITLE
Azure EA Content Pack reference

### ISSUE THREAD

**Issue by dvherk** [MicrosoftDocs/cloud-adoption-framework#171]
I belief the EA Content Pack is deprecated. There was a new Consumption Insight connector (https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights), but has meanwhile also been update to Azure Costmangement PowerBi Connector (https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management).
Please update the table above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0725b78b-10ee-3868-12be-d9b6c7a2740b
* Version Independent ID: fa71f1c3-7dc5-ac48-6eaf-3d880b84cf38
* Content: [Cost Management tools in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/cost-management/toolchain)
* Content Source: [docs/govern/cost-management/toolchain.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/cost-management/toolchain.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#206123

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
