### ISSUE TITLE
Subscription or Subscription Type? Region or Sub region?

### ISSUE THREAD

**Issue by mattruma** [MicrosoftDocs/cloud-adoption-framework#172]
Might just be me ... but seems like there might be some inconsistencies in some of the network naming recommendations as per the guidance at https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#recommended-naming-components?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#recommended-naming-components)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#206908

**Comment by stephen-sumner** [comment]
@JanetCThomas @alexbuckgit - my PR for this merged 

PR -  https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3768

It's probably safe to close this issue.
