### ISSUE TITLE
Az Databricks is not following the CAF naming recommendations?

### ISSUE THREAD

**Issue by dwainew** [MicrosoftDocs/cloud-adoption-framework#173]
Creating a databricks workspace, without specifying a pre-existing vnet, automatically creates a new rg, nsg and vnet, without following the recommendations specified here?  Even the easily accommodated names within the new rg scope aren't following these rules.  This doesn't engender much faith that CAF is being taken seriously within MS.  Please advise.

New vnet: workers-vnet
New nsg: workers-sg
New rg: Databricks-&lt;workspace rg name&gt;-$RANDOM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#feedback)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#207220

**Comment by alexbuckgit** [comment]
We've added this item to our backlog and are working with our many internal stakeholders to drive a common approach across our services. Thanks for the feedback!
