### ISSUE TITLE
Change "Strategy and Plan template" to "Cloud Adoption Plan template"

### ISSUE THREAD

**Issue by mpvenables** [MicrosoftDocs/cloud-adoption-framework#174]
The "Strategy and Plan template" is incorrectly named, and should be changed to "Cloud Adoption Plan template."

URL: https://archcenter.blob.core.windows.net/cdn/fusion/readiness/Microsoft-Cloud-Adoption-Framework-Strategy-and-Plan-Template.docx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d6acd7-52c2-0fcd-77ad-a30e96ecbf45
* Version Independent ID: af35206e-2b05-0ae7-8ca9-6e43330e96e6
* Content: [Tools and templates - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/tools-templates)
* Content Source: [docs/reference/tools-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/tools-templates.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by alexbuckgit** [comment]
Won't fix. The chosen name is "Strategy and Plan template".
