### ISSUE TITLE
Management Group Hierarchy

### ISSUE THREAD

**Issue by phwill1204** [MicrosoftDocs/cloud-adoption-framework#175]
The suggestion in the graphic above that geography is higher in the hierarchy than environment is opposing to the guidance in the Management group documentation graphic:

https://docs.microsoft.com/en-us/azure/governance/management-groups/overview#hierarchy-of-management-groups-and-subscriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1986a7b3-58ca-7e02-3dcf-8f3a6cac7bdc
* Version Independent ID: f2efbcd5-666d-7399-3f6a-58bc58d29f12
* Content: [Governance guide for complex enterprises - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/complex/)
* Content Source: [docs/govern/guides/complex/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/guides/complex/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#208422

**Comment by alexbuckgit** [comment]
The diagram in the governance guide is aligned with the narrative detailed in the page linked in Next Steps. Different organizations may choose to put geography above business unit (or vice-versa) in their hierarchy if it better reflect their business organization.

Closing this issue. Thanks for the feedback.
