### ISSUE TITLE
Add Azure Migrate and remove ASR in the Migration Section

### ISSUE THREAD

**Issue by sastrykn** [MicrosoftDocs/cloud-adoption-framework#176]
Add "Azure Migrate" and remove "ASR" as now Azure Migrate is the suggest tool.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#210390

**Comment by JanetCThomas** [comment]
@sastrykn Could you please let us know which topic this suggestion applies to?  Thanks!

**Comment by sastrykn** [comment]
I thought the feedback typically is attached to the page, here I do not find the page link. Searched for it, but could not find it. This was about our migration tooling to the Cloud, the article only mentioned ASR, however, now our primary tool is Azure Migrate.

**Comment by BrianBlanchard** [comment]
Closed in aPR to be released in the next few days
