### ISSUE TITLE
Best practice for separating production from non-production resources

### ISSUE THREAD

**Issue by FallenHoot** [MicrosoftDocs/cloud-adoption-framework#178]
The suggestion in this section would be how or what is the best practice when it comes to separating subscriptions between non-prod (dev/test) and prod. This is a common question that CSA and people just starting out within Azure will get asked or think about. 
Of course, depends on a lot of variables, but it would be great to show an enterprise best practice workflow.  

Should they be separated by Business Units (BU) and then depending on the workload, the resource group gets separated based on the project and environment ({project}-Dev/{project}-Test/{project}-Prod).

Or should we use the (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/subscriptions/) of separating the subscription by environments by (Dev/Test/Prod). The only issue I see with this is if a customer gets above 800 resource groups (projects)

A crude drawing would look something like this top from bottom:
Tenant
Management Groups (Split by BU with attached policies based on subscription requirements)
Subscription (Split by BU with attached policies based on subscription requirements.)
*Maybe talk about a Sandbox subscription for people to learn but can be restricted with attached policies based on Subscription requirements
Resource Groups (are used for projects within those BU for the environment of choice.)
Services/Resources (for the project)

```
                                                              Tenant
               |                                                   |                                         | 
            BU-1 (MG + Policy)                      BU-2 (MG + Policy)           BU-3 (MG + Policy)
               |                                                   |                                         |
            BU-1 (Sub + Policy)                      BU-2 (Sub + Policy)          BU-3 (Sub + Policy)
               |                          |                                                                |                            | 
{project}-Prod-1      {project}-Test-1                              {project}-Prod-1      {project}-Test-1  
 (RES + Policy)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3604b57a-0baa-577d-529e-e36eeb8396d2
* Version Independent ID: b43d934b-49ac-3c0f-295c-334259d65826
* Content: [Organize Azure resources effectively - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/organize-resources?tabs=AzureManagementGroupsAndHierarchy#feedback)
* Content Source: [docs/ready/azure-setup-guide/organize-resources.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/organize-resources.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @laraaleite
* Microsoft Alias: **kfollis**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#212661

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
