### ISSUE TITLE
Azure SQL MI GA

### ISSUE THREAD

**Issue by deltadan** [MicrosoftDocs/cloud-adoption-framework#18]
This article shows the wrong information. https://techcommunity.microsoft.com/t5/Microsoft-Data-Migration/Announcing-General-Availability-of-Azure-SQL-Database-Managed/ba-p/368706

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c1b11a-7bd3-6ed2-d9ad-ec31da29bd55
* Version Independent ID: 5bddd6fb-c779-f408-94bf-937934c5ca29
* Content: [Rehost an on-premises app by migrating to Azure VMs and Azure SQL Database Managed Instance - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance#feedback)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-rehost-vm-sql-managed-instance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
update to be released in next push to live site.
