### ISSUE TITLE
Networking section missing networking resource type naming recommendations

### ISSUE THREAD

**Issue by JuliaHazelwood** [MicrosoftDocs/cloud-adoption-framework#183]
This section: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#example-names-networking
is missing many of the networking resource types, for example:
-ExpressRoute circuit
-ExpressRoute connections
-vWAN and vWAN hub resources
-Azure Firewall

It seems this section of the documentation should match the corresponding resource name rules documentation for Networking listed here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftnetwork

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#example-names-networking)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#218399

**Comment by WendyRing** [comment]
Thanks for reporting this. Microsoft Internal DevOps Bug ID AB#218399 has been resolved.
