### ISSUE TITLE
Best Practices Source Code link 404

### ISSUE THREAD

**Issue by wayneme75** [MicrosoftDocs/cloud-adoption-framework#186]
The BP source code link under manage is 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d6acd7-52c2-0fcd-77ad-a30e96ecbf45
* Version Independent ID: af35206e-2b05-0ae7-8ca9-6e43330e96e6
* Content: [Tools and templates - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/tools-templates)
* Content Source: [docs/reference/tools-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/tools-templates.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#219188

**Comment by alexbuckgit** [comment]
This issue has been fixed. Thanks!
