### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by richardmunn17** [MicrosoftDocs/cloud-adoption-framework#187]
Sorry to be a pedant, but these jarred a bit when reading this article and I lost concentration for a bit:

"Before deploing landing zones," missing a 'y'.
'seperation' not 'separation' used in a few places, but correct in others.
' isolations of tasks'
' to scale you adoption ' - 'your'

Overall, a good intro, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6230652-e478-a07e-45cf-5d560c276c13
* Version Independent ID: 888cb6ce-2c26-3d98-1327-c91805083665
* Content: [What is a landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/#feedback)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#219377

**Comment by alexbuckgit** [comment]
Not pedantic at all. :-)
These have been fixed. Thanks for noticing!
