### ISSUE TITLE
Quickstart title has changed

### ISSUE THREAD

**Issue by grayjeremy** [MicrosoftDocs/cloud-adoption-framework#188]
Looks like we changed "Migrate your environment to Azure" in the green tooltip to "Azure migration guide"...probably need to update this doc to agree. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45820f5-5487-da92-83f2-828a702797da
* Version Independent ID: 748e6375-5f69-62a1-6ea1-24ba5dc5972e
* Content: [Introduction to the Azure migration guide - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-migration-guide/?tabs=MigrationTools)
* Content Source: [docs/migrate/azure-migration-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-migration-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @Matticusau
* Microsoft Alias: **mlavery**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#219605

**Comment by JanetCThomas** [comment]
This issue has been fixed.  Thanks!
