### ISSUE TITLE
Sandbox environment

### ISSUE THREAD

**Issue by rajashekhargundeti** [MicrosoftDocs/cloud-adoption-framework#189]
[Enter feedback here]
Hi,
my scenario is: 
I have to have two different workloads/projects under one subscription.
Each workload/project would have two environments like prod and non-prod.
A set of users would be assigned to each workload.
Each user would have a full fledged sandbox environment for each workload like he should be able to spin all kinds of resources, not just limited to VMs and Secrets(except the ones permitted by global admin) and his resources should be isolated from others users'

A user would be assigned as a owner to a workload/project and shouldn't access other workloads.

How should this be designed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f39eebf-968a-e696-f2ff-258562f9231e
* Version Independent ID: 81d347c9-d591-d31d-33e0-d637ed668a64
* Content: [Multiple team governance design in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/governance-multiple-teams)
* Content Source: [docs/govern/resource-consistency/governance-multiple-teams.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/resource-consistency/governance-multiple-teams.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#221663

**Comment by alexbuckgit** [comment]
Please review the article series below to establish separate subscriptions for production and non-production workloads. Multiple workloads can reside in each of these subscriptions.

https://docs.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions
