### ISSUE TITLE
Unable to create service principal

### ISSUE THREAD

**Issue by rajashekhargundeti** [MicrosoftDocs/cloud-adoption-framework#191]
Hi team,

i have followed https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/governance-multiple-teams article to create two workloads under one subscription.
I have created identities/accounts for two workload owners, created two resource groups for each workload and assigned them to workload owners.
Now, workload owners can create any resource with in the group through azure portal.

But the problem we are facing now is " workload owners are unable to create service principals".

both of below commands are failing with "Insufficient privileges to complete the operation.":
az ad sp create-for-rbac --skip-assignment --name "myappsp"

az ad sp create-for-rbac --skip-assignment -n "myappsp" --role contributor --scopes /subscriptions/<subId>/resourceGroups/<rg1>

How can i let users create a SP to automate stuff?

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#222494

**Comment by alexbuckgit** [comment]
Creating service principals requires Azure Active Directory admin permissions. You probably don't want to assign these rights to all of your workload owners. Instead, you can have Azure AD admins create the service principals required and then use those existing service principals to automate other tasks.

For more information, see:
https://docs.microsoft.com/powershell/azure/create-azure-service-principal-azureps?view=azps-4.5.0
