### ISSUE TITLE
table line up hard to read using <br> suggest MD table

### ISSUE THREAD

**Issue by eric-camplin** [MicrosoftDocs/cloud-adoption-framework#193]
|                 Critical business events                 |                  Migration                  |                    Innovation                   |
|:--------------------------------------------------------:|:-------------------------------------------:|:-----------------------------------------------:|
| Datacenter exit                                          | Cost savings                                | Preparation for new technical capabilities      |
| Merger, acquisition, or divestiture                      | Reduction in vendor or technical complexity | Building new technical capabilities             |
| Reduction in capital expenses                            | Optimization of internal operations         | Scaling to meet market demands                  |
| End of support for mission-critical technologies         | Increase in business agility                | Scaling to meet geographic demands              |
| Response to regulatory compliance changes                | Preparation for new technical capabilities  | Improved customer experiences and engagements   |
| New data sovereignty requirements                        | Scaling to meet market demands              | Transformation of products or services          |
| Reduction of disruptions and improvement of IT stability | Scaling to meet geographic demands          | Market disruption with new products or services |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e48aaf-b0c5-ea0e-2d5d-af0f53affd3a
* Version Independent ID: 73399b00-c2a0-2aca-929f-f19e97ddab94
* Content: [Why are we moving to the cloud? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/motivations)
* Content Source: [docs/strategy/motivations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/motivations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#224317

**Comment by JanetCThomas** [comment]
This issue has been addressed. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/motivations
