### ISSUE TITLE
Cost Template references "Actionable Journeys section of CAF"

### ISSUE THREAD

**Issue by phduf** [MicrosoftDocs/cloud-adoption-framework#195]
In the word document on the web site for the cost management template, it references the "Actionable Journeys section of CAF". While the hyperlink goes to the cloud governance page, there is no reference to the words "Actionable Journeys "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14c03ac-b5c4-3a40-4274-6829f21997fb
* Version Independent ID: 2dc04807-9f40-d63f-34e9-a0bd93cd166b
* Content: [Risk tolerance metrics and indicators in the Cost Management discipline - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/cost-management/metrics-tolerance)
* Content Source: [docs/govern/cost-management/metrics-tolerance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/cost-management/metrics-tolerance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by JanetCThomas** [comment]
This issue has been resolved.
