### ISSUE TITLE
More Clarifications for landing zone refactoring

### ISSUE THREAD

**Issue by khairop** [MicrosoftDocs/cloud-adoption-framework#197]
In this article, the author  related the number of workloads with the readiness of the production environment, Not sure how the number of the 10 worklaods came up and needs to be clarified if the author refers to the test or production environment.  For example " .... first 10 workload and then first prod workload ....": This implies that 10 workload are probably in test/dev tenant or they are in production without any embedded security principles.
Additionally its not clear which design principles are included in the first landing zone (which of the five pillars, which are the minimum default for the landing zone?) . It seems that the author proposes a two-lanes model (the cloud adoption team and and the cloud platform team). Which is in charge of what? Are any specific roles and responsibilities  for both teams?  How many iterations and time are estimated to deliver the "cloud excellence state" . This reflects costs and resources and the total TCO. 

Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74cbae87-6a54-46b3-773a-a6fc2a44367b
* Version Independent ID: 77054fb0-5c40-c68f-d027-b495fccd7fa8
* Content: [Refactor landing zones - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/refactor)
* Content Source: [docs/ready/landing-zone/refactor.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/refactor.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#229821

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
