### ISSUE TITLE
Best query experience section

### ISSUE THREAD

**Issue by mikedzikowski** [MicrosoftDocs/cloud-adoption-framework#201]
[Enter feedback here]
 "If you're looking for trends across all your data, it makes sense to import all your data into **Azure Logs**, unless it's already in Application Insights."

Should this stay Azure Log Analytics? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69e4c5c-5c2a-db06-0004-eb82266ff2d8
* Version Independent ID: e38b7173-583b-f294-3f6f-cc6f7b11e70c
* Content: [Cloud monitoring guide: Alerting - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/monitor/alerting)
* Content Source: [docs/manage/monitor/alerting.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/monitor/alerting.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#232119

**Comment by MGoedtel** [comment]
@mikedzikowski - Thanks for raising this question.  It should actually state "Azure Monitor Logs" to align with our current taxonomy for Azure Monitor.  @JanetCThomas - I can address this since I'm the original author.  Thanks.

**Comment by JanetCThomas** [comment]
This issue has been resolved.

**Comment by JanetCThomas** [comment]
Thank you @MGoedtel
