### ISSUE TITLE
 levels of the hosting hierarchy broken link in the initial decision template

### ISSUE THREAD

**Issue by kknight-valorem** [MicrosoftDocs/cloud-adoption-framework#202]
initial decision template has a link to levels of the hosting hierarchy which does not work.

Error I receive is - We are sorry, the page is forbidden.
You do not have permission with this credential, please sign out to try with others and go back again.

https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/cloud-concepts?branch=release%2Fcaf-journey-2#step-4-define-hosting-hierarchy-depth-to-align-portfolio

Upon further testing of the document many of the links provide the same error.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d09a91-aa00-19c5-8c92-c571fd388f34
* Version Independent ID: 8be4ff41-b5f3-da3c-b43d-f3c7347748f5
* Content: [Get started: Document foundational alignment decisions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/cloud-concepts#step-3-review-the-portfolio)
* Content Source: [docs/get-started/cloud-concepts.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/cloud-concepts.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#235755

**Comment by JanetCThomas** [comment]
This issue has been fixed https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/cloud-concepts#step-4-define-portfolio-hierarchy-depth-to-align-the-portfolio

**Comment by kknight-valorem** [comment]
thank you - verified that I have access now.
