### ISSUE TITLE
Documents refer to 'the customer'

### ISSUE THREAD

**Issue by scottstout** [MicrosoftDocs/cloud-adoption-framework#205]
The documents make frequent reference to 'the customer'. This probably is a remnant from when these were internal-only documents meant for Microsoft to use as guidance for working with a customer. Now the customer is directly reading the documents so the terminology should change.

I've pointed this out on one doc but it applies to others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0ba091-358a-58a1-2a4f-7dd0270f8cb6
* Version Independent ID: b85a54c6-03a8-7039-31f1-b0e473d20831
* Content: [Network topology and connectivity - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/network-topology-and-connectivity)
* Content Source: [docs/ready/enterprise-scale/network-topology-and-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/network-topology-and-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#237650

**Comment by JanetCThomas** [comment]
This issue has been addressed and should go live soon. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/657
