### ISSUE TITLE
Links to samples are broken.

### ISSUE THREAD

**Issue by klawrawkz** [MicrosoftDocs/cloud-adoption-framework#207]
Hi there,

My name is klawrawkz. I'm fine; how are you?

All the "sample" links in the article are broken; links to nowhere, in the parlance of our times.

Example deployment | Description | GitHub repo | Deploy to Azure
-- | -- | -- | --
Enterprise-scale foundation | This is the suggested foundation for enterprise-scale adoption. | [Example in GitHub-Broken link -]( https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/wingtip/README.md) | Deploy example to Azure
Enterprise-scale Virtual WAN | Add a Virtual WAN network module to the enterprise-scale foundation. | [Example in GitHub-Broken link -](https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/contoso/Readme.md) | Deploy example to Azure
Enterprise-scale hub and spoke | Add a hub and spoke network module to the enterprise-scale foundation. | [Example in GitHub-Broken link -](https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/adventureworks/README.md)| Coming soon

Broken Links:
-  https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/wingtip/README.md
- https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/contoso/Readme.md
- https://github.com/Azure/Enterprise-Scale/blob/master/docs/reference/adventureworks/README.md

>As an end user of the Microsoft documentation, I need working links so I don't burn hours searching for content, and so I can easily find the content pertaining to specific topics.

Please fix this.

Thanks,

klawrawkz
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 953e95f0-cff8-29ed-65a9-a1d78496e31b
* Version Independent ID: 669b1c14-8f99-fd2e-4bde-c815172a1196
* Content: [Implement enterprise-scale landing zones in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation)
* Content Source: [docs/ready/enterprise-scale/implementation.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/implementation.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#237678

**Comment by JanetCThomas** [comment]
This issue has been fixed. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation
