### ISSUE TITLE
three sets of assets or four?

### ISSUE THREAD

**Issue by rich-davies** [MicrosoftDocs/cloud-adoption-framework#213]
There is mention of four sets of assets, but only three are listed?
![image](https://user-images.githubusercontent.com/28859545/84872053-439b3d00-b079-11ea-99fa-f68d1e60a271.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 049214ee-75b7-e427-4f16-cf98cca0d2ab
* Version Independent ID: bb487cb6-676d-03e3-057d-5d6a65807c20
* Content: [Start with enterprise-scale landing zones - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/)
* Content Source: [docs/ready/enterprise-scale/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#238598

**Comment by JanetCThomas** [comment]
This issue has been fixed and should go live soon. https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/657
