### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by catay** [MicrosoftDocs/cloud-adoption-framework#215]
The first link in the 'customize-or-deploy-a-landing-zone' section referencing a github repo is broken.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/enterprise-scale#customize-or-deploy-a-landing-zone

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3afb86-4ddb-07e9-eae0-e61482df8912
* Version Independent ID: f4fb266d-b74d-6878-24eb-a4289deaa479
* Content: [Deploy a CAF enterprise-scale landing zone in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/enterprise-scale)
* Content Source: [docs/ready/landing-zone/enterprise-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/enterprise-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#238912

**Comment by JanetCThomas** [comment]
This issue has been fixed. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/enterprise-scale#customize-or-deploy-a-landing-zone
