### ISSUE TITLE
Link to larger view of the High-level architecture.

### ISSUE THREAD

**Issue by ClinteRich** [MicrosoftDocs/cloud-adoption-framework#217]
Can you add a link to a larger view of the High-level architecture at the bottom of the article? I know its in GitHub but that direct link would be helpful for folks who don't know that. Also, providing a link to the Visio drawing or similar template would be great!

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [CAF enterprise-scale landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
* Content Source: [docs/ready/enterprise-scale/architecture.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/architecture.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
A link to download the visio diagram has been added.  Thanks!

**Comment by cgtheflash** [comment]
Hi, the link that was made available for the diagram at the bottom of the page is for the PDF version. Can you post a link for the actual Visio diagram please?

**Comment by JonesMikael** [comment]
It seems like there's a "hidden" URL available but not posted on the page:
https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/enterprise-scale-architecture.vsdx
However, it's not the same as the following:
https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/enterprise-scale-architecture.pdf
