### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by strichar** [MicrosoftDocs/cloud-adoption-framework#222]
Deploy-Diag-ActivityLog
Deploy-Diag-LogAnalytics
Deploy-VM-Monitoring 

Appear to be broken
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 676fa0a6-b6e0-eb9f-5c75-e3b2f457adf5
* Version Independent ID: fde434af-3412-8139-51cd-988751061617
* Content: [Implementation guidelines - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation-guidelines)
* Content Source: [docs/ready/enterprise-scale/implementation-guidelines.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/implementation-guidelines.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241380

**Comment by JanetCThomas** [comment]
This issue has been resolved.
