### ISSUE TITLE
subscription or tenant level - looks wrong

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/cloud-adoption-framework#225]
[Enter feedback here]

Hi should this say root or "tenant" level rather than subscription level ?

A management group tree can support up to six levels of depth. This limit doesn't include the root or subscription level.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38786a5-e931-e614-55a1-2980b8a28087
* Version Independent ID: a72b6f97-dd0f-252c-f6d9-f1c517aa9a2f
* Content: [Management group and subscription organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization)
* Content Source: [docs/ready/enterprise-scale/management-group-and-subscription-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-group-and-subscription-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#241656

**Comment by alexbuckgit** [comment]
Updating the sentence to: "This limit doesn't include the tenant root level or the subscription level."

The subscription level and below are not included in the hierarchy limit.

This issue will be resolved via a PR in the next several days.
