### ISSUE TITLE
duplicate content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#230]
[Enter feedback here]
This page has some of the same recommendations as the on the Security Baseline page https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/security-baseline-improvement#incremental-improvement-of-governance-practices. I would expect this page to have different recommendations, recommendations about Firewall settings don't seem appropriate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0564e-af43-0b66-cd25-52528a2242ab
* Version Independent ID: db663e40-aaff-d9c3-f91c-04429c890a72
* Content: [Standard enterprise governance: Improve the Resource Consistency discipline - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/resource-consistency-improvement)
* Content Source: [docs/govern/guides/standard/resource-consistency-improvement.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/guides/standard/resource-consistency-improvement.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244051

**Comment by alexbuckgit** [comment]
@MarkSimos - Please review.

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
