### ISSUE TITLE
Nothing about using Azure Sentinel

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#231]
[Enter feedback here]
in a multicloud scenario, it could be appropriate to use Azure Sentinel, adding some content about this would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2dac1e-8592-1b4b-af26-d0923313bd4a
* Version Independent ID: c671291c-c3c0-d890-3789-6edaf9596245
* Content: [Standard enterprise governance: Multicloud improvement - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/standard/multicloud-improvement)
* Content Source: [docs/govern/guides/standard/multicloud-improvement.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/guides/standard/multicloud-improvement.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244053

**Comment by alexbuckgit** [comment]
We've added this to our backlog to address in a future release.

Thanks for the feedback.
