### ISSUE TITLE
raci-template.xlsx

### ISSUE THREAD

**Issue by AzureArchitecture** [MicrosoftDocs/cloud-adoption-framework#234]
The link "Additional information available online" in cell B3 on sheets "MVP Best Practice" and "Fully-staffed Best Practice" in the [raci-template.xlsx](https://archcenter.blob.core.windows.net/cdn/fusion/management/raci-template.xlsx) points to: 
https://review.docs.microsoft.com/en-us/azure/architecture/cloud-adoption/organization/?branch=pr-en-us-47#best-practice-minimally-viable-product-mvp
Should point to:
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/organization/?branch=pr-en-us-47#best-practice-minimally-viable-product-mvp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d6acd7-52c2-0fcd-77ad-a30e96ecbf45
* Version Independent ID: af35206e-2b05-0ae7-8ca9-6e43330e96e6
* Content: [Tools and templates - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/tools-templates)
* Content Source: [docs/reference/tools-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/tools-templates.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#244315

**Comment by JanetCThomas** [comment]
This issue has been resolved.
