### ISSUE TITLE
Great read starter moving to the cloud

### ISSUE THREAD

**Issue by ctemplo** [MicrosoftDocs/cloud-adoption-framework#237]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e48aaf-b0c5-ea0e-2d5d-af0f53affd3a
* Version Independent ID: 73399b00-c2a0-2aca-929f-f19e97ddab94
* Content: [Why are we moving to the cloud? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/motivations)
* Content Source: [docs/strategy/motivations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/motivations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thank you for your feedback!
