### ISSUE TITLE
Incorrect image markup

### ISSUE THREAD

**Issue by josevarela** [MicrosoftDocs/cloud-adoption-framework#239]
Just noticed the browser is not rendering the overview image referenced in this page. Looks like an issue with the markup.

![image](https://user-images.githubusercontent.com/1648509/86805964-669c8980-c046-11ea-8e21-2bbcf9dcb86b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66744a3f-7ab3-80ae-4c76-639ee78601bf
* Version Independent ID: 081c5a49-8bd7-778e-da3f-11ad4667c4a2
* Content: [Microsoft Cloud Adoption Framework for Azure documentation - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview?source=docs)
* Content Source: [docs/overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#249510

**Comment by JanetCThomas** [comment]
The fix should be live by tomorrow.  Thank you.
