### ISSUE TITLE
Missing word?

### ISSUE THREAD

**Issue by vlele** [MicrosoftDocs/cloud-adoption-framework#240]
The first or best players to market are always the winners ( did you mean to include a  "not" in this sentence -  The first or best players to market are **not** always the winners)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7102d8b3-1ed2-c956-e8d0-0645fbdad94c
* Version Independent ID: 6f471b70-f89d-86a0-3c49-1676228df334
* Content: [The build-measure-learn feedback loop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/considerations/adoption)
* Content Source: [docs/innovate/considerations/adoption.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/considerations/adoption.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#263843

**Comment by JanetCThomas** [comment]
This issue has been fixed and will be live soon.   Thanks!
