### ISSUE TITLE
Change Tracking & Inventory Management

### ISSUE THREAD

**Issue by dalejmarshall** [MicrosoftDocs/cloud-adoption-framework#241]
[Enter feedback here]

The diagram on this page seems to suggest a centralised automation account with Change Tracking & Inventory Management enabled in the management subscription, yet in the [Change Management & Inventory documentation](https://docs.microsoft.com/en-us/azure/automation/change-tracking) it states that  "_To use the Change Tracking and Inventory feature, you must locate all your VMs in the same subscription and region of the Automation account_."

Is it possible to clarify if the Change Tracking will actually work across subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a01671-cf1f-63e1-b526-7346953d8042
* Version Independent ID: 9ae96c16-1771-f098-f581-6a5abc630ed6
* Content: [Management and monitoring - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-and-monitoring)
* Content Source: [docs/ready/enterprise-scale/management-and-monitoring.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-and-monitoring.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#264267

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!

**Comment by alexbuckgit** [comment]
@JefferyMitchell - Please review.

**Comment by victorar** [comment]
This requirement is not applicable anymore.

This issue can be closed.
