### ISSUE TITLE
The image has misspelled words in it.

### ISSUE THREAD

**Issue by juancvegaMS** [MicrosoftDocs/cloud-adoption-framework#246]
Please verify / correct the the Image at the top of the page, the word, "enrolment" is misspelled - should read, "enrollment".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0075e68e-d22e-f35d-d7d4-b936dcb3e6ad
* Version Independent ID: 11caebc2-6caf-0095-3eb5-564e18a15488
* Content: [Enterprise Agreement enrollment and Azure Active Directory tenants - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants)
* Content Source: [docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#267907

**Comment by JanetCThomas** [comment]
This issue has been fixed.
