### ISSUE TITLE
Unclear paragraph

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/cloud-adoption-framework#247]
The paragraph:
'Do not add users directly to Azure resource scopes. This lack of centralized management greatly increases the management required to prevent unauthorized access to restricted data.'

Sounds a bit like we should not add users directly to ANY resource scopes (there are 4 - Management Groups, Subscriptions, Resource Groups or Resources). Is only Resources scope implied? (see https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38786a5-e931-e614-55a1-2980b8a28087
* Version Independent ID: a72b6f97-dd0f-252c-f6d9-f1c517aa9a2f
* Content: [Management group and subscription organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization)
* Content Source: [docs/ready/enterprise-scale/management-group-and-subscription-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-group-and-subscription-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#268583

**Comment by Agazoth** [comment]
Wrong article
