### ISSUE TITLE
Unclear paragraph

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/cloud-adoption-framework#248]
The paragraph:
'Do not add users directly to Azure resource scopes. This lack of centralized management greatly increases the management required to prevent unauthorized access to restricted data.'

Sounds a bit like we should not add users directly to ANY resource scopes (there are 4 - Management Groups, Subscriptions, Resource Groups or Resources). Is only Resources scope implied? (see https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2540a7-f3a9-4440-2c97-163f45993672
* Version Independent ID: d08b3a6f-113f-7f5b-2c11-c278ce11e905
* Content: [Identity and access management - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management)
* Content Source: [docs/ready/enterprise-scale/identity-and-access-management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/identity-and-access-management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#268584

**Comment by BrianBlanchard** [comment]
Resolved in PR 339
