### ISSUE TITLE
Image is deprecated

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/cloud-adoption-framework#251]
In the visio-drawing here: https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/enterprise-scale-architecture.vsdx Management and Monitoring is D, not E. Image should be updated accordingly.

Likewise, https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/platform-automation-and-devops.md needs to have the picture updated. I is the current reference in the image on the page it is H.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a01671-cf1f-63e1-b526-7346953d8042
* Version Independent ID: 9ae96c16-1771-f098-f581-6a5abc630ed6
* Content: [Management and monitoring - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-and-monitoring)
* Content Source: [docs/ready/enterprise-scale/management-and-monitoring.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-and-monitoring.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#270099

**Comment by JanetCThomas** [comment]
This issue has been resolved.
