### ISSUE TITLE
Missing Azure Site Recovery header

### ISSUE THREAD

**Issue by devan10** [MicrosoftDocs/cloud-adoption-framework#259]
Phase 2 highlights the three tools to use for migration:
Azure Migrate
Azure Site Recovery
Azure Database Migration Service

But this does not have a section header for Azure Site Recovery and kind of talks about it in the Azure Migrate section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec4ba22-6c84-8ff4-cd28-edb539877792
* Version Independent ID: 3f38a5c4-7064-ba17-6b89-59658aa746e1
* Content: [Scale a migration to Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-scale)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#275406

**Comment by BrianBlanchard** [comment]
Closed in a pr to be released in the next few days
