### ISSUE TITLE
awkward phrase

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#260]
The phrase "Tagging and classifying the sensitive of assets" should probably be "Tagging and classifying the sensitivity of assets"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c4be3e-1358-576a-fe23-c1de0b0d2cb6
* Version Independent ID: 23a6ad98-f3b2-004a-0b03-316ead662272
* Content: [Function of cloud security policy and standards - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-security-policy-standards)
* Content Source: [docs/organize/cloud-security-policy-standards.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/organize/cloud-security-policy-standards.md)
* Service: **cloud-adoption-framework**
* Sub-service: **organize**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#282932

**Comment by BrianBlanchard** [comment]
Resolved in PR to be released shortly: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/840
