### ISSUE TITLE
Word(s) missing?

### ISSUE THREAD

**Issue by aqasrawi** [MicrosoftDocs/cloud-adoption-framework#264]
I believe the statement "Determine incident response plan for Azure services before allowing." is missing something at the end.  Before allowing what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061d80aa-0c57-8ae8-c9ae-a2ea52dff98f
* Version Independent ID: f77eeafe-a217-7959-3d5c-6e5f5e54d908
* Content: [CAF enterprise-scale security governance and compliance - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/security-governance-and-compliance)
* Content Source: [docs/ready/enterprise-scale/security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#284218

**Comment by alexbuckgit** [comment]
@krnese - Please review.

**Comment by JanetCThomas** [comment]
@MarkSimos can you please take a look at this issue.

**Comment by JanetCThomas** [comment]
This issue has been addressed. The sentence should read, "Determine the incident response plan for an Azure service before allowing it into production."  The fixed topic should be live soon.  Thank you!
