### ISSUE TITLE
Storage account naming and examples inconsistent with majority of naming conventions.

### ISSUE THREAD

**Issue by CraigThatcher** [MicrosoftDocs/cloud-adoption-framework#265]
Storage naming and tagging suggestions and examples should contain a dash after the prefix.  This would make the names and tags created easier to read. 

Requested Changes

Storage account "st-"
Azure StorSimple "ssimp-"

Example names Storage
| Asset type | Scope | Format | Examples |
|---|---|---|---|
| Storage account (general use) | Global | st\-\<storage name\>\-\<###\> | * st-navigatordata-001 * st-emissionsoutput-001|
| Storage account (diagnostic logs) | Global | stdiag\-\<first 2 letters of subscription name and number\>\-\<region\>\-\<###\> | * stdiag-sh001-eastus-2001 * stdiag-sh001-westus-001 |
| Azure StorSimple | Global | ssimp\-\<App Name\>\-\<Environment\> | * ssimp-navigator-prod  * ssimp-emissions-dev|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#284250

**Comment by pherbel** [comment]
@CraigThatcher 
The storage account name can't contain a hyphen.

Docs:
> Naming storage accounts
> When naming your storage account, keep these rules in mind:
> 
> Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
> Your storage account name must be unique within Azure. No two storage accounts can have the same name.

https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#:~:text=Storage%20account%20names%20must%20be,must%20be%20unique%20within%20Azure.

Read more about our approach:
https://medium.com/gettech-blog/azure-naming-conventions-98d6e5a6ae80

**Comment by alexbuckgit** [comment]
Closing this item, since storage account names can't contain a hyphen.
