### ISSUE TITLE
GatewaySubnet in Central US VNET has a conflicting IP address range

### ISSUE THREAD

**Issue by david-stewart-palapanou** [MicrosoftDocs/cloud-adoption-framework#266]
The table that contains the subnet list ([link](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure#subnets-in-the-central-us-hub-network-vnet-hub-cus)) has a conflicting IP address range.

The GatewaySubnet uses 10.250.2.0/24 which conflicts with 10.250.2.0/24. This virtual network is intended to be a like-for-like of the other subnet ([link](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure#subnets-in-the-east-us-2-hub-network-vnet-hub-eus2)) but the GatewaySubnet in that virtual network uses 10.240.10.0/24.

I therefore think that should be the same for the GatewaySubnet which is currently conflicting.

Many thanks,
David Stewart-Palapanou

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097a8a15-21c5-619d-05f6-8722da3c0d7c
* Version Independent ID: 7cc4e4f3-fa5d-dd6c-5462-7f587e708d5e
* Content: [Deploy a migration infrastructure - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-infrastructure#virtual-networks-in-east-us-2)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-infrastructure.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-infrastructure.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @deltadan
* Microsoft Alias: **abuck**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#284702

**Comment by deltadan** [comment]
I write this document and there does appear to be a bug in the table mentioned. The value should be 10.250.10.0/24 to match the drawing.

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for the feedback!
