### ISSUE TITLE
Link to new diagram Visio

### ISSUE THREAD

**Issue by ClinteRich** [MicrosoftDocs/cloud-adoption-framework#268]
The updated "Start with Enterprise Scale" diagram looks awesome! Would it be possible to get the Visio file uploaded to GitHub and linked in the .md? I see the PDF but Visio is really helpful as well!

[Here is the PDF link for your info](https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/enterprise-scale-architecture.pdf).

Thanks in advance!

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#285605

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!

**Comment by ClinteRich** [comment]
Any update on DevOps Bug ID AB#285605  Looking for the Visio of the start with ent scale diagram.
