### ISSUE TITLE
Add Call Out Descriptions for Enterprise Scale Diagram

### ISSUE THREAD

**Issue by ClinteRich** [MicrosoftDocs/cloud-adoption-framework#269]
The diagram at the bottom of the Enterprise Scale Architecture page has call out bubbles in green on the diagram. Would it be possible to get the descriptions behind these call outs added to the .md? I think that would help define what each one is referencing for the reader.

[Here is a link](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture#high-level-architecture) to the page/diagram in question.

Thanks!

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#285623

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
