### ISSUE TITLE
type on it stability in the critical business events

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/cloud-adoption-framework#278]
[Enter feedback here]
Hello, just checking if the below is correct..

The "it" at the end.
Reduction of disruptions and improvement of it stability

should it be Reduction of disruptions and improvement of stability
or
Reduction of disruptions and improvement of IT stability

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30e48aaf-b0c5-ea0e-2d5d-af0f53affd3a
* Version Independent ID: 73399b00-c2a0-2aca-929f-f19e97ddab94
* Content: [Why are we moving to the cloud? - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/strategy/motivations)
* Content Source: [docs/strategy/motivations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/motivations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#293458

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
