### ISSUE TITLE
Error I think in the stages of the CAF

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/cloud-adoption-framework#279]
[Enter feedback here]

Hello when listing the stages in the intro it mentions Operate.  I believe this should be Manage.

Each of the processes across the Strategy, Plan, Ready, Adopt, and Operate 

Looking at the stages and also the menu on the left we see Manage, not Operate.  Manage includes the operational aspects but is not named as a stage itself. 
Many Thanks!
MC
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7842e7a6-a58f-2ec2-1873-da5a3f68f472
* Version Independent ID: b204986b-9463-24e6-7327-eb0c0071401b
* Content: [First cloud adoption project - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/strategy/first-adoption-project)
* Content Source: [docs/strategy/first-adoption-project.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/first-adoption-project.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#293597

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
