### ISSUE TITLE
Confusing sentence when talking about accelerating migration

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/cloud-adoption-framework#283]
Please see value statement. Maybe I am missing something here ?  The phrase here..
Following these steps might slow the process. 

From the paragraph below..should it say speed up the process or if it slows it down it is not clear how..and what would cause it ? Thanks

Value statement
The steps outlined in this guide can help your teams speed up their migration efforts through better change management and stakeholder alignment. Following these steps might slow the process. These steps also remove common blockers and accelerate the realization of business value.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150e319d-d5c9-5e7e-a233-a4818bf53a72
* Version Independent ID: c2d8e1bd-a4ef-a979-095a-148bc2276d9e
* Content: [Get started: Accelerate migration - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/get-started/migrate)
* Content Source: [docs/get-started/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#294873

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
