### ISSUE TITLE
Special naming for resources is counter productive. We should remove it 

### ISSUE THREAD

**Issue by lawrencegripper** [MicrosoftDocs/cloud-adoption-framework#287]
Tags and the metadata on resources provide all the information crammed into these names in higher fidelity and with more useful context. Attempting to cram it into a three character string is an antipattern in my option.

More over the use of characters reduces the number of characters left to accurately describe the name of the resource as lots are waisted outlining data that is accessible in the metadata of the object or the tags. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#297665

**Comment by BrianBlanchard** [comment]
@lawrencegripper 
Thanks for the feedback. We've debated the same thought a few times internally. 

Our commitment to multi-cloud still requires naming that is identifiable without tags or meta... Tags & Meta don't transition well between public and private cloud providers today. Until there is a standard for effortless transition of meta, tag and meta dependencies could create cloud provider lock in.

We will continue to review this periodically, but for the time being, it is a necessary pattern to avoid Azure only adoption guidance.
