### ISSUE TITLE
Incorrect hyper links to Msft Learn

### ISSUE THREAD

**Issue by lunar87** [MicrosoftDocs/cloud-adoption-framework#289]
At 
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/suggested-skills#microsoft-learn

it has links for Azure Fundamentals and also Manage resources in Azure. both of these link to https://docs.microsoft.com/en-us/learn/paths/azure-for-the-data-engineer/ which seem incorrect.

First one should probably be https://docs.microsoft.com/en-us/learn/paths/azure-fundamentals/
second is probably https://docs.microsoft.com/en-us/learn/modules/control-and-organize-with-azure-resource-manager/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e324c2-9d00-346b-64e8-53e515a1d758
* Version Independent ID: 69da1435-3b49-d903-a0a3-e584b924b67e
* Content: [Skills readiness path during the Ready phase of a migration journey - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/suggested-skills#microsoft-learn)
* Content Source: [docs/ready/suggested-skills.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/suggested-skills.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#299200

**Comment by JanetCThomas** [comment]
This issue has been resolved. Thank you!
