### ISSUE TITLE
Naming convention massively outdated and needs updating

### ISSUE THREAD

**Issue by byronbayer** [MicrosoftDocs/cloud-adoption-framework#290]
The naming convention outlined in https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging is massively outdated and not reflective of real world scenarios. 
From my experience of working with many clients over the past 25 years there has never been a time where the naming outlined in the above document has been implemented or would have been implemented due to the confusion it leaves when infrastructure has been deployed.

The examples need to be broken down into several different use cases depending on the client needs. Naming conventions can be different from company to company, for example for a company only providing infrastructure for their own organisation to a company that has multiple clients that need infrastructure (for possible security and GDPR purposes)
Just to quickly highlight:

### Prefixing is never a good idea. 
When looking through infrastructure in Azure that has the naming of the following
```
webapi-org-dev-application-001
ai-org-dev-application-001
```
it is a lot harder to understand than:
```
org-dev-application-001-webapi
org-dev-application-001-ai
```
Both are the same but just named differently. This makes a huge difference when trawling through masses of infrastructure in Azure

### Environments vs purpose 
Environments are not just `dev`, `test`, `preprod` and `prod` on their own, they are the purpose of the infrastructure
Environments are made up of purpose `dev` and a version `001`
```
dev-001
prd-001
prd-002
```
having infrastructure naming built up like this allows you to have multiple instances of sites that you can easily switch to or create blue green testing for. It also helps with not having pets (long standing infrastructure) and breeds more cattle (short lived easily destroyed infrastructure)

### Positional values in the naming convention matter.
How you construct your naming convention is very important. having a name of
`org-dev-app1-001`
`org-dev-app1-002`
is a lot easier to read and predictably create using automation than
`org-dev-001-app1`
`org-dev-002-app1`

A naming convention could be built up from the following items

**Owner**: short descriptor of the organisation - it  unique naming for some infrastructure
org1 - Organisation 1

**Purpose:**
Dev - Development
Tst - Test
Qa - Qa
pp - PreProd
Prd - Production
 
**Application:**
ap1 Application1
 
**Environment:**
001, 002 ect
 
**Base name**
org1-dev-ap1-001
 
**Infrastructure:**
App insights
-ai
Web UI
-webui
Web api
-webapi
Web job
-webjob
App service plan
-asp
Service Bus
Sb
Function App
-func
Key Vault
-kv

This is just a very brief overview of where I feel the naming conventions should go for enterprise scale infrastructure.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#300758

**Comment by byronbayer** [comment]
If I was to branch this and start working on separate pages for different organisational requirements, would anyone have the time to review on a regular basis so work done doesn't drift too far from the requirements

**Comment by alexbuckgit** [comment]
@byronbayer - The CAF team is meeting over the next few weeks to review our overall approach to this article. Once we make adjustments to the article based on those decisions, that would probably be a good time for you to branch and contribute further.

In the meantime, can you provide some more detail on your thoughts about using separate pages for different organizational requirements?

Thanks for contributing!

**Comment by alexbuckgit** [comment]
Beyond the detail you provided at the top of the PR, I mean. :-)

**Comment by byronbayer** [comment]
Hi @alexbuckgit 
That is great news that this is being talked about and I would be happy to be involved in any way I can help.

There are several scenarios for different organisational requirements when it comes to naming and constructing infrastructure in a very repeatable and manageable way. There is not one silver bullet that will solve all possibilities and companies should make decisions based on their current and future requirements.
below are just some of the benefits and scenarios that can be leveraged from a good naming convention. There are always edge case scenarios that should/could be added to the list below.

Using segments withing your naming patterns,  I have used above, help simplify a solid naming structure and convention that can be implemented at top level so that DevOps and Dev teams don't have to worry about it.
This greatly increases the time to deployment and conflicts withing naming patterns.

### Tagging
Tags do play a part, but I think we need to get naming right first. 

### Benefits 
Getting naming right up front is absolutely crucial to having:
- A simplified deployment process managed at any level
- Visually quick and easy identification of infrastructure
- Easily maintaining infrastructure
- Pattern matching when searching for deleting/updating Resource groups or infrastructure.

### Scenarios 
- Company with one application/website
- Company with multiple applications/websites
- Company with multiple overarching application groups (products) that have multiple applications inside. 
- Company has multiple client applications and no infrastructure of its own
---
- Company has multiple client applications that feed back into a central organisational application
- Company has multiple client applications that feed back into a central organisational application and has any of the following
  - Company with one application/website
  - Company with multiple applications/websites
  - Company with multiple overarching application groups (products) that have multiple applications inside.

**Comment by byronbayer** [comment]
Hi @alexbuckgit , Has there been any update or thoughts on this?

**Comment by byronbayer** [comment]
I still see that there has been no update to the naming convention web page which is giving bad advice to organisations trying to define a naming convention. I am advising organisations that I work with to ignore this bad advice that Microsoft is recommending.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24325 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
