### ISSUE TITLE
Difficulty in building understanding

### ISSUE THREAD

**Issue by pkothare** [MicrosoftDocs/cloud-adoption-framework#291]
The [Cloud adoption plan > Prerequisites > Tactical inputs](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/prerequisites#tactical-inputs) section references having the Skill readiness completed. All elements of strategic and tactical inputs appear higher in the navigation hierarchy except the [Skills readiness plan](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/adapt-roles-skills-processes) (which appears below the Cloud adoption plan). This can cause confusion when trying to understand a sequential set of steps to realize path to success. Please consider revising the navigation (or the language in the Tactical inputs section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8598a1-1be6-8707-4175-3f98449dae3a
* Version Independent ID: 35d33d80-2533-3b02-ad69-21e8de761941
* Content: [Prerequisites for a cloud adoption plan - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/prerequisites)
* Content Source: [docs/plan/prerequisites.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/plan/prerequisites.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#301542

**Comment by JanetCThomas** [comment]
This issue has been resolved.
