### ISSUE TITLE
Image descriptions need next line.

### ISSUE THREAD

**Issue by StChrist-MSFT** [MicrosoftDocs/cloud-adoption-framework#295]
[Enter feedback here]

After each image on this page there is a text description. These descriptions need to be aligned correctly as they are "on the same line" as the image right now, making the text hard to read. So in markdown add line change after each images ;)

Sorry don't know how to do a pull request myself 😢

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bc9f39-cae7-2967-dfd5-58caa34452d1
* Version Independent ID: 9118485a-56d8-ce9e-fbfd-6e66be87a611
* Content: [Hub and spoke network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology)
* Content Source: [docs/ready/azure-best-practices/hub-spoke-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/hub-spoke-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305533

**Comment by StChrist-MSFT** [comment]
Figured out how to create the change myself (i think) and I have created the pull request ;)

**Comment by BrianBlanchard** [comment]
Resolved in PR 296  https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/296
