### ISSUE TITLE
Visio Diagram Download

### ISSUE THREAD

**Issue by cgtheflash** [MicrosoftDocs/cloud-adoption-framework#297]
Hi, 

Can you post a link to download the actual Visio Diagram at the bottom of the page? Issue #217 requested this and a PDF version was made available to download, but it would be great to have the actual Visio file made available for download please and thank you.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#305602

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
