### ISSUE TITLE
Missing guidance for managed disks

### ISSUE THREAD

**Issue by rwaal** [MicrosoftDocs/cloud-adoption-framework#301]
This page suggests a naming convention for Virtual Machines. But it doesn't contain any recommendation for managed disks. I'm looking for guidance from Microsoft about naming the operating system disk and data disks. 

Oddly enough, `VM storage account` is mentioned. But these days nobody would create VMs with (unmanaged) storage accounts anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#307914

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
