### ISSUE TITLE
Post Landing-Zone implementation assessment

### ISSUE THREAD

**Issue by Mahesh-MSFT** [MicrosoftDocs/cloud-adoption-framework#308]
As outlined in this page, there are multiple options to implement a landing zone. Each landing zone implementation in unique in its approach, scale, timelines, etc.

In time-bound projects, landing zone implementation may be rushed through, implemented partially or postponed for a future date.
In such scenarios, its important for customers to be aware of risks.

Before customers move into "Adopt" phase, knowing clear status of landing zone implementation will enable them to make right trade-offs between "Adopt" and "Ready" activities, if at all.

Having a WAF assessment like score-based system for measuring effectiveness of the landing zone implementation across 8 design areas will help customers make a decision on moving into "Adopt" phase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b43a5fb1-1dd3-e33d-2d39-0e0cbb255458
* Version Independent ID: f619c41a-a623-0373-d621-6c6f3190c0ca
* Content: [Landing zone implementation options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options)
* Content Source: [docs/ready/landing-zone/implementation-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/implementation-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#314533

**Comment by JanetCThomas** [comment]
There is a Well Architected assessment here.  https://docs.microsoft.com/en-us/assessments/ 
We will investigate adding a link from the article.  Thank you for your feedback.

**Comment by JanetCThomas** [comment]
@BrianBlanchard - please review.

**Comment by Mahesh-MSFT** [comment]
@JanetCThomas - thanks for responding.

I am aware of the WAF assessment. The WAF assessment assesses a workload across 5 categories of reliability, security, costs, performance and operations.

I am proposing a similar assessment for Landing Zone across 8 design areas. This will help customers/partners have a view on the effectiveness of landing zone implementation before they move into "Adopt" phase.

**Comment by JanetCThomas** [comment]
This has been added to our backlog. Thank you.
