### ISSUE TITLE
Scope and method for the monitoring of Azure Front Door

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/cloud-adoption-framework#311]
The table in the "Azure Cloud Monitoring" section
https://docs.microsoft.com/ja-jp/azure/cloud-adoption-framework/manage/monitor/cloud-models-monitor-overview#azure-cloud-monitoring
shares the scope and method for monitoring Azure Application Gateway and Azure Traffic Manager, but does not have information about Azure Front Door.

Since the [general availability of Azure Front door in 2019](https://azure.microsoft.com/en-us/blog/azure-front-door-service-is-now-generally-available/), I believe Azure Front door is often becoming the preferred choice for load balancing, especially for applications that are global in nature. Therefore, I think it would be great to add guidance around scope and method for monitoring Azure Front door.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4b7cf2-ec0b-158a-5afa-2338193a90dc
* Version Independent ID: 5faaf3cf-97e7-8044-c166-f97ff4716fa3
* Content: [Monitoring strategy for cloud deployment models - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/monitor/cloud-models-monitor-overview)
* Content Source: [docs/manage/monitor/cloud-models-monitor-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/monitor/cloud-models-monitor-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#318809

**Comment by MGoedtel** [comment]
Great point and I will include this while I am working on several updates to this article for other improvements I've planned for this sprint.

**Comment by rukasakurai** [comment]
One specific suggestion would be to combine Application Gateway, Traffic Manager, and Front Door (and maybe also Azure Load Balancer) into one category. The "method" could be to configure diagnostic logging, which is relevant for all.
Not sure if the "scope" would be different.

**Comment by MGoedtel** [comment]
I'm addressing this in a new PR I'm working on and identified an architecture article that covers the Azure load balancing offerings in one place that I can link to.  This PR should get completed by end of week or early next week. #please-close.
