### ISSUE TITLE
"Scope" missing for the AAD row in the "Azure Cloud Monitoring" section

### ISSUE THREAD

**Issue by rukasakurai** [MicrosoftDocs/cloud-adoption-framework#312]
In the table in the "Azure Cloud Monitoring" section
https://docs.microsoft.com/ja-jp/azure/cloud-adoption-framework/manage/monitor/cloud-models-monitor-overview#azure-cloud-monitoring
the AAD row is missing a "scope", and what should be written in the "method" column is written in the "scope column".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4b7cf2-ec0b-158a-5afa-2338193a90dc
* Version Independent ID: 5faaf3cf-97e7-8044-c166-f97ff4716fa3
* Content: [Monitoring strategy for cloud deployment models - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/monitor/cloud-models-monitor-overview#azure-cloud-monitoring)
* Content Source: [docs/manage/monitor/cloud-models-monitor-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/monitor/cloud-models-monitor-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by rukasakurai** [comment]
Sent a PR: https://github.com/MicrosoftDocs/cloud-adoption-framework/pull/313

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
