### ISSUE TITLE
IBM Continues to support Netezza and release new Products with Netezza Technology

### ISSUE THREAD

**Issue by SugarPancakes** [MicrosoftDocs/cloud-adoption-framework#314]
Hello - The first sentence is not accurate. Especially if it's written in 2020. IBM's support for Netezza is not ending. That may have been the case in 2019. But not any more. In June 2019 IBM announced it will continue supporting Netezza and is releasing new products based on Netezza Technology such as the Netezza Performance Server both On Premise and On Cloud!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fe3278-b43a-96b7-494d-88ca84cc8f1f
* Version Independent ID: d7935e7f-3e8d-06fb-f639-9d6e97f58966
* Content: [Azure Synapse Analytics migration for Netezza - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/analytics-solutions-netezza)
* Content Source: [docs/migrate/azure-best-practices/analytics/analytics-solutions-netezza.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/analytics/analytics-solutions-netezza.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @v-hanki
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#319056

**Comment by JanetCThomas** [comment]
This issue has been resolved.  The fix should be published in the next day or two.  Thank you for reporting the issue.
