### ISSUE TITLE
Missing sample policies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#315]
[Enter feedback here]

The introduction states that there are "three levels of sample policy: cloud-native, enterprise, and cloud-design-principle-compliant" I see the cloud-native example, but not the others. Where can I find them?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0adac86-b138-d165-6c8c-4caf9ba00a6e
* Version Independent ID: 649a6874-879b-3915-d59c-a260005271f7
* Content: [Cloud-native Security Baseline policy - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/security-baseline/cloud-native-policy)
* Content Source: [docs/govern/security-baseline/cloud-native-policy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/security-baseline/cloud-native-policy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#319121

**Comment by alexbuckgit** [comment]
@NaomiOooo - Please review.

**Comment by NaomiOooo** [comment]
The wording was incorrect/vague and changed to reflect that there was only an example of cloud-native.
