### ISSUE TITLE
Virtual TAP is no longer available

### ISSUE THREAD

**Issue by kodubeau** [MicrosoftDocs/cloud-adoption-framework#316]
[Enter feedback here]
Virtual TAP is no longer available and not accepting customers into preview. I believe this project/initiative has ended.

Also, region to region traffic is encrypted at Layer 2 using MACSec at the edge.
https://gearup.microsoft.com/communications/macsec-encryption-for-azure-inter-region-traffic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0ba091-358a-58a1-2a4f-7dd0270f8cb6
* Version Independent ID: b85a54c6-03a8-7039-31f1-b0e473d20831
* Content: [Network topology and connectivity - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/network-topology-and-connectivity)
* Content Source: [docs/ready/enterprise-scale/network-topology-and-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/network-topology-and-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#319168

**Comment by victorar** [comment]
Thanks for pointing this out, @kodubeau . We'll update the article accordingly.

**Comment by fguerri** [comment]
Customer-ready info about Azure Virtual Network Tap availability is here: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-tap-overview. 
"Virtual network TAP Preview is currently on hold in all Azure regions"

**Comment by stephen-sumner** [comment]
This looks good. 

[TAP reference](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-traffic-inspection). I'm not sure what the article looked like in 2020, but it appears to have been fixed. TAP reference notes it's not available in all regions and provides link to another page that has the same message.

[Encryption reference](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/define-network-encryption-requirements). Encryption reference are to MacSec at layer 2.
