### ISSUE TITLE
Naming standard for diagnostic logs storage accounts

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/cloud-adoption-framework#319]
Hi,
The naming standards are fantastic and have improved a lot.

I have one complaint though :-)

This is the standard for diagnostic logs storage accounts:
**stdiag<first 2 letters of subscription name and number><region><###>**

This does not work. It has to be globally unique and you only have the first to letters make it unique.

Many will have the same subscription name. We are not able to follow it because the names conflict with existing accounts.

You need an App Name also. Since it can only be 24 long you need to drop the region.

Regards Peter

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Recommended naming and tagging conventions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#320080

**Comment by stephen-sumner** [comment]
this has been resolved

**Comment by stephen-sumner** [comment]
#please-close
