### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by prakashchocky** [MicrosoftDocs/cloud-adoption-framework#322]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3accc9a-c1bd-0902-ff93-b7c6cda4fc1f
* Version Independent ID: b5577fca-2148-824a-e6b6-35bb3d8001a5
* Content: [Azure management overview - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-management-guide/)
* Content Source: [docs/manage/azure-management-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/azure-management-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#322537

**Comment by JanetCThomas** [comment]
Please open a new issue with more information if there is an issue you would like us to address.  Thank you!
