### ISSUE TITLE
Add Visio drawing of ESLZ [ready/enterprise-scale-architecture.vsdx] to page, and make it downloadable 

### ISSUE THREAD

**Issue by mpvenables** [MicrosoftDocs/cloud-adoption-framework#323]
@alexbuckgit @BrianBlanchard - since there has been demonstrable interest from users in downloading the original Visio file of the ESLZ, can we include a link to the file on the page, which could prove to be useful for customers? It was already in a  Jun 25, 2020 commit. Cheers.

[ESLZ diagram](https://github.com/microsoft/CloudAdoptionFramework/blob/0a624bc1e793f5e99d4a9c05a2f8a18ac4936f0f/ready/enterprise-scale-architecture.vsdx)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [Cloud Adoption Framework enterprise-scale landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
* Content Source: [docs/ready/enterprise-scale/architecture.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/architecture.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#323071

**Comment by victorar** [comment]
Link to Visio diagram is available on this article: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture

@JanetCThomas > this issue can now be closed.
