### ISSUE TITLE
Incorrect data on Network Design and Encryption

### ISSUE THREAD

**Issue by azwildfire** [MicrosoftDocs/cloud-adoption-framework#324]
this https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/network-topology-and-connectivity#define-network-encryption-requirements:~:text=Azure%20doesn't%20currently%20offer%20native%20encryption,rather%20than%20global%20virtual%20network%20peering. - that text is wrong and conflicts with https://docs.microsoft.com/en-us/azure/security/fundamentals/encryption-overview#encryption-of-data-in-transit 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0ba091-358a-58a1-2a4f-7dd0270f8cb6
* Version Independent ID: b85a54c6-03a8-7039-31f1-b0e473d20831
* Content: [Network topology and connectivity - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/network-topology-and-connectivity#define-network-encryption-requirements)
* Content Source: [docs/ready/enterprise-scale/network-topology-and-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/network-topology-and-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#323419

**Comment by victorar** [comment]
Thanks for pointing this out, @azwildfire . We'll update the article.
