### ISSUE TITLE
Use NAT or not... text is confusing

### ISSUE THREAD

**Issue by karlochacon** [MicrosoftDocs/cloud-adoption-framework#325]
hi guys
I have this customer that has ask me to connect to azure using VPN in order to migrate their workload but they required the same network segment in Azure and I said "well that's not possible" and he talk me how is not possible if Azure says yes
From your documentation below so I am like is possible or not... do not use NAT but you can use it so I don't get it

- Don't use network address translation (NAT).
- Overlapping addresses can cause networks that can't be connected, and routing that doesn't work properly. If networks overlap, you'll need to redesign the network or use NAT._

thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c309fa0-4224-e36f-4ed2-062891b9b46a
* Version Independent ID: 4f2c4f46-69a0-962e-a1a5-17e280489bef
* Content: [Best practices to set up networking for workloads migrated to Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking)
* Content Source: [docs/migrate/azure-best-practices/migrate-best-practices-networking.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/migrate-best-practices-networking.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#325256

**Comment by BrianBlanchard** [comment]
Resolved in PR 1089
