### ISSUE TITLE
What about Azure Resource Mover?

### ISSUE THREAD

**Issue by froand** [MicrosoftDocs/cloud-adoption-framework#327]
Wouldn't it be a good idea to mention the new Resource mover hub and features to move resources? Its in preview but should be mentioned in a couple of places to make the move easier and help to choose the right move tool.

https://docs.microsoft.com/en-us/azure/resource-mover/select-move-tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06391912-66bd-8905-d50e-8b06307fd2e9
* Version Independent ID: e807a790-2b7a-faac-eba4-692a8936fdc7
* Content: [Transitioning existing Azure environments to enterprise-scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/transition)
* Content Source: [docs/ready/enterprise-scale/transition.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/transition.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#325507

**Comment by JanetCThomas** [comment]
The context we are speaking to in the transition article is transition of resources in subscriptions to other subscriptions (not regions) and subscription moves to a new AD Tenant for transferring billing ownership. Our context is mostly on alignment with organizing subscriptions into management groups. It seems to me the Azure Resource Mover tools focus on moving resources across regions. I don’t think this is prescriptive to a specific scenario we observe in enterprise scale landing zone.

Thank you for your feedback.
