### ISSUE TITLE
Wording with SPN permissions

### ISSUE THREAD

**Issue by denisbuco** [MicrosoftDocs/cloud-adoption-framework#329]
Assign Contributor permission to the SPN previously mentioned at the root management group scope (/), which allows tenant-level operations. This permission level ensures that the SPN can be used to deploy and manage resources to any subscription within your organization.

The wording tenant-level is wrong, the SPN ca only perform root management group scope and not tenant-leve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38786a5-e931-e614-55a1-2980b8a28087
* Version Independent ID: a72b6f97-dd0f-252c-f6d9-f1c517aa9a2f
* Content: [Management group and subscription organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization)
* Content Source: [docs/ready/enterprise-scale/management-group-and-subscription-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-group-and-subscription-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#326066

**Comment by JanetCThomas** [comment]
This issue has been addressed.  Thank you for your feedback.
