### ISSUE TITLE
Implementing risk tolerance metrics in Security Baseline discipline

### ISSUE THREAD

**Issue by Hemagupta-cloud** [MicrosoftDocs/cloud-adoption-framework#335]
Could you please add a section on how to implement these metrics. Are they already there for us to configure and view in Security Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d774fe-4427-0493-14d1-d08683dd7589
* Version Independent ID: f46f1230-9053-90fe-0213-a8fc906a84a8
* Content: [Risk tolerance metrics and indicators in the Security Baseline discipline. - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/security-baseline/metrics-tolerance?source=docs#feedback)
* Content Source: [docs/govern/security-baseline/metrics-tolerance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/security-baseline/metrics-tolerance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#327592

**Comment by NaomiOooo** [comment]
Thank you for your comment. As each environment is unique, the threshold is different and dependent on the specific level of risk tolerance. [Further in the documentation](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/security-baseline/policy-statements) there are sample security baseline policies which can be utilized as a starting point to build example monitoring and verification of policy compliance.
