### ISSUE TITLE
Enterprise scale Figures

### ISSUE THREAD

**Issue by NelsonRuest** [MicrosoftDocs/cloud-adoption-framework#337]
Hi, I don't see much difference between figures 2 and 3 on this page. Is there an error. Figure 3 is a hub and spoke network, yet the network components seem identical to the Virtual WAN configuration in Figure 2.

Perhaps you can highlight the differences between the two diagrams to make it clearer. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [Cloud Adoption Framework enterprise-scale landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
* Content Source: [docs/ready/enterprise-scale/architecture.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/architecture.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#332553

**Comment by victorar** [comment]
There is no error on the pictures. As described in the high level architecture section, Enterprise-Scale architecture allows both network architectures, one based on Azure Virtual WAN (figure 2), while the other is based on the traditional hub and spoke model (figure 3). Hence, the only difference on those picture is the network connectivity model in the connectivity subscription: either a VWAN VHUB or a traditional hub VNet.

**Comment by alexbuckgit** [comment]
Resolved issue by added a description of the difference to the label on Figures 2 and 3.
