### ISSUE TITLE
Introduction to some tools missing in the article

### ISSUE THREAD

**Issue by Paken** [MicrosoftDocs/cloud-adoption-framework#344]
[Enter feedback here]
Hi, could you please add an introduction to the following tools with a link to the articles? Thanks!

Azure Change Tracking and Inventory, Azure Activity Log, Azure Monitor for VMs, Azure Network Watcher, DNS Analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd392fd5-89d1-10e8-10f5-5b40be0a3d63
* Version Independent ID: 827ffe94-f5ce-6b14-16e9-a10473e82442
* Content: [Inventory and visibility in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-management-guide/inventory?tabs=AzureServiceHealth%2CLog-Analytics%2CAzure-Monitor%2CConfigure-solutions)
* Content Source: [docs/manage/azure-management-guide/inventory.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/azure-management-guide/inventory.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#335633

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
