### ISSUE TITLE
Incorrect statement in regards to changing tenant not having impact

### ISSUE THREAD

**Issue by lunar87** [MicrosoftDocs/cloud-adoption-framework#345]
In the table, "Moving resources in Azure" in the 2nd row, it states "Can be moved to different management groups, and different tenants" and in the next column says this has no impact. In reality if you change the tenant it can have a significant impact on the subscription. Change the first statement to just "Can be moved to different management groups"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06391912-66bd-8905-d50e-8b06307fd2e9
* Version Independent ID: e807a790-2b7a-faac-eba4-692a8936fdc7
* Content: [Transitioning existing Azure environments to enterprise-scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/transition)
* Content Source: [docs/ready/enterprise-scale/transition.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/transition.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336088

**Comment by BrianBlanchard** [comment]
Addressed in https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/1144/
