### ISSUE TITLE
Example use cases

### ISSUE THREAD

**Issue by TomVanHauwaert** [MicrosoftDocs/cloud-adoption-framework#347]
[Enter feedback here]
As-Is: For example, developers might have contributor access in **production subscriptions** but only reader access in **nonproduction subscriptions**.

To-be: For example, developers might have contributor access in **nonproduction subscriptions** but only reader access in **production subscriptions**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b24efd3-3fda-7c73-6bf6-cfed8a3e2785
* Version Independent ID: 95e455f3-674a-7554-bfd8-d43e46c60271
* Content: [Organize and manage multiple Azure subscriptions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/organize-subscriptions)
* Content Source: [docs/ready/azure-best-practices/organize-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/organize-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#336738

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for the feedback!
