### ISSUE TITLE
.

### ISSUE THREAD

**Issue by swampthing1984** [MicrosoftDocs/cloud-adoption-framework#348]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f7abf1-fbaf-82dc-16a7-0e977675f624
* Version Independent ID: 111a77e0-d565-355f-3ee0-425f61912e75
* Content: [Azure enterprise scaffold is now the Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/azure-scaffold)
* Content Source: [docs/reference/azure-scaffold.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/azure-scaffold.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#337257
