### ISSUE TITLE
Unclear explanation

### ISSUE THREAD

**Issue by JacMos** [MicrosoftDocs/cloud-adoption-framework#358]
Hi,

The last paragraph in this section does not explain the issue well. Could it perhaps be restructured to better convey the message? 

This is OK: 
"When possible, plan for a business continuity and DR network architecture that provides concurrent connectivity to all sites."

This is not clear: 
"DR networks that use the same classless inter-domain routing blocks, such as production networks, require a network failover process that can complicate and delay application failover in the event of an outage."

Perhaps an example could make the explanation clearer?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa647f44-4d81-dca9-933e-22ad48be2f65
* Version Independent ID: 79a68713-ec22-3d5c-f51c-874003d75d90
* Content: [Enterprise-scale business continuity and disaster recovery - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/business-continuity-and-disaster-recovery)
* Content Source: [docs/ready/enterprise-scale/business-continuity-and-disaster-recovery.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/business-continuity-and-disaster-recovery.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
@JefferyMitchell - Please review.

**Comment by stephen-sumner** [comment]
Updates merged in https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3771
