### ISSUE TITLE
replace 001 with 1 for a convention

### ISSUE THREAD

**Issue by GitMje** [MicrosoftDocs/cloud-adoption-framework#359]
Please consider changing `001` to `1` for the convention on VMs and other resources.  In the past, many companies have used the `01` and `001` convention to ensure that a simple `dir` command will sort a name like `vmhelloworld001` before a name like `vmhelloworld100`.

This made sense in legacy systems of the past where the operational staff could predict that the system will never have more than N number of resources.  N being 99 for `01` or 999 for the `001` convention resources.  These conventions breakdown if the operational staff miscalculates and the number of resources exceeds N.

Since the cloud is virtually limitless, it doesn't seem to make sense to put an N limit on the number of VMs that would be in a convention.  Practically, I believe that an Azure Subscription has a [hard upper limit of 10,000 VMs](https://build5nines.com/azure-subscription-resource-limits-and-quotas/), so you could make that the N value and the convention would then be `0001`, but that number may possibly change over time.

I suggest either making the convention the true limit of `0001` for VMs or better yet to use the convention of `1` instead.  In today's world, sorting is just a matter of formatting through tools and shouldn't be built into the structure of the system. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
Padded numbering would be used per combination of resource type, workload/application, environment, and region. So using the example in the diagram, you might have pip-sharepoint-prod-westus-001, pip-sharepoint-prod-westus-002, pip-sharepoint-prod-westus-003, etc., but you could also have pip-sharepoint-prod-eastus-001, pip-sharepoint-prod-eastus-002, etc. as needed. So the upper limit is really the number of resources that all share the same resource type, workload/application, environment, and region, which is almost always less than 1000 items.

The existing note under "Example names for common Azure resource types" also discusses the pros and cons of padding and recommends making your own determination based on your organization's expected needs.

Thanks for the feedback!
