### ISSUE TITLE
If possible, use a service principal to create new subscriptions?

### ISSUE THREAD

**Issue by J0F3** [MicrosoftDocs/cloud-adoption-framework#36]
Can you please elaborate a bit more what you mean by the Tip "If possible, use a service principal to create new subscriptions. Define a security group that can request new subscriptions via an automated workflow". 
Is there somewhere a example how such an automated workflow may looks like?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 047f93ff-16f1-11d8-e29e-b5a1c1713f4c
* Version Independent ID: 66fc9e62-ff99-0424-fc8f-699bc601f023
* Content: [Scaling with multiple Azure subscriptions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/scaling-subscriptions#feedback)
* Content Source: [docs/ready/considerations/scaling-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/scaling-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID AB# 185427

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
