### ISSUE TITLE
Can this page be elevated up the TOC and renamed to Azure fundamentals? 

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/cloud-adoption-framework#360]
These concepts are foundational but very far down the toc - I have to search for them every time I need to link to them - and the are great new-to-cloud day 1 concepts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca59ce2d-4eac-f0c4-6a86-e33a46574975
* Version Independent ID: 0cf30682-6247-7715-69d5-10d8abce29e0
* Content: [Best practices for Azure readiness - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/)
* Content Source: [docs/ready/azure-best-practices/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
Thanks for the suggestion. We'll review how we can best improve the discoverability of this content.
