### ISSUE TITLE
Title change to What is Azure? instead of Foundational alignment

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/cloud-adoption-framework#361]
I'm not sure what the TOC entry for this page is supposed to mean but it might be better represented with "What is Azure?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca59ce2d-4eac-f0c4-6a86-e33a46574975
* Version Independent ID: 0cf30682-6247-7715-69d5-10d8abce29e0
* Content: [Best practices for Azure readiness - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/)
* Content Source: [docs/ready/azure-best-practices/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
The terminology for this section came out of long discussions between many stakeholders. We won't revisit it at this time. Thanks for the feedback.
