### ISSUE TITLE
Page Loop

### ISSUE THREAD

**Issue by anthonypelosi74** [MicrosoftDocs/cloud-adoption-framework#362]
I read the page, get to the end and click on the next topic.  I read the next page, click on the link for the next article and it brings me back here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d70b1a-338e-6f92-8889-0abe2a0dacae
* Version Independent ID: afbbf40d-efe7-5193-7673-ac49999ef6fb
* Content: [Subscription decision guide - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/subscriptions/)
* Content Source: [docs/decision-guides/subscriptions/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/decision-guides/subscriptions/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by alexbuckgit** [comment]
We're planning to review and update the next steps across the framework for consistency. Thanks for the feedback.
