### ISSUE TITLE
Add the "Cloud data functions" to the "Manage organizational alignment" page

### ISSUE THREAD

**Issue by abdeslemmenacere** [MicrosoftDocs/cloud-adoption-framework#363]
add the ["Cloud data functions"](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-data) to the ["Manage organizational alignment"](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/) page as it's already present under the "required cloud functions" left menu.
![image](https://user-images.githubusercontent.com/545124/102285164-f7508d00-3f35-11eb-9862-bd614ec3bf3a.png)

**Comment by JanetCThomas** [comment]
This issue has been resolved.  Thank you.
