### ISSUE TITLE
ServiceNow mentioned as a SIEM Product

### ISSUE THREAD

**Issue by lmqferreira** [MicrosoftDocs/cloud-adoption-framework#369]
"on-premises security information and event management (SIEM) systems such as ServiceNow,"
Correct me if I'm wrong but I don't think ServiceNow qualifies as something on premises nor as a SIEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13a01671-cf1f-63e1-b526-7346953d8042
* Version Independent ID: 9ae96c16-1771-f098-f581-6a5abc630ed6
* Content: [Management and monitoring - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-and-monitoring)
* Content Source: [docs/ready/enterprise-scale/management-and-monitoring.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-and-monitoring.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
@JefferyMitchell - could you please take a look at this issue?
