### ISSUE TITLE
Azure Tag Values Examples: ISO date format must be recommended as a best practice instead of en-US

### ISSUE THREAD

**Issue by peternazarov** [MicrosoftDocs/cloud-adoption-framework#370]
Not all people in the world live in the USA - ISO date format must be recommended as a best practice: **yyyy-MM-dd**

Global azure resources are menage globally by international teams. Using a county-specific date format will cause confusion for other countries. Thus, the ISO date format would be most appropriate. Microsoft Best Practices must cover this aspect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7230a9-5b65-919f-1ed7-e4c3647cdc55
* Version Independent ID: 705b4355-78aa-b573-c833-de558da2a958
* Content: [Define your tagging strategy - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-tagging)
* Content Source: [docs/ready/azure-best-practices/resource-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
