### ISSUE TITLE
Abbreviation defined for Event Hub but not its EventHub namespace

### ISSUE THREAD

**Issue by jmostella** [MicrosoftDocs/cloud-adoption-framework#371]
It seems that in the documentation we have overlooked providing a recommendation for an `Event Hub namespace` prefix.
I'm thinking this should be the same pattern as `Notification Hubs` so we end up with:

| Asset type |  Abbreviation |
| --- | --- |
| Event hub | `evh-` |
| Event hub namespace | `evhns-` |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!

**Comment by jmostella** [comment]
Thanks alot!
