### ISSUE TITLE
broken Link behind Microsoft IT Pro Center

### ISSUE THREAD

**Issue by skiddder** [MicrosoftDocs/cloud-adoption-framework#372]
in section: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/suggested-skills#typical-mappings-of-cloud-it-roles
the link [Microsoft IT Pro Center](https://www.microsoft.com/itpro) seems to be broken. I am forwarded to this page: https://www.microsoft.com/de-de/microsoft-365/enterprise?rtc=1 which does not look like MS IT Pro Center to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3987c901-9893-d2ec-69a4-8e0365782a79
* Version Independent ID: eeef013b-6b45-4c1c-48f4-fbdcf99e4ad8
* Content: [Skills readiness path during the Plan phase of a migration journey - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/suggested-skills)
* Content Source: [docs/strategy/suggested-skills.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/suggested-skills.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
@BrianBlanchard - please review and recommend a new link or other fix.
