### ISSUE TITLE
Methodologies Summary Duplication

### ISSUE THREAD

**Issue by LazarusRSKAJ** [MicrosoftDocs/cloud-adoption-framework#376]
In the section that summarises the 8 methodologies, the 'Organize' summary is the same as the 'Govern' summary. They both say 'Govern the environment and workloads'. I assume the Organize summary should actually be something different?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66744a3f-7ab3-80ae-4c76-639ee78601bf
* Version Independent ID: 081c5a49-8bd7-778e-da3f-11ad4667c4a2
* Content: [Microsoft Cloud Adoption Framework for Azure documentation - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview)
* Content Source: [docs/overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/357638/>357638</a>

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
