### ISSUE TITLE
Do snapshots really provide high availability?

### ISSUE THREAD

**Issue by jbsilva** [MicrosoftDocs/cloud-adoption-framework#384]
"Azure Synapse Analytics uses database snapshots to provide high availability of the warehouse".
I don't see how snapshots provide high availability. Restoring snapshots can take a long time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e06f46-d1d0-6ed9-62ed-a700274a7584
* Version Independent ID: 300a8337-56b8-c81f-c3b9-e4d79879cbb3
* Content: [High availability for Azure Synapse Analytics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/azure-synapse)
* Content Source: [docs/migrate/azure-best-practices/analytics/azure-synapse.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/analytics/azure-synapse.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @v-hanki
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/361855/>361855</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved.  You should see the changes go live soon.  Thank you for your feedback.
