### ISSUE TITLE
Lack of information regarding RDS License Server

### ISSUE THREAD

**Issue by fchambon** [MicrosoftDocs/cloud-adoption-framework#385]
The doc should hightlight that you need to setup a RD Licensing Server when migrating RDS servers to WVD.

Also, the diagram should be updated: the architecture showcases the RDMI service with a "licensing" component managed by Microsoft. However, this licensing component works only for Client OS, not servers OSES. Something like this should be added:

[https://zupimages.net/viewer.php?id=21/03/kr6x.png](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177be313-669c-b534-575c-27eaa49b76b8
* Version Independent ID: 33169923-9568-077a-7f12-19554a9dbb94
* Content: [Move on-premises Remote Desktop Services to Azure Windows Virtual Desktop scenario - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rds-to-wvd)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @benstegink
* Microsoft Alias: **abuck**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363598/>363598</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.

**Comment by alexbuckgit** [comment]
@BrianBlanchard

**Comment by stephen-sumner** [comment]
I believe the issue is slightly misapplied to this article. 

To my knowledge, the RD licensing server is for [Windows-Server based VMs](https://docs.microsoft.com/en-us/azure/virtual-desktop/deploy-windows-server-virtual-machine#prerequisites). The CAF article only references Windows, not Windows Server.
