### ISSUE TITLE
Some spelling errors in topic "Primary: Hybrid and multicloud concerns"

### ISSUE THREAD

**Issue by marcelohazuma** [MicrosoftDocs/cloud-adoption-framework#387]
In the title "Primary: Hybrid and multicloud concerns" it seems that "Primary: " can be removed. I'm not seeing the reason for it.

In the sentence "Others require significant effort pre- & post-deployment to realize those benefits.". The "-" from "pre-" can be removed.

In the sentence "To account for deviations in the cloud environments, companies often end up with distinct operations tooling and operations practices, this multiples the cost of operations by the number of cloud environments supported.", "this multiples" should be replaced by "this multiplies"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb496583-bc70-51c0-72ad-be82b742e1c1
* Version Independent ID: dcd37951-e125-4faa-ec81-824348b8b4cc
* Content: [Introduction to Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363695/>363695</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
