### ISSUE TITLE
Azure Static Web Apps Abbreviation

### ISSUE THREAD

**Issue by MichaelEdwardBlack** [MicrosoftDocs/cloud-adoption-framework#388]
With Azure Static Web Apps now available I thought it would be nice to suggest an abbreviation for the resource group. My suggestion would be STAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363736/>363736</a>

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
