### ISSUE TITLE
Unable to see the image

### ISSUE THREAD

**Issue by sushantrane** [MicrosoftDocs/cloud-adoption-framework#389]
Image Link broken for 3 illustrations showing how different customers distribute workloads across cloud providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da811d0e-df5f-0715-cc72-8b4f1bb1bb49
* Version Independent ID: 55e4182b-954d-0822-d6cf-2f59c37a1b2c
* Content: [Ready methodology for Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/ready?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363781/>363781</a>

**Comment by JanetCThomas** [comment]
This has been fixed in the private repo. Thanks,
