### ISSUE TITLE
Misspelling in Governance disciplines block

### ISSUE THREAD

**Issue by marcelohazuma** [MicrosoftDocs/cloud-adoption-framework#390]
Governance disciplines

In the sentence "THe following best practices will help preserve your security baseline across all environments:" the "THe" is misspelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aebf0942-1829-cb38-5263-c7ff39269f32
* Version Independent ID: c54cb208-a8b1-1f65-39e4-2b3a383d7ca5
* Content: [Govern your portfolio of hybrid and multicloud workloads - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/govern?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/govern.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/govern.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363865/>363865</a>

**Comment by JanetCThomas** [comment]
Typo fixed.  Thanks.
