### ISSUE TITLE
Missing Monitoring for the Unified Operations and Hybrid Scenarios

### ISSUE THREAD

**Issue by marcelohazuma** [MicrosoftDocs/cloud-adoption-framework#391]
I'm missing in the Unified Operations and Hybrid Scenarios strategy the Monitoring piece. What will be the approach to consolidate logs, generate alerts, and provide dashboards?

Maybe not a blocker for the initial MVP, but it is always one of the initial questions I get when planning for a deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51aa3a88-e631-e489-bbb8-3cacf0524555
* Version Independent ID: 7628b439-449f-2715-ac1a-8f5e116d7811
* Content: [Strategy for unified operations adoption - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/strategy?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
Added to the review backlog.
