### ISSUE TITLE
Hybrid and Multicloud definitions - Edge clarification suggestion

### ISSUE THREAD

**Issue by peteb-ms** [MicrosoftDocs/cloud-adoption-framework#392]
In the edge section, I was a little confused about where the edge was and what was being brought to where.  I reworded it to better match what I felt was the intent of the paragraph as a potential as a suggestion:

The hybrid cloud is evolving to include edge workloads as well. Cloud-managed Edge computing devices bring the computing power of the public cloud to the private cloud—closer to where the IoT devices reside. By moving workloads to the edge, devices spend less time communicating with the cloud, reducing latency, and they are even able to operate reliably in extended offline periods.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb496583-bc70-51c0-72ad-be82b742e1c1
* Version Independent ID: dcd37951-e125-4faa-ec81-824348b8b4cc
* Content: [Introduction to Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363892/>363892</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
