### ISSUE TITLE
Hybrid and Multicloud Narrative Last paragraph

### ISSUE THREAD

**Issue by peteb-ms** [MicrosoftDocs/cloud-adoption-framework#393]
The final paragraph of this section regarding what I believe to be referencing Azure Stack and Databox Edge was a little confusing to me.  The following is a suggestion for a little different wording:

Cloud services are often thought of only in the context of moving data and applications to the public cloud.  Scenarios where customers operate in highly regulated industries (e.g. government infrastructure, healthcare, financial services) where both internal and customer data must remain within the boundaries of on-premises datacenters, data latency sensitivity requires compute to be close to source data in on-premises datacenters, or when Internet connectivity disruptions have critical implications or are expected can prevent the use of the public cloud for some workloads. In these scenarios, hybrid solutions that bring cloud services, decreased management overhead, and the cloud billing model can be deployed in on-premises datacenters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb496583-bc70-51c0-72ad-be82b742e1c1
* Version Independent ID: dcd37951-e125-4faa-ec81-824348b8b4cc
* Content: [Introduction to Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363957/>363957</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
