### ISSUE TITLE
Modify your environment to reflect your cloud mix - Spelling - Missing URL - Format

### ISSUE THREAD

**Issue by peteb-ms** [MicrosoftDocs/cloud-adoption-framework#394]
Identity: Which cloud will host your primary identity provider? If that provider is outside of Azure, you may need to integrate your identity provider with Azure Active Directory. **See the following for additional guidance**. Missing URL link

Public network connectivity: Best practice suggests that all ingress and egress traffic should route through one cloud platform when possible. But, your requirements or cloud mix may require more of a peer model. This is especially common, if your cloud mix is used to reach redundancy and reliability requirements. How will **your - should be you** configure connectivity between each cloud platform and the public internet?

Backup and Recovery: It is very common for customers to centralize their backup and recovery strategy around the most reliable provider in their cloud mix. This often results in one of the cloud providers serving as a shared recovery center. Azure Backup and Azure Site Recovery can help in each case. - **Cloud platform connectivity: - Carriage return needed** If your cloud platforms will share common recovery, operations, or governance resources, you may require connectivity between each cloud platform. How will your configure connectivity between each cloud platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da811d0e-df5f-0715-cc72-8b4f1bb1bb49
* Version Independent ID: 55e4182b-954d-0822-d6cf-2f59c37a1b2c
* Content: [Ready methodology for Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/ready?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/363977/>363977</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
