### ISSUE TITLE
Analyze your cloud mix

### ISSUE THREAD

**Issue by peteb-ms** [MicrosoftDocs/cloud-adoption-framework#395]
This section seems out of place in the timeline.  This article is focused on preparing for the cloud and identifying the Azure architectural inputs based on the customer's intended hybrid cloud strategy.  This section describes how to inventory an existing hybrid cloud deployment.  Perhaps this is meant to show that you can be intentional, understand your current deployment, then reimagine even your existing architectures.  You can follow this process even if you have already deployed?  That sentiment doesn't come across, however, and the content feels a little out of place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da811d0e-df5f-0715-cc72-8b4f1bb1bb49
* Version Independent ID: 55e4182b-954d-0822-d6cf-2f59c37a1b2c
* Content: [Ready methodology for Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/ready?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364391/>364391</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
