### ISSUE TITLE
Minor change to Evaluate your cloud mix

### ISSUE THREAD

**Issue by BobJK** [MicrosoftDocs/cloud-adoption-framework#396]
Within 'Evaluate your cloud mix' for readability consider changing:

'...moving from a -hybrid first- mix to an -Azure first- mix, as their cloud strategy matures.'  to '...moving from a 'hybrid first' mix to an 'Azure first' mix, as their cloud strategy matures.'

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364434/>364434</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
