### ISSUE TITLE
Missing Hyperlink within Modify your environment to reflect your cloud mix section

### ISSUE THREAD

**Issue by BobJK** [MicrosoftDocs/cloud-adoption-framework#397]
Within the Modify your environment to reflect your cloud mix under 'Identity' it reference 'See the following for additional guidance.' however there is no hyperlink to take you to additional guidance

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364443/>364443</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
