### ISSUE TITLE
Manage your portfolio across hybrid and multicloud operations Hyperlink broken

### ISSUE THREAD

**Issue by BobJK** [MicrosoftDocs/cloud-adoption-framework#398]
Within the 'Extending your operations baseline' the following hyperlink is directed to a link that provides a 404 error...

Follow this guide on hybrid and multicloud update management to deploy tools that can control patching across cloud providers.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364485/>364485</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
