### ISSUE TITLE
Additional Hyperlinks broken within 'Manage your portfolio across hybrid and multicloud operations 

### ISSUE THREAD

**Issue by BobJK** [MicrosoftDocs/cloud-adoption-framework#399]
Within ‘Enhanced baseline’ section ‘Onboard Azure assets: linux VMs and Windows VMs’  the hyperlink for ‘Windows VMs’ receives a 404 error when you try to follow the link

Within ‘Operations manement discplines’ section ‘Manage VMs with MMA’ hyperlink provides a 404 error when you follow the link; ‘Scale configuration of MMA’ receives a 404 error when you try to follow the link

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364493/>364493</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
