### ISSUE TITLE
Physical Machine Assessments

### ISSUE THREAD

**Issue by tjsullivan1** [MicrosoftDocs/cloud-adoption-framework#4]
Hello,

What can be done for the assessment of physical machines? As far as I know, Azure Migrate does not yet have support for physical assessments, and a tool like the Microsoft Assessment Planning Toolkit could be used, but I think a recommendation should be added to this document or [this document](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/decision-guides/migrate-decision-guide/index).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15019be8-d19c-e28b-6dac-d5dc044fcdab
* Version Independent ID: d2a0c05a-d264-de58-b251-ef955e0316df
* Content: [Assess the digital estate - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/migrate/azure-migration-guide/assess?tabs=Tools#feedback)
* Content Source: [docs/cloud-adoption/migrate/azure-migration-guide/assess.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/cloud-adoption/migrate/azure-migration-guide/assess.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @Matticusau
* Microsoft Alias: **mlavery**

**Comment by BrianBlanchard** [comment]
Resolved with the release of Azure Migrate V2
