### ISSUE TITLE
Is it possible to create Azure policy to enforce budget control and prevent resource underutilization? 

### ISSUE THREAD

**Issue by mpchen** [MicrosoftDocs/cloud-adoption-framework#40]
Wondering what are some of Azure Policy examples for cost management? For example, is it possible to use Azure Policy to limit spending at Resource Group level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9a86fd-b0f3-8de4-0800-5124ce4f0f4a
* Version Independent ID: 6337b7e3-c10b-bfc7-9ebc-c175c938c967
* Content: [Cost Management sample policy statements - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/cost-management/policy-statements)
* Content Source: [docs/govern/cost-management/policy-statements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/cost-management/policy-statements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Great idea. This feature is currently unavailable. I'll pass along the feedback to the policy and cost management teams.
