### ISSUE TITLE
Azure Resource Graph based inventorying - provide documentation

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/cloud-adoption-framework#400]
In this page it is mentioned "Azure Resource Graph can be used to perform an inventory of existing resources and compare their configuration with the policies existing at the destination." - Please provide a documentation on how to do this, and link that document to this page.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/364922/>364922</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
