### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sckissel** [MicrosoftDocs/cloud-adoption-framework#401]
[Enter feedback here]
Suggest removing the word "Primary" in the heading "Primary: Hybrid and multicloud concerns." Perhaps there is another section yet to be added called secondary? Should it instead be "Primary Hybrid and multicloud concerns?" or "Common concerns with Hybrid and multicloud?"

Under the same heading, there is the sentence "Existing operations management platforms were not build for these types of environments." which has a spelling error. It should be "...built..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb496583-bc70-51c0-72ad-be82b742e1c1
* Version Independent ID: dcd37951-e125-4faa-ec81-824348b8b4cc
* Content: [Introduction to Hybrid and Multicloud - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/?branch=pr-en-us-884#feedback)
* Content Source: [docs/scenarios/unified-operations/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/365296/>365296</a>

**Comment by sckissel** [comment]
Any maybe Hybrid shouldn't be capitalized, as it does not appear to always be capitalized in subsequent docs.

**Comment by alexbuckgit** [comment]
Added to the review backlog.
