### ISSUE TITLE
Unified operations - hybrid, multicloud, and edge - Suggestions

### ISSUE THREAD

**Issue by sckissel** [MicrosoftDocs/cloud-adoption-framework#402]
1st paragraph:
"...is necessary to understand what might affect primary cost options, such as capital expenses and operating costs." - suggest changing to "..is necessary to understand what options might affect costs, such as capital expenses and operating costs."

3rd paragraph:
"...and required cloud functions that support developing a long-term cloud operating model." - should "required" be past tense, or present tense, like require (like demand) cloud functions? If "required", what are examples of the cloud functions?

4th paragraph:
"Develop and evolve a mature team, starting from a Minimum viable product (MVP)..." - _mature team_ is the hyperlink here, but it's anchored to a section of the page about MVP on a whole page about "mature team structure". Perhaps hyperlink _mature team_ to the main "mature team structure" page, and hyperlink  _Minimum viable product (MVP)_ to the anchor for "Best practice: Minimum viable product (MVP)..."

"Delegate responsibilities, and execute on modern technical abilities." - I understand the innate desire to pause here but technically the comma is unnecessary. 

5th paragraph:
"...falsely..." is a pretty harsh word here, signifying a binary value between true and false. Is that the intention, or would "inaccurately" fit better here?

Hyperlink "...three-year return on investment, and substantial avoided on-premises infrastructure and staff costs..." - Misspelling - should be _substantially_.

"(For small deployments, energy use and emissions can be reduced by more than 90 percent with a shared cloud service)" - Suggest not putting this in parentheses. It can be a standalone sentence, perhaps reworded to something like "Additionall,y Energy use and emissions for smaller deployments can be reduced by more than 90 percent with a shared cloud solution.

6th paragraph:
"Organizations can modernize and optimize overall operations using a simple approach to overcoming risks—overhead cost increases, or challenges related to staffing core functions." - I'm lost on what this is trying to convey unless the the dash is really supposed to be a comma.

"This article describes the provider-neutral approach of using unified operations to extend a control plane over distributed resources across hybrid, multi-cloud, and edge environments." - At first, I thought "this article" was supposed to be a hyperlink, but then I read the first sentence of the 2nd paragraph, and I think this docs page is **the** article. If that's correct, perhaps it could be reworded to "The following article..." or "This article that follows..." or "The rest of this doc..." or move this sentence down under another heading called "Approach" or "Overview" or something and combine it with paragraph 7. I just don't consider it an article. Guidance maybe?. Same for using "more articles will follow..." in paragraphy 7. 

**Heading: Primary Cloud Platform**
1st major paragraph: 
"Your primary cloud platform will also include a series of controls, designed to support operations within that cloud." - Suggest removing the comma. 

Caution note: At the very end, does it make sense to say something like "Azure is one such platform" with a link to our Azure main page or something about our overall platform capabilities? I know the doc is attempting to stay neutral, but the caution doesn't give any examples when someone asks "like who?"

**Heading: Unified Operations**
Overall, suggest replacing parentheses with commas or finding another way to break up the sentence. Last paragraph - same response as note immediately above this. After all, Azure was mentioned in the 2nd paragraph twice. 

**Heading: Unified Operations Decomposed**
1st paragraph: 
Could probably shorten "This image displays the individual components required for unified operations, and shows how they interact with each other." to "This image displays the individual components required for unified operations and how they interact with each other." No comma needed. 

Customer Processes Image - Suggest this should either be the first thing under the heading, or the first thing under the first two paragraphs, but not in the center of the first two paragraphs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6ac624-cfc2-7056-6b94-bbb064740884
* Version Independent ID: f53a9128-0e7d-69f2-693a-60318438a23c
* Content: [Unified operations for hybrid, multicloud, and edge - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/unified-operations?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/unified-operations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/unified-operations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/365340/>365340</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
