### ISSUE TITLE
using region in the resource name, might not be a good idea.

### ISSUE THREAD

**Issue by CODevOp** [MicrosoftDocs/cloud-adoption-framework#403]
I just finished looking at this page and implementing some of it suggestions. I question using the region in the resource name. What if resource you are using is replicated to another region. In this case the region in the name will be mis-leading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366297/>366297</a>

**Comment by jocontr** [comment]
Feel free to use our tool https://github.com/microsoft/CloudAdoptionFramework/tree/master/ready/AzNamingTool for your resource naming needs.

We will make sure that our documentation reflects this as well.

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24070 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
