### ISSUE TITLE
Issues across this docs elements

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/cloud-adoption-framework#404]
https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/scenario-overview?branch=pr-en-us-2312 is broken as well as others:

https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/migrate

https://review.docs.microsoft.com/en-us/azure/architecture/framework/hybrid/hybrid-overview?branch=pr-en-us-2237&bc=%2fazure%2fcloud-adoption-framework%2f_bread%2ftoc.json&toc=%2fazure%2fcloud-adoption-framework%2ftoc.json&branch=pr-en-us-2237

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9e6371-997b-be0c-5208-b36daf7d9e51
* Version Independent ID: e9eaa9ee-f021-8ec7-ecf8-76be29ca5ad3
* Content: [Plan for unified operations - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/plan?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/plan.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/plan.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366758/>366758</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
