### ISSUE TITLE
Link for Hybrid and multicloud readiness plan

### ISSUE THREAD

**Issue by binals** [MicrosoftDocs/cloud-adoption-framework#405]
It would be great to link to a page providing next steps guidance to hybrid/ multicloud readiness plan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9e6371-997b-be0c-5208-b36daf7d9e51
* Version Independent ID: e9eaa9ee-f021-8ec7-ecf8-76be29ca5ad3
* Content: [Plan methodology for hybrid and multicloud strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/plan?branch=pr-en-us-884#add-pagebreak-here)
* Content Source: [docs/scenarios/unified-operations/plan.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/plan.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @mpvenables
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366860/>366860</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
