### ISSUE TITLE
Update picture

### ISSUE THREAD

**Issue by binals** [MicrosoftDocs/cloud-adoption-framework#406]
The image in 'Evaluate your cloud mix' section should have the label 'Azure' in the top right box for the 'Multicloud first' image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da811d0e-df5f-0715-cc72-8b4f1bb1bb49
* Version Independent ID: 55e4182b-954d-0822-d6cf-2f59c37a1b2c
* Content: [Ready methodology for hybrid and multicloud strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/ready?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @mpvenables
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366868/>366868</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
