### ISSUE TITLE
Patch and update management link is not working

### ISSUE THREAD

**Issue by binals** [MicrosoftDocs/cloud-adoption-framework#407]
There is reference to patch and update management but the link seems to be not live yet. It gives me a 404 error. 

https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/unified-operations/server/best-practices/arc-updatemanagement.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ca1c40-0fd9-092c-335b-7c6d55dc7433
* Version Independent ID: 9e69b47c-c2c6-44ff-b5b5-a74ff0b88a4a
* Content: [Manage your portfolio across hybrid and multicloud operations - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/manage?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/manage.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/manage.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/366933/>366933</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
