### ISSUE TITLE
Correct wording in the Azure Arc description

### ISSUE THREAD

**Issue by markohot** [MicrosoftDocs/cloud-adoption-framework#409]
My feedback is about this:
This cloud-based service extends the Azure Resource Manager-based management model to non-Azure resources including virtual machines (VMs), Kubernetes clusters, and containerized databases.

I think "containerized databases", even though accurate from the implementation perspective, is not how we want to position Azure Arc enabled SQL MI or PostgreSQL Hyperscale. We should say "data services".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 689b6839-ae47-030e-4539-30939fe17a38
* Version Independent ID: 460d91fe-8cde-2405-6f46-9530e63cca17
* Content: [Introduction to Azure Hybrid and Multicloud products - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/toolchain?branch=pr-en-us-884&source=docs)
* Content Source: [docs/scenarios/unified-operations/toolchain.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/toolchain.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/367391/>367391</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
