### ISSUE TITLE
Microsoft Monitoring Agents (MMA)

### ISSUE THREAD

**Issue by francesco-sodano** [MicrosoftDocs/cloud-adoption-framework#411]
"One example of a mature operations management discipline is to use Microsoft Monitoring Agents to manage software installation"

should be changed as 

"One example of a mature operations management discipline is to use Microsoft Monitoring Agents (MMA) to manage software installation"

as it is the first time you are introducing it in the page and later you have only reference to MMA (not the expanded name anymore)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ca1c40-0fd9-092c-335b-7c6d55dc7433
* Version Independent ID: 9e69b47c-c2c6-44ff-b5b5-a74ff0b88a4a
* Content: [Manage your portfolio across hybrid and multicloud operations - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/unified-operations/manage?branch=pr-en-us-884)
* Content Source: [docs/scenarios/unified-operations/manage.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/unified-operations/manage.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/367880/>367880</a>

**Comment by alexbuckgit** [comment]
Added to the review backlog.
