### ISSUE TITLE
Consider updating naming convention to post-fix resource type

### ISSUE THREAD

**Issue by kyleburnsdev** [MicrosoftDocs/cloud-adoption-framework#412]
The published naming recommendation uses the resource type as a prefix. Since resource type is already an available stand-alone filter and sorting criteria in the portal, it is common practice for this to be used as a post-fix instead of pre, leaving other parts of the existing recommendation in place. Even the quick start quide embedded in the Azure portal follows the convention of post-fixing the resource type. The quick start guide and documented convention recommendations should be aligned and I recommend keeping what is demonstrated in the quick start guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/369076/>369076</a>

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24378 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/5534
