### ISSUE TITLE
Grammar wording - RBAC Design

### ISSUE THREAD

**Issue by desonier** [MicrosoftDocs/cloud-adoption-framework#414]
RBAC Design
Role Based Access Controls (RBAC) can help you provide separation of duties among engineering and operational staff. As part of your landing zone design **you should** who will be added to each role and create security groups for each to simplify adding and removing users from each role.

Link: https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-identity-and-access-management?branch=wvd-scenario

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/374170/>374170</a>

**Comment by JanetCThomas** [comment]
This is on our backlog. Thank you!
