### ISSUE TITLE
Load balancer is regional, not global

### ISSUE THREAD

**Issue by dohughes-msft** [MicrosoftDocs/cloud-adoption-framework#416]
Hi, in the table comparing load balancing solutions the Azure Load Balancer is listed as a global service. This is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee541725-0b3e-153c-6875-de17ea85e4b3
* Version Independent ID: 0686e67e-7908-5666-1baf-1e4ae202b11d
* Content: [Enterprise-Scale security, governance, and compliance for SAP - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/eslz-security-governance-and-compliance?branch=SAP-scenario)
* Content Source: [docs/scenarios/sap/eslz-security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/sap/eslz-security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @deepakonics
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/375784/>375784</a>

**Comment by JanetCThomas** [comment]
This is in our backlog.

**Comment by JanetCThomas** [comment]
@deepakonics can you make sure this is fixed in the private repo.

**Comment by deepakonics** [comment]
Thank you @JanetCThomas , as part of our recent announcement at https://docs.microsoft.com/en-us/azure/load-balancer/cross-region-overview its a global (preview) . Details below- 
Azure Load Balancer - Azure Standard Load Balancer supports cross-region load balancing enabling geo-redundant HA scenarios such as:
Incoming traffic originating from multiple regions.
Instant global failover to the next optimal regional deployment.
Load distribution across regions to the closest Azure region with ultra latency.
Ability to scale up/down behind a single endpoint.
Static IP
Client IP preservation
Build on existing load balancer solution with no learning curve
