### ISSUE TITLE
CAF Baseline tool is unavailable

### ISSUE THREAD

**Issue by clouddude** [MicrosoftDocs/cloud-adoption-framework#418]
https://cafbaseline.com/ is unavailable 

HTTP Error 500.30 - ANCM In-Process Start Failure
Common solutions to this issue:
The application failed to start
The application started but then stopped
The application started but threw an exception during startup
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028265

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d6acd7-52c2-0fcd-77ad-a30e96ecbf45
* Version Independent ID: af35206e-2b05-0ae7-8ca9-6e43330e96e6
* Content: [Tools and templates - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/tools-templates)
* Content Source: [docs/reference/tools-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/tools-templates.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/375984/>375984</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved.  Thank you!
