### ISSUE TITLE
Azure Dev Spaces is bring retired

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/cloud-adoption-framework#419]
I think Azure Dev Spaces is being retired and Bridge to Kubernetes replaces it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d04bb23f-c4d6-ee39-0843-084b1411328b
* Version Independent ID: 5aba2c57-770d-4bed-c178-44cd05aab9c2
* Content: [Application development and deployment - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/kubernetes/application-development)
* Content Source: [docs/innovate/kubernetes/application-development.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/kubernetes/application-development.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @sabbour
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/376036/>376036</a>

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
