### ISSUE TITLE
resource-type prefix inconsistencies

### ISSUE THREAD

**Issue by mikemwalsh** [MicrosoftDocs/cloud-adoption-framework#42]
Some prefixes are suggested to use the leading 'a' from Azure while others are not.  This should be consistent or a general reason given for differences.  For example, next to each other in the list:

Azure Stream Analytics | asa-
Azure Data Factory | df-

Why not 'adf' or 'sa'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/naming-and-tagging)
* Content Source: [docs/ready/considerations/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by licentiat** [comment]
Resource-type shouldn't be included on the resource name. I don't think that's or should be considered best practice.

**Comment by jlorich** [comment]
This has been addressed in #73 (which is merged and deployed)

If marketing from the PG embraces an acronym (e.g. AKS, ADF) the `a` prefix stayed, otherwise it's gone and all of the `az` prefixes are gone.

**Comment by BrianBlanchard** [comment]
Resolved
