### ISSUE TITLE
Step 2 leads to a page that leads to a 404

### ISSUE THREAD

**Issue by eyast** [MicrosoftDocs/cloud-adoption-framework#420]
Step 2 of the checklist links to an e-book download site (Containerize your Apps with docker and Kubernetes).
On that download site, after filling the form, a 404 is returned. just thought of letting you know, it's a little broken and maybe we're better off removing the link to the e-book if we can tfind owner?
Thanks, Eyas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d04bb23f-c4d6-ee39-0843-084b1411328b
* Version Independent ID: 5aba2c57-770d-4bed-c178-44cd05aab9c2
* Content: [Application development and deployment - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/kubernetes/application-development)
* Content Source: [docs/innovate/kubernetes/application-development.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/kubernetes/application-development.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @sabbour
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/376038/>376038</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved.
