### ISSUE TITLE
Synapse Analytics Workspace naming convention is missing!

### ISSUE THREAD

**Issue by nansravn** [MicrosoftDocs/cloud-adoption-framework#430]
We should add a naming convention for Synapse Analytics Workspace. We only have a convention for SQL DW (old naming for the solution). New customers doesn't know what is SQL DW, what they know is our new name Synapse Analytics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/383650/>383650</a>

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
