### ISSUE TITLE
Add PPTX for managing information and cyber risk

### ISSUE THREAD

**Issue by rowbot1** [MicrosoftDocs/cloud-adoption-framework#431]
[Enter feedback here]

Is it possible to get the powerpoint slide of https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/_images/security/enterprise-security-team.png? I'm looking to adapt it to my own organisation. 
Thanks
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a63cfdc-ec6b-d418-c776-33c5f81c3f2d
* Version Independent ID: 91bcd8ea-6acc-1c50-0c3b-ef3dce565632
* Content: [Cloud security functions - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/organize/cloud-security)
* Content Source: [docs/organize/cloud-security.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/organize/cloud-security.md)
* Service: **cloud-adoption-framework**
* Sub-service: **organize**
* GitHub Login: @MarkSimos
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/383676/>383676</a>

**Comment by alexbuckgit** [comment]
@MarkSimos - Can we make the PPT file for this diagram available?

**Comment by rowbot1** [comment]
Any update on this?
