### ISSUE TITLE
"Managed identity" template not matching with example shown

### ISSUE THREAD

**Issue by johnfreitasau** [MicrosoftDocs/cloud-adoption-framework#432]
Hi there,

Under **Example names - General**, the example shown for the item **Managed identity** gives the template `id-<app or service name>`, however the example under this template shows `id-appcn-keda-prod-eastus2-001` which includes region and instace as well. Could you please clarify what is the best practice for this item.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/386338/>386338</a>

**Comment by stephen-sumner** [comment]
Thanks! This has been addressed. I'll close this.
