### ISSUE TITLE
encryption for traffic between Azure regions

### ISSUE THREAD

**Issue by chanstev** [MicrosoftDocs/cloud-adoption-framework#436]
[Enter feedback here]
In the recommandation of this page, it stated "If traffic between Azure regions must be encrypted, use global VNet peering to connect virtual networks across regions." It seems inconsistent with other docs about if vnet peering is encrypted. 

However, in VNet peering document, it suggested no encryption is required as within Microsoft backbone network. 
[Virtual network peering](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview)
```
"Network traffic between peered virtual networks is private. Traffic between the virtual networks is kept on the Microsoft backbone network. No public Internet, gateways, or encryption is required in the communication between the virtual networks."
```
Or the encryption should be maintained in application layer rather than network layer. 
[Choosing between Azure VNet Peering and VNet Gateways](https://azure.microsoft.com/en-us/blog/vnet-peering-and-vpn-gateways/)
```
VNet Peering Encrypted? "Software level encryption is recommended"
```
Should the recommandation be "If traffic between Azure regions must be encrypted, use global VNet peering to connect virtual networks across regions **with software/application layer level encryption**"?"
```
"Evaluate the capability to configure a Site-to-Site VPN connection over ExpressRoute private peering (in preview."
```
S2S VPN over ER private peering is announced as [GA](https://azure.microsoft.com/en-gb/updates/general-availability-vpn-over-expressroute-private-peering). Suggest to include the [link with details](https://docs.microsoft.com/en-us/azure/vpn-gateway/site-to-site-vpn-private-peering), which highlighted the requirements of using RFC1918 IP spaces and zone-redundant gateways.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd3063c-5b6c-1245-3b68-ee4f14a0d30c
* Version Independent ID: 79ef82ad-8792-8b3d-8e43-ca0ee12a71dd
* Content: [Define network encryption requirements - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/define-network-encryption-requirements)
* Content Source: [docs/ready/azure-best-practices/define-network-encryption-requirements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/define-network-encryption-requirements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/389333/>389333</a>

**Comment by alexbuckgit** [comment]
@JefferyMitchell - Please review.

**Comment by fguerri** [comment]
The "Design  Considerations" section contains a clear statement about encryption applied to VNet peering traffic: "When Azure traffic moves between datacenters (outside physical boundaries not controlled by Microsoft or on behalf of Microsoft), MACsec data-link layer encryption is used on the underlying network hardware. This is applicable to VNet peering traffic".
I suggest that we keep this statement and simply remove this one: "If traffic between Azure regions must be encrypted, use global VNet peering to connect virtual networks across regions" in the "Design Recommendations" section.
