### ISSUE TITLE
Beginning

### ISSUE THREAD

**Issue by ddsmatt** [MicrosoftDocs/cloud-adoption-framework#439]
[Seeking supporters involved in this process of moving into a cloud environment]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1610c03-0d55-650d-f6dc-6d01e5eaa4d9
* Version Independent ID: 8f783a6b-d355-be34-2f0d-6bee33f53a89
* Content: [Complex enterprise governance: Multiple governance layers - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/guides/complex/multiple-layers-of-governance)
* Content Source: [docs/govern/guides/complex/multiple-layers-of-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/govern/guides/complex/multiple-layers-of-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/391167/>391167</a>

**Comment by ddsmatt** [comment]
Thanks for your reply!

**Comment by alexbuckgit** [comment]
Hi @ddsmatt - Can you provide some clarification about the issue you would like to see resolved?

**Comment by ddsmatt** [comment]
I'm trying to resolve my Azure directory instance connecting or verifying with sts.windows directory--just beginning and learning.
