### ISSUE TITLE
Spelling incorrect for 'Role entitlement' in Visio download 

### ISSUE THREAD

**Issue by the-chad-at-ms** [MicrosoftDocs/cloud-adoption-framework#440]
The 'role entitlement' label in the Visio file is spelt incorrectly (i.e. Role enttlement').
In the actual image, it is spelt correct but when you download the .vsdx it is spelt incorrectly across both the VWAN and Hub and Spoke diagrams.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/394737/>394737</a>

**Comment by WendyRing** [comment]
This issue has been resolved. Thanks for reporting it.
