### ISSUE TITLE
Reference Architecture images

### ISSUE THREAD

**Issue by stevemagid** [MicrosoftDocs/cloud-adoption-framework#441]
The reference architecture images in Step 3 look very valuable however, the links do not take you to the templates that correspond to these images.

Step 3: Develop a security plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f21a1b1a-5437-e0a8-f0c7-cbc02c9e1ea3
* Version Independent ID: a4ad4d32-16f5-caf4-f6e4-400062197184
* Content: [Get started: Secure the enterprise environment - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/security)
* Content Source: [docs/get-started/security.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/security.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/396896/>396896</a>

**Comment by skabou** [comment]
Thank you for your feedback.  It appears your suggestion has been addressed. If you are still experiencing an issue, please feel free to re-open with additional information.

**Comment by skabou** [comment]
#please-close
