### ISSUE TITLE
More examples to connect to other providers

### ISSUE THREAD

**Issue by PatricSten** [MicrosoftDocs/cloud-adoption-framework#444]
With your partnership with SAP, would be nice to have some information about connectivity to their SAP Cloud
https://blogs.sap.com/2019/12/16/multi-cloud-capability-model-for-sap-cloud-platform-and-microsoft-azure/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dc8cffa-98d4-1729-e3da-4e481745d785
* Version Independent ID: 8988c67c-cd03-4bd5-a6e5-5611e5152cfe
* Content: [Connectivity to other cloud providers - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/connectivity-to-other-providers)
* Content Source: [docs/ready/azure-best-practices/connectivity-to-other-providers.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/connectivity-to-other-providers.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexandreweiss
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
Thanks for your feedback. We've added this to our backlog for review and prioritization.
