### ISSUE TITLE
Errors in the Identify compute services requirements flowchart

### ISSUE THREAD

**Issue by colinbeales** [MicrosoftDocs/cloud-adoption-framework#445]
I think the flow chart for compute (in https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/compute-options#identify-compute-services-requirements) is a great idea, but I think the flow doesn't quite work.

The Yes/No question for on the Build New fork around the need for full fledged orchestration would have you use ACI when you want an orchestrator rather than ASF/AKS which seems a mistake.

In this area too I would argue the guidance to use ASF for .NET applications is no longer correct now we have Windows Nodes in AKS.

Finally on the same Build New fork I would say the Yes/No for "Microservices architecture" is probably the wrong way around. Again leading you to App Service when you have microservices. Whilst if you have a few services this may work it would take away from the fact that AKS (or ASF) would be a much better choice for microservices and so again would read better if the Yes/No were inverted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ad3f0b-32fa-bdf7-d0b3-0e8b8c31ea0d
* Version Independent ID: 9a686ba2-a4ea-0dba-c1f5-003e9824a0ee
* Content: [Review your compute options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/compute-options#identify-compute-services-requirements)
* Content Source: [docs/ready/considerations/compute-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/compute-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/401989/>401989</a>
