### ISSUE TITLE
storage-options.md needs updating

### ISSUE THREAD

**Issue by cengxiye** [MicrosoftDocs/cloud-adoption-framework#446]
This article is too old. Several aspects need to be updated.
For example the ultra SSD regions are now not only in East US 2.
In addition to LRS, ZRS, GRS, now we have GZRS etc..

This is a great article but lack of updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acd2fd4-b22c-5c11-e891-cc4993d9891e
* Version Independent ID: 1acbff98-4a94-53f5-dd45-8f22637602b4
* Content: [Review your storage options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/storage-options)
* Content Source: [docs/ready/considerations/storage-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/storage-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/403280/>403280</a>

**Comment by skabou** [comment]
It appears this was addressed some time ago.  If help is still needed, please feel free to re-open with additional details.
