### ISSUE TITLE
Content is very similar with Accelerate Migration

### ISSUE THREAD

**Issue by vunvulear** [MicrosoftDocs/cloud-adoption-framework#447]
I was looking at the following two pages

1. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/migrate
2. https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/innovate

The content that is available for Innovate is very similar to the one for migration. For innovate I would expect more information related to greenfield projects, not about migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909bcd2f-c3cd-6a51-7929-89181fe63188
* Version Independent ID: af62a7e3-3f59-090d-5ac4-377748ac2ca2
* Content: [Get started: Build new products and services in the cloud - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/innovate)
* Content Source: [docs/get-started/innovate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/innovate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/404692/>404692</a>

**Comment by JanetCThomas** [comment]
We have added this to our backlog. Thank you.
