### ISSUE TITLE
Do you plan to modify the Azure portal according to this rule in the future?

### ISSUE THREAD

**Issue by takekazuomi** [MicrosoftDocs/cloud-adoption-framework#449]
It looks like it's best practice with rules that aren't common today.  For example,  Azure Portal does not follow this naming convention. Do you plan to modify the Azure portal according to this rule in the future?

The important difference is whether it is a post-fix resource type or a prefix resource type.
It's a big difference and best practices are an important guide. I think the prefix resource type is a good idea.
If it is not appropriate to provide feedback here, please let us know.

Related 
https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/412

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming?WT.mc_id=AZ-MVP-5002499)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/410944/>410944</a>

**Comment by alexbuckgit** [comment]
We've added this item to our backlog for review and prioritization. Thanks for your feedback!
