### ISSUE TITLE
Azure consumption costs in ROI calculation?

### ISSUE THREAD

**Issue by PaulTzl** [MicrosoftDocs/cloud-adoption-framework#450]
In terms of cost calculation you don't seem to mention anything about estimating Azure consumption costs. For example, if the calculation is including the reduction in operational costs of the existing data centre, surely it should also include new costs associated with Azure consumption (and not just in support of the migration activities, but Azure costs associated with the Azure landing zone and workloads to be migrated)? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42f8649e-4a66-2667-b4c7-88698cf5183f
* Version Independent ID: ce9e86a7-423d-7177-685d-ed9f426940b5
* Content: [Financial model for cloud migration - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/financial-models)
* Content Source: [docs/strategy/financial-models.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/financial-models.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/411645/>411645</a>

**Comment by alexbuckgit** [comment]
Estimating cost deltas using the Azure pricing calculator and the Azure TOC calculator is discussed in the previous article. https://docs.microsoft.com/azure/cloud-adoption-framework/strategy/cloud-migration-business-case

Thanks for your feedback.
