### ISSUE TITLE
Private link and DNS integration at scale with AKS

### ISSUE THREAD

**Issue by jkroepke** [MicrosoftDocs/cloud-adoption-framework#451]
Hi!

thanks for sharing this document. I tried to integrate this concept with a private AKS cluster from a spoke.

The policy works well, I can see that the private endpoint "kube-apiserver" is linked to private dns zone from the hub, but unlike step 11 I could not see a dns entry inside the dns zone.

It's possible that this concept won't work with private AKS endpoints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-US/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/411713/>411713</a>
