### ISSUE TITLE
Zx

### ISSUE THREAD

**Issue by XZ07** [MicrosoftDocs/cloud-adoption-framework#452]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69abf33c-9597-13b9-a7e0-3329a1a29346
* Version Independent ID: 43c6a4e4-879b-c521-d81f-db2ed0d47a37
* Content: [Get started with the Cloud Adoption Framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/)
* Content Source: [docs/get-started/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/412968/>412968</a>

**Comment by XZ07** [comment]
> [Enter feedback here]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 69abf33c-9597-13b9-a7e0-3329a1a29346
> * Version Independent ID: 43c6a4e4-879b-c521-d81f-db2ed0d47a37
> * Content: [Get started with the Cloud Adoption Framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/)
> * Content Source: [docs/get-started/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/index.md)
> * Service: **cloud-adoption-framework**
> * Sub-service: **overview**
> * GitHub Login: @JanetCThomas
> * Microsoft Alias: **janet**
