### ISSUE TITLE
Changes recommended to Netezza article

### ISSUE THREAD

**Issue by milczyk** [MicrosoftDocs/cloud-adoption-framework#453]
1. it's is hard to understand about wich Synapse do you speak the old one or the new one. I'm missing both descriptions. 
2. by Data type mapping: "The following table shows the data types and the recommended approaches for mapping the data types." the table is missing and I'm highly interested in getting to know about this data type, as I plan to migrate Netezza
3. there is no description about Migration to Azure SQL DB (single instances / pool) you recommend to consider SQL DB for operational workloads, but there is not even a single page with recommendation about Netezza migration to Azure SQL DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12fe3278-b43a-96b7-494d-88ca84cc8f1f
* Version Independent ID: d7935e7f-3e8d-06fb-f639-9d6e97f58966
* Content: [Azure Synapse Analytics migration for Netezza - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/analytics-solutions-netezza)
* Content Source: [docs/migrate/azure-best-practices/analytics/analytics-solutions-netezza.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/analytics/analytics-solutions-netezza.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @v-hanki
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/412978/>412978</a>

**Comment by JanetCThomas** [comment]
We've updated this article.  Thank you for your feedback.
