### ISSUE TITLE
Add a recommended abbreviation for Microsoft.EventGrid/eventSubscriptions

### ISSUE THREAD

**Issue by ryanhofdotgov** [MicrosoftDocs/cloud-adoption-framework#454]
For our system, we've just adopted the Microsoft recommended abbreviations for Azure resources rather creating and documenting our own. So far, every resource we've needed to name has been in [this doc](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations), with the exception of `Microsoft.EventGrid/eventSubscriptions`. 

It's a very minor request, but it would be useful for a standard abbreviation for event subscriptions be documented. Perhaps `evgs-` which would be consistent with with `evgd-` and `evgt-`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/414650/>414650</a>

**Comment by WendyRing** [comment]
Event Grid subscriptions has been added to this article. Thanks for the feedback and we'll close this issue.
