### ISSUE TITLE
Article may not account for global enterprises with multiple paths into Azure

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/cloud-adoption-framework#456]
The article assumes that the enterprise, regardless of size (global or not), has a single pathway for DNS resolution when it comes to Azure endpoints.

Consider adding a best practice for the below scenario for the Cloud Adoption Framework:
An enterprise that has multiple on-prem environments (that have connectivity to eachother), the on-prem environments have their own connectivity path to their own individual Azure Vnet (that don't connect to eachother within Azure).

Now if more than 1 VNet are using Private Endpoints, the Cloud Adoption Framework fails because DNS (at a basic design level) can only go 1 path for resolving a specific Private Link DNS zone, rather than going to the VNet hosting the specific endpoint for resolution.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/414948/>414948</a>
