### ISSUE TITLE
How to manage Subscription centrally and programtically?

### ISSUE THREAD

**Issue by smoms** [MicrosoftDocs/cloud-adoption-framework#459]
[Enter feedback here]
If I need to manage all subscriptions (e.g. the landing zones) from a single script, do I need to create an AAD Service Principal with proper RBAC role and add it to each and every Subscription at creation time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [Cloud Adoption Framework enterprise-scale landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture)
* Content Source: [docs/ready/enterprise-scale/architecture.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/architecture.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/416675/>416675</a>

**Comment by dominicallen** [comment]
Hi - thanks for the question! 
Based on an organizations security requirements the approach could include a role with permissions across the subscriptions or one per subscription. 
Further guidance here - https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management

In this proposed approach, Platform owners are granted permissions to MG and Subscription life-cycles. There are then roles for subscription owner and application owners - which, based on the application, could be a single subscription or resource group or multiple.
