### ISSUE TITLE
please fix the image

### ISSUE THREAD

**Issue by santhoshbomma9** [MicrosoftDocs/cloud-adoption-framework#463]
Please fix the image
https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4ad3f0b-32fa-bdf7-d0b3-0e8b8c31ea0d
* Version Independent ID: 9a686ba2-a4ea-0dba-c1f5-003e9824a0ee
* Content: [Review your compute options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/compute-options)
* Content Source: [docs/ready/considerations/compute-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/compute-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/418631/>418631</a>

**Comment by WendyRing** [comment]
Closing this issue. Please provide additional details for any further issues with the image. Thank you!

**Comment by santhoshbomma9** [comment]
![image](https://user-images.githubusercontent.com/40445595/120352033-3c366900-c2b5-11eb-8ddb-d1ff0c66ed55.png)
![image](https://user-images.githubusercontent.com/40445595/120352084-48222b00-c2b5-11eb-9a54-364e425532e0.png)
Please see the difference and the image on this page is wrong. You have the right image on https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree
