### ISSUE TITLE
H/A with Snapshots how does that work?

### ISSUE THREAD

**Issue by D-Moonesinghe** [MicrosoftDocs/cloud-adoption-framework#465]
This statement sounds wrong.
"Azure Synapse Analytics uses database snapshots to provide high availability of the warehouse. A data warehouse snapshot creates a restore point that can be used to recover or copy a data warehouse to a previous state."

Snapshots are good for rolling back. But how does it provide high availability?  
Doesn't a human operator have to detect and roll it back. If then it won't be H/A would it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e06f46-d1d0-6ed9-62ed-a700274a7584
* Version Independent ID: 300a8337-56b8-c81f-c3b9-e4d79879cbb3
* Content: [High availability for Azure Synapse Analytics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/azure-synapse)
* Content Source: [docs/migrate/azure-best-practices/analytics/azure-synapse.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/analytics/azure-synapse.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @v-hanki
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/419082/>419082</a>

**Comment by WendyRing** [comment]
We are aware of this issue and are working on a resolution. Thank you!
