### ISSUE TITLE
Netezza migration to Azure SQL DB missing

### ISSUE THREAD

**Issue by milczyk** [MicrosoftDocs/cloud-adoption-framework#466]
there is no description about Migration to Azure SQL DB (single instances / pool). In some documentation you recommend to consider SQL DB for operational workloads, but there is not even a single page with recommendation about Netezza migration to Azure SQL DB.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/419405/>419405</a>

**Comment by JanetCThomas** [comment]
We have this article about Netezza migration. 
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/analytics/analytics-solutions-netezza 
Hopefully this helps. 
Thanks!
