### ISSUE TITLE
Cost - Container Insights

### ISSUE THREAD

**Issue by woutervanranst** [MicrosoftDocs/cloud-adoption-framework#467]
At _least_ mention a reference to the first party Container Insights (https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-cost), next to Kubecost. This implements very much the same feature set but at a lower/"included" price point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9c02f1-b536-94e8-04b5-f8733ad74461
* Version Independent ID: 39026912-0ec3-6fcc-5da2-4caa9e7af4f4
* Content: [Enterprise-scale Azure Kubernetes Service (AKS) security governance and compliance - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/aks/eslz-security-governance-and-compliance#cost-governance)
* Content Source: [docs/scenarios/aks/eslz-security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/aks/eslz-security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/420989/>420989</a>

**Comment by woutervanranst** [comment]
I may have had a serious brainfart when making this suggestion. The Cost Insight for Containers does _not_ provide the cost per workload but the cost of the actual insight solution. Apologies for the confusion here, but you may probably close this.
