### ISSUE TITLE
Update on the ES Data for deployment time

### ISSUE THREAD

**Issue by FallenHoot** [MicrosoftDocs/cloud-adoption-framework#469]
![image](https://user-images.githubusercontent.com/19664186/117197333-fbe3e800-ade7-11eb-8930-db3902af80dd.png)

Enterprise-scale data is wrong

If you just deploy the policies it takes about 5-10 min
If you deploy with Networking it takes about 30-60~ min

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca49bac-b45a-8db1-b8fb-f80de9e8d227
* Version Independent ID: 75749ee0-c1e0-2ef8-c790-14db0fb6da4c
* Content: [Choose the landing zone for your organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/choose-landing-zone-option#overview-of-landing-zone-options)
* Content Source: [docs/ready/landing-zone/choose-landing-zone-option.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/choose-landing-zone-option.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/421577/>421577</a>
