### ISSUE TITLE
Aligning CAF with other Azure guidance? 

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/cloud-adoption-framework#47]
How does the CAF Governance model align with the Governance model guidance outlined here - https://docs.microsoft.com/en-us/azure/governance/azure-management. 

There appears to be overlap but it does not appear consistent.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID AB#185429

**Comment by BrianBlanchard** [comment]
After several iterations of updates to the naming conventions used in CAF govern, Azure governance, and other governance guidance, the requested alignment should now be in place.
