### ISSUE TITLE
2 min to read?

### ISSUE THREAD

**Issue by ilyah22** [MicrosoftDocs/cloud-adoption-framework#474]
At the top of the page it is stated: "2 minutes to read", but there is a video introduction included that is about 2.5 min. How accurate or helpful is this "X min to read" statement? Should it say something like: 2 min to read, 3 min to watch the video, 3 day s to learn and 1 week to implement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6230652-e478-a07e-45cf-5d560c276c13
* Version Independent ID: 888cb6ce-2c26-3d98-1327-c91805083665
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/423511/>423511</a>

**Comment by JanetCThomas** [comment]
Thank you for your feedback. The estimated time to read is auto generated and doesn't take the video, or time to implement into account.
