### ISSUE TITLE
Incorrect image

### ISSUE THREAD

**Issue by SeanStL** [MicrosoftDocs/cloud-adoption-framework#477]
It looks like the KPI for the % User Tickets is in the wrong place in the image. On prem and Azure are switched. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be5476d1-25b5-60b8-ed2d-8c1b00a1762a
* Version Independent ID: dd41c7f9-c000-f169-fff2-036c46d05b01
* Content: [Measure business outcomes with AppDynamics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/digital-estate/app-dynamics)
* Content Source: [docs/digital-estate/app-dynamics.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/digital-estate/app-dynamics.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @wayneme75
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/426980/>426980</a>

**Comment by wayneme75** [comment]
updated the image and added to the wayneme75-1 repo.

**Comment by JanetCThomas** [comment]
This issue has been fixed.  The screenshot was updated and should be live shortly.  Thanks!
