### ISSUE TITLE
Static Web Apps listed twice with two different abbreviations?

### ISSUE THREAD

**Issue by DavidCBerry13** [MicrosoftDocs/cloud-adoption-framework#479]
In the "Compute and Web" section there is a line titled "Static web app" with the suggested abbreviation of "stapp"

Then in Developer tools, there is "Azure Static Web Apps" with a suggested abbreviation of "stap-"

It sure looks like these two lines represent the same thing (though with different suggested abbreviation).  Hard to be sure though.  Some clarification would be great (and maybe one of these lines should go away)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/428514/>428514</a>

**Comment by LevYas** [comment]
@JanetCThomas what abbreviation is the recommended one?
BTW I can enter hyphens in the name of a static web app, so it can be "stapp-" with a hyphen, isn't it?

**Comment by WendyRing** [comment]
Thanks for your feedback. The article has been updated and this issue will be closed.
