### ISSUE TITLE
Organize is referenced in the LHS navigation but isn't in the diagram nor mentioned on the CAF home page?

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/cloud-adoption-framework#48]
Organize is referenced in the LHS navigation but isn't in the overview diagram nor mentioned on the CAF home page?

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/

**Comment by BrianBlanchard** [comment]
Organize is currently an unofficial "bonus" methodology. This is high on our testing and design list but will likely be a while before it is addressed. Holding on test results regarding the definition of the broader operating model. More to follow...
