### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by RichardatMS** [MicrosoftDocs/cloud-adoption-framework#483]
There are two considerations I wanted to point out with regards to point out:
1) We have a potential legal risk with our reference to ITIL. Firstly because he have not included (R) as a superscript next to ITIL as a registered trademark which would be cause for legal action, and because we are painting a specific framework with a bad light. Microsoft should likely not be taking an official stance on a specific framework in our public domain like this.
2) While the intent is completely correct, CAB's will cause a bottleneck, I believe this is an unfortunate understanding in application and practice. ITIL recommends risks are correctly managed, these can be done through standard change models which do not need preauthorization or CAB sessions. So if Axelos (publishers of ITIL) was to see what has been written here they may be able to take legal action because the statement is not entirely correct. It must also be noted that ITIL v4 has just been released and its narrative has been updated to help facilitate understanding around more iterative approaches to change management. 

If assistance in getting the operational guidance around the practice for change management and cloud migration is needed I am happy to support the team as I am an FTE and specialize in our customers adopting this approaches for Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7e0deec-1bf5-5971-d1e7-e2736f2ed5fc
* Version Independent ID: 3e6311b1-e0de-d532-b7eb-46deb6b6e64a
* Content: [Approve architecture changes before migration - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/migration-considerations/assess/approve)
* Content Source: [docs/migrate/migration-considerations/assess/approve.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/migration-considerations/assess/approve.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/430193/>430193</a>

**Comment by JanetCThomas** [comment]
@RichardatMS  – We would be very interested in hearing your suggestions for an appropriate change.  You can open a PR with the changes in the private repo at: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr or by clicking the edit button on the article staged in the master branch:  https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/migration-considerations/assess/approve?branch=master

Thank you so much for bringing this to our attention and for offering to help fix the issue.

**Comment by alexbuckgit** [comment]
@RichardatMS - Closing per email thread.
