### ISSUE TITLE
404 hyperlink azuresecuritytop10

### ISSUE THREAD

**Issue by vandyrodrigues** [MicrosoftDocs/cloud-adoption-framework#486]
[I am getting a 404 error  - https://aka.ms/azuresecuritytop10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca71e9c-4132-63ab-382a-d25b299f4078
* Version Independent ID: 6dc4e1c6-1f14-9a05-7c78-1a5ff3dbdff2
* Content: [Security in the Microsoft Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/secure/)
* Content Source: [docs/secure/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/secure/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **secure**
* GitHub Login: @MarkSimos
* Microsoft Alias: **mas**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/431919/>431919</a>

**Comment by MarkSimos** [comment]
This looks like it's due to the rename of the folder from security to secure

https://docs.microsoft.com/azure/cloud-adoption-framework/secure/security-top-10

I fixed the aka.ms URL for this (and each of the direct links)

Mark

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks for your feedback!
