### ISSUE TITLE
App-V

### ISSUE THREAD

**Issue by Niglb** [MicrosoftDocs/cloud-adoption-framework#487]
I am surprized to see AppV as the sole quoted technology.

Shouldn't AppAttach be quoted? 

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-platform-automation-and-devops#application-installation-in-windows-virtual-desktop-images

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516d6288-2c04-3934-04a9-ca95dca66d3d
* Version Independent ID: 049eeabb-25b0-9d96-7bba-1aff3f7e5015
* Content: [Enterprise-scale platform automation and DevOps for Windows Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-platform-automation-and-devops#application-installation-in-windows-virtual-desktop-images)
* Content Source: [docs/scenarios/wvd/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/wvd/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/432141/>432141</a>

**Comment by RobBagby** [comment]
The article was updated on 4/4/22 to add MSIX app attach in the guidance.
