### ISSUE TITLE
Azure and operational readiness resources? 

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/cloud-adoption-framework#49]
Are these resources useful ? 

https://azurechecklist.com/ 

https://prr-website-qa-arm-542l7.azurewebsites.net/ (note we will update this with a proper DNS name soon) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8aa3a67-185b-39a0-047a-9364fc9d051a
* Version Independent ID: 78e44609-dd9e-efe7-01f9-5eab765e6e1c
* Content: [Establish an operational fitness review - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/operational-fitness-review)
* Content Source: [docs/manage/operational-fitness-review.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/operational-fitness-review.md)
* Service: **cloud-adoption-framework**
* Sub-service: **operate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID AB#185436

**Comment by BrianBlanchard** [comment]
The align very well to the assessment tool that we have been building into the docs platform. As we lock in the roadmap for additional assessments, it would be great to get you feedback on the individual assessments going into that tool
