### ISSUE TITLE
Header typo on mainframe application migration

### ISSUE THREAD

**Issue by glitchassassin** [MicrosoftDocs/cloud-adoption-framework#490]
"Perform a staged mainframe to Azure" should probably be "Perform a staged migration to Azure"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4911c9f2-91ea-a05f-69d8-899bed3d6cf3
* Version Independent ID: c3ef47bc-5c9d-822a-8184-a0c5861e96a3
* Content: [Mainframe application migration strategies - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/infrastructure/mainframe-migration/application-strategies)
* Content Source: [docs/infrastructure/mainframe-migration/application-strategies.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/infrastructure/mainframe-migration/application-strategies.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @njray
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/433101/>433101</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved. Thanks!
