### ISSUE TITLE
Editorial correction

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#491]
The text states that "two main metrics" but then 4 metrics are described. Please correct this.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5ef245-95c1-7dd1-3375-e342b81b5513
* Version Independent ID: bb0821e9-ad1e-85f8-4301-5be96929c7b4
* Content: [Security operations - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/secure/security-operations)
* Content Source: [docs/secure/security-operations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/secure/security-operations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **secure**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/433978/>433978</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved. Thank you for your feedback.
