### ISSUE TITLE
Double abbreviation

### ISSUE THREAD

**Issue by hugovoerman** [MicrosoftDocs/cloud-adoption-framework#492]
The abbreviation 'st' is used for Storage Account as well as VPN site.

Also 'syn' is used for 'Azure Synapse Analytics' as well as 'Azure Synapse Analytics Workspaces'

Please use unique abbreviations.

My suggestion is to use synaw for 'Azure Synapse Analytics Workspaces' and to use 'vpnst' for 'VPN site'

And is there a reason why Azure Active Directory, Azure Active Directory B2C and Azure Active Directory B2B is not part of this list?

And perhaps a CSV download of the Asset types and abbreviations is possible? 

We intend to use this to feed into our architecture system to be 100% consistent with the names/abbreviations used in Microsoft Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/434009/>434009</a>

**Comment by hugovoerman** [comment]
Also 'syn' is used for 'Azure Synapse Analytics' as well as 'Azure Synapse Analytics Workspaces'
My suggestion is to use synaw for 'Azure Synapse Analytics Workspaces'

and (from the above) to use 'vpnst' for 'VPN site'

**Comment by WendyRing** [comment]
Thanks for your feedback and suggestions. The VPN, storage and Synapse abbreviations have been updated. Your suggestion to add Azure Active Directory, Azure Active Directory B2C and Azure Active Directory B2B, and a csv download option will be added to the backlog for further review and consideration. This issue will be closed.
