### ISSUE TITLE
Blueprints introduction wording not clear

### ISSUE THREAD

**Issue by Rubenisme** [MicrosoftDocs/cloud-adoption-framework#493]
In the Azure setup guide under the Blueprints it has this sentence:

> Azure Blueprints makes it possible for development teams to rapidly build and stand up new environments and trust that they're building within organizational compliance using a set of built-in components like networking to speed up development and delivery.

I think I understand what is meant by "stand up" here, but in English the transitive verb according to [Merriam-Webster's dictionary](https://www.merriam-webster.com/dictionary/stand%20up) means "to fail to keep an appointment with". I don't think that's what is meant here.

When I look at [another dictionary](https://www.thefreedictionary.com/stand%20up) I don't see other meanings for the transitive verb, I do see some meanings under the intransitive verb that might be meant here, but that's just confusing.

So can this be changed to some other way of phasing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c18016-c40e-c856-7270-a61a300beaa7
* Version Independent ID: 802ab303-1df6-e752-6f78-25d5e65eccff
* Content: [Governance, security, and compliance in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/govern-org-compliance?tabs=AzureBlueprints)
* Content Source: [docs/ready/azure-setup-guide/govern-org-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/govern-org-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tvuylsteke
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/435359/>435359</a>
