### ISSUE TITLE
Incorrect info about Sysprep

### ISSUE THREAD

**Issue by DeanCefola** [MicrosoftDocs/cloud-adoption-framework#494]
The Image Creation section has a statement that is wrong. 
"Windows is limited to running Sysprep eight times, which limits how many times you can create a gold image."

There is a link to the sysprep docs in that same text that says the limit is 1001, not 8 
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation#limits-on-how-many-times-you-can-run-sysprep

This section should read as follows:
"Windows is limited to running Sysprep one Thousand ones (1001) times, which practically removed the limits of how many times you can create a gold image."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516d6288-2c04-3934-04a9-ca95dca66d3d
* Version Independent ID: 049eeabb-25b0-9d96-7bba-1aff3f7e5015
* Content: [Enterprise-scale platform automation and DevOps for Windows Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-platform-automation-and-devops?source=docs#image-creation)
* Content Source: [docs/scenarios/wvd/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/wvd/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/435603/>435603</a>

**Comment by stephen-sumner** [comment]
This has been addressed. #please-close
