### ISSUE TITLE
Missing scale worksheet

### ISSUE THREAD

**Issue by cwidhelm** [MicrosoftDocs/cloud-adoption-framework#496]
In the section marked as **Use the template** it references a Scale worksheet.  This worksheet does not exist in the file linked.

https://raw.githubusercontent.com/Microsoft/CloudAdoptionFramework/master/manage/opsmanagementworkbook.xlsx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 320b8301-4aac-a65c-c8e9-00e85c911d48
* Version Independent ID: 51c100c4-ae5f-5542-9370-cb5fae2d34c2
* Content: [Business criticality in cloud management - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/considerations/criticality)
* Content Source: [docs/manage/considerations/criticality.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/considerations/criticality.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438429/>438429</a>

**Comment by JanetCThomas** [comment]
Closing this issue.  The spreadsheet has been updated. If you still see an issue, please let us know.  Thank you!
