### ISSUE TITLE
VPN Site abbreviation collides with Storage Account

### ISSUE THREAD

**Issue by carldjohnston** [MicrosoftDocs/cloud-adoption-framework#498]
Good morning,

I'm reviewing the abbreviations, and considering a PR to the azurecaf Terraform Provider, but the VPN Site abbreviation `st-` appears to collide with the Storage Account `st`.

I suggest changing this to `vst-`.

Also, the VPN Connection resource abbreviation is `cn-`, but I think this would be better as `vcn-`.

Thanks!

Carl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438777/>438777</a>

**Comment by WendyRing** [comment]
Thanks for the feedback. The article has been updated and this issue will be closed.
