### ISSUE TITLE
The image doesn't match the headings in the document

### ISSUE THREAD

**Issue by wmeints** [MicrosoftDocs/cloud-adoption-framework#500]
The labels in the image at the top of this document do not match the headings in the document. It's kind of confusing to be honest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 130e32b0-bca6-d185-1988-07baed84e77d
* Version Independent ID: 95eb87fc-fb45-06ae-70c6-f4e4109ae96f
* Content: [Responsible and trusted AI - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/trusted-ai)
* Content Source: [docs/innovate/best-practices/trusted-ai.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/best-practices/trusted-ai.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @msteller-Ai
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/438992/>438992</a>

**Comment by WendyRing** [comment]
The images have been updated and will go live this week. Thanks for your feedback.
