### ISSUE TITLE
Consider adding links to the different tools proposed

### ISSUE THREAD

**Issue by omri374** [MicrosoftDocs/cloud-adoption-framework#503]
This is a great document. Consider adding links to SEAL, SmartNoise, Presidio and the other tools proposed in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f90f6cea-98d6-d360-0f15-f9843d54a434
* Version Independent ID: 3c03d1a4-4cba-189d-2920-eb05d67a89b8
* Content: [Responsible AI - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/responsible-ai)
* Content Source: [docs/strategy/responsible-ai.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/responsible-ai.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @v-hanki
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/439348/>439348</a>

**Comment by JanetCThomas** [comment]
The fixes in PR 504 has been approved. You should see the changes live soon.  Thank you.
