### ISSUE TITLE
Difficult to understand this page

### ISSUE THREAD

**Issue by PaulTzl** [MicrosoftDocs/cloud-adoption-framework#505]
Hi, the first few paragraphs of this page makes sense where you talk about "learning metrics".

But I then realised I don't actually know what you mean by learning metrics.

I first thought you might be talking about skilling up staff and learning from the experience of the first few migrations etc.

But the page then goes on to have sections for "Cloud Migration", "Application innovation" and "Data innovation".

So taking "Cloud Migration" section as an example, are you trying to say that the number of VMs migrated is a "learning metric"? In which case the work "learning" is confusing me.

Regards

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9062ac-00cf-b148-b73f-cda525d99c45
* Version Independent ID: 6740abb0-dbc9-5590-eb93-24cc068c6fed
* Content: [Align efforts to learning metrics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/learning-metrics)
* Content Source: [docs/strategy/learning-metrics.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/learning-metrics.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/439506/>439506</a>

**Comment by mpvenables** [comment]
Resolved. @JanetCThomas ok to close.

**Comment by v-andreaco** [comment]
@mpvenables 

Thanks! I'm seeing an open PR with the fixes in the private repo. Once that PR is signed off and merged, we'll close this. :)

**Comment by stephen-sumner** [comment]
@JanetCThomas @v-andreaco - this issue came up in our backlog. I believe it has been addressed. I couldn't even find "Learning metrics" in the current article.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/learning-metrics

We can close this issue.
