### ISSUE TITLE
SAP Subscriptions in wrong MG within Architecture Diagram?

### ISSUE THREAD

**Issue by PaulJohnston88** [MicrosoftDocs/cloud-adoption-framework#508]
Are the SAP subscriptions linked to the wrong Management Group within the Architecture diagram? There is a SAP Management Group but the subscriptions appear to be linked to the Corp Management group instead which might cause some confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f1fff-2485-a841-1b26-aa9601d2a121
* Version Independent ID: d8f114ec-93c2-f30b-6ac8-bfa47160813b
* Content: [Enterprise-scale for SAP on Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone?source=docs#architecture)
* Content Source: [docs/scenarios/sap/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/sap/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/440809/>440809</a>

**Comment by prasad3017** [comment]
@JanetCThomas @WendyRing What is being published is correct. SAP environment is under "**Corp**"  management group for Corporate network connectivity. AKS in this example does not connect to Corporate network and has separate management policies from online management group.

Thanks @PaulJohnston88  for your feedback and hope my response answers your query. Please feel free to leave a comment

**Comment by PaulJohnston88** [comment]
@prasad3017 thanks! I'm still a little confused as to why there is a SAP Management Group if the SAP subscriptions aren't placed there. If the SAP subscriptions belong in the Corp Management Group, would it be best to then remove the SAP Management Group from the diagram to prevent confusion? I don't see any AKS subscriptions or workloads in this diagram.

**Comment by jocontr** [comment]
Closing issue given @prasad3017 response. Thank you
