### ISSUE TITLE
Azure Migrate Project naming

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/cloud-adoption-framework#51]
Can you please include a naming suggestion for newer services like Azure Migrate Project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fae12c42-b9f4-ae42-566f-35435f80f9c6
* Version Independent ID: 4d714a74-031d-c9f7-2fa0-6b69fc5f609a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
Azure Migrate projects have been added to the list. Thanks!
