### ISSUE TITLE
Link to wrong page

### ISSUE THREAD

**Issue by TLaue** [MicrosoftDocs/cloud-adoption-framework#511]
Hello,

the link for the following title "We want to build new products and services in the cloud." leads to the wrong page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69abf33c-9597-13b9-a7e0-3329a1a29346
* Version Independent ID: 43c6a4e4-879b-c521-d81f-db2ed0d47a37
* Content: [Get started with the Cloud Adoption Framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/)
* Content Source: [docs/get-started/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/442542/>442542</a>

**Comment by JanetCThomas** [comment]
We've fix the link. Thanks for letting us know about it.  You should see it on the live site in the next day or so.
