### ISSUE TITLE
Incorrect URLs 

### ISSUE THREAD

**Issue by ankulbhardwaj** [MicrosoftDocs/cloud-adoption-framework#512]
When clicked the on the following URLs under section Security baseline, Error Page 404 is received -

1. Azure Virtual Desktop security baseline.

2. Azure Virtual Desktop security guide.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f788b00-61d5-116a-4e50-bd6c8d86b0ef
* Version Independent ID: eefa9216-197f-f9f9-5266-8867b5b88458
* Content: [Governing a Azure Virtual Desktop environment - Cloud Adoption Framework](https://review.docs.microsoft.com/en-gb/azure/cloud-adoption-framework/scenarios/wvd/govern?branch=wvd-v2)
* Content Source: [docs/scenarios/wvd/govern.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/wvd/govern.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/443864/>443864</a>

**Comment by alexbuckgit** [comment]
Links to content in other repos might not resolve properly during review, but will resolve correctly when deployed to production.
