### ISSUE TITLE
Duplicated information

### ISSUE THREAD

**Issue by nicoride93** [MicrosoftDocs/cloud-adoption-framework#513]
Hello. 
On the textbox where is explain the structure of the RGs to deploy the HPs, it says
 Windows Virtual Desktop Service Objects:  Separate Windows Virtual Desktop Service Objects from Host Pool VMs.  Service objects include Workspaces, Host Pools and RemoteApp/Desktops App groups. Create a resource group for these objects

And also says 
Host Pools:  Create a resource group for each host pool

Its saying that the hostpool should be deployed on 2 RGs? Or it is just saying that the Service objects can include the hostpools?

Thans!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b9ccce-3b04-f974-5c86-3c82fa2f046b
* Version Independent ID: d61f507b-95a7-c706-29c8-d68adf0ddb45
* Content: [Enterprise-scale security governance and compliance for Windows Virtual Desktop infrastructure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-security-governance-and-compliance)
* Content Source: [docs/scenarios/wvd/eslz-security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/wvd/eslz-security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @AdamWhitlatch
* Microsoft Alias: **dawhitla**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/444214/>444214</a>

**Comment by wahidsaleemi** [comment]
This is an error. Host Pools should not be included with the AVD service objects.

#assign:@wahidsaleemi

**Comment by PRMerger16** [comment]
Users wahidsaleemi are already assigned.

**Comment by JanetCThomas** [comment]
This update is now live.  Thank you!
