### ISSUE TITLE
Entitlement is misspelled

### ISSUE THREAD

**Issue by tibor19** [MicrosoftDocs/cloud-adoption-framework#515]
In the architecture diagram for the AKS-ESL (
https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/1a26c2fbe95175ec454587a6f11e643b9f6f0f03/docs/scenarios/aks/enterprise-scale-landing-zone.md) **Role entitlement** is spelled **Role entitlement** in several places (I counted 5)
![Role enttlement](https://user-images.githubusercontent.com/3577486/122730737-dc5f2c80-d27a-11eb-9d63-fa4ff9851f67.png)
.

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/444389/>444389</a>

**Comment by WendyRing** [comment]
Hi, this issue has been resolved and will be live on 7/1. Thank you for reporting it.
