### ISSUE TITLE
Old Examples

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#516]
Please update to include some examples of how Azure Sentinel can be used to enhance the security baseline. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ed72aa5-0b5c-5393-0277-7d96990cb196
* Version Independent ID: 8db532bf-30cf-82f9-fa73-42b89b7c75ed
* Content: [Enhanced management baseline in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/azure-management-guide/enhanced-baseline?tabs=AzureAutomation%2CAzureSecurityCenter)
* Content Source: [docs/manage/azure-management-guide/enhanced-baseline.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/azure-management-guide/enhanced-baseline.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # 444750

**Comment by skabou** [comment]
It appears this has been addressed.  If assistance is still needed, please re-open with additional details.

**Comment by skabou** [comment]
#please-close
