### ISSUE TITLE
missing/typo for link

### ISSUE THREAD

**Issue by sharuzzaman** [MicrosoftDocs/cloud-adoption-framework#518]
> Lastly, we've updated guidance on how enterprises can [optimize management groups and organize subscriptions](../ready/enterprise-scale/management-group-and-subscription-organization] in Azure to meet cloud governance requirements.

There is a missing/typo for link here. I'm not sure how to fix it, so I just report it so that it can be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da6ad00a-5e4a-32dc-baed-106e4d45982b
* Version Independent ID: 3367a77a-b2c8-34f0-9405-355aa6c748e4
* Content: [What's new in the Microsoft Cloud Adoption Framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/get-started/whats-new)
* Content Source: [docs/get-started/whats-new.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/get-started/whats-new.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by WendyRing** [comment]
https://ceapex.visualstudio.com/pnp/_workitems/edit/400340

**Comment by WendyRing** [comment]
Thanks for your feedback. The link has been fixed and the update to the article will be published.
