### ISSUE TITLE
Design Recommendations suggests preferred option is to use Private Link instead of Microsoft Peering, would be good to document rationale behind this 

### ISSUE THREAD

**Issue by andyjballgit** [MicrosoftDocs/cloud-adoption-framework#519]
[Enter feedback here]
As per below snip.  It would be good to understand and **document** the rationale of pushing Private Link instead of Microsoft Peering (With perhaps a table comparing features / cost diffs etc).

I searched and couldnt find this documented anywhere else , apologies if i missed / if so would be good to have a link to that info.

"Access Azure PaaS services from on-premises via ExpressRoute private peering. Use either virtual network injection for dedicated Azure services or Azure Private Link for available shared Azure services. To access Azure PaaS services from on-premises when virtual network injection or Private Link isn't available, use ExpressRoute with Microsoft peering. This method avoids transiting over the public internet."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188d9f77-7e00-31de-ff3b-9dcbd51a1363
* Version Independent ID: e109069b-918d-f33d-4d22-a75229e2a198
* Content: [Connectivity to Azure PaaS services - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/connectivity-to-azure-paas-services)
* Content Source: [docs/ready/azure-best-practices/connectivity-to-azure-paas-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/connectivity-to-azure-paas-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by WendyRing** [comment]
https://ceapex.visualstudio.com/pnp/_workitems/edit/444389/

**Comment by WendyRing** [comment]
Thank you for your feedback. We are in the process of updating this article to provide further clarity.
