### ISSUE TITLE
Update points regarding EA to talk about MCA

### ISSUE THREAD

**Issue by jleonelion** [MicrosoftDocs/cloud-adoption-framework#520]
Recommend updating documentation talking about Enterprise Accounts to include discussion (or make reference to) the Microsoft Customer Agreements which many EAs are being converted to.
https://azure.microsoft.com/en-us/resources/knowledge-center/transition-faq/

It would also be helpful to have a good cohesive explanation about the different subscription types (such as DevTest, Enterprise DevTest, and MSDN credits).  It's all kind of confusing and seems to be evolving.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0075e68e-d22e-f35d-d7d4-b936dcb3e6ad
* Version Independent ID: 11caebc2-6caf-0095-3eb5-564e18a15488
* Content: [Enterprise Agreement enrollment and Azure Active Directory tenants - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants)
* Content Source: [docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by WendyRing** [comment]
https://ceapex.visualstudio.com/pnp/_workitems/recentlyupdated/

**Comment by WendyRing** [comment]
Thanks for the feedback! This article has been updated and the issue will be closed.
