### ISSUE TITLE
Virtual Hub and Virtual Network connection

### ISSUE THREAD

**Issue by sjsaravanan** [MicrosoftDocs/cloud-adoption-framework#521]
In the Figure 1: Virtual WAN network topology , the connection type mentioned between the VWAN Hub and VNet is suppose to be VNet Connections, and not VNet Peering.

Thanks
### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3f50d-5fc4-32d7-400a-4876b83a1535
* Version Independent ID: e159e485-d2db-10a0-2615-73e78f3733f3
* Content: [Virtual WAN network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/virtual-wan-network-topology)
* Content Source: [docs/ready/azure-best-practices/virtual-wan-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/virtual-wan-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by WendyRing** [comment]
https://ceapex.visualstudio.com/pnp/_workitems/edit/449043

**Comment by WendyRing** [comment]
Thanks for the feedback! This article has been updated and the issue will be closed.
