### ISSUE TITLE
ASR vs Azure Migrate

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/cloud-adoption-framework#530]
The ASR section says "aka Azure Migrate" in the heading but it just looks like this page is out of date and no-one has properly shown how Azure Migrate is used to drive the replication. In fact, your FAQ mentions that Azure migrate is different to ASR
https://docs.microsoft.com/en-us/azure/migrate/resources-faq

The info on the Azure Migrate docs is much clearer and should at least be linked to this article https://docs.microsoft.com/en-us/azure/migrate/tutorial-migrate-vmware

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35a3cab-4e8f-9b27-cf40-cecf585a1513
* Version Independent ID: 367254c9-7628-f58a-57d2-98a107c825d3
* Content: [Replication options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/migration-considerations/migrate/replicate-options)
* Content Source: [docs/migrate/migration-considerations/migrate/replicate-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/migration-considerations/migrate/replicate-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453596/>453596</a>

**Comment by stephen-sumner** [comment]
This issue will has been resolved and updates will be seen tomorrow.
