### ISSUE TITLE
Similar but Different Content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#532]
There is another Security Best Practices page at https://docs.microsoft.com/en-us/azure/security/fundamentals/best-practices-and-patterns. It would be helpful if this page could be combined with that page to decrease confusion associated with searching for best practices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81125cd-1520-8f83-150f-04d95581c8e1
* Version Independent ID: 28adb70c-3fc4-338f-ed69-e21e66be521d
* Content: [Azure security best practices - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/secure/security-top-10)
* Content Source: [docs/secure/security-top-10.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/secure/security-top-10.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/454596/>454596</a>

**Comment by alexbuckgit** [comment]
Thanks for the feedback. The CAF best practices article focuses on the people aspects of security best practices, while the fundamentals article focuses on the technical aspects of security best practices.
