### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/cloud-adoption-framework#533]
[Enter feedback here]
In the "This approach is commonly used when the follow data points are observed in the migration plan:" **follow** should be **following**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8c397b-0179-d7a1-5eef-38308496fad1
* Version Independent ID: 890b28e5-4b20-8892-2435-4508083de26d
* Content: [Migrate an SAP platform to Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/migrate)
* Content Source: [docs/scenarios/sap/migrate.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/sap/migrate.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @deepakonics
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/454685/>454685</a>

**Comment by v-andreaco** [comment]
Typo fixed.
