### ISSUE TITLE
Consider Suggesting Workload/Application Be Placed First in a General Naming Convention

### ISSUE THREAD

**Issue by ZACommando** [MicrosoftDocs/cloud-adoption-framework#539]
If an organization is _not_ using an external-to-Azure management system for its resources (i.e., one that is solely based on Resource Name without accompanying metadata), recommending resources be named starting with their type seems like bad practice.

For example, based on how Azure is constructed with each Resource Provider having its own REST endpoints, the vast majority of users are going to be using those endpoints to find and retrieve resources.

If someone is looking for a Storage Account in Azure, they are likely going to use the `Microsoft.Storage/storageAccounts` provider and not the generic `resources` provider with a `$filter` parameter.  This behavior doesn't change whether they're using REST, CLI, PowerShell, or the Azure Portal.

If all those Storage Accounts are returned with a name like `st...`, it becomes significantly harder for a user to locate the Storage Account they are looking for based on how human eyes scan text.  And the user already knows everything that was returned is a Storage Account and the `st...` becomes irrelevant.

Alternatively, if the `Workload/Application` portion of the name were to come first the returned list of Resources now becomes easier to sort and filter and scan by eye.  Now the format becomes `[Workload/Application]-[Resource Type]-[Environment]-[Region]-[Instance]`.

The only time it is useful to have the Resource Type Abbreviation (i.e., `st`) be first in a naming convention is if the only information available is a list of resource names and a use is filtering using `startsWith(...)`.  How often does that occur to recommend that Resource Type Abbreviation should be placed first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/456858/>456858</a>

**Comment by JanetCThomas** [comment]
Every business has its own organizational and management requirements. These recommendations help start a discussion with your cloud adoption teams. As the discussion proceeds, use the tools below to document the naming and tagging decisions you make when aligning these recommendations to your specific business needs.

Download the [Azure Naming Tool](https://github.com/microsoft/CloudAdoptionFramework/tree/master/ready/AzNamingTool) to create an organizational naming reference and name generator.

Download the [naming and tagging conventions tracking template](https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/ready/naming-and-tagging-conventions-tracking-template.xlsx).
