### ISSUE TITLE
404 on naming guidelines article 

### ISSUE THREAD

**Issue by mohsenramy** [MicrosoftDocs/cloud-adoption-framework#54]
this link https://docs.microsoft.com/azure/architecture/best-practices/naming-conventions gives 404 I think it should change to https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fc82b5-34a5-ec62-85bf-aa3f6b365827
* Version Independent ID: a6fd18dc-0536-06e5-86b9-ff99ff58f3c2
* Content: [Organize your Azure resources effectively - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/organize-resources?tabs=NamingStandards#feedback)
* Content Source: [docs/ready/azure-setup-guide/organize-resources.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/organize-resources.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @laraaleite
* Microsoft Alias: **kfollis**

**Comment by BrianBlanchard** [comment]
Resolved via a redirect
