### ISSUE TITLE
Bandwidth Calculator

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/cloud-adoption-framework#548]
When Azure Site Recovery was used as the primary migration tool, there used to be an Excel spreadsheet calculator you could download to help assess the bandwidth requirements. Is there an equivalent tool to help understand this in Azure Migrate? In theory we've already captured the assets and storage requirements, but the CAF would really benefit from actually telling us _how_ to calculate this sort of thing (as most orgs don't have specialist network people).
Ideally we could just enter our bandwidth into Azure Migrate and it would tell us the answer, but a guided paper-based method explained on this page would be the next best thing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d99dbc5-a624-98be-1aaf-8ee4edfa3e87
* Version Independent ID: dfd54e3b-23fb-6381-c64f-71df654085d3
* Content: [Best practices when data requirements exceed network capacity during a migration effort - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/network-capacity-exceeded)
* Content Source: [docs/migrate/azure-best-practices/network-capacity-exceeded.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/network-capacity-exceeded.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458838/>458838</a>

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24383 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
