### ISSUE TITLE
Adopt refers to Build-Measure-Learn but doesn't reference Lean StartUp / Eric Ries?

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/cloud-adoption-framework#55]
Adopt section explicitly refers to Build-Measure-Learn but doesn't reference Lean StartUp by Eric Ries?

Might be nice to reference the book as a source of the Build-Measure-Learn cycle?

**Comment by BrianBlanchard** [comment]
We don't mention it on every page, but do have Eric's work as a footer on at least three of the deeper dive pages.
Build: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/considerations/build
Measure: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/considerations/measure
Learn: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/considerations/learn

If there are other pages that you think would benefit from a similar reference, please open an issue on those pages. 

Or better still, open a PR. We welcome contributions from knowledgeable partners like DevOps Group. You are welcome to make changes to the content to better guide our shared customers.
