### ISSUE TITLE
High

### ISSUE THREAD

**Issue by Mraungmyin** [MicrosoftDocs/cloud-adoption-framework#550]
Brian new

**Comment by Mraungmyin** [comment]
Hello work

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/459334/>459334</a>

**Comment by WendyRing** [comment]
Thanks for reporting. Closing as there are no details about the issue. Thank you!
