### ISSUE TITLE
Data Lake Zones folder

### ISSUE THREAD

**Issue by kbhatiaGIT** [MicrosoftDocs/cloud-adoption-framework#555]
It will be good to include best practices and suggestions for implementing PII data and 'Right to forgotten Request' as they play a critical role.

Some of the specific comments
- In the section RAW Data, it is assumed that the data can land in different folder structure for sensitive and  non-sensitive data. This might not be true for a number of scenarios and it will be likely that certain columns will be sensitive in certain datasets.
- Not sure if the provided folder structure is a recommendation or just an example. There could be alternate folder structure as well and it will be good to provide pros/cons for each of those. For example, lookup tables for pseudonymization
- Data Lifecycle management section can include considerations for GDPR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174bef87-bea0-a095-3712-2c9dcf9e9388
* Version Independent ID: 9deb539b-93a8-a3d0-25c3-ebf65e5a4441
* Content: [Azure Enterprise Scale Analytics and AI Teams Data Lake Services - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-services?branch=scenario-data-management)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/data-management/best-practices/data-lake-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/461081/>461081</a>

**Comment by mboswell** [comment]
This is up to the individual case but has been enhanced in a future version release.

#please-close
