### ISSUE TITLE
What is the correction pronunciation for On-premise?

### ISSUE THREAD

**Issue by binoysmail** [MicrosoftDocs/cloud-adoption-framework#556]
What is the correction pronunciation for On-premise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42a45e5-803c-10f4-c652-294bfab95e96
* Version Independent ID: d372c810-b04c-f3fa-acbe-fd8c2f89d505
* Content: [Cloud migration - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/)
* Content Source: [docs/migrate/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/461535/>461535</a>
