### ISSUE TITLE
Wrong guidance - exact opposite of CAF & Landing Zone Guidance

### ISSUE THREAD

**Issue by krishsub** [MicrosoftDocs/cloud-adoption-framework#559]
Our guidance is the exact opposite of this page content.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-app-delivery
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-landing-zone-network-segmentation
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/

Above links and our own guidance is to have Application Gateway deployed in the Spokes together with the workload. So App GW deployment and configuration is part of the application - also from CI/CD.

But this page instead recommends a shared model and all public access through the Hub VNET. And then goes on to say this is Enterprise Scale. Nothing could be further than the truth here. For large enterprises with 1000s of applications, you end up many hundreds of Application Gateways in the Hub VNET and centralized configuration for those 100s of App GWs. This is not workable or scalable or enterprise-scale at all.

So this page should be removed. Almost all the guidance in it is incorrect per current Microsoft recommendations for 'Enterprise Scale'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bc9f39-cae7-2967-dfd5-58caa34452d1
* Version Independent ID: 9118485a-56d8-ce9e-fbfd-6e66be87a611
* Content: [Hub and spoke network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology)
* Content Source: [docs/ready/azure-best-practices/hub-spoke-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/hub-spoke-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tracsman
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/465290/>465290</a>

**Comment by krnese** [comment]
@JefferyMitchell, can you pls drive this as part of alignment for LZ?

**Comment by JanetCThomas** [comment]
This issue has been addressed. Updated content will be available in the near future.  Thank you!

**Comment by krishsub** [comment]
> This issue has been addressed. Updated content will be available in the near future. Thank you!

Could you give an estimate of when updated content will be available? 
Because the wrong guidance is still out there and the top result on Google.
