### ISSUE TITLE
Platform Operations diagram?

### ISSUE THREAD

**Issue by TheOpsMgr** [MicrosoftDocs/cloud-adoption-framework#56]
I don't know if this is useful for the platform page - https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/manage/considerations/platform 

![image](https://user-images.githubusercontent.com/3353242/68608090-fdaa4500-04a9-11ea-9cbc-f1d7653a5606.png)

**Comment by BrianBlanchard** [comment]
@TheOpsMgr Love the diagram. Its very similar to what Microsoft Services uses during delivery of the CCOE offering. However, I like your view a bit better. 

Is that image IP belonging to your company or did that originate elsewhere?

**Comment by BrianBlanchard** [comment]
Terminated due to lack of response.
