### ISSUE TITLE
Hub and Spoke architecture - Internet access

### ISSUE THREAD

**Issue by Daniloben** [MicrosoftDocs/cloud-adoption-framework#560]
Hi,

   I'm from Avande and I'm working on a large Cloud Transition project. We are considering deployng Hub and Spoke architecture in two Azure Regions, mainly for redundancy. Our plan was to use the Hubs as centralised Internet ingress/egress point, but we have been told that this approach is deprecated and that, in case of web services present in the spokes, Microsoft preferred solution is to have the spokes accessing the Internet directly, without passing through the Hub. 
Can you confirm that this scenario is now Microsoft preferred approach?

Thanks and regards
Danilo 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bc9f39-cae7-2967-dfd5-58caa34452d1
* Version Independent ID: 9118485a-56d8-ce9e-fbfd-6e66be87a611
* Content: [Hub and spoke network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology)
* Content Source: [docs/ready/azure-best-practices/hub-spoke-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/hub-spoke-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tracsman
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/465345/>465345</a>

**Comment by krishsub** [comment]
> Hi,
> 
> I'm from Avande and I'm working on a large Cloud Transition project. We are considering deployng Hub and Spoke architecture in two Azure Regions, mainly for redundancy. Our plan was to use the Hubs as centralised Internet ingress/egress point, but we have been told that this approach is deprecated and that, in case of web services present in the spokes, Microsoft preferred solution is to have the spokes accessing the Internet directly, without passing through the Hub.
> Can you confirm that this scenario is now Microsoft preferred approach?
> 
> Thanks and regards
> Danilo
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: f9bc9f39-cae7-2967-dfd5-58caa34452d1
> * Version Independent ID: 9118485a-56d8-ce9e-fbfd-6e66be87a611
> * Content: [Hub and spoke network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology)
> * Content Source: [docs/ready/azure-best-practices/hub-spoke-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/hub-spoke-network-topology.md)
> * Service: **cloud-adoption-framework**
> * Sub-service: **ready**
> * GitHub Login: @tracsman
> * Microsoft Alias: **brblanch**

Hello Danilo,

Just a clarification: you state 'Microsoft preferred solution is to have the spokes accessing the Internet directly, without passing through the Hub' 

We are talking about **ingress from Internet to workload**; not outbound connectivity from workload/Spoke to Internet. In the former case, the latest guidance is below (and for latter case, scroll to bottom):

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology (In this last link we state explicitly: **Don't deploy Layer-7 inbound NVAs, such as Azure Application Gateway, as a shared service in the central-hub virtual network. Instead, deploy them together with the application in their respective landing zones.**)
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-app-delivery
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-landing-zone-network-segmentation
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/

For **outbound internet connectivity from Spoke**, it may traverse the Hub (Azure FW in hub) depending on the scenario:
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-inbound-and-outbound-internet-connectivity 

Regards,

-krish
