### ISSUE TITLE
Typo error under Subscription Quota and Capacity section

### ISSUE THREAD

**Issue by amanjeetsingh** [MicrosoftDocs/cloud-adoption-framework#561]
Typographical error under Design Recommendations for  subscription quota and capacity section (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization#configure-subscription-quota-and-capacity)

Replace "pf" with "of. 

![image](https://user-images.githubusercontent.com/7122931/127724710-6e26a7f3-9ec0-415b-a0b4-6c3656c7ca05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38786a5-e931-e614-55a1-2980b8a28087
* Version Independent ID: a72b6f97-dd0f-252c-f6d9-f1c517aa9a2f
* Content: [Management group and subscription organization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/management-group-and-subscription-organization#subscription-organization-and-governance)
* Content Source: [docs/ready/enterprise-scale/management-group-and-subscription-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/management-group-and-subscription-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/465581/>465581</a>

**Comment by JanetCThomas** [comment]
This issue has been fixed.  Thank you.
