### ISSUE TITLE
Featured Azure Products links

### ISSUE THREAD

**Issue by namtazpro** [MicrosoftDocs/cloud-adoption-framework#563]
Under title Featured Azure Products, all the links to the Azure products lead to 404. page not found. (21 links)

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/466655/>466655</a>

**Comment by namtazpro** [comment]
adding a couple of example 404 links
https://review.docs.microsoft.com/en-us/azure/azure-resource-manager/templates/

https://review.docs.microsoft.com/en-us/azure/data-explorer/

**Comment by JanetCThomas** [comment]
We’ll be pushing the data management scenario live soon.  We’ll verify that the links all work before it goes live. I’m closing this issue. Thank you!
