### ISSUE TITLE
UPD not clear enough

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/cloud-adoption-framework#564]
In the section "[Step 3: Convert the UPDs to FSLogix profile containers](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rds-to-wvd#step-3-convert-the-upds-to-fslogix-profile-containers)"  it doesn't say where these commands are run from. 
Can you clarify in the doc if you are running these commands on the legacy on-prem RDS estate or the new AVD host pools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177be313-669c-b534-575c-27eaa49b76b8
* Version Independent ID: 33169923-9568-077a-7f12-19554a9dbb94
* Content: [Move on-premises Remote Desktop Services to Azure Virtual Desktop scenario - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rds-to-wvd#rds-on-premises-to-azure-virtual-desktop-in-the-cloud-goals)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @benstegink
* Microsoft Alias: **abuck**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/466659/>466659</a>

**Comment by JanetCThomas** [comment]
The contoso scenario is an example, not a how-to article.  If you have a suggestion for how to make this content clearer, please let us know.  Thank you.

**Comment by JanetCThomas** [comment]
Closing this issue.  Thanks for the feedback.
