### ISSUE TITLE
Limiting step 2 based on resource type

### ISSUE THREAD

**Issue by zaalion** [MicrosoftDocs/cloud-adoption-framework#565]
[Enter feedback here]
Hello,

Regarding step 2 [Deny creation of a private DNS zone with the privatelink prefix policy.]. Is there a way to limit this enforcement only to specific resource types? For example, deny creation of this private zone if the private link is getting created for a storage account.

Basically, we need to enforce this for only select type of Azure resources.

Thanks,
R

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#policy-definitions)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/467180/>467180</a>

**Comment by dominicallen** [comment]
Thanks for your feedback. For further guidance on how to create custom policies, please refer to this document set: https://docs.microsoft.com/en-us/azure/governance/policy/tutorials/create-custom-policy-definition
