### ISSUE TITLE
Not all apps can use Azure AD DS

### ISSUE THREAD

**Issue by Amethi** [MicrosoftDocs/cloud-adoption-framework#566]
[Enter feedback here]

"Applications that rely on domain services and use older protocols can use Azure AD DS."

I would change that to "might be able to use Azure AD DS", as not all can, i.e. Azure AD Connect is not supported on Azure AD DS (just asked the PG this question).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a2540a7-f3a9-4440-2c97-163f45993672
* Version Independent ID: d08b3a6f-113f-7f5b-2c11-c278ce11e905
* Content: [Identity and access management (IAM) - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/identity-and-access-management)
* Content Source: [docs/ready/enterprise-scale/identity-and-access-management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/identity-and-access-management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/467631/>467631</a>

**Comment by dominicallen** [comment]
Thank you for your feedback! This change has been included in an upcoming release to the content.
