### ISSUE TITLE
How to dynamically create the policy parameter value?

### ISSUE THREAD

**Issue by zaalion** [MicrosoftDocs/cloud-adoption-framework#568]
[Enter feedback here]

Hello,

In step 3, we need to pass the privateDnsZoneId parameter when assigning the policy. The value is _[/subscriptions/<subscription-id>/resourceGroups/<resourceGroupName>/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net]_

I need to assign this policy to a subscription and have it create all DNS records for all resources in various resource groups. How would I dynamically find the _<resourceGroupName>_? Say I have 5 resource groups. Should I create 5 assignments and hard-code the _<resourceGroupName>?_

Thanks,
R

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale#policy-definitions)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/467754/>467754</a>

**Comment by jocontr** [comment]
It truly depends on how your IT ops has been designed. You could leverage environment variables, powershell scripting, etc.

From our perspective, in this and other guidance contained in the Azure Architecture Center you could find examples of how variables have been used in various deployment configurations. Thank you.
