### ISSUE TITLE
Recommendation: Change "Go to" Link

### ISSUE THREAD

**Issue by snpdev** [MicrosoftDocs/cloud-adoption-framework#57]
The link at the bottom of the "Developer productivity" tab is:

> Go to the [Azure DevOps Projects documentation](https://docs.microsoft.com/azure/devops-project)

Personally, I would demo Azure DevOps Projects to developers new to Azure DevOps but to get them started, this document makes more sense to me: 

> [Start using Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dc745-f2dd-406b-2a9b-016775c9b7ed
* Version Independent ID: c0d94094-2598-acb4-5d9f-71262cc7feb2
* Content: [Azure innovation guide: Empower adoption - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/innovation-guide/ci-cd?tabs=DeveloperProductivity#feedback)
* Content Source: [docs/innovate/innovation-guide/ci-cd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/innovate/innovation-guide/ci-cd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @absheik
* Microsoft Alias: **absheik**

**Comment by BrianBlanchard** [comment]
Great suggestion! Thank you
