### ISSUE TITLE
Resource abbreviation for public DNS Zone

### ISSUE THREAD

**Issue by Frank-Geisler** [MicrosoftDocs/cloud-adoption-framework#571]
Hi!

I wonder if the abberivation suggestion for public DNS Zones is right. To my understanding the name of the DNS Zone is also the Name of the DNS-Domain e.g. if the Zone is named contoso.com the DNS-Domain is contoso.com as well. So if I stick to your suggestion I would call the Zone dnsz-contoso.com the Domain would also be dnsz-constoso.com. Or am I missing something out here?

Thank you and have a nice day

Frank 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/469866/>469866</a>

**Comment by stephen-sumner** [comment]
Fixed this on 9/30/2022
