### ISSUE TITLE
deploy to Azure is missing info about deployment Pre-Requirements 

### ISSUE THREAD

**Issue by kiwibayer** [MicrosoftDocs/cloud-adoption-framework#574]
the deploy to Azure button will most likely fail for 95% of our customers because we do not tell them about the pre requirements of the deployment within the same area. 

There should be a link to: https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md to call out the Permission pre-requ

we need to add a link to https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6230652-e478-a07e-45cf-5d560c276c13
* Version Independent ID: 888cb6ce-2c26-3d98-1327-c91805083665
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/472222/>472222</a>

**Comment by kiwibayer** [comment]
fixed with 
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2337
