### ISSUE TITLE
Add updating the machine-id

### ISSUE THREAD

**Issue by Harrison-S1** [MicrosoftDocs/cloud-adoption-framework#575]
You will need to regenerate the machine-id to avoid problems later on. 
I don't know how you can do this from the build process, but I just put a scripts on the box to run with Ansible later on,

```
#!/bin/sh

rm -f /etc/machine-id
rm /var/lib/dbus/machine-id
dbus-uuidgen --ensure=/etc/machine-id
dbus-uuidgen --ensure
```

You can check it has been change by running `hostnamectl` before and after.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f97610-b965-bfd3-e006-0c35df0cb68a
* Version Independent ID: 412e9c54-393f-fb40-952c-f5b2a6b60e6d
* Content: [Create a VMware vSphere template for Ubuntu server 18.04 - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/vmware-ubuntu-template)
* Content Source: [docs/manage/hybrid/server/best-practices/vmware-ubuntu-template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/hybrid/server/best-practices/vmware-ubuntu-template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/473565/>473565</a>

**Comment by stephen-sumner** [comment]
Thanks for the input! Machine ID is outside the scope of this article since we're creating a template. Ubuntu documentation recommends that the etc/machine-id file be empty for template images. An ID should be generated during boot and saved to etc/machine-id.
