### ISSUE TITLE
Highlight impact/complexity of hybrid connectivity

### ISSUE THREAD

**Issue by GrahamMcKendry** [MicrosoftDocs/cloud-adoption-framework#577]
[Enter feedback here]
The **'Release backlog data points'** section indicates _"Don't include a workload in a release until one of the following criteria can be met:
All dependent workloads have been migrated.
Network and security configurations have been implemented to allow the workload to access all dependencies in alignment with existing performance expectations."_

It would be beneficial for this page to further highlight the impact of hybrid connectivity challenges when migrating complex workloads in a multi-wave approach. Namely, it's often difficult for customers to project the application performance impacts as portions of a given workload are migrated to cloud, due to the many years/decades of technical debt established in the application architecture. As such it may not be possible for the customer to know whether all of the appropriate network and security configurations have been implemented in alignment with existing performance expectations (& moreover many customers' Business users may have performance "ideals" but no formal performance SLAs).

In order to avoid the potentially high rate of migration rollbacks caused by unanticipated application performance degradation, the article should emphasize the importance that the migration team be able to confirm whether the performance degradation is temporary (due to the hybrid connectivity until the rest of the workload is migrated in a later wave), and if so to have a balanced decision process with the Business so that the temporary nature is understood (along with any potential short-term investment in improving the application architecture to optimize communications).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306d7e39-43ad-faad-a8b4-7537512c6a2c
* Version Independent ID: dca7ccb9-fb74-15cb-420d-b36aa6509288
* Content: [Prepare for agile change management complexity - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/migration-considerations/prerequisites/technical-complexity)
* Content Source: [docs/migrate/migration-considerations/prerequisites/technical-complexity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/migration-considerations/prerequisites/technical-complexity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/475069/>475069</a>

**Comment by stephen-sumner** [comment]
The feedback is valid. So I added a few notes around multi-wave migrations.
