### ISSUE TITLE
Minor detail:  Typo on the blue button

### ISSUE THREAD

**Issue by CloudLassoUK** [MicrosoftDocs/cloud-adoption-framework#58]
I think

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db8a7502-196b-cbea-6911-1975531ad7b1
* Version Independent ID: 54517f71-c332-02fb-5b77-52df8a1bb99c
* Content: [Cloud center of excellence - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-center-of-excellence#feedback)
* Content Source: [docs/organize/cloud-center-of-excellence.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/organize/cloud-center-of-excellence.md)
* Service: **cloud-adoption-framework**
* Sub-service: **organize**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Great catch! Thank you!
