### ISSUE TITLE
Plan: Develop the skills needed to prepare an actionable migration plan.

### ISSUE THREAD

**Issue by autocloudarc** [MicrosoftDocs/cloud-adoption-framework#582]
[Enter feedback here]

The Plan hyperlink links back to the same page for this article, which is:

![image](https://user-images.githubusercontent.com/15109536/130680841-c3177167-4f31-4200-a33f-71f978a2d9d1.png)

Also, the text for both the Strategy and Plan phases are identical, so that may have been unintended.

![image](https://user-images.githubusercontent.com/15109536/130681198-7e0a4687-0793-45e0-aa28-9ff6558d5a34.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5beb8241-27e4-fbc0-2372-16a224dcff0c
* Version Independent ID: 65b2c7b2-5443-9f44-98f3-d831963b87b7
* Content: [Get started on a skills readiness path - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/suggested-skills)
* Content Source: [docs/plan/suggested-skills.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/plan/suggested-skills.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/477844/>477844</a>

**Comment by v-andreaco** [comment]
Fixed in internal PR: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2584
