### ISSUE TITLE
Too frequent and arbitrary changes

### ISSUE THREAD

**Issue by shadcollins** [MicrosoftDocs/cloud-adoption-framework#585]
Microsoft seems to constantly be changing its naming standards. To make matters worse a lot of the changes are very different philosophically than the standard from a few years ago.

The other major challenge is we can't change the name of our resources to make the new standard so the end result is nothing is standardized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
We've added this feedback to our backlog for review.  Thanks you.
