### ISSUE TITLE
Hi Team,  I am Vijay (Sr CE in Singapore), while exploring this doc I saw a spelling mistake in this doc. Please fix it. Thank You :) 

### ISSUE THREAD

**Issue by vijayyadavcloud** [MicrosoftDocs/cloud-adoption-framework#587]
[Enter feedback here]
![Capture](https://user-images.githubusercontent.com/23454873/131618863-cbeff18f-9851-4855-9000-e7936e760c18.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0075e68e-d22e-f35d-d7d4-b936dcb3e6ad
* Version Independent ID: 11caebc2-6caf-0095-3eb5-564e18a15488
* Content: [Enterprise Agreement enrollment and Azure Active Directory tenants - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants)
* Content Source: [docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/481439/>481439</a>

**Comment by jtracey93** [comment]
@david-stanford have raised a PR to resolve this which you should be able to see 👍

**Comment by WendyRing** [comment]
This issue has been resolved. Thanks for providing feedback!
