### ISSUE TITLE
Updated positioning of Virtual WAN now that Azure Route Server is GA

### ISSUE THREAD

**Issue by adstuart** [MicrosoftDocs/cloud-adoption-framework#589]
> - Your organization intends to integrate a large-scale branch network directly in to Azure, either via a software-defined WAN (SD-WAN) deployment or requires more than 30 branch sites for native IPsec termination.
- You require transitive routing between VPN and ExpressRoute. E.g. Remote branches connected via Site-to-site VPN or remote users connected via Point-to-site VPN, require connectivity to an ExpressRoute connected DC, via Azure.

I believe we should update/temper the above message. Azure Route Server provides enhanced option for traditional customer hub/spoke networks to both integrate SDWAN appliances, and also provides VPN to ER transit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94c74d6-9c05-360e-c036-d185df3dbe8c
* Version Independent ID: f9548281-809d-8a48-14e7-d155011b2ca4
* Content: [Define an Azure network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/define-an-azure-network-topology)
* Content Source: [docs/ready/azure-best-practices/define-an-azure-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/define-an-azure-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/483494/>483494</a>

**Comment by dominicallen** [comment]
Thanks for your feedback. This will be included in a new content currently in development.
