### ISSUE TITLE
Deny policy for privatelink doesn't work when privatelink is not the prefix in the dns zone

### ISSUE THREAD

**Issue by SenthuranSivananthan** [MicrosoftDocs/cloud-adoption-framework#591]
This rule doesn't work when the privatelink's zone doesn't start with `privatelink`.  Azure Site Recovery's dns zones are `{region}.privatelink.siterecovery.windowsazure.com`

Reference:  https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns

```
{
  "description": "This policy restricts creation of private DNS zones with the `privatelink` prefix",
  "displayName": "Deny-PrivateDNSZone-PrivateLink",
  "mode": "All",
  "parameters": null,
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/privateDnsZones"
        },
        {
          "field": "name",
          "like": "privatelink*"
        }
      ]
    },
    "then": {
      "effect": "Deny"
    }
  }
}
```
Suggested improvement (only the rule).  Change `like` to `contains` with value `privatelink.`

```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Network/privateDnsZones"
      },
      {
        "field": "name",
        "contains": "privatelink."
      }
    ]
  },
  "then": {
    "effect": "Deny"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/487163/>487163</a>

**Comment by victorar** [comment]
Thanks @SenthuranSivananthan for reporting this and the detailed feedback. We're updating the article as well as related custom policy definition in the ESLZ GitHub repo.

**Comment by WendyRing** [comment]
Thanks @SenthuranSivananthan and @victorar. We'll close this issue as the article is being worked on.
