### ISSUE TITLE
Deny policy for privatelinks need to support when zones does not start with "privatelink" 

### ISSUE THREAD

**Issue by SenthuranSivananthan** [MicrosoftDocs/cloud-adoption-framework#592]
Azure Site Recovery's private zone is in the format `{region}.privatelink.siterecovery.windowsazure.com` and the policy will not prevent the zone from being created.

Suggestion:  Replace like condition with `"contains": "privatelink."`

```
{
  "if": {
    "allOf": [
      {
        "field": "type",
        "equals": "Microsoft.Network/privateDnsZones"
      },
      {
        "field": "name",
        "contains": "privatelink."
      }
    ]
  },
  "then": {
    "effect": "Deny"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/487208/>487208</a>

**Comment by SenthuranSivananthan** [comment]
I duplicated the issue since I didn't see it in Azure Docs repo.  You can close this in favor of #591
