### ISSUE TITLE
Remove references to automation templates in Github

### ISSUE THREAD

**Issue by shaunjacob** [MicrosoftDocs/cloud-adoption-framework#597]
[Enter feedback here]
Hi Team, providing some feedback here. I believe the references and section "Implementation with Azure Resource Manager (ARM) templates for Remote Desktop Services" should be removed

For the non AVD expert, or someone just looking at this page - it looks and reads like we are offering an automated way and templates to deploy the actual construction set. When in reality, all we are pointing them to are the old ARM templates in Github, which just deploy a hostpool and VM's. Nothing Enterprise scale about this link

Additioally, the Github templates do not have the correct artifact URL's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ebd567-bf69-afa9-625e-38eb81dccfba
* Version Independent ID: ef4ee644-1df3-433b-b11e-cb32dc58bad1
* Content: [Enterprise-scale support for Azure Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/enterprise-scale-landing-zone)
* Content Source: [docs/scenarios/wvd/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/wvd/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488392/>488392</a>

**Comment by RobBagby** [comment]
The content requested to be removed is no longer there. The section was replaced by 'Deploy Azure Virtual Desktop with the Landing Zone Accelerator'.
Closing this issue.
