### ISSUE TITLE
Billing question

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/cloud-adoption-framework#598]
If I would deploy agents like this would it incur the additional ARC cost involved with "Azure Policy guest configuration", or does this fall under the "Azure control plane functionality" of ARC?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0c1e46-c91f-56d3-7bb8-7dbc1493a5f4
* Version Independent ID: ab8d5efc-4fba-c2f9-df92-096cccfa5beb
* Content: [Deploy Microsoft Monitoring Agent to Azure Arc Linux and Windows servers - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/arc-vm-extension-mma?WT.mc_id=email)
* Content Source: [docs/manage/hybrid/server/best-practices/arc-vm-extension-mma.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/hybrid/server/best-practices/arc-vm-extension-mma.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/488599/>488599</a>

**Comment by likamrat** [comment]
@andrePKI thx for Q. Couple of things:
- Deploying the agent via the extension is 0$ but the usage of Azure Monitor does == $.
- If the deploying of the Log Analytics agent is done via Guest Configuration Azure Policy, then yes, this will be == 6$ per Azure Arc-enabled server.
- The reason is because of the scale remidation capabilities as a result of Azure Arc-enabled server+Guest Configuration Azure Policy

**Comment by likamrat** [comment]
@andrePKI Let's do this. Wait for the new Azure Arc-enabled servers ESLZ docs and then let's circle back, I have a feeling it will be resolved :-)

**Comment by hallihan** [comment]
I believe this is addressed by the previous comments and the Arc-enabled servers Docs. Please reopen with any outstanding questions if this is not the case.

**Comment by andrePKI** [comment]
Thank you. By now it seems not all that relevant anymore, as we don’t deploy MMA, but instead use integration between Defender for Cloud and Defender for Endpoint (Servers) which results in an extension (MDE.Windows) to be deployed to the Arc enabled machines. As far as I know is that part of the free Arc functionality ( ofcourse MDE will cost $5 or $15 depending on the MDE plan))
