### ISSUE TITLE
example used, if applied, breaks other resource deployments, such as SQL Database

### ISSUE THREAD

**Issue by phwecker** [MicrosoftDocs/cloud-adoption-framework#599]
the example used (storage account) for the policies has adverse impact, if deployed to a scope. storage accounts are also deployed implicitly with e.g. SQL Database. the two deny polices (#1 and #2) will be triggered regardless but for implicit deployments via the portal there is no way for a customer to satisfy the policies as the respective settings are not exposed. 

it would be good to add info on how to overcome this in a real-life scenario and -short term- add a note to that respect as i already had a customer run into this causing grief and negative attitude against us.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/490168/>490168</a>

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24390 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
