### ISSUE TITLE
Conflict with other Best Practices

### ISSUE THREAD

**Issue by trolleyboy** [MicrosoftDocs/cloud-adoption-framework#6]
Hi there,
This article somewhat conflicts with another Best Practices article for Naming Conventions... 
https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/naming-and-tagging)
* Content Source: [docs/ready/considerations/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by toddysm** [comment]
@trolleyboy Interestingly the link from your post redirects to this article. I agree that it conflicts and also key information for naming rules and restrictions included in the old article is missing.

**Comment by ardalon** [comment]
Also conflicts with: https://github.com/MicrosoftDocs/architecture-center/blob/master/docs/best-practices/naming-conventions.md also why the redirect back to the same article?

**Comment by BrianBlanchard** [comment]
The conflicting article is being removed from the Architecture Center.
