### ISSUE TITLE
Restrictions naming resources

### ISSUE THREAD

**Issue by Depechie** [MicrosoftDocs/cloud-adoption-framework#601]
The article describes in length the benefits of having a well structured naming convention for all resources, but not all resource can handle the presented optimal schema.

For example currently a StorageAccount name is limited to : must be between 3 and 24 characters in length and use numbers and lower-case letters only

Meaning we can't follow the full example like st-storagename-prod-westus-001.

Will all resources be able to have longer names in the future? Or is there a better uniform naming convention that can be applied to all resources now available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/492915/>492915</a>

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24082 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
