### ISSUE TITLE
Inconsistent abbreviation entry for Service Endpoint Policy

### ISSUE THREAD

**Issue by svdHero** [MicrosoftDocs/cloud-adoption-framework#602]
In the section "Networking", there is the row
```
Service endpoint | Microsoft.serviceEndPointPolicies | se-
```
which does not make clear whether this is the abbreviation for a Service Endpoint or for a Service Endpoint Policy. Should this maybe read
```
Service endpoint policy | Microsoft.serviceEndPointPolicies | se-
```
instead? Also, should the abbreviation for policies be `se-` or rather `sep-`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/492924/>492924</a>

**Comment by stephen-sumner** [comment]
This is absolutely correct. I updated the article today.
