### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by krishsub** [MicrosoftDocs/cloud-adoption-framework#609]
Recommended content has 4 links -- all of which are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3b4e04-b8c6-676d-ac0d-bb1c334c7c72
* Version Independent ID: d39c5cd1-5f94-e795-ea2b-f21c3f55c1c2
* Content: [Cloud Adoption Framework enterprise-scale design guidelines - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/design-guidelines)
* Content Source: [docs/ready/enterprise-scale/design-guidelines.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/design-guidelines.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/495499/>495499</a>

**Comment by JanetCThomas** [comment]
This issue has been resolved. Thank you.
