### ISSUE TITLE
Security Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#611]
I don't see anything in this documentation that addresses the unique security requirements of the retail industry, i.e, point of sale systems, frontline workers etc. Would it be possible to get this added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6012dda6-a55c-1ee2-6f3f-984972c897b2
* Version Independent ID: 91ddfd7a-97d1-466b-4551-209e06bf2ae7
* Content: [Introduction to cloud adoption for the retail industry - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/industry/retail/)
* Content Source: [docs/industry/retail/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/industry/retail/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/496131/>496131</a>

**Comment by hallihan** [comment]
@DeanGross This content has been evolving, and the detail at https://docs.microsoft.com/azure/cloud-adoption-framework/industry/retail/govern#compliance-with-data-security-standards may address your request. If there are still gaps, feel free to reopen this issue with more details or open a new feedback starting from that page with specific requirements.
