### ISSUE TITLE
Prerequisites seems unnecessary

### ISSUE THREAD

**Issue by neilpeterson** [MicrosoftDocs/cloud-adoption-framework#623]
The prerequisites section of this doc walks through creating a service principal and also cloning an Azure ARC jumpstart code repo however these two asserts are then not mentioned again. Neither of these assets seem necessary.

This doc from the Azure Security Center doc set seems to be more straight forward and addresses things like deployment at scale. Perhaps consider referencing it or replacing the CAF doc with the product doc.

https://docs.microsoft.com/en-us/azure/security-center/quickstart-onboard-machines?pivots=azure-arc

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e6f4836-a5ce-cca0-7aae-cc194f3d4b88
* Version Independent ID: b4a0849a-cda8-edcb-21e0-56ca274183d4
* Content: [Connect Azure Arc-enabled servers to Azure Security Center - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/arc-security-center)
* Content Source: [docs/manage/hybrid/server/best-practices/arc-security-center.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/hybrid/server/best-practices/arc-security-center.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/499796/>499796</a>
