### ISSUE TITLE
Cost management displayed in Identity subscription only

### ISSUE THREAD

**Issue by tvuorenmaa89** [MicrosoftDocs/cloud-adoption-framework#626]
Cost management is displayed in Identity and this might cause confusion even if its described that Cost Management is applied through out the design. If possible add cost management for Landing zone example as well to visualize that its included in more parts then just identity. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [Cloud Adoption Framework enterprise-scale landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/architecture?source=docs)
* Content Source: [docs/ready/enterprise-scale/architecture.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/architecture.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by ckittel** [comment]
@victorar did this ever fixed?  The image still only has Cost management in the Identity subscription.
