### ISSUE TITLE
chief investment officer

### ISSUE THREAD

**Issue by WayneHoggett-ACG** [MicrosoftDocs/cloud-adoption-framework#627]
"chief investment officer" seems odd in this context, does it mean to say chief information officer?

I could be missing something here, of course.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9740a354-0e3e-10b8-1f63-ac52084ac142
* Version Independent ID: 4a326a4d-5568-7661-ee9a-bf1b4bbc21d3
* Content: [Examples of agility outcomes - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/agility-outcomes#feedback)
* Content Source: [docs/strategy/business-outcomes/agility-outcomes.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/business-outcomes/agility-outcomes.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @mpvenables
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/502221/>502221</a>

**Comment by mpvenables** [comment]
Fixed. @JanetCThomas ok to close.
