### ISSUE TITLE
Missing naming convention for private endpoint connection

### ISSUE THREAD

**Issue by robertlyson** [MicrosoftDocs/cloud-adoption-framework#629]
Hi 👋 

Is there any chance for updating this docs page with a naming convention for private endpoint connection?

Really enjoy this docs so far, great work :+1:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/502351/>502351</a>

**Comment by robertlyson** [comment]
Thanks @david-stanford!

**Comment by stephen-sumner** [comment]
Add private endpoint abbreviation.
