### ISSUE TITLE
Understanding rationale behind suggested patterns

### ISSUE THREAD

**Issue by spmanjunath** [MicrosoftDocs/cloud-adoption-framework#63]
I am trying to understand the reason why Aspects such as Region, Environment is included in certain naming formats/pattern, while left out in others.  It would be helpful to understand the rational behind this decision.

For Ex:  

- Azure Function naming convention has 'Environment', but not 'Region'.
- Azure Virtual Network naming convention has both 'Environment' and 'Region'

What is the reason behind including 'Region' aspect for one of the formats, while leaving it out in the other?

**Comment by JanetCThomas** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID AB#185440

**Comment by v-andreaco** [comment]
@spmanjunath 

Closing this issue, as the content in question has gone through significant revision since this was reported. If the issue remains, please submit a new issue.

Thanks!
#please-close
