### ISSUE TITLE
Document need to updated to match v.1.0.0 of the TF module

### ISSUE THREAD

**Issue by tvuorenmaa89** [MicrosoftDocs/cloud-adoption-framework#631]
The documentation have not been updated since release of mangement, identity and connectivity resources. 

Most of the information regarding resources that can be deployed can be fetched from https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/README.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b505a5-c7a1-6641-dd29-4c4e71a1b3cf
* Version Independent ID: a4759d26-4bef-be02-a553-4fbc58a814e6
* Content: [Terraform module for Cloud Adoption Framework enterprise-scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/terraform-module-caf-enterprise-scale)
* Content Source: [docs/ready/enterprise-scale/terraform-module-caf-enterprise-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/terraform-module-caf-enterprise-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @krowlandson
* Microsoft Alias: **brblanch**

**Comment by krowlandson** [comment]
Just to confirm that we have an active PR awaiting approval for exactly this, so please watch out for this in the coming days.

**Comment by JanetCThomas** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2548 will address this.  Thanks @krowlandson

**Comment by JanetCThomas** [comment]
This issue has been addressed.  Thank you.
