### ISSUE TITLE
Conflicting information around naming and organization of resources

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/cloud-adoption-framework#636]
The Cloud Adoption Framework naming recommendations (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging) does not align with the recommendations in this page or the deployment template examples. Please provide more detailed full example naming for the full architecture solution that follows the Cloud Adoption Framework naming recommendation. This will help as a starting point for many projects. At the moment it is really hard and confusing to follow the conflicting information between the Enterprise Scale Analytics, the deployment templates and the Cloud Adoption Framework...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9becca-1961-4843-c651-84bdb2a29182
* Version Independent ID: 661f0d08-614c-e9b9-637c-cec7e9ec0268
* Content: [Resource organization for enterprise-scale data management and analytics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-resource-organization)
* Content Source: [docs/scenarios/data-management/eslz-resource-organization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/data-management/eslz-resource-organization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by mboswell** [comment]
@JanetCThomas  - fixed in pr #2788
