### ISSUE TITLE
Contradictory information

### ISSUE THREAD

**Issue by lunar87** [MicrosoftDocs/cloud-adoption-framework#638]
[Enter feedback here]
On one hand this page says that COM is represented by the different methodologies of the CAF which includes strategy and plan, but then later on in the article is says that strategy and plan are inputs into the COM. 

I would suggest updating the CAF alignment paragraph to state strategy and plan are inputs and the other methodologies help define the COM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb736919-3318-849a-f18d-0ebe09936203
* Version Independent ID: 7970d251-13ec-f1e1-8102-ffdf9346b88e
* Content: [Define your cloud operating model - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/define)
* Content Source: [docs/operating-model/define.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/operating-model/define.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 23825 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
