### ISSUE TITLE
More detail re the reccomendation of no dashes in VM name

### ISSUE THREAD

**Issue by mdi-db** [MicrosoftDocs/cloud-adoption-framework#64]
It would be really helpful to have a bit of background regarding the recommendation not to use dashes within the name of a virtual machine resource, despite the fact they are allowed and used in the majority of other resource types that do allow it.

The only reason I could think of that may be driving the recommendation is the fact that the VM name may be used within the name of another resource (e.g., a Public IP address). If the VM name had hyphens, it would mean either removing the hyphens or creating a confusing name for the PIP. Is this a factor in the recommendations and are there any others?

Many thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by mdi-db** [comment]
Why was this closed without any response?

**Comment by brandontaylor1994** [comment]
I would also like an explanation to this question. Certain resources don't support hyphens so I understand why the naming convention drops the hyphen in those cases but this is not one of those times. I'm sure there is a good reason for it but could we please document this somewhere?

**Comment by alphabt** [comment]
Me too. According to the official guide VM can have dashes, just not end with one. https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

I hope to name all my resources with dash as the separator whenever possible so they are consistent, but would love to understand why VMs are recommended to name without dash.
