### ISSUE TITLE
Additional permissions required for the policy assignment managed identity

### ISSUE THREAD

**Issue by valtynikov** [MicrosoftDocs/cloud-adoption-framework#640]
In addition to `Private DNS Zone Contributor` permissions, the managed identity created by the policy assignment also requires the `Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write` permission in the subscriptions where private endpoints get created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by victorar** [comment]
Thanks @valtynikov for reporting this. We've updated the article to describe the roleDefinition defined in the policy, which addresses the permission you are listing.
