### ISSUE TITLE
DeployIfNotExists Azure Policy does not work if groupIds are the same (Cosmos DB and Synapse Analytics).

### ISSUE THREAD

**Issue by tullydwyer** [MicrosoftDocs/cloud-adoption-framework#644]
Hi there,

We are trying to utilise the Private Link and DNS integration at scale Cloud Adoption Framework and have found that the DeployIfNotExists Azure Policy is failing with Cosmos DB (SQL) and Synapse Analytics (SQL), this seems to be due to them both having the same groupid (subresource) "Sql". It seems to be randomly triggering either policy.

Are we able to update the policy to work with Cosmos DB (SQL) and Synapse Analytics (SQL), and any resources that have the same groupid?

Documentation showing the same groupids (subresources):
- https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration
- https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview#private-link-resource

Incorrectly configured Cosmos DB endpoint:
![image](https://user-images.githubusercontent.com/7508115/138980173-3e10ceb2-ad69-4a95-8fbe-5e89dadfcd1c.png)

Kind regards,

Edit 23/11/2021:

We have solved this issue (and https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/666) with the following statements:

Single statement:
```json
{
  "contains": "Microsoft.DocumentDB/databaseAccounts",
  "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].privateLinkServiceId"
}
```

Full if statement:
```json
"policyRule": {
  "if": {
    "allOf": [
      {
        "equals": "Microsoft.Network/privateEndpoints",
        "field": "type"
      },
      {
        "count": {
          "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*]",
          "where": {
            "allOf": [
              {
                "contains": "Microsoft.DocumentDB/databaseAccounts",
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].privateLinkServiceId"
              },
              {
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
                "in": [
                  "Sql"
                ]
              }
            ]
          }
        },
        "greaterOrEquals": 1
      }
    ]
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by timwebster9** [comment]
@tullydwyer glad to see that fix worked.  I've just run into the same issue and was about to try the exact same thing!

**Comment by skabou** [comment]
It appears this has been addressed since the issue was initially opened.  If this is not the case, please re-open with additional details.
