### ISSUE TITLE
The architecture figure is very blur, please use a high resolution one.

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/cloud-adoption-framework#645]
[Enter feedback here]
The architecture figure is very blur, please use a high resolution one. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f1fff-2485-a841-1b26-aa9601d2a121
* Version Independent ID: d8f114ec-93c2-f30b-6ac8-bfa47160813b
* Content: [Enterprise-scale for SAP on Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone#feedback)
* Content Source: [docs/scenarios/sap/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/sap/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
We've recently updated the visuals on this page, and all diagrams are now in vector graphics. 
Thank you for reporting this.

#please-close
