### ISSUE TITLE
Statement and design decisions are incorrect anymore

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/cloud-adoption-framework#648]
Following wording "https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/security-governance-and-compliance#:~:text=Key%20Vault%20serves,certificate%20key%20management."  is incorrect. Azure Keyvault supports granular data plane restrictions where Azure RBAC data plane roles are used (https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli). I assume design guidelines were written when it was not available and probably need to be changed accordingly.

> Key Vault serves a security boundary because access permissions for keys, secrets, and certificates are at the vault level. 
> Key Vault access policy assignments grant permissions separately to keys, secrets, or certificates. 
> They don't support granular, object-level permissions like a specific key, secret, or certificate key management.
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061d80aa-0c57-8ae8-c9ae-a2ea52dff98f
* Version Independent ID: f77eeafe-a217-7959-3d5c-6e5f5e54d908
* Content: [Enterprise-scale security governance and compliance - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/security-governance-and-compliance)
* Content Source: [docs/ready/enterprise-scale/security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
It is unclear which article this is about. Please reopen with additional details if help is still needed.
