### ISSUE TITLE
Image shows subscriptions groups?!

### ISSUE THREAD

**Issue by sesmailjee** [MicrosoftDocs/cloud-adoption-framework#65]
See attached image, I think the subscription groups should be Management Groups
Thanks
Seif
![image](https://user-images.githubusercontent.com/18234424/69920343-d6b1b400-1454-11ea-9c97-a8b6068be491.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c23010-70d4-60db-8b58-308b2dbed3f3
* Version Independent ID: 4c11f06d-bac4-292e-bd70-f16d1e409707
* Content: [Best practices for enterprises moving to Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/reference/azure-scaffold)
* Content Source: [docs/reference/azure-scaffold.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/reference/azure-scaffold.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @rdendtler
* Microsoft Alias: **rodend**

**Comment by BrianBlanchard** [comment]
This image and the Azure scaffold approach are in the process of being deprecated.
