### ISSUE TITLE
Document Security Implications

### ISSUE THREAD

**Issue by bloudraak** [MicrosoftDocs/cloud-adoption-framework#650]
Within Step 5 there are some optional steps to be taken, which actually reduces the security posture of Windows Server and can be in conflict with industry guidelines for hardened Windows systems (which is why we often create templates to begin with). 

These kinds of documents are invaluable, but needs to have a section discussing implications of such a template. For example, if one were to deploy the template to a DMZ or public networks with reduced security, or perhaps a network segment that has been breached (aka assume breach mentality). Or what would happen if the template and it's disks end up on a public file sharing site (hint: encryption may help, or don't store credentials in the template, or secure the template appropriately with access controls, including the hosts). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3a80ef-f27f-b12c-ed7c-6c04288f758f
* Version Independent ID: 7f9fb40f-ca54-439e-76c4-b3de5d36a91c
* Content: [Create a VMware vSphere template for Windows Server 2019 - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/vmware-windows-template)
* Content Source: [docs/manage/hybrid/server/best-practices/vmware-windows-template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/hybrid/server/best-practices/vmware-windows-template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/509992/>509992</a>

**Comment by JanetCThomas** [comment]
@jaalmond @dominicallen @JefferyMitchell - can you please review this article and recommendations for how to use the template.
