### ISSUE TITLE
Dedicate VMs step question

### ISSUE THREAD

**Issue by dmdj** [MicrosoftDocs/cloud-adoption-framework#652]
Is the Yes/No reversed for "Dedicate VMs"?   If No, then go to an App Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8000fd6f-1bb1-dc48-1fbb-94797e1ef672
* Version Independent ID: a3a2a262-5943-6018-52ce-2030048a4760
* Content: [Migration tools decision guide - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/migrate-decision-guide/)
* Content Source: [docs/decision-guides/migrate-decision-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/decision-guides/migrate-decision-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/512954/>512954</a>

**Comment by jocontr** [comment]
Updated guidance, please reopen issue if it still exists. Thank you
