### ISSUE TITLE
Any changes needed for Server 2022 GUI or Core?

### ISSUE THREAD

**Issue by severud** [MicrosoftDocs/cloud-adoption-framework#653]
Any changes needed for Server 2022 GUI or Core? If not it would be nice to proactively say that this applies to Server 2022 as well. Thanks.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3a80ef-f27f-b12c-ed7c-6c04288f758f
* Version Independent ID: 7f9fb40f-ca54-439e-76c4-b3de5d36a91c
* Content: [Create a VMware vSphere template for Windows Server 2019 - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/vmware-windows-template?/azure/cloud-adoption-framework/_bread/toc.json&toc=/azure/cloud-adoption-framework/scenarios/hybrid/toc.json)
* Content Source: [docs/manage/hybrid/server/best-practices/vmware-windows-template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/manage/hybrid/server/best-practices/vmware-windows-template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/513049/>513049</a>

**Comment by jocontr** [comment]
Thank you for your feedback. We will aim to address this need via product documentation.
