### ISSUE TITLE
Improperly worded sentence regarding Azure AD

### ISSUE THREAD

**Issue by mbilalamjad** [MicrosoftDocs/cloud-adoption-framework#654]
Hi Team, just wanted to highlight that the following sentence in quotes doesn't seem to read well in the EA and AAD tenants design area

"Organizations already using on-premises Azure AD can integrate it with their current infrastructure and extend cloud authentication"

Probably could be reworded as below

"Organizations already using on-premises AD can integrate it with their Azure AD and extend cloud authentication"

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants#define-azure-ad-tenants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0075e68e-d22e-f35d-d7d4-b936dcb3e6ad
* Version Independent ID: 11caebc2-6caf-0095-3eb5-564e18a15488
* Content: [Enterprise Agreement enrollment and Azure Active Directory tenants - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants#define-azure-ad-tenants)
* Content Source: [docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/enterprise-enrollment-and-azure-ad-tenants.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/514466/>514466</a>

**Comment by mbilalamjad** [comment]
Team also wanted to report that it seems to be showing correctly in the md file but for some reason the same is not showing in the public website, please see below
![MicrosoftTeams-image1](https://user-images.githubusercontent.com/79409563/140744392-9e97b00a-d808-44ae-bba7-dcca59da0ffa.png)

**Comment by jtracey93** [comment]
cc: @dominicallen FYI

**Comment by v-andreaco** [comment]
@mbilalamjad @dominicallen 

Fixed in private repo: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2740
