### ISSUE TITLE
Separation of "nonprod" and "prod" management groups

### ISSUE THREAD

**Issue by cswhitehead** [MicrosoftDocs/cloud-adoption-framework#656]
In the management group page can we have some clarification as to whether explicit management groups for "nonprod" and "prod" under landing zones is a viable option?  We generally don't recommend it (do this at subscription level), but it is often implemented.

Rather than just the one management group hierarchy recommendation, would it possible to highlight a number of common hierarchies we see?  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a74b194-bd41-fb45-a758-6d48e05b9465
* Version Independent ID: 1a74b194-bd41-fb45-a758-6d48e05b9465
* Content: [Resource organization - management groups - design area - Cloud Adoption Framework](https://review.docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-management-groups?branch=collab-alz-milestone-2)
* Content Source: [docs/ready/landing-zone/design-area/resource-org-management-groups.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/landing-zone/design-area/resource-org-management-groups.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/515878/>515878</a>

**Comment by cswhitehead** [comment]
Have found this link - https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-handle-devtestproduction-workload-landing-zones-in-enterprise-scale-architecture 

This helps explain the reasoning behind not doing the "nonprod" / "prod" dedicated MGs - are we keeping this in the new docs?

**Comment by cswhitehead** [comment]
Will close this issue given the content of the above link / doc.
