### ISSUE TITLE
Link for the next section is not per table of contents.

### ISSUE THREAD

**Issue by kochmon7140** [MicrosoftDocs/cloud-adoption-framework#657]
According to the table of contents, there is one more section within the same chapter, before jumping into the next Financial chapter. But, if I click on the "next section" link, it is going somewhere else. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9062ac-00cf-b148-b73f-cda525d99c45
* Version Independent ID: 6740abb0-dbc9-5590-eb93-24cc068c6fed
* Content: [Align efforts to learning metrics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/learning-metrics)
* Content Source: [docs/strategy/learning-metrics.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/learning-metrics.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/516301/>516301</a>

**Comment by v-andreaco** [comment]
@kochmon7140 

Thanks for the feedback! I'd like to ask for some clarification before we move forward. Do you mean that the links in the 'Next steps' section at the bottom of the page doesn't take you to the next listed article in table of contents on the left-hand side of the page?

**Comment by mpvenables** [comment]
@v-andreaco this issue was resolved in a previous PR, and can be closed.
