### ISSUE TITLE
Woodgrove Bank or Woodgrove Health?

### ISSUE THREAD

**Issue by elenaterenzi** [MicrosoftDocs/cloud-adoption-framework#663]
I'd suggest you make it clear if it's a bank or an healthcare provider that we are dealing with.
Specifically you mention "(...) security of the patient data. As a healthcare company, (...)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb298292-f7db-3e03-adac-1df0ce571786
* Version Independent ID: bb298292-f7db-3e03-adac-1df0ce571786
* Content: [Financial institution scenario for data mesh - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/reference-architecture-data-mesh)
* Content Source: [docs/scenarios/data-management/architectures/reference-architecture-data-mesh.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/data-management/architectures/reference-architecture-data-mesh.md)
* Service: **cloud-adoption-framework**
* GitHub Login: @pietheinstrengholt
* Microsoft Alias: **pstrengholt**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/521903/>521903</a>

**Comment by pietheinstrengholt** [comment]
Pull request is on its way: https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2715

**Comment by jocontr** [comment]
Issue has been addressed. Thank you.
