### ISSUE TITLE
Add abbreviation recommendation for Private Endpoint

### ISSUE THREAD

**Issue by vijayshinva** [MicrosoftDocs/cloud-adoption-framework#664]
Add abbreviation recommendation for **Private Endpoint**

Private Endpoint : pe-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/521964/>521964</a>

**Comment by VitalyMCT** [comment]
Is there a chance we could get a heads up on what the abbreviation would be while that bug works its way through the system? 

Would it be "pe-"?

Thank you.
