### ISSUE TITLE
DeployIfNotExists Azure Policy does not support multiple group ids (subresources)

### ISSUE THREAD

**Issue by tullydwyer** [MicrosoftDocs/cloud-adoption-framework#666]
Hi there,

The DeployIfNotExists Azure Policy does not support multiple group ids (subresources). This means we have to duplicate the policy for each group id (subresource) for resources with multiple group ids (subresources).

For example the following resources (https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration): 
- Storage account (Microsoft.Storage/storageAccounts) / Blob
  - blob, blob_secondary
- Storage account (Microsoft.Storage/storageAccounts) / Table
  - table, table_secondary
- Storage account (Microsoft.Storage/storageAccounts) / Queue
  - queue, queue_secondary
- Storage account (Microsoft.Storage/storageAccounts) / File
  - file, file_secondary
- Storage account (Microsoft.Storage/storageAccounts) / Web
  - web, web_secondary
- Azure Data Lake File System Gen2 (Microsoft.Storage/storageAccounts)
  - dfs, dfs_secondary
- Azure Automation / (Microsoft.Automation/automationAccounts)
  - Webhook, DSCAndHybridWorker

Can the Cloud Adoption Framework update the policy to support resources with multiple group ids (subresources)? 

We have solved this issue (and https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/644) with the following policy statements:

Single statement:
```json
{
  "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
  "in": [
    "blob",
    "blob_secondary"
  ]
}
```

Full if statement:
```json
"policyRule": {
  "if": {
    "allOf": [
      {
        "equals": "Microsoft.Network/privateEndpoints",
        "field": "type"
      },
      {
        "count": {
          "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*]",
          "where": {
            "allOf": [
              {
                "contains": "Microsoft.Storage/storageAccounts",
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].privateLinkServiceId"
              },
              {
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
                "in": [
                  "blob",
                  "blob_secondary"
                ]
              }
            ]
          }
        },
        "greaterOrEquals": 1
      }
    ]
  }
}
```

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd28f7b-1764-83c9-9d82-d65ba75bcb94
* Version Independent ID: e91679fb-9d61-7f89-5cb6-238e2eb91757
* Content: [Private Link and DNS integration at scale - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale)
* Content Source: [docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/private-link-and-dns-integration-at-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/522282/>522282</a>

**Comment by skabou** [comment]
It appears this has been addressed since the issue was initially opened.  If this is not the case, please re-open with additional details.
