### ISSUE TITLE
add Microsoft Defender for Cloud

### ISSUE THREAD

**Issue by mslaurie** [MicrosoftDocs/cloud-adoption-framework#668]
hey folks, on this page, you mention Identity Framework and Microsoft Sentinel, but not Microsoft Defender for Cloud as our cloud native way to improve your multi cloud security posture and detect threats on your cloud resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b171e46f-0ac2-f740-b2c7-2bb120cd03c8
* Version Independent ID: d2628d9e-676b-799d-1ae6-24a95170ef09
* Content: [Define a security strategy - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/define-security-strategy)
* Content Source: [docs/strategy/define-security-strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/define-security-strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @MarkSimos
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525559/>525559</a>

**Comment by v-andreaco** [comment]
Fixed in internal PR. Thanks for bringing this to our attention!
