### ISSUE TITLE
ARM script will not run

### ISSUE THREAD

**Issue by thornethammer** [MicrosoftDocs/cloud-adoption-framework#669]
I am trying to run the "Enterprise-scale foundation" ARM script (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation) on my free Azure Domain, and I get "You don’t have authorization to perform action 'Microsoft. Resources/deployments/validate/action'."  I have been assigned the role 'Owner' (type BuiltInRole) and 'User Access Administrator' (type BuiltInRole).  I have toggled to yes the Access management for Azure resources.  I have followed the instructions at https://github.com/Azure/Enterprise-Scale/blob/main/docs/EnterpriseScale-Setup-azure.md but when I tried the powershell scripts but they all fail to run, it looks like a command structure error (not a power shell guy.. yet) 

Any suggestions... is it possible that the free domain does not support this particular ARM script?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 676fa0a6-b6e0-eb9f-5c75-e3b2f457adf5
* Version Independent ID: fde434af-3412-8139-51cd-988751061617
* Content: [Cloud Adoption Framework enterprise-scale landing zones in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation)
* Content Source: [docs/ready/enterprise-scale/implementation.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/enterprise-scale/implementation.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525731/>525731</a>

**Comment by dominicallen** [comment]
Thanks for your feedback. Please refer to this page for guidance: https://github.com/Azure/Enterprise-Scale/wiki/Deploying-Enterprise-Scale-Pre-requisites#grant-access-to-the-user-at-tenant-root-scope--to-deploy-enterprise-scale
