### ISSUE TITLE
Is this "recommended naming" BEST PRACTICE?

### ISSUE THREAD

**Issue by licentiat** [MicrosoftDocs/cloud-adoption-framework#67]
Please Microsoft, stop recommended/referring as BEST PRACTICE your opinion.
Why do you think is best practice to include the resource type as part of the resource name? Azure is not the only place where those resources are visible. Think of a SQL Server database administrator managing Azure databases. If the administrator uses SSMS or another tool to manage databases, all those databases will be named "***-db"? Another example will be files on Windows operating system. Imagine all files on Windows will have the file type included on the file name. I think it's a bad idea to include resource type as part of the resource name. You have the column and possibility to filter by resource type in Azure, why should the name include that?

**Comment by BrianBlanchard** [comment]
Thank you for your feedback. For years before taking on this role, I would have agreed with you. It seems redundant. After studying cause & affect on thousands of customers with & without naming standards, I'm a clear convert to the need for this simple best practice.

This particular best practice is less about human filtration of the naming sequence & more about operational and governance processes. We've noticed that a number of customers encounter governance, management, and operational requirements later in the adoption lifecycle that are eased by three simple practices... 
- Include a consistent naming standard with a common abbreviation for resource type in the name. 
- Organize resources into a logical strategy including subscriptions, management groups, and resources groups.
- Tag resources with non-technical requirements like app criticalilty, data sensitivity, billing codes, etc...

These three practices may seem redundant during adoption, but later in the lifecycle, they can help reduce operational burdens & costs through more easily implemented processes and platform automation.
