### ISSUE TITLE
Visio File

### ISSUE THREAD

**Issue by Tech200910** [MicrosoftDocs/cloud-adoption-framework#670]
Can you please share Visio diagram of figure 1.   
I am looking for Visio reference architectures of vWAN showing hub spoke for different subscriptions with different subnets of network management , DMZ and shared services

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/525982/>525982</a>

**Comment by Tech200910** [comment]
I am looking for Visio reference architectures of vWAN showing hub spoke for different subscriptions with different subnets of network management , DMZ and shared services

**Comment by v-andreaco** [comment]
@Tech200910 

Thanks for the feedback! Can you please link to the article you're referencing?

**Comment by jocontr** [comment]
Please reopen once you have identified the article you are referencing. Thank you
