### ISSUE TITLE
Tag inheritance

### ISSUE THREAD

**Issue by darrenjoycenz** [MicrosoftDocs/cloud-adoption-framework#671]
When is tag inheritance available (in the Note on the page)? Or is the document referring to Azure Policy doing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b24efd3-3fda-7c73-6bf6-cfed8a3e2785
* Version Independent ID: 95e455f3-674a-7554-bfd8-d43e46c60271
* Content: [Organize and manage multiple Azure subscriptions - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/organize-subscriptions)
* Content Source: [docs/ready/azure-best-practices/organize-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/organize-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/526232/>526232</a>

**Comment by BryanLa** [comment]
@darrenjoycenz - our apologies for the delay in responding to this, and thanks for your contribution.

This article has been updated and will republish tomorrow, Pacific time.

#please-close
