### ISSUE TITLE
General Use Storage Account Guidance doesn't include environment

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/cloud-adoption-framework#676]
The guidance for a storage account doesn't provide and environment component:

![image](https://user-images.githubusercontent.com/7981510/144734391-c80cd78d-58ba-4dd9-babb-4d3e40a44e51.png)

Not sure if it would make sense to have additional guidance for storage account naming with hns enabled for analytics purposes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/528138/>528138</a>

**Comment by stephen-sumner** [comment]
@jasonhorner - I know it's been several years since you opened this issue. We're working on updating this page and I would personally use something like <resource abbreviation + app or project name + organization identifier + environment> for most all global resources.

**Comment by stephen-sumner** [comment]
#please-close
