### ISSUE TITLE
TOC has a broken link

### ISSUE THREAD

**Issue by zojovano** [MicrosoftDocs/cloud-adoption-framework#680]
Link to "Hybrid Architectures - Overview" is broken. The link points to "Browse Azure Architectures" and page loads (so no real broken link) but it opens an empty page with message "No results. Sorry, we couldn't find anything that fit your search."

The link in the question: 
(https://docs.microsoft.com/en-us/azure/architecture/browse/?azure_categories=hybrid?
bc=/azure/cloud-adoption-framework/_bread/toc.json&toc=/azure/cloud-adoption-framework/scenarios/hybrid/toc.json)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3002f436-84c3-d666-4d8a-d4b561239348
* Version Independent ID: b5d45c98-e3b9-c664-98aa-28f4b239946a
* Content: [Introduction to hybrid and multicloud - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/hybrid/)
* Content Source: [docs/scenarios/hybrid/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/hybrid/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-andreaco** [comment]
@zojovano 

Thanks for letting us know! A PR was created and merged in the private repo. Closing this issue. Please allow up to 24 hours for the changes to publish.
