### ISSUE TITLE
Link to initial organization alignment is wrong

### ISSUE THREAD

**Issue by DebabrataHowlee** [MicrosoftDocs/cloud-adoption-framework#682]
THe correct URL to orgnization alignment should be 
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/

instead of 
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e324c2-9d00-346b-64e8-53e515a1d758
* Version Independent ID: 69da1435-3b49-d903-a0a3-e584b924b67e
* Content: [Skills readiness path during the readiness phase of a migration journey - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/suggested-skills)
* Content Source: [docs/ready/suggested-skills.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/suggested-skills.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/530706/>530706</a>

**Comment by mpvenables** [comment]
@JanetCThomas fixed. ok to close.

**Comment by v-andreaco** [comment]
@mpvenables 
Thanks! It looks like the live page is still pointing to the wrong place. Is there an open PR to fix this? I can close the issue once the fix is complete and published. :)

**Comment by v-andreaco** [comment]
Verified fix. Thanks for the suggestion!
