### ISSUE TITLE
Cloud strategy functions Roles

### ISSUE THREAD

**Issue by Gassela** [MicrosoftDocs/cloud-adoption-framework#684]
Hello,
on the page https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-strategy near the phrase "_When a cloud strategy team is defined, it should include many of the following roles :_ " these items are listed:

- Finance
- Line of business
- Human resources
- Operations
- Enterprise architecture
- IT infrastructure
- Application groups
- Project managers (often with agile project management experience)

As you can see for yourself, we have a mix between:

- Departmental Units (Finance, Human Resources)
- Roles (Project Managers)
- functions (Operations, Application Group, Line of Business, IT infrastructure, Enterprise architecture)

**It creates a lot of confusion.**
Since it is important to highlight and list which roles are mandatory for this area, I believe that it is necessary to reframe this list; for instance:

- Finance -> Finance Owner? Finance Lead? Finance Manager?
- Line of business -> Business Reference? Business Owners?
- Human resources -> HR Lead? HR Manager?
- Operations -> Operations Lead? Operations Manager?
- Enterprise architecture -> Enterprise Architect? Solution Architect?
- IT infrastructure -> Infrastructure Lead? Infrastructure Manager? THAT IS?
- Application groups -> Application Owner?
- Project managers (often with agile project management experience) -> OK

Please check with the CAF PGs which are the roles they were thinking of when they made this strange list.

I stress the **importance of linking** this function **to roles and not to functions or departmental units**.

Thanks a lot in advance,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4ffcb7-5d4a-80c3-7156-73c6c3979707
* Version Independent ID: 243f1778-81d6-e412-4000-67b012653e68
* Content: [Understand the function of cloud strategy - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-strategy)
* Content Source: [docs/organize/cloud-strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/organize/cloud-strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **organize**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **janet**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/532582/>532582</a>

**Comment by Gassela** [comment]
If my assumption is correct, please consider you have same problem at following pages:
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-governance

- IT governance --> ? CIO? Service Management Team? Adoption Lead?
- Enterprise architecture --> ? Enterprise Architect? Solution Architect?
- Security --> ? please refer to https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/organize/cloud-security#role-types for maintaining their alignment
- IT operations --> ? is similar to Operations mentioned with Cloud Strategy? Yes/No? Should it be Operations Lead? Operations Manager?
- IT infrastructure --> ? Infrastructure Lead? Infrastructure Manager?
- Networking --> ? Network Lead? Network Manager? Network Admin?
- Identity --> ? Identity Lead? Identity Manager? Identity Admin?
- Virtualization --> ? Virtualization Lead? Virtualization Manager? Virtualization Admin?
- Business continuity and disaster recovery --> ?
- Application owners within IT --> OK
- Finance owners --> OK

**Comment by Gassela** [comment]
Hi @david-stanford,
do you have news about this my ticket?

Thanks

**Comment by JanetCThomas** [comment]
@BrianBlanchard - could you please review and respond?

**Comment by Gassela** [comment]
Dear @david-stanford , @JanetCThomas , @BrianBlanchard,
as you read from ticket history, **it had been opened 28 days ago**.
**It means a month**. 
I can understand we had the Christmas holiday, the pandemic situation doesn't help us, but the world does not stop itself, right?
docs.microsoft.com is one of our **"business card"** for cloud adoption service used by our customers.
So we cannot fail with it.
As Microsoft employee, I think it is important to collaborate in making sure that this channel is correct and constantly updated.
So we cannot fail with it.

Please let me know, if I can have the same commitment by you or less.

thanks a lot in advance,
Alex

**Comment by JanetCThomas** [comment]
Thank you for your feedback. We have added it to our backlog. It is under review.

**Comment by Gassela** [comment]
hi @v-fearam, @JanetCThomas and @david-stanford 
sorry for my delay too.

I agree with your general sentence Federico, but the page reports some key words in contrast with you.
Had you the chance to see my original post?

I'm asking to you for it because I reported specific page's sections to sustain my viewpoint.
I believe it is important to have precise statements otherwise we risk to create confusion in everyone.

<img width="455" alt="image" src="https://github.com/MicrosoftDocs/cloud-adoption-framework/assets/46483393/ed962e3a-631b-430c-a25c-3509dbc6bcb9">
