### ISSUE TITLE
SHIR placement guidance for data management and analytical scenario inquiry

### ISSUE THREAD

**Issue by saif-chaudhry** [MicrosoftDocs/cloud-adoption-framework#687]
Hoping some clarification can be provided with respect to the SHIR placement in this scenario. Under the 'shared integration' section of this page it's stated _"We recommend you deploy a virtual machine scale set with self-hosted integration runtimes into the **data management landing zone**. It should be hosted in the integration resource group. "_

Is the guidance indeed to host the SHIR in the **data management landing zone** ? If so then it should be reflected in the diagram of the  "data management landing zone" on the page (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-management-landing-zone) as well - the data management landing zone diagram has no SHIR and RG mentioned that align with this recommendation. 

If it's a typo and recommendation is to run the SHIR in the **"data landing zone"** as the architecture diagram shows then please update the text accordingly to avoid confusion to the reader of the document.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a913402-aa8d-3ae7-2589-81d7bee16c09
* Version Independent ID: 5857fc40-82a4-18e2-e152-67841ca03f51
* Content: [Overview of the data management and analytics scenario architecture data landing zone in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone)
* Content Source: [docs/scenarios/data-management/architectures/data-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/data-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/534444/>534444</a>

**Comment by mboswell** [comment]
Thank you - fixed and merged to docs.
