### ISSUE TITLE
Visio Diagrams

### ISSUE THREAD

**Issue by gabudd** [MicrosoftDocs/cloud-adoption-framework#688]
Could we please add Visio Diagrams for each version of the Enterprise-Scale Architecture's as more customers keep asking for these in order to create logical designs for their Landing Zones.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 676fa0a6-b6e0-eb9f-5c75-e3b2f457adf5
* Version Independent ID: fde434af-3412-8139-51cd-988751061617
* Content: [Cloud Adoption Framework enterprise-scale landing zones in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation)
* Content Source: [docs/ready/enterprise-scale/implementation.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/enterprise-scale/implementation.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/535174/>535174</a>

**Comment by v-andreaco** [comment]
@gabudd 

Thanks for the suggestion! I'm seeing diagrams in the links from this page. If you follow the "Example in GitHub" links, do those diagrams suffice?

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24763 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
