### ISSUE TITLE
"This product" link at bottom of page is broken

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#691]
This is probably a widespread issue now that Uservoice was discontinued, this is just an example of one such page. Clicking on

![image](https://user-images.githubusercontent.com/1765732/147172592-5c2d0806-79b3-4050-bab0-5aeaf58f1d1c.png)

Goes to:

![image](https://user-images.githubusercontent.com/1765732/147172612-d3af2209-f19c-4e37-86df-af84d9c16220.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/535327/>535327</a>

**Comment by JanetCThomas** [comment]
This issue has been fixed. Thanks.
