### ISSUE TITLE
Backup Policies

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#692]
Is there an abbreviation for this item type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/535328/>535328</a>

**Comment by v-andreaco** [comment]
@VitalyMCT 

Thanks for asking! We're looking into this.

**Comment by hallihan** [comment]
@VitalyMCT - I don't see what item type you are asking for an abbreviation for.  Can you provide more detail on what is missing?

**Comment by stephen-sumner** [comment]
@VitalyMCT - Thanks for the requests! You should see some updates soon.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3962
