### ISSUE TITLE
supported version of TFS/Azure DevOps Server

### ISSUE THREAD

**Issue by cecedxx** [MicrosoftDocs/cloud-adoption-framework#693]
The data migration tool for Azure DevOps supports the two latest releases of Azure DevOps Server at a given time. Check the following documentation: 

https://docs.microsoft.com/en-us/azure/devops/migrate/migration-overview?view=azure-devops

This page is using TFS 2018 as an example and not indicates the supported version, which will cause confusion. Please update the TFS version in the example or declare the supported version in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecab90d0-e29c-f995-dcc4-ec80e94b7ba7
* Version Independent ID: fe315705-2398-6b60-d81a-c9013bc97ed4
* Content: [Refactor a Team Foundation Server deployment to Azure DevOps Services - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-tfs-vsts)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-tfs-vsts.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-tfs-vsts.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/537406/>537406</a>

**Comment by skabou** [comment]
Thank you for your feedback.  This article has been deprecated.
