### ISSUE TITLE
Missing Legends

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/cloud-adoption-framework#695]
In the first section the colors of the graphics are not clear
<img width="717" alt="image" src="https://user-images.githubusercontent.com/908734/148217295-0c130299-d999-4b49-a340-38f8cf41884f.png">

- What does orange, yellow and purple mean?
- What do the numbers along the edges refer to?
- I believe the subtitle that appears when you click on those images should be adjusted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d1b1ca-12b7-6005-5858-e6f59eb697bb
* Version Independent ID: e4e00fee-ac9d-e79f-f6e6-9e2dc57a0883
* Content: [Build data management and analytics capabilities in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/plan-capabilities)
* Content Source: [docs/scenarios/data-management/plan-capabilities.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/plan-capabilities.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pratimdas
* Microsoft Alias: **prda**

**Comment by mboswell** [comment]
Thank you @fmms, they were on our backlog to update and the point you make above are valid
