### ISSUE TITLE
Typo an -> a

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/cloud-adoption-framework#697]
Twice on this page 
"of an data management"
should be
"of a data management"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79d04244-7898-4d57-46bf-004615a11c51
* Version Independent ID: f1ce1962-58fd-5631-334d-6e72d6d441a1
* Content: [Scaling data management and analytics in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-scale)
* Content Source: [docs/scenarios/data-management/eslz-scale.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/eslz-scale.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @esbran
* Microsoft Alias: **espen**

**Comment by JanetCThomas** [comment]
This issue has been fixed.  Thanks.
