### ISSUE TITLE
Azure Synapse is referred to in two sections

### ISSUE THREAD

**Issue by fmms** [MicrosoftDocs/cloud-adoption-framework#698]
Hi,

the document contains the following paragraph:
_For datasets in Azure data lakes, consider using access control lists (ACLs). For more information, see Access control model in Azure Data Lake Storage Gen2. Using Azure AD passthrough with access control lists is supported ***by most native Azure services***, including Azure Machine Learning, ***Azure Synapse Analytics***, and Azure Databricks.
***Other polyglot storage*** is likely to be used in data management and analytics scenario. Examples include Azure Database for PostgreSQL, Azure Database for MySQL, Azure SQL Database, SQL Managed Instance, and ***Azure Synapse Analytics***. They could be used by data integrations to store read data stores or by data product teams._

So which section should Synapse go to? I believe it might have been intended to write that Azure Synapse SQL Serverless can use pass through and Azure Synapse SQL Dedicated pools be used by data integration to store data ...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d5dedcd-a74c-94bc-36ea-0eba575d4ef5
* Version Independent ID: f8dd1768-a7d4-b25c-f792-a159d95a4aa4
* Content: [Identity and access management for data management and analytics - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-identity-and-access-management)
* Content Source: [docs/scenarios/data-management/eslz-identity-and-access-management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/eslz-identity-and-access-management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
Fixed in PR 2869

**Comment by mboswell** [comment]
@JanetCThomas  please can you now close this
