### ISSUE TITLE
East-West Traffic -- Conflicts with other documentation

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/cloud-adoption-framework#7]
This section of the documentation: "Best practice: Secure north/south and east/west traffic"

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#best-practice-secure-northsouth-and-eastwest-traffic

conflicts with section "How traffic is evaluated"
https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#how-traffic-is-evaluated

Please note open GitHub issue https://github.com/MicrosoftDocs/azure-docs/issues/20848 specifically asking for clarification on this point, where it seems to be signed off on by Microsoft people that NSGs *will block* East-West traffic inside of subnet. Hopefully we can get all this documentation to agree...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c309fa0-4224-e36f-4ed2-062891b9b46a
* Version Independent ID: 4f2c4f46-69a0-962e-a1a5-17e280489bef
* Content: [Best practices to set up networking for workloads migrated to Azure - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#securing-vnets)
* Content Source: [docs/migrate/azure-best-practices/migrate-best-practices-networking.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/migrate-best-practices-networking.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
@tracsman Any suggestions on how best to clarify & align these two docs?

**Comment by BrianBlanchard** [comment]
Terminated due to lack of response.
