### ISSUE TITLE
Combine Best Practices

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#700]
It would be helpful if these were combined with https://docs.microsoft.com/en-us/security/compass/compass we don't need 2 sets of Best Practices
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81125cd-1520-8f83-150f-04d95581c8e1
* Version Independent ID: 28adb70c-3fc4-338f-ed69-e21e66be521d
* Content: [Azure security best practices - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/secure/security-top-10#4-process-update-incident-response-ir-processes-for-cloud)
* Content Source: [docs/secure/security-top-10.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/secure/security-top-10.md)
* Service: **cloud-adoption-framework**
* Sub-service: **secure**
* GitHub Login: @JanetCThomas
* Microsoft Alias: **brblanch**

**Comment by v-andreaco** [comment]
@DeanGross 

Thanks for the suggestion! These two articles are maintained by different teams, and it's unlikely they'll be combined. However, we'll consider your suggestion as an opportunity to reduce redundancy as necessary. Much appreciated!

**Comment by DeanGross** [comment]
@v-andreaco I understand why they may want to combine them, but could we at least get a cross-reference between them so that people could easily find the companion presentation?
