### ISSUE TITLE
5 'Rs' should be 6 'Rs'

### ISSUE THREAD

**Issue by godwindejong** [MicrosoftDocs/cloud-adoption-framework#701]
We are missing 'Retirement' as an option.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3503b34b-102b-18b7-de00-a485c9a24d81
* Version Independent ID: 2f35f885-7c4d-0eb7-bf7c-1c29c27d399b
* Content: [Cloud rationalization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/digital-estate/5-rs-of-rationalization#feedback)
* Content Source: [docs/digital-estate/5-rs-of-rationalization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/digital-estate/5-rs-of-rationalization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24583 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
