### ISSUE TITLE
Better and more understandable example for directory layout

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/cloud-adoption-framework#704]
The example directory layout for the Raw, enriched, curated zone is fairly good described, but could you make it even clearer and better by providing a E2E scenario as an example? 
Not everyone understands all the terms used in the examples such as Data Integration, Data Product, Source, Entity, Dataset so it can be confusing and hard guess and translate those to their own use case / business.

### **Raw Directory Layout**
.
|-General
|--Source
|--Source
|---Entity
|---LoadTS=YYMMDDHHMSS
|       file001.parquet
|       file001.parquet
|-Sensitive(Personal data)
|--Source
|---Entity
|---LoadTS=YYMMDDHHMSS
|       file001.parquet
|       file001.parquet

### **Enriched Directory Layout**
.
|-Data Integration
|-Data Integration
|--Transactional
|---General
|----Dataset
|-----Entity
|------LoadTS=YYMMDDHHMMSS
|        file001.parquet
|        file001.parquet
|---Sensitive (Personal data)
|----Dataset
|-----Entity
|------LoadTS=YYMMDDHHMMSS
|--Master Data
|----Dataset

### **Curated Directory Layout**
.
|-Data Product
|-Data Product
|--Transactional
|---General
|----Dataset
|-----Entity
|------LoadTS=YYMMDDHHMMSS
|        file001.parquet
|        file001.parquet
|---Sensitive(Personal data)
|----Dataset
|-----Entity
|------LoadTS=YYMMDDHHMMSS
|--Master Data
|----Dataset

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174bef87-bea0-a095-3712-2c9dcf9e9388
* Version Independent ID: 9deb539b-93a8-a3d0-25c3-ebf65e5a4441
* Content: [Provision three Azure Data Lake Storage Gen2 accounts for each data landing zone - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-services)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by ozhug** [comment]
Same request here.
I found this page by trying to work out what LoadTS=YYMMDDHHMSS would look like in the real world as an actual file or folder naming structure.

**Comment by mboswell** [comment]
We will clarify this content soon as part of our next set of updates.

**Comment by mboswell** [comment]
This has been updated in a future release. Thank for the feedback

#please-close
