### ISSUE TITLE
Advertising: Sample AVD - Azure DevOps project using CAF

### ISSUE THREAD

**Issue by bfrankMS** [MicrosoftDocs/cloud-adoption-framework#706]
Hi,

together with some colleagues I did a DevOps project for automating the deployment of AVD using CAF principles
[aka.ms/avdcollege
](https://aka.ms/avdcollege)

hth,
Bernhard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516d6288-2c04-3934-04a9-ca95dca66d3d
* Version Independent ID: 049eeabb-25b0-9d96-7bba-1aff3f7e5015
* Content: [Platform automation and DevOps for Azure Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-platform-automation-and-devops)
* Content Source: [docs/scenarios/wvd/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by hallihan** [comment]
This may make a good contribution, I'll follow up offline with some links for that option.
