### ISSUE TITLE
Azure Load Testing

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#707]
Can we add a standard abbreviation for this resource type please?

https://docs.microsoft.com/en-ca/azure/load-testing/quickstart-create-and-run-load-test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950

**Comment by stephen-sumner** [comment]
@VitalyMCT - Thanks for the feedback! It's really appreciated! You should see some updates soon.
