### ISSUE TITLE
Template Specs

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/cloud-adoption-framework#708]
Please provide a standard abbreviation for this resource type.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-specs

**Comment by stephen-sumner** [comment]
[@VitalyMCT ](https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950)

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950
