### ISSUE TITLE
Spelling mistake on the Enterprise Scale Architecture diagram - "Indentity Subscription" (see snapshoot attached)

### ISSUE THREAD

**Issue by cbezenco** [MicrosoftDocs/cloud-adoption-framework#709]
You want to fix the spelling mistake on "identity subscription" in the enterprise scale diagram (currently "Indentity")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60ebd567-bf69-afa9-625e-38eb81dccfba
* Version Independent ID: ef4ee644-1df3-433b-b11e-cb32dc58bad1
* Content: [Enterprise-scale support for Azure Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/enterprise-scale-landing-zone#feedback)
* Content Source: [docs/scenarios/wvd/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch*
![Screenshot 2022-01-18 114547](https://user-images.githubusercontent.com/12773102/149923870-eede9571-b1f6-4585-8255-13622e2333ee.png)
*

**Comment by v-andreaco** [comment]
@cbezenco 

Great catch, thanks! We'll assign someone to fix that ASAP and will let you know when it's done.

**Comment by v-andreaco** [comment]
@cbezenco 

Fixed in private repo. Issue resolved; closing.
