### ISSUE TITLE
Subscriptions and Resource Groups

### ISSUE THREAD

**Issue by PChipVIA** [MicrosoftDocs/cloud-adoption-framework#71]
So in the end, both Subscriptions and Resource Groups are logical containers for resources.  Question then is what is the benefit of using a RG to logically group resources when one can use a subscription instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec28c5f-8da8-8c68-da8f-6bd7dd5234b8
* Version Independent ID: ee97fd28-acb1-cf2c-7f3f-f9dbf242d412
* Content: [Azure fundamental concepts - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/fundamental-concepts)
* Content Source: [docs/ready/considerations/fundamental-concepts.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/fundamental-concepts.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by BrianBlanchard** [comment]
To be addressed in PR 193

**Comment by PChipVIA** [comment]
If not updated why closed?  It should be marked as pending change but not closed

**Comment by BrianBlanchard** [comment]
Should say "addressed in PR 193". That PR went live this morning.
