### ISSUE TITLE
Link Target Issue

### ISSUE THREAD

**Issue by sachatomey** [MicrosoftDocs/cloud-adoption-framework#711]
The following links under the 'Reference Architecture' section both point to the same page (the Management page).

- Data management landing zone
- Data landing zone

Cheers, Sacha
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
@JanetCThomas  - Fixed.
