### ISSUE TITLE
More details/Examples

### ISSUE THREAD

**Issue by ozhug** [MicrosoftDocs/cloud-adoption-framework#713]
Hi All,

This is fabulous start it would be great to have some examples.
Like taking raw data from sql server tables, sharepoint lists and csv files through the layers.
Showing how this would look in the raw, enriched and curated zones in a stater guide using World Wide Importers data or similar existing example datasets from Microsoft.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174bef87-bea0-a095-3712-2c9dcf9e9388
* Version Independent ID: 9deb539b-93a8-a3d0-25c3-ebf65e5a4441
* Content: [Provision three Azure Data Lake Storage Gen2 accounts for each data landing zone - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-services#raw-directory-layout)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
Thanks for the input. We hope to add some more info to this soon.

**Comment by mboswell** [comment]
This has been updated in updated guidance.

#please-close
