### ISSUE TITLE
Validation guide for Enterprise Scale Landing Zone Partner Offers

### ISSUE THREAD

**Issue by Mahesh-MSFT** [MicrosoftDocs/cloud-adoption-framework#715]
[CAF For Partners](https://azureforpartners-staging.azurewebsites.net/azure/partners/cloud-adoption-framework#cloud-adoption-framework-become-a-partner) page lists a [Partner Offer Validation guide](https://azurepartners.blob.core.windows.net/media/Resources/Enable/CAF/Cloud%20Adoption%20Framework%20-%20Partner%20Validation%20Guide%20v3%20_updated.pdf).  

In this guide, for the "Ready" (ESLZ!) offers, deliverables has a requirement of ESLZ offers to be validated against a separate validation guide for ESLZ. See the screenshot below.

![image](https://user-images.githubusercontent.com/20776028/150772322-1d6d5f40-8774-4670-b8e8-018fb96a5cc7.png)

The current status of this ESLZ Validation Guide for assessing Partner offers is shown as "Coming Soon".
 
**ASK:**

When will be ESLZ Validation Guide for assessing Partner offers be made available?  
 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 612d2372-96b0-4db0-e4fa-9e73d20d354a
* Version Independent ID: a4aa1dc8-2d23-5b7c-adfb-4cf47052faff
* Content: [Partner options for implementing Azure landing zones - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/partner-landing-zone)
* Content Source: [docs/ready/landing-zone/partner-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/partner-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
I rewrote this page in August and worked with Mahesh on it.
