### ISSUE TITLE
What is the purpose of the numeric suffix for subscription names? Is it necessary?

### ISSUE THREAD

**Issue by jpierson-at-riis** [MicrosoftDocs/cloud-adoption-framework#716]
Why is the recommendation for subscriptions, as just an example, to have some type of numeric suffix? If we're assuming to have only a very few high level subscriptions in our Azure account then why would there be a need to add some type of suffix?

Examples from the documentation are `mktg-prod-001`, `corp-shared-001`, `fin-client-001` but in these examples what good does `001` do if you only have one subscription that has a unique business unit and subscription type pairing? Am I missing something or is there an expectation to create much more subscriptions and perhaps on the fly than what I'm imagining for a small to medium sized business?

Either by adding some examples of what this suffix number would be used for, what it would represent, and perhaps whether it is recommended or not to omit for smaller organizations would be helpful information within this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
#please-close
