### ISSUE TITLE
Clarity around conventions that don't include '-'

### ISSUE THREAD

**Issue by bioengstrom** [MicrosoftDocs/cloud-adoption-framework#717]
Some of the resources can only have names that contain numbers or lowercase letters, e.g. storage accounts. However, this is only clear once you have enough experience to remember this, or if you are creating the resource through the Azure Portal. When reading this article, I had a hard time understanding if the reason why some conventions lacked the '-' character was because of a typo or not. Especially as I am currently working with ARM templates, where no hints are given about the requirement for alphanumerisy. Therefore, maybe there could be some added clarity in the article about this topic? 

Bests,
Isak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#example-names-storage)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@bioengstrom - Thanks so much for the feedback. You're absolutely right. The '-' character has been removed from our guidance.
