### ISSUE TITLE
Antipattern suggestion - use of naming convention, especially resource name prefixes over tag based metadata

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/cloud-adoption-framework#718]
Whilst many resources allow names that aren't required to be globally unique in name and therefore what ever you name them generally isn't an issue, there are however resources that do require globally unique names and therefore should more oftent than not be randomly named and have the correct tag based metadata applied instead of giving them a staticly definted name based on internal resource naming conventions that can and do collide with those of other organisations naming conventions.

Therefore, it is arugable that it is in fact an anti-pattern to have naming conventions applied to these resources and arguably still an anti-pattern to do so with other resources that aren't required to have a globally unique name.

Users/Developers/Admins should instead be encouraged to make use of tag-based metadata instead which is also better for building data queries in Azure Resource Graph and other tooling.

Whilst Resource Naming conventions are something that we've seen used across Tech for decades, and therefore are incredibly widespread in their use & in some cases can be of some use from a governance POV, they are unfortunately linear in nature whereas tags are multi-dimensional which often makes tags much better when used for any resource discoverability or resource management actions. Due to the multi-dimensional nature of tags and that some resources require a globally unique name across all of Azure we should be recommending that in most cases it is a better practice to use of more modern management & governance practices (like tagging, resource group isolation and subscription isolation) and not particularly care about the name we give a resource, and instead should quietly discourage the use of resource naming conventions in these scenarios or highly encourage organisations to supplement them if they choose to use them in their organisation with metadata that is applied via tags instead.

---
#### Document  

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51666a71-6be9-ea0d-77a4-2f37afbc83e6
* Version Independent ID: 261a6e99-1613-c2c9-f921-d22c081cd0eb
* Content: [Cloud adoption antipatterns - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/antipatterns/antipatterns-to-avoid)
* Content Source: [docs/antipatterns/antipatterns-to-avoid.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/antipatterns/antipatterns-to-avoid.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @lpassig
* Microsoft Alias: **brblanch**

**Comment by kilasuit** [comment]
To add further to this

There is little if any benefit in having a resource which has the following in it's name and instead should be queried from the rest of the metadata that is already available as part of the resource type and if not can be supplemented to with appropriate tags

- Subscription display name (whether full or an acroynm) / ID
- RG Prefix (literally ‘RG-’)
- Resource Group Display Name (whether full or an acroynm)
- Resource location
- Environment type (Dev, UAT, SIT, Prod, etc)
- Application Codename (used for logical grouping of disparate resources across regions, resource groups, environments or even across subscriptions or even across management groups)
- Resource Type (examples being Stg for storage, pip for public IP Address, VM for VirtualMachine, Vnet for virtual network, NSG for Network Security Groups, LB for Load balancer, AGW for Application Gateway, FD for Front Door etc etc)


I see in consulting with organisations across a wide range of organisation sizes that resource naming conventions when badly implemented (which is often the case many months after an org starts down the path with Azure) can and does add unnecessary friction in the development and deployment processes. When badly implemented or implemented months or years after the initial start with Azure this often leads to having to rewrite a number of internal governance practices, which then leads to having to apply a number of process fixes which can and do addd development/administration overheads. 

Examples of these include 
- allowed value RegEx's in templates
- organisational Azure Policies that either audit use of or enforce naming standards be followed
- loosely controlled wrapper scripts that expose a subset of available functionality to end developers but bake in these naming conventions
- loosely controlled wrapper templates that expose a subset of available functionality to end developers but bake in these naming conventions

All of the above is very often an overthought and done well after organisations have already got to grips with Azure and have many applications already in development and worse, applications already deployed to production with active clients making use of them. This alone makes it incredibly hard (& expensive) for organisations to retrofit to their existing environments as well as making it hard for forward fitting without increasing development frictions. It also does not help if/when organisations have to go through merger/acquistion processes as most resources cannot be renamed, and instead lead to costly & often unneccessary migrations to rectify when a cheaper and more sustainable action would be to make a simple metadata update would make most sense in many cases & in a select few a resource teardown and redeployment with a new unique name and apt metadata would be  vastly more sensible idea going forward.

**Comment by kilasuit** [comment]
Had some back and forths with others on this so to clarify a bit more

It **may** be an antipattern to use a naming convention, especially if an organisation **does not** already have one in place in existing environments.
Therefore, it **may** be better use of their time to spend that time on a properly tagging strategy and defining resource management processes, than to be bogged down with naming conventions for all resource types.

**Comment by JanetCThomas** [comment]
Thanks for your feedback. This seems to be a very specific rather than a “generalizable” antipattern. We would have to include a lot of assumption into the antipattern in terms of: How is deployment, stages and operations done. Therefore, it’s not an ideal fit for the category, as we want to point out obvious and quickly identifiable antipatterns, that people should not run into.  I will pass this on for consideration in the naming and tagging articles.  We appreciate the time and thought you put into providing feedback.  Thanks again!
