### ISSUE TITLE
The page Network topology and connectivity overview in Azure is not in the toc.yml

### ISSUE THREAD

**Issue by noopman** [MicrosoftDocs/cloud-adoption-framework#719]
The page [Network topology and connectivity overview in Azure](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/enterprise-scale/network-topology-and-connectivity.md) seems to have fallen out of the [toc.yml](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/toc.yml). There exists another .md file by the same name located in the landing zone part of the docs structure and not under enterprise scale. This second document by the same file name is in fact referenced in the toc (ready/landing-zone/design-area/network-topology-and-connectivity.md). Either this is duplicate work - but the content of the files is different - or there is something else amiss. The content of the page that does not show up in the toc is quite good. You should evaluate if it should or should not be there!

**Comment by TimShererWithAquent** [comment]
New article superseded the article. It was meant to be removed. Article removed and forwarding added.
