### ISSUE TITLE
Vague information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#720]
The section on Governance and protection disciplines is very general and does not provide any specific guidance. It would be helpful if this topic could be expanded to include actionable items that we should actually consider performing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fba3745-5608-1ff2-ec88-c2562c17788f
* Version Independent ID: ebd80d63-8036-0f83-7bec-a08400a596b6
* Content: [Security governance, risk, and compliance - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/secure/security-governance)
* Content Source: [docs/secure/security-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/secure/security-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **secure**
* GitHub Login: @NaomiOooo
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24769 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
