### ISSUE TITLE
Limit cross-tenant private endpoint connections recommendation is confusing

### ISSUE THREAD

**Issue by aschabus** [MicrosoftDocs/cloud-adoption-framework#722]
This guidance is a little bit confusing.
First it says that "This guidance shows you recommended configuration options to limit or prevent cross-tenant private endpoint connections." Then it explains the recommended configuration, followed by "However, this approach isn't recommended,".
So, is it a not recommended recommendation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49413641-0c1f-9862-9113-9b24f39b6dd9
* Version Independent ID: ed547d74-59ed-0f48-ba0d-825370d792a8
* Content: [Limit cross-tenant private endpoint connections in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections#next-steps)
* Content Source: [docs/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @marvinbuss
* Microsoft Alias: **mabuss**

**Comment by marvinbuss** [comment]
Hi @aschabus,
Can you please elaborate what is not clear for you in this article? Happy to help make this more precise. Maybe there is a misunderstanding here. Are you talking about this paragraph:
![image](https://user-images.githubusercontent.com/34542414/151589911-f7a4466b-6570-4d16-a906-78e869909e73.png)

Please note that we are saying here that you should not maintain a list of subscription IDs. We are NOT saying that the overall guidance should not be followed.

**Comment by aschabus** [comment]
Hi @marvinbuss,
yes I too. I think it's clear, but IMHO somehow confusing, because it recommends a way to solve it and afterwards it states that this isn't recommended. But to my understanding, this is the only way how to achieve it - because it doesn't make a difference if I need to change the parameter or the policy itself if the list of subscriptions is included in it?

**Comment by marvinbuss** [comment]
All we are saying in this paragraph is that we are NOT recommending you to change the policy definition above from `"notEquals": "[subscription().subscriptionId]"` to `"notIn": "[parameters('allowedSubscriptions')]"`.  Maintaining a list of subscriptions is not a great idea and just creates unnecessary management overhead.

Other than taht the policy in [this paragraph](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/limit-cross-tenant-private-endpoint-connections#mitigation-for-scenario-one) is still valid.

Is that more clear?

I think there is just a misunderstanding.

**Comment by aschabus** [comment]
Well, if I understand it right, "notEquals": "[subscription().subscriptionId]" only limits a cross-subscription connection, but not cross-tenant? But probably there isn't a better solution for this now?

**Comment by marvinbuss** [comment]
A subscription is always assigned to a single tenant. There is no way that a subscription can exist in two subscriptions. Therefore, if cross-subscription private endpoints are disabled, cross-tenant private endpoints are also disabled.

No, this is still the recommended approach. There is no tenant property on the private endpoint resource that we can filter on today.

**Comment by aschabus** [comment]
Yes, but I mean the following. When I've two subscriptions A und B in the same tenant, it blocks also a private link from A to B.
But I agree, so I think we can close this.
Thanks for your support.

**Comment by marvinbuss** [comment]
@WendyRing or @BrianBlanchard Can we please close this issue as mentioned here: https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/722#issuecomment-1024475090
