### ISSUE TITLE
Inconsistent terminology

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#723]
The first sentence states that this does not deploy a landing zone, the last sentence tells us what we should do after our landing zone has been completed. Please resolve this discrepancy, its confusing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194842ab-a899-bcaf-d22f-cef100d934f0
* Version Independent ID: 5e0941f7-d651-d08f-65f6-9c8f6d5df4c1
* Content: [Deploy a CAF Foundation blueprint in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/foundation-blueprint)
* Content Source: [docs/ready/landing-zone/foundation-blueprint.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/foundation-blueprint.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by ckittel** [comment]
Thank you @DeanGross for this observation.  That was indeed confusing and inconsistent.  I've pushed an update to help clarify for feature readers.  Should be live about this time tomorrow.
