### ISSUE TITLE
Cloud adoption framework appears to lack an Identity Perimeter perspective

### ISSUE THREAD

**Issue by elafnit** [MicrosoftDocs/cloud-adoption-framework#724]
Your cloud adoption frameworks is well thought through and provides solid advise, but seems to provide this for environments reliant on network perimeter constructs given the vms, network security groups, ip filtering and controls, etc. Do you have an equivalent perspective based on identity perimeter using only SaaS and Server-less consumption based resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
Hi @elafnit - Thank you so much for your feedback! So sorry for the delay. I hope you found something in the meantime. If not perhaps, this series of documents can help: https://learn.microsoft.com/en-us/azure/security/fundamentals/identity-management-overview.
