### ISSUE TITLE
Scenario 4 diagram update

### ISSUE THREAD

**Issue by prasannag6** [MicrosoftDocs/cloud-adoption-framework#726]
Diagram for Scenario 4 needs an update (it is the same as Scenario 3). Internet egress in scenario 4 (purple line) should be via On-prem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa825ef-dbe1-3147-2362-812e546b8501
* Version Independent ID: bec5cea5-7688-4911-09a2-504915e0cccd
* Content: [Enterprise-scale network topology and connectivity for Azure VMware Solution - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-network-topology-connectivity)
* Content Source: [docs/scenarios/azure-vmware/eslz-network-topology-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-network-topology-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @rodrigosantosms
* Microsoft Alias: **janet**

**Comment by skabou** [comment]
It appears this issue has been addressed. If this is not the case, please feel free to re-open.
