### ISSUE TITLE
Event Hub in Ingestion or Data integration?

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/cloud-adoption-framework#728]
Where (or which resource group) should an IoT/Event Hub that contains data from third party data source be put in (Ingestion or Data Integration) ?

Could you provide more detailed explanation on the documentation for the decision process for the above scenario and maybe with some clear examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a913402-aa8d-3ae7-2589-81d7bee16c09
* Version Independent ID: 5857fc40-82a4-18e2-e152-67841ca03f51
* Content: [Overview of the data management and analytics scenario architecture data landing zone in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone)
* Content Source: [docs/scenarios/data-management/architectures/data-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/data-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
We have updated the resource groups and architecture in an updated version to be released soon. This should help clean this confusion up.

#please-close

**Comment by olatoerstad** [comment]
Hi.
I also see some ambiguity, and epescially when it comes to data ingestion. 

The current model has ingestion capasity both in the "Data Integration"-layer, and the "Core Services"-layer. The resource groups of "Data Integration", and "Upload Ingest Storage" and "Ingest and Processing" respectively.

It seems there initially is made some sort of distinciton between ingestion in "Data Integration"where ingestion is handled with Data Fctory and/or Event Hubs - and ingestion as part of "Core Services" where a "Upload Ingest Storage"-rg is provided in the "Core Services"-layer to land the data in the landing zone, data to then be processed with Databricks in the "Ingest and Processing"-rg before it is stored in the "Data Lake Services"-rg. 

As it is now "Event Hubs" and "Data Factory" also is optional services in the "Ingest and Processing"-rg, witch makes it even more confusing.

Information and clarifiacation on differentiator between these types of ingestion would be appriciated.

I see the article was last updated the 19. january 2022 - any timeframe on when the new version with updated architecture will be released?
