### ISSUE TITLE
Add suffix resource abbreviation recommendation

### ISSUE THREAD

**Issue by rprashad** [MicrosoftDocs/cloud-adoption-framework#730]
Can we be inclusive of an abbreviations best practices that supports prefix and suffix formats?  

Currently resource abbreviation prefixes are recommended, but a resource abbreviation suffix is helpful in environments that use a common name as the prefix for all resource types within a given group.  Viewing the resource in list view or search via the Azure Console is usually done by name.
 
Refs:
https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@rprashad - This is a great suggestion. I know it's been over 2 years since you suggested it, but we are working on updating this page in the future and have taken your feedback into consideration. Thank you so much!

**Comment by stephen-sumner** [comment]
#please-close
