### ISSUE TITLE
Review Request - CAF Lifecycle Diagram

### ISSUE THREAD

**Issue by shekhag-zz** [MicrosoftDocs/cloud-adoption-framework#731]
Dear Team, 

The diagram in the section https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview#understand-the-lifecycle doesn't state the position of Organize phase. Could you please have a look and see if it makes sense to have Organize phase also in the diagram?

Thanks,
Shekhar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66744a3f-7ab3-80ae-4c76-639ee78601bf
* Version Independent ID: 081c5a49-8bd7-778e-da3f-11ad4667c4a2
* Content: [Microsoft Cloud Adoption Framework for Azure documentation - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview)
* Content Source: [docs/overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BryanLa** [comment]
@shekhag-zz - thanks for your inquiry, and our apologies for the long delay.

The lifecycle is designed such that the Organize phase can be optional for companies. For some customers, it’s a critical component of adoption, whereas others will not require organizational changes. The diagram reflects this, so as to not suggest that customers are expected to reorganize as part of Azure adoption. We hope this helps.

#please-close
