### ISSUE TITLE
Please add recommended abbreviation for Container Apps

### ISSUE THREAD

**Issue by thepaulmacca** [MicrosoftDocs/cloud-adoption-framework#732]
I'm guessing this would be `ca` or something?

**Comment by kbulte** [comment]
Will it be 'ca' or 'aca'? Some abbreviations add Azure prefix and others not.

They only ones I see with Azure prefix are:
- 'aks' for azure kubernetes service
- 'asa' for azure stream analytics
- 'adf' for azure data factory

**Comment by thepaulmacca** [comment]
Good question!

**Comment by cmendible** [comment]
I suggest 

* aca- for azure container app
* ace- for azure container app environment

**Comment by stephen-sumner** [comment]
@thepaulmacca - Thanks for your feedback! We've updated our guidance with `ctap`. It should see it shortly. Prefixing with Azure (a) does create some challenges so we've opted not to here. 

Best!
