### ISSUE TITLE
Cloud Adoption Framework - Number of Containers in The 3 Data Lakes

### ISSUE THREAD

**Issue by XavierGuerette** [MicrosoftDocs/cloud-adoption-framework#734]
Hi,

Would it be possible to know why Microsoft recommends one container per Data Lake (except for Data Lake 2)? Is it because there are a limited number of RBAC Assignments (2000) per Subscription/Data Landing Zone? If we have RBAC on Containers, it may consume a large portion of RBAC Assignments?

Thanks for letting us know!

Xavier
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174bef87-bea0-a095-3712-2c9dcf9e9388
* Version Independent ID: 9deb539b-93a8-a3d0-25c3-ebf65e5a4441
* Content: [Provision three Azure Data Lake Storage Gen2 accounts for each data landing zone - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-services)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-services.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-services.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
This guidance has been detailed out in the https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-overview#the-three-data-lakes. Further updates are being made

#please-close
