### ISSUE TITLE
Need a more compelling story...cost was the only reason that was given for Azure for mainframe migrations...I  am hopeful that we can do better than that on our public facing website

### ISSUE THREAD

**Issue by JaxKimberly** [MicrosoftDocs/cloud-adoption-framework#736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea5e85a-9ee6-ef62-5785-cdd343d0362d
* Version Independent ID: 504645bb-23cf-04a5-53fa-9e849754b8e4
* Content: [Mainframe migration overview - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/infrastructure/mainframe-migration/)
* Content Source: [docs/infrastructure/mainframe-migration/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/infrastructure/mainframe-migration/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @njray
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
#please-close
