### ISSUE TITLE
Mash networking model

### ISSUE THREAD

**Issue by dreampost** [MicrosoftDocs/cloud-adoption-framework#739]
[Enter feedback here]
This main page contains a reference architecture picture witch describes a mash networking model. Why not following the concept of hub and spoke, which is the foundation for an Enterprise-scale landing zone? I believe VNET peering between spokes (i.e. Data landing zones) should not be encouraged like that, instead should only be used in an exception. Spokes should primarily be able to communicate to each other only through a central firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?source=docs)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
We are part of the enterprise scale team and the full explanation of why we must do mesh is in  https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-network-considerations
