### ISSUE TITLE
Sample names for Storage accounts not consistent with the recommended prefix for the resource type  

### ISSUE THREAD

**Issue by rahulbhansali2111** [MicrosoftDocs/cloud-adoption-framework#74]
In the section 'Recommended-resource-type-prefixes', the recommended prefix for Azure Storage is 'stor'. However, the sample in the section https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#storage depicts an example that is not in agreement with the previous recommendation. 
Ex: st&lt;storage name&gt;&lt;###&gt;  --&gt; stnavigatordata001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging#storage)
* Content Source: [docs/ready/azure-best-practices/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Resolved
