### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by omurthy** [MicrosoftDocs/cloud-adoption-framework#747]
When I apply `vagrant up` ı get this error : Box 'StefanScherer/windows_10' could not be found. " 

So I added this config below in vagrantfile and I solved this problem.
`config.vm.box_download_insecure = true`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e814f9-cb52-3c58-66e8-65c79a36ddcc
* Version Independent ID: 74038063-025e-0518-0b1d-3effc8c6aaa2
* Content: [Deploy a local Ubuntu server hosted with Vagrant and connect it to Azure Arc - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/local-vagrant-ubuntu?/azure/cloud-adoption-framework/_bread/toc.json&toc=/azure/cloud-adoption-framework/scenarios/hybrid/toc.json)
* Content Source: [docs/manage/hybrid/server/best-practices/local-vagrant-ubuntu.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/manage/hybrid/server/best-practices/local-vagrant-ubuntu.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
I believe this is for the Windows instructions though the Ubuntu link was provided.

Adding that config will skip SSL validation and should not be necessary.

If assistance is still needed, please re-open with additional details.
