### ISSUE TITLE
Inconsistent language

### ISSUE THREAD

**Issue by pticku** [MicrosoftDocs/cloud-adoption-framework#750]
Suggest using consistent language:
1. Please use either "operating model" or "operations" when referring to an organisation's IT/Data operations team.
2. Please use complete name i.e. azure data management and analytics scenario when mentioning the scenario. Inconsistent use e.g. "data scenario", "data management and analytics", "data management and analytics strategies".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
Fixed in 
commit 752ea25099d4b2ef9183c052acc7b2ab85a9be25 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Wed Mar 2 14:12:18 2022 +0100

    Fixing Inconsistent language  issue #750

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3059

**Comment by simonlid** [comment]
#please-close
