### ISSUE TITLE
Request for application decommissioning guidance.

### ISSUE THREAD

**Issue by chrisjeffreyuk** [MicrosoftDocs/cloud-adoption-framework#754]
Several partner engagements have asked for some guidance or process for removal of a service from on-prem. The idea being that the docs cover areas such as the 5Rs and WAF, but do not offer much guidance on how an application can be reviewed for all of its connections, reliance and interactions with other on-prem applications, in order to ensure a safe and controlled decommissioning event. What would be great to have is a high level set of considerations to work with for this subject, that the partners could then integrate into their offerings, or use to reference as a best practice guideline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3503b34b-102b-18b7-de00-a485c9a24d81
* Version Independent ID: 2f35f885-7c4d-0eb7-bf7c-1c29c27d399b
* Content: [Cloud rationalization - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/digital-estate/5-rs-of-rationalization)
* Content Source: [docs/digital-estate/5-rs-of-rationalization.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/digital-estate/5-rs-of-rationalization.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @chrisjeffreyuk. 
We'll close the issue here and keep track of this as a new internal backlog item for review.
