### ISSUE TITLE
enlarge of 2nd image doesn't work, points to enlarge of first image

### ISSUE THREAD

**Issue by sgrass-valhalla** [MicrosoftDocs/cloud-adoption-framework#755]
It points to here: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/images/data-mesh-plane.png#lightbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb298292-f7db-3e03-adac-1df0ce571786
* Version Independent ID: bb298292-f7db-3e03-adac-1df0ce571786
* Content: [Financial institution scenario for data mesh - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/reference-architecture-data-mesh)
* Content Source: [docs/scenarios/data-management/architectures/reference-architecture-data-mesh.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/reference-architecture-data-mesh.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pietheinstrengholt
* Microsoft Alias: **pstrengholt**

**Comment by mboswell** [comment]
fixed

**Comment by mboswell** [comment]
#please-close
