### ISSUE TITLE
Data Mesh deployable template

### ISSUE THREAD

**Issue by ryancrawcour** [MicrosoftDocs/cloud-adoption-framework#756]
it would be great if we had a 1-stop deployable template for a data mesh here in the deployable template section. 
it's great that we have batch, streaming etc. but let's take it 1 step further and give someone a "data mesh in a box" if you will. 
i'd be happy to work on this if needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dc556ba-8a6c-36e5-3739-fc2b99ce9f1e
* Version Independent ID: 5dc556ba-8a6c-36e5-3739-fc2b99ce9f1e
* Content: [Deployment templates for data management and analytics scenario deployments - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/deployment-templates?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/architectures/deployment-templates.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/deployment-templates.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
@mboswell Not sure that we can adress this comment,  as a data mesh will essentially be a combination of the different zone's and some of the templates. What do you think?

**Comment by mboswell** [comment]
@simonlid - agree. @ryancrawcour - we will focus on putting a tutorial instead which will allow someone to build up a data mesh.

**Comment by mboswell** [comment]
#please-close
