### ISSUE TITLE
Add some graphics to this page 

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#758]
This page is too text heavy. Please add some graphics to it so the reader can better relate to the text.
Specifically this part: https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1#data-management-and-analytics-evaluation
where we have this nice explanation of the evolution of the data platform would fit well.
![image](https://user-images.githubusercontent.com/15715677/156316043-7bae1076-4d9b-4fdc-bf3e-950271e012db.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a4c609-db68-7d7d-0229-fec630de559d
* Version Independent ID: 29423660-00f2-b43b-c205-a0a57d9d3098
* Content: [What is data governance? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1#data-management-and-analytics-evaluation)
* Content Source: [docs/scenarios/data-management/overview-data-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/overview-data-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
@ralphke Agree here that this type of visual could be good, will try and find out if the visual that you linked is something that we own or if it was borrowed from somewhere and we would need to create our own

**Comment by simonlid** [comment]
@ralphke unfortunately that visual cannot be used so we would need to create something ourselves, right now I will not prioritize that since we do have a lot of other issues that needs to be fixed

**Comment by simonlid** [comment]
#please-close
