### ISSUE TITLE
Trusted Data add images and videos as data source/apply data quality early on.

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#759]
Within the section Trusted data, I am missing the reference to images and videos, which are commonly one of the triggers to use a data lake approach.
This will resonate better with the audience as the term unstructured data.
Also the principal to enforce data quality at the source, as much as possible, should also be outlined as a key concept for improving data quality. Specifically pointing out that the removal of "bad" data after it has entered the processing layer is much more complex than applying quality Gards early in the ingestion phase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a4c609-db68-7d7d-0229-fec630de559d
* Version Independent ID: 29423660-00f2-b43b-c205-a0a57d9d3098
* Content: [What is data governance? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1#data-management-and-analytics-evaluation)
* Content Source: [docs/scenarios/data-management/overview-data-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/overview-data-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3059

**Comment by simonlid** [comment]
#please-close
