### ISSUE TITLE
Missing a topic on APIs to data

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#760]
Within the operationalize-data-management section, I do miss the outlining of providing APIs for data consumption in a well documented and easy to find way. The data and services providing the data might change over time, but with an standardized API to access the data assets these changes in the data producers can be abstracted away.
https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1#operationalize-data-management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a648bf-51ec-f9da-6c4f-d721616fcdb1
* Version Independent ID: 7bdb8bfa-289e-bee5-bc45-a0a6fb78d5ff
* Content: [Integrate data management and analytics into your cloud adoption strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
APIs to data is just one way of delivering data assets in a data mesh. While it certainly has the benefits mentioned it is not a requirement for data mesh. I am not sure that we should add it in the document here, we do have a section on it I believe. @mboswell what do you think?

**Comment by mboswell** [comment]
Agree - Fabric is API based but mesh is about using the correct tech for what you need. We can update the reference use case to highlight the access methods.

#assign @pietheinstrengholt

**Comment by mboswell** [comment]
@pietheinstrengholt please can review and agree with @simonlid/@ralphke  to keep open or close.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24256 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
