### ISSUE TITLE
Data ingestion missing an APP to accomplish the task of meta data driven ingest

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#761]
The section https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1#data-ingestion is focusing on a meta data driven approach to ingest data. But how should that be accomplished? It should be mentioned that a web application need to be developed so end users can enter the relevant assets and descriptions of the data before it is loaded via a data pipeline. Also the freshness of the data need to be clearly exposed to end users, so they know what they are looking at. This information has to be pulled thru from the ingest to the final dashboard or wherever the data lands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a648bf-51ec-f9da-6c4f-d721616fcdb1
* Version Independent ID: 7bdb8bfa-289e-bee5-bc45-a0a6fb78d5ff
* Content: [Integrate data management and analytics into your cloud adoption strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
@ralphke this is mentioned in https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/automated-ingestion-pattern?branch=collab-data-mesh-v1 have a look at that part and see what needs to be added.

**Comment by mboswell** [comment]
assign @ralphke

**Comment by mboswell** [comment]
assign: @ralphke 

please can you look @ralphke  at the link @simonlid has suggested

**Comment by mboswell** [comment]
#label:"data management and analytics"

**Comment by ralphke** [comment]
@mboswell @simonlid yes, the above link describes what is needed for such an application. Would be great if we could provide a basic template for such an app via a Github repro.

**Comment by mboswell** [comment]
#please-close
