### ISSUE TITLE
Roles and responsibilities high level picture

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#763]
Within the final section a high-level overview of the roles and responsibilities of the team might be valuable for getting the context across. https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1#foster-commitment-communication-and-engagement
I could imagine that this picture might help here:

![image](https://user-images.githubusercontent.com/15715677/156325835-e18fbd61-1bf0-4c43-b797-e8ddb3063e7a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a648bf-51ec-f9da-6c4f-d721616fcdb1
* Version Independent ID: 7bdb8bfa-289e-bee5-bc45-a0a6fb78d5ff
* Content: [Integrate data management and analytics into your cloud adoption strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
Have a look at the following section, and add what we need to add, we are adding some of the stuff from MS Digital as well:

https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/organize?branch=collab-data-mesh-v1

**Comment by mboswell** [comment]
#assign: @mboswell

**Comment by mboswell** [comment]
We have a drawing like this but needs to be tidied up before it is ready for public consumption.

#label:"data management and analytics"

**Comment by ralphke** [comment]
@simonlid I think this [article ](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/organize-roles-and-teams?branch=collab-data-mesh-v1) describes it quite well, which is indeed linked with the initial content. Nevertheless, I think a picture here would also be beneficial for the reader.

**Comment by hallihan** [comment]
@ralphke and @mboswell - It looks like this issues was reported on an in-progress collaboration branch. If this was not addressed prior to publication of that branch, can you open a new issue from the published doc?
