### ISSUE TITLE
Strategic Initiatives need measures

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#764]
Within the section https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/plan?branch=collab-data-mesh-v1#strategic-initiatives
the outlining of the need for measures is missing. Without proper KPI's which measure the impact these strategic initiative will be a paper tiger or wishful thinking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6556a27-e67b-2e14-2687-3bd0925e4260
* Version Independent ID: 347b8803-e239-7258-9e57-5c965b7c2d72
* Content: [Develop a plan for data management and analytics - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/plan?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/plan.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/plan.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pratimdas
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
@ralphke In the strategy work you typically do not want to create KPI's since this is just a prioritizing effort of different strategies and their value. Later I would agree that KPI's need to be defined but typically not in this step.

**Comment by mboswell** [comment]
@ralphke - agree wtih @simonlid and will close for now.
#please-close

**Comment by mboswell** [comment]
#label:"data management and analytics"
