### ISSUE TITLE
Operational Excellence Measurement?

### ISSUE THREAD

**Issue by ralphke** [MicrosoftDocs/cloud-adoption-framework#765]
In the section https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/ready?branch=collab-data-mesh-v1#operational-excellence
The topic how to measure what is excellent and what not should be added. For example the request to and new data should be accomplished in less than a day as goal, versus a reality check how long it actually takes. These numbers should be aggregated in an operational dashboard so success and failure is clearly outlined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c297777-3d19-9c15-b14b-3492ed3c928b
* Version Independent ID: 4973b799-c6bf-dae0-854d-c467631b4d1e
* Content: [Review your environment for Azure landing zones - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/ready?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
@ralphke Agree that this could be a good addition but maybe not to this section could you please open an issue against https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/organize-data-operations?branch=collab-data-mesh-v1 and close this one?

**Comment by mboswell** [comment]
#assign @mboswell

**Comment by mboswell** [comment]
#label:"data management and analytics"

**Comment by mboswell** [comment]
@ralphke we have this covered in https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/manage-observability?branch=collab-data-mesh-v1. 

Please take a look and if it is needs more, please reopen this PR.

**Comment by mboswell** [comment]
#please-close
