### ISSUE TITLE
Outdated page

### ISSUE THREAD

**Issue by gbeaud** [MicrosoftDocs/cloud-adoption-framework#766]
[Enter feedback here]

I believe some of the technologies promoted by this page are somehow superseded/outdated:

- Packer is now available with Azure Image Builder
- GitHub Actions can also be used to deploy images in DevOps mode
- App-V is deprecated, now replaced by MSIX App Attach
- FSLogix app masking is - in my understanding - not the Microsoft first choice for app delivery anymore
- MEM is one of the mainstream manner to deploy apps to AVD hosts and is not mentioned in the article
- Bicep is now somehow superseding the usage of ARM templates

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516d6288-2c04-3934-04a9-ca95dca66d3d
* Version Independent ID: 049eeabb-25b0-9d96-7bba-1aff3f7e5015
* Content: [Platform automation and DevOps for Azure Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-platform-automation-and-devops)
* Content Source: [docs/scenarios/wvd/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24255 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
