### ISSUE TITLE
Cosmos DB for metadata graph

### ISSUE THREAD

**Issue by kbhatiaGIT** [MicrosoftDocs/cloud-adoption-framework#767]
Using CosmosDB to build the metadata graph isn't explained in sufficient detail. Isn't the graph for just holding the metadata and not the data itself?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5440fc-f829-4e1c-107c-f8645659b04a
* Version Independent ID: cc5440fc-f829-4e1c-107c-f8645659b04a
* Content: [metadata standards and data marketplace - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-metadata-standards?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern-metadata-standards.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern-metadata-standards.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pietheinstrengholt
* Microsoft Alias: **pstrengholt**

**Comment by simonlid** [comment]
commit 66eb58ecc83aa884ee24b8719d439e1bb36edf43 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Thu Mar 3 19:01:06 2022 +0100

    Added some clarifications to adress #767

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3059

**Comment by simonlid** [comment]
@kbhatiaGIT I added some comments on this, I agree that we could go in and describe it in more detail but I am not sure that this is something that we will do as part of this effort @mboswell, @pietheinstrengholt what do you think?

**Comment by mboswell** [comment]
#please-close
