### ISSUE TITLE
fully "meshed" as recommeded? 

### ISSUE THREAD

**Issue by angusforeman** [MicrosoftDocs/cloud-adoption-framework#768]
Respecting that the goal of this update is to support the implementation of Mesh aligned architectures, is Microsoft's recommended position (e.g. the one that the majority of our customer should adopt) the one that assumes the most sophisticated operational model and most organisation maturity? Unless I am misunderstanding this recommendation, its listed here before any of the organisational topics, and hence maybe read as a correct technical approach for all situations, independent of an organisations actual operational or organisation ability to implement & support it in a production scenario. 

Put another way, we know that most customers are "on a journey" towards a mesh like implementation, but that most are looking to **grow** their business aligned data services, but are not yet at the stage where cross business unit (BU)data sharing is needed between every BU. 

I would suggest we need a "modifier" to say this approach is recommened for customers who have a clearly aligned need and are operationally ready. For others we would suggest the mesh is created based on business demand 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49839f2d-87d5-2cf3-3ed5-0fa1053c54ad
* Version Independent ID: 49839f2d-87d5-2cf3-3ed5-0fa1053c54ad
* Content: [Network architecture considerations - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-network-considerations?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/eslz-network-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/eslz-network-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @marvinbuss
* Microsoft Alias: **mabuss**

**Comment by simonlid** [comment]
@mboswell is going to split the networking considerations into several pages, Mike can you also address this comment during that change?

**Comment by mboswell** [comment]
Have added on every page...

[!IMPORTANT]
> Whilst this and the other documents in the networking section outline cross business units sharing data. Microsoft recognize that this might not be your initial strategy and that you need to start at a base level before enabling this. Therefore, are you read this connectivity section, design your networking that you can eventually implement our recommended setup between landing zones and focus on making sure you have the data management landing zones directly connected to the landing zones for governance.

**Comment by marvinbuss** [comment]
> Respecting that the goal of this update is to support the implementation of Mesh aligned architectures, is Microsoft's recommended position (e.g. the one that the majority of our customer should adopt) the one that assumes the most sophisticated operational model and most organisation maturity? Unless I am misunderstanding this recommendation, its listed here before any of the organisational topics, and hence maybe read as a correct technical approach for all situations, independent of an organisations actual operational or organisation ability to implement & support it in a production scenario.
> 
> Put another way, we know that most customers are "on a journey" towards a mesh like implementation, but that most are looking to **grow** their business aligned data services, but are not yet at the stage where cross business unit (BU)data sharing is needed between every BU.
> 
> ## I would suggest we need a "modifier" to say this approach is recommened for customers who have a clearly aligned need and are operationally ready. For others we would suggest the mesh is created based on business demand
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 49839f2d-87d5-2cf3-3ed5-0fa1053c54ad
> * Version Independent ID: 49839f2d-87d5-2cf3-3ed5-0fa1053c54ad
> * Content: [Network architecture considerations - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/eslz-network-considerations?branch=collab-data-mesh-v1)
> * Content Source: [docs/scenarios/data-management/eslz-network-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/eslz-network-considerations.md)
> * Service: **cloud-adoption-framework**
> * Sub-service: **scenario**
> * GitHub Login: @marvinbuss
> * Microsoft Alias: **mabuss**

Thanks @angusforeman for the feedback. This update is not changing our recommendation. The recommendation always was and still is a meshed network architecture and many customers out there are following that guidance. The article includes guidance on how to restrict traffic between landing zones if this is required in certain scenarios.
The guidance has not changed and was in place with or without data mesh in mind.
I would personally not change anything wrt the guidance.

**Comment by mboswell** [comment]
#please-close. fixed
