### ISSUE TITLE
Should we position the Centralised <-> Fully Mesh spectrum early on - e.g. in the strategy section

### ISSUE THREAD

**Issue by angusforeman** [MicrosoftDocs/cloud-adoption-framework#770]
One of the key points re the Mesh model as describe by ThoughtWorks is that it represents a "desired state". This is useful as it provides a guiding star for orgs looking to drive towards being more data driven. It however also represents a practical challenge as most organisations cannot simply jump to "the end state" as practical considerations like operational readiness , business alignment (including culture and trust) and new team models & skills all need develop from their current state.

Reflecting that fact, does this guidance need practical guidance to help the customer understand that MSFT's tech aligns to Mesh, but  that we recommend the customer take a staged approach to adopting based on current state. This is alluded to in terms of the number of landing zones, but that text doesnt reference the fact that Mesh alignment pre-supposes multiple highly meshed DLZs. So the audience risks being confused 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a648bf-51ec-f9da-6c4f-d721616fcdb1
* Version Independent ID: 7bdb8bfa-289e-bee5-bc45-a0a6fb78d5ff
* Content: [Integrate data management and analytics into your cloud adoption strategy - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/strategy?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/strategy.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/strategy.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
commit f85075784a249c83f0a3b7b449a3427d53b162ad (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 12:10:24 2022 +0100

    Fixing issue #770

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
@angusforeman I added a section under Deliver value that tries to adress your comments

**Comment by mboswell** [comment]
#please-close
