### ISSUE TITLE
Does this page need a reference to Mesh?

### ISSUE THREAD

**Issue by angusforeman** [MicrosoftDocs/cloud-adoption-framework#771]
Given the importance of data sharing to the Mesh approach, does this page need some link or reference to the Mesh model implementation of data sharing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8164dd01-029b-1782-473a-5e674ea16a1e
* Version Independent ID: 3d7bc3c5-2a3c-baea-61d3-6539b59d00b0
* Content: [Data sharing agreements in data management and analytics - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-data-sharing-agreements?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern-data-sharing-agreements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern-data-sharing-agreements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pietheinstrengholt
* Microsoft Alias: **pstrengholt**

**Comment by simonlid** [comment]
@angusforeman I rewrote the sharing contracts in this page have a look at it https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/blob/collab-data-mesh-v1/docs/scenarios/data-management/architectures/data-contracts.md to see if this address your concerns

**Comment by mboswell** [comment]
#label:"data management and analytics"
#please-close
