### ISSUE TITLE
Data Mesh is presented as an alternative tech architecture... 

### ISSUE THREAD

**Issue by angusforeman** [MicrosoftDocs/cloud-adoption-framework#772]
... (which we know it isnt). Can this article clearly state something like 

- the benefits from a data mesh approach are achieved through the adoption of both the "business architecture" (e.g. multi disciplinary teams who both publish and consume data products) and the "technical architecture". 
- data mesh approaches drive organisational change as well as technical change, and to be successful both aspects must be managed in an aligned manner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121c12b1-adf4-b711-e8e7-14ccc3ecfdd6
* Version Independent ID: 121c12b1-adf4-b711-e8e7-14ccc3ecfdd6
* Content: [What is a data mesh? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/what-is-data-mesh?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/architectures/what-is-data-mesh.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/what-is-data-mesh.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @simonlid
* Microsoft Alias: **simonlid**

**Comment by simonlid** [comment]
Fixed in 
commit 5d8e0f9a008a516faf8400a610be310d4d6f56e6 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 13:25:57 2022 +0100

    Fixing issue #772

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
