### ISSUE TITLE
Enhance the baseline policy page to reference Azure Security Baseline

### ISSUE THREAD

**Issue by phduf** [MicrosoftDocs/cloud-adoption-framework#773]
It would be great to have this page reference back to the appropriate Azure Security Benchmark standards as the examples, to link it into the next step of implementation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa6983f-7085-55a2-e017-927a2b658208
* Version Independent ID: 4bf591ee-5667-cd9c-084b-0e739dbae94b
* Content: [Security Baseline sample policy statements - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/security-baseline/policy-statements)
* Content Source: [docs/govern/security-baseline/policy-statements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/security-baseline/policy-statements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24456 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
