### ISSUE TITLE
List formatting is broken for "Other Design Considerations"

### ISSUE THREAD

**Issue by fabragaMS** [MicrosoftDocs/cloud-adoption-framework#774]
[Enter feedback here]

https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/ready?branch=collab-data-mesh-v1#other-design-considerations

List formatting is broken for "Other Design Considerations".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c297777-3d19-9c15-b14b-3492ed3c928b
* Version Independent ID: 4973b799-c6bf-dae0-854d-c467631b4d1e
* Content: [Review your environment for Azure landing zones - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/ready?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
commit fb559a60aa13ed4a97ff1d1060759a13e50dcfa2 (HEAD -> collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 13:30:02 2022 +0100

    Fixed issue #774

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
