### ISSUE TITLE
Including GraphQL as an alternative to REST

### ISSUE THREAD

**Issue by ydaponte** [MicrosoftDocs/cloud-adoption-framework#775]
GraphQL is increasing  popularity at the moment, and while is not a replacement for REST it can provide some benefits for specific requirements/scenarios.
It would be beneficial perhaps to include it as an alternative guidance in the diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1a2d6f-811f-17ba-1c63-c0eceeb7cd2a
* Version Independent ID: 0e1a2d6f-811f-17ba-1c63-c0eceeb7cd2a
* Content: [Platform automation and DevOps for a data management and analytics enterprise-scale scenario - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/manage-platform-automation-and-devops?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/manage-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/manage-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by simonlid** [comment]
Yes GraphQL could be an alternative but I do not think that we should add additional API's and clutter the diagram @mboswell what do you think?

**Comment by mboswell** [comment]
@simonlid agree. It is an example and we cannot cover everything.

#please-close
