### ISSUE TITLE
Link to  "Azure Well-Architected Framework" is retrieving Content Not Found

### ISSUE THREAD

**Issue by ydaponte** [MicrosoftDocs/cloud-adoption-framework#776]
The link to Link to  "Azure Well-Architected Framework": https://review.docs.microsoft.com/en-us/azure/architecture/framework/?branch=collab-data-mesh-v1 is retrieving Content Not Found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f111fa38-1ddb-b7bc-397c-1620171bf283
* Version Independent ID: 0470b643-0da7-b813-39e9-6a5c5941decc
* Content: [The Azure Well-Architected Framework for data workloads - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/well-architected-framework?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/well-architected-framework.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/well-architected-framework.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pratimdas
* Microsoft Alias: **prda**

**Comment by simonlid** [comment]
This will be fixed automatically when the content is promoted to production. It is broken in the review platform.

**Comment by simonlid** [comment]
#please-close
