### ISSUE TITLE
Data Marketplace for external consumers

### ISSUE THREAD

**Issue by ydaponte** [MicrosoftDocs/cloud-adoption-framework#777]
Is there any specific guidance we could add in regards the Data Marketplace for external consumption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a77c23b-62d6-48a6-c570-409c73fce00f
* Version Independent ID: 5a77c23b-62d6-48a6-c570-409c73fce00f
* Content: [Data marketplace - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-mesh-data-marketplace?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/architectures/data-mesh-data-marketplace.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/data-mesh-data-marketplace.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @pietheinstrengholt
* Microsoft Alias: **pstrengholt**

**Comment by simonlid** [comment]
Fixed in 
commit c9f55af5228366f82aa49151eecbc801d8654643 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 13:47:59 2022 +0100

    Fixed issue #777

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
