### ISSUE TITLE
Typo "Data Democratize"

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#778]
Suggest "Data Democratize by making data and insights accessible to the average end user (subject to access privileges)."
should be "Data democratization by making data and insights accessible to the average end user (subject to access privileges)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
Fixed in one of the earlier fixes

**Comment by simonlid** [comment]
#please-close
