### ISSUE TITLE
Reason why DMZ and DLZ accelerates deployment

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#779]
"Data management landing zone and data landing zone architectures help accelerate deployment for many common data management and analytics solutions. The guidance can be adopted for lakehouse and data mesh architectures. It highlights the capabilities required for a well-governed analytics platform which can scale according to your requirements."

Suggest we add a line or two about why the architectures accelerate deployment in this introduction. Maybe something like:
"Data management landing zone and data landing zone architectures help accelerate deployment for many common data management and analytics solutions by standardising best practice and minimising deployment bottlenecks for development teams.

The guidance can be adopted for lakehouse and data mesh architectures. It highlights the capabilities required for a well-governed analytics platform which can scale according to your requirements."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
commit 6eb605db7334e7d11292248bb29032bdd025f821 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 13:54:46 2022 +0100

    Fixed issue #779

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
