### ISSUE TITLE
Lots of missing items

### ISSUE THREAD

**Issue by RP-RISING-STAR** [MicrosoftDocs/cloud-adoption-framework#78]
There are lots of Azure resources types not present in the table:

1. API Management
2. Application Insights
3. App Service Plan
4. Log Analytics Workspace
5. Service Fabric Cluster
6. Virtual Machines Availability Sets
7. Virtual Machines Scale Sets

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
