### ISSUE TITLE
Typo: avoid - avoiding

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#780]
Suggested edit
from
You might be familiar with the dreaded data swamp analogy. Governance and organization are key to avoid this situation. When you create a solid foundation, it will increase the chance of sustained data lake success and business value.
to
You might be familiar with the dreaded data swamp analogy. Governance and organization are key to avoiding this situation. When you create a solid foundation, it will increase the chance of sustained data lake success and business value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b406c0d4-b63d-60c5-2d73-3dc2e416950d
* Version Independent ID: cc1d6520-2fe6-8044-ba7b-bac145887e62
* Content: [Overview of Azure Data Lake Storage for the data management and analytics scenario - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-overview?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
