### ISSUE TITLE
Section not clear regards HNS Pt 1

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#781]
1. This section has a few references to generic storage account capability and does not restrict itselft to ADLS G2 HNS capability as described here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-feature-support-in-storage-accounts#standard-general-purpose-v2-accounts

E.g.
- Transition blobs, blob versions, and blob snapshots to a cooler storage tier to optimize for cost. This transition is useful if the blobs are not accessed or modified for a period of time. For example, hot to cool, hot to archive, or cool to archive. [Versioning not supported for HNS]

-Delete blobs, blob versions, and blob snapshots at the end of their lifecycle.[Versioning not supported for HNS]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef64508f-c861-4eed-0fa5-67b2655f0b37
* Version Independent ID: ec6447bb-4173-45e3-df8e-31448bfdae99
* Content: [Key considerations for Azure Data Lake Storage - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-key-considerations?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-key-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-key-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
Fixed in 
commit 7fda9e7443d43b17c8d45fcb31d2db9264b703e7 (HEAD -> collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 14:17:23 2022 +0100

    Fixed issue #781

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
