### ISSUE TITLE
Clarifying the Overview

### ISSUE THREAD

**Issue by whhender** [MicrosoftDocs/cloud-adoption-framework#783]
**For this section:**

_Creating data governance classification schemes such as the examples shown in [Data confidentiality classification scheme](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-requirements#data-confidentiality-classification-scheme) and [data retention classification scheme](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-requirements#data-retention-classification-scheme) provide different levels of governance classification. These schemas must be defined in the data catalog. At this point, policies and rules can be created in the data catalog and associated with different levels of governance classification._

Is "data governance classification" industry standard? If not, can we define data governance classification at the start of this paragraph?

**For this section:**

_It should then be possible to label (or tag) data attributes in the business glossary with confidentiality and retention classes to specify how to govern it. And because the data catalog already knows the mappings of physical data attributes in different data stores to attributes in business glossary, then labeling an attribute in the glossary automatically determines how to govern data mapped to it in underlying data stores._ 

Can we give an example of a data attribute here, to solidify what we're talking about? Is a data attribute a specific piece of data like a column in a csv, or is it metadata, like the name of the column?

**For this section:**

_Master data entities are critical because this data is so widely shared. It's also frequently associated with documents. For example, a customer and an invoice, a supplier and a contract, an asset and an operating manual. That's why master data values, such as supplier name, can be used to tag related documents to ensure that relationships between structured and unstructured data is preserved._

What are master data entities? Can we define that or provide a link for more information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebc90107-5f71-51f9-8c7a-3c8ce1f221d2
* Version Independent ID: 7b46c90c-d251-d709-6046-591fbcc11e3e
* Content: [Data summary and maturity model for Azure - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
#label:"data management and analytics"

**Comment by mboswell** [comment]
#assign: @pietheinstrengholt

**Comment by mboswell** [comment]
#assign: @mboswell

**Comment by mboswell** [comment]
Have tried to tidy up this section.

**Comment by mboswell** [comment]
#please-close
