### ISSUE TITLE
Shorten the TOC label

### ISSUE THREAD

**Issue by SnehaGunda** [MicrosoftDocs/cloud-adoption-framework#784]
I would shorten the "Azure landing zones for data management and analytics" to "Azure landing zones" because the docs already belong to the "data management and analytics" category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c297777-3d19-9c15-b14b-3492ed3c928b
* Version Independent ID: 4973b799-c6bf-dae0-854d-c467631b4d1e
* Content: [Review your environment for Azure landing zones - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/ready?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
#please-close
