### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by whhender** [MicrosoftDocs/cloud-adoption-framework#785]
Discover and identify what data you have, what it means. And where it's stored

Should be: Discover and identify what data you have, what it means, and where it's stored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e02e4b64-80ca-b9fc-ffde-00c7a8ed7c91
* Version Independent ID: 49f1b43d-1b69-2d69-583c-efd1899a40d3
* Content: [Requirements for governing data - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-requirements?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern-requirements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern-requirements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
commit a3aee222eb9af36d4c110d9b7c6a38ab8f93be77 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 14:52:39 2022 +0100

    Fixed #785

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070
