### ISSUE TITLE
Azure Purview Policies

### ISSUE THREAD

**Issue by whhender** [MicrosoftDocs/cloud-adoption-framework#789]
For Azure Purview there is also a tutorial for creating access policies across entire resource groups/subscriptions:
https://docs.microsoft.com/en-us/azure/purview/tutorial-data-owner-policies-resource-group

This may also be useful for your customers at scale. (Though because policies are still in preview, it does still only onboard ADLS Gen 2 and Storage accounts in the resource groups/subscriptions.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2074402-c919-d3fb-cda3-ddbb6ed2ffee
* Version Independent ID: c75fecc6-7f35-44d6-65ff-d958c833f453
* Content: [Provision security for data management and analytics in Azure - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/security-provisioning?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/security-provisioning.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/security-provisioning.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
commit 78567568f1b890c6ae69a7584b01203ccb5f2f71 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 15:53:25 2022 +0100

    Fix issue #789

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
