### ISSUE TITLE
Additional Information

### ISSUE THREAD

**Issue by whhender** [MicrosoftDocs/cloud-adoption-framework#790]
For Phase 1 -- Azure Purview also has a 'Pricing Guidelines' article that explains Azure Purview pricing in more detail: https://docs.microsoft.com/en-us/azure/purview/concept-guidelines-pricing

For Phase 2 & 3 -- there are Azure Purview articles that could be linked for many of the validation steps in these phases. I'd be happy to help link them if that's something you think would be useful, but the number of links could potentially be distracting.

For Phase 3 -- the collections article you have linked does provide information on how to manage collections, but we also now have a best practices article that covers potential collections articles based on your data estate:
https://review.docs.microsoft.com/en-us/azure/purview/concept-best-practices-collections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80001cb2-79da-3d98-5872-8fa693e4d514
* Version Independent ID: 887424be-b915-cb8f-6805-00d45d1961fc
* Content: [Azure Purview readiness checklist for the data management and analytics enterprise-scale scenario - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/purview-checklist?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/purview-checklist.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/purview-checklist.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @Zeinam
* Microsoft Alias: **zeinam**

**Comment by simonlid** [comment]
Fixed in 
commit 745482828572bfd96515c1374fb4a05535b41e7a (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 16:15:26 2022 +0100

    Fixed issue #790

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
