### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by whhender** [MicrosoftDocs/cloud-adoption-framework#791]
This section:
A managed storage account and a managed Event Hubs namespace are deployed inside this resource group and are used to ingest the metadata **because of scans.**

Could/should be something more like: A managed storage account and a managed Event Hubs namespace are deployed inside this resource group and are used to ingest data asset metadata collected through scans.

In the Private Endpoint section it also may be useful to explain that the Azure Purview Studio is the management UI for Azure Purview that allows you to access and manage Azure Purview from the browser. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51517cd-a9d1-348f-8033-36c1a1f8b94e
* Version Independent ID: e21b0528-df55-455d-1ac3-5c17f42a0f2e
* Content: [Azure Purview deployment best practices for data management and analytics scenario - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/purview-deployment?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/purview-deployment.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/purview-deployment.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @Zeinam
* Microsoft Alias: **zeinam**

**Comment by simonlid** [comment]
Fixed in 
commit adf25ed9fbec37dc523cf21b8deb9278debbab70 (HEAD -> collab-data-mesh-v1, origin/collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 16:20:59 2022 +0100

    Fix issue #791

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
