### ISSUE TITLE
title headline

### ISSUE THREAD

**Issue by pticku** [MicrosoftDocs/cloud-adoption-framework#792]
[Very well written! Suggest changing the title to either "introduction" or "overview". The title says both introduction and overview]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a4c609-db68-7d7d-0229-fec630de559d
* Version Independent ID: 29423660-00f2-b43b-c205-a0a57d9d3098
* Content: [What is data governance? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/overview-data-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/overview-data-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
Fixed in 
commit acd6e8e6f7d07bd84799718c4c8131f5eef7c3c3 (HEAD -> collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 17:22:22 2022 +0100

    Fixed issue #792

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by mboswell** [comment]
#please-close
