### ISSUE TITLE
Data Management and Analytics Scenario should be in Title Case

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/cloud-adoption-framework#795]
Every reference of the DMAS should ideally be in title case, both in headers as well as in regular text, as it is a specific term.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
@mboswell This is something that you can address when you do search and replace for the term

**Comment by mboswell** [comment]
We have change to our new name and this has been vetted by MS Docs team. DMAS should be in lower case unless when used at the start of a sentence. Only then can we capitalise the 'D'. These are MS docs standards.

#please-close
