### ISSUE TITLE
Readibility/Flow: Intro to DMAS should be a different section to Governance

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/cloud-adoption-framework#797]
The flow across the Intro to DMAS page is a little confusing. It starts off with comparing architectures and switches to Governance rather abruptly. Different pages with a line or two to segue into Governance might be easier for the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a4c609-db68-7d7d-0229-fec630de559d
* Version Independent ID: 29423660-00f2-b43b-c205-a0a57d9d3098
* Content: [What is data governance? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1#feedback)
* Content Source: [docs/scenarios/data-management/overview-data-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/overview-data-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
@mboswell there is a lot of redundancy in this overview, same content can be found in the intro to data mesh and the introduction to data management and analytics. Do we need to have the same information in this section as well?

**Comment by mboswell** [comment]
#assign @simonlid 

Please can we rewrite these sections to that there is a good flow between all of them.

**Comment by mboswell** [comment]
Rewritted

**Comment by mboswell** [comment]
#please-close
