### ISSUE TITLE
Multiple links broken in the immutability section

### ISSUE THREAD

**Issue by hurtn** [MicrosoftDocs/cloud-adoption-framework#798]
Many links result in a 404 as they don't have the correct URL prefix it seems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef64508f-c861-4eed-0fa5-67b2655f0b37
* Version Independent ID: ec6447bb-4173-45e3-df8e-31448bfdae99
* Content: [Key considerations for Azure Data Lake Storage - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-key-considerations?branch=collab-data-mesh-v1#store-business-critical-blob-data-with-immutable-storage)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-key-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-key-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
This will be solved when the content has been promoted to production. @mboswell is there anything that we can do here to ensure that they work when we reference them in the preview environment?

**Comment by mboswell** [comment]
This is a challenge with the preview environment. They work in production.

#please-close
