### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hurtn** [MicrosoftDocs/cloud-adoption-framework#799]
Please change "don not" to "do not"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef64508f-c861-4eed-0fa5-67b2655f0b37
* Version Independent ID: ec6447bb-4173-45e3-df8e-31448bfdae99
* Content: [Key considerations for Azure Data Lake Storage - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-key-considerations?branch=collab-data-mesh-v1#store-business-critical-blob-data-with-immutable-storage)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-key-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-key-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
I think that this has been solved in one of the previous check-ins

**Comment by mboswell** [comment]
#please-close

**Comment by mboswell** [comment]
#label:"data management and analytics"
