### ISSUE TITLE
Azure KeyVault Asset Type is Missing

### ISSUE THREAD

**Issue by cweisbrod** [MicrosoftDocs/cloud-adoption-framework#8]
Hello All - Is the Azure KeyVault missing from this document or is there more information elsewhere? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6dff4c3-d2d7-3825-d753-fc7338004f43
* Version Independent ID: b2c190ac-1d2e-93fc-caee-d59c278f549a
* Content: [Ready: Recommended naming and tagging conventions - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/naming-and-tagging)
* Content Source: [docs/ready/considerations/naming-and-tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/naming-and-tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by pijemcolu** [comment]
Just a thought, I'd question whether one would want to name a publicly accessible secret manager following a default naming covnention `kv-we-prod-company-01`, or something of that sort. That URL holds your configuration management secrets.

**Comment by cweisbrod** [comment]
That’s a great point!

**Comment by cweisbrod** [comment]
That's a great point. Thanks!
