### ISSUE TITLE
Lifecycle management concerns

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#801]
This document does not make clear our guidance on using lifecycle management on data lakes, rather uses standard storage guidance.

Hypothesis:  Moving data from hot to cool is generally not suitable for user accessible portions of the data lake.
Rationale: Since all data in the lake tends to be discoverable, it is difficult to predict when data will be accessed. Since it costs money to move data to cool tier and it is more expensive to access it, it would be difficult to predict the actual benefit for moving to cool. This makes cool tier only suitable for sections of the lake that only interact with well understood workloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef64508f-c861-4eed-0fa5-67b2655f0b37
* Version Independent ID: ec6447bb-4173-45e3-df8e-31448bfdae99
* Content: [Key considerations for Azure Data Lake Storage - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-key-considerations?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-key-considerations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-key-considerations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
Agree, Will get this changed.

#assign mboswell

**Comment by mboswell** [comment]
#please-close
