### ISSUE TITLE
Typo in calculation

### ISSUE THREAD

**Issue by FPMilan** [MicrosoftDocs/cloud-adoption-framework#802]
Using management groups per App-Environment should scale with N and not with N^2:
(N apps) x (N+3) = Total management groups --> (N apps) x (1+x) = Total management groups, with x as the number of different environments e.g., Dev/Test/Prod

(thanks for the great documentation! keep up the good work)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72345a49-0a6f-78aa-7419-94c733f99a51
* Version Independent ID: 5ddffa14-9feb-59da-fa1a-939113bc3a02
* Content: [Enterprise-scale FAQ - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-handle-devtestproduction-workload-landing-zones-in-enterprise-scale-architecture)
* Content Source: [docs/ready/enterprise-scale/faq.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/enterprise-scale/faq.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **doalle**

**Comment by TimShererWithAquent** [comment]
Rewrote calculation -
