### ISSUE TITLE
Suggest language change from multiple lakes to multiple storage accounts

### ISSUE THREAD

**Issue by bricrsa** [MicrosoftDocs/cloud-adoption-framework#803]
I believe it would be better to keep the concept of a single logical data lake with multiple storage accounts, rather than describing the data lake as multiple lakes.

Also I believe it will be better to soften the position on multiple storage accounts by stating when that would be recommended, such as scale limits, very large throughput requirements etc. 

This _is_ stated in the section "To decide to create one or multiple accounts has no definitive answer. It requires thought and planning based on your unique scenario.", however the rest of the section appears to assume that it is general guidance to create a number of storage accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b406c0d4-b63d-60c5-2d73-3dc2e416950d
* Version Independent ID: cc1d6520-2fe6-8044-ba7b-bac145887e62
* Content: [Overview of Azure Data Lake Storage for the data management and analytics scenario - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-overview?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
