### ISSUE TITLE
Review of overview section

### ISSUE THREAD

**Issue by hurtn** [MicrosoftDocs/cloud-adoption-framework#804]
Looking at the following sentence: "When a new system of record is registered via the data agnostic or onboarding application, it should create the required folders on the containers in the raw, enriched and standardized data layers. " 
Few things require review. 
- if naming convention is important then standardized is not a layer according to the chart above this sentence , it's a container, so is this meant to be "curated" ?
- the sentence seems to be missing something before or after "data agnostic" 
- I would imagine that it's unlikely that a new SOR will need a folder in all 3 layers up front, definitely one for ingestion/raw and maybe another for enriched but by the time it's left raw, it may become something completely different being joined to another SOR perhaps.

Looking at the following paragraph there seems to be a mix/ambiguity of terms between folders vs containers and layers and zones which the guidance is applicable to:
"Each data product should have two folders in the curated data lake layer over which the data product team should have ownership.

At the standardized container, in the enriched zone, there would be two folders per source system divided by classification. This will allow the team to store data with different security and data classification separately and different security access can be assigned to them. The container would contain a general folder, for confidential or below, and a sensitive personal data folder. Access will be controlled, by access control lists (ACLs). By having these two folders, you can choose to create a dataset with all the personal data removed located in the general folder. You can then have another dataset with all personal data in the sensitive personal data folder."

The sentence "A child file's access control list (ACL) files do not have a default ACL. " I think is meant to read "A child file's access control list (ACL) do not have a default ACL. "

The sentence " You might choose to store the data in its original format, such as JSON or .CSV. But there might be scenarios where it makes sense to store it as a column in compressed format..." should perhaps read " You might choose to store the data in its original format, such as JSON or CSV, but there might be also scenarios where it is more cost effective to store the contents of the file as a column in a compressed file format..."

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a9e844-d37a-9ca3-37b4-62a8e5a216f9
* Version Independent ID: b1a9e844-d37a-9ca3-37b4-62a8e5a216f9
* Content: [Provision three Azure Data Lake Storage Gen2 accounts for each data landing zone - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/best-practices/data-lake-zones?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/best-practices/data-lake-zones.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/best-practices/data-lake-zones.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
Great feedback @hurtn 
#assign: @mboswell 
#label:"data management and analytics"

**Comment by PRMerger9** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: bel"data managemen

**Comment by mboswell** [comment]
#assign: @mboswell

**Comment by mboswell** [comment]
edits made and updated

**Comment by mboswell** [comment]
#please-close
