### ISSUE TITLE
General Readability edits

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/cloud-adoption-framework#806]
- "The other challenge is that data is being collected.." - there is no previous challenge discussed.
- "Discover what data exists across the hybrid multicloud distributed data landscape, including geographic location, to" - suggest rewrite as "Discover data distributed across multiple clouds and geographic locations.."
- Data retention classification scheme: Temporary& Fixed Period "Short lived, such as keep Twitter data for a week". Suggest change to "Short lived data. For .e.g., Twitter data retained for a week only" or something similar
- "Automate the data confidentiality and data retention classification process using the classes defined in each scheme is needed.. " - should be Automating...
- "Without accountability, confusion lingers as to who is accountable for governing data. " - redundant.
-  "Because master data is so widely shared, its application agnostic.." - "it is"
- Next step should probably be renamed to "data governance processes" not "components"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e02e4b64-80ca-b9fc-ffde-00c7a8ed7c91
* Version Independent ID: 49f1b43d-1b69-2d69-583c-efd1899a40d3
* Content: [Requirements for governing data - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-requirements?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern-requirements.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern-requirements.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by simonlid** [comment]
Fixed in 
commit 492fdea42de396f55b7af83dae0b3b6e950591fe (HEAD -> collab-data-mesh-v1)
Author: Simon Lidberg <simonlid@microsoft.com>
Date:   Fri Mar 4 18:12:03 2022 +0100

    Fixed issue #806

**Comment by simonlid** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3070

**Comment by simonlid** [comment]
#please-close
