### ISSUE TITLE
Misleading Data Mesh Reference

### ISSUE THREAD

**Issue by aaliraaza** [MicrosoftDocs/cloud-adoption-framework#807]
[Enter feedback here]

Under "Reference Architecture" section the Data Mesh has been referenced as an Architecture as opposed to an operational pattern. Whereas in the [Overview](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1) section it's used as an operational pattern alongside Lakehouse, data fabric etc.

This would be confusing for the users so need to use these terminologies carefully for standardisation & clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Azure data management and analytics scenario overview - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
#label:"data management and analytics"
#assign @simonlid

**Comment by mboswell** [comment]
fixed #please-close
