### ISSUE TITLE
Introduction to working groups needed

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/cloud-adoption-framework#808]
"Each working group should take responsibility to define a specific data entity or data subject area, such as multiple related entities." - working groups are not introduced prior to this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81de9c63-35a0-cc10-2bf9-df1b6284f79a
* Version Independent ID: bc57f8ab-4ed8-90ae-c6ee-0a6f6ced07b5
* Content: [Data governance processes - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/govern-components?branch=collab-data-mesh-v1)
* Content Source: [docs/scenarios/data-management/govern-components.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/govern-components.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
#label:"data management and analytics"

**Comment by mboswell** [comment]
Great point - will correct.
#assign: @mboswell

**Comment by mboswell** [comment]
Great point - let me link it to our data governance board and put in data governance working group.

**Comment by mboswell** [comment]
#please-close
