### ISSUE TITLE
Selecting "Next steps" links lead to skipping huge chunks of the framework

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/cloud-adoption-framework#81]
If one follows the "next steps" link at the bottom of this page, one skips the entire remainder of the Strategy section, jumping straight into a subsection of the "Plan" section, skipping over Strategy/Business justification, Strategy/First cloud adoption project, and Strategy/Suggested skills. There are numerous other examples of this in the Cloud Adoption Framework. It's not possible to read the whole thing using the "Next steps" links. Is one intended to skip over topics that "next steps" skip over? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9062ac-00cf-b148-b73f-cda525d99c45
* Version Independent ID: 6740abb0-dbc9-5590-eb93-24cc068c6fed
* Content: [How can we align efforts to meaningful learning metrics? - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/learning-metrics)
* Content Source: [docs/strategy/learning-metrics.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/strategy/learning-metrics.md)
* Service: **cloud-adoption-framework**
* Sub-service: **strategy**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
This specific issue has been resolved. We are reviewing the broader use of Next Steps for navigating sequentially through the content.
