### ISSUE TITLE
General Readability edits

### ISSUE THREAD

**Issue by rathulya** [MicrosoftDocs/cloud-adoption-framework#811]
Deliver a personalized, rich, connected experience that's inspired through your brand. - not sure what this means?

Also, think about adding the architectural pillars to help you dive deeper into the scenario. - what scenario is being talked about here?

Data management and analytics are aligned to...  -should this be DMAS _is_ aligned to..?

Understand and prioritize your LOBs needs'.  - what is LOB here? Acronym used without precedent.

Data, applications, and services all have their own gravitational pull. But data is the heaviest here, and so it has the most gravitational pull. Unlike Newton's apple, data doesn't have a physical mass to draw in surrounding objects. Instead, latency and throughput act as accelerators to the analytics process.  - could we review this analogy? Find it a little distracting.

"..To activate your data strategy to overcome your challenges by iteratively building a scalable and agile modern data platform.." - not sure what this means?

The other major driver for data governance is data protection.  - no first driver is discussed before this. If data quality if that driver, it is not clear from the write-up

Data privacy, and the growing number of data breaches, have made data protection a top priority in the boardroom. change 'have' to 'has'. Also suggest rewriting as 'Data privacy, along with the growing...'
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a4c609-db68-7d7d-0229-fec630de559d
* Version Independent ID: 29423660-00f2-b43b-c205-a0a57d9d3098
* Content: [What is data governance? - Cloud Adoption Framework](https://review.docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/overview-data-governance?branch=collab-data-mesh-v1#feedback)
* Content Source: [docs/scenarios/data-management/overview-data-governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/overview-data-governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
#label:"data management and analytics"
#assign @simonlid 

Another one to tackle on the first pages.

**Comment by PRMerger4** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: kle on the first p

**Comment by mboswell** [comment]
#assign @simonlid

**Comment by hallihan** [comment]
@rathulya @mboswell  It looks like this issues was reported on an in-progress collaboration branch. If this was not addressed prior to publication of that branch, can you open a new issue from the published doc?
