### ISSUE TITLE
Visio file misspelling

### ISSUE THREAD

**Issue by QiMata** [MicrosoftDocs/cloud-adoption-framework#817]
The picture of the landing zone desired state shows "Identity subscriptions" whereas the Visio file has it spelled "Indentity subscriptions". Just FYI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by hallihan** [comment]
This should be fixed in the latest Visio.
