### ISSUE TITLE
No Reference Architecture for "Implement a DMZ between Azure and the internet"

### ISSUE THREAD

**Issue by bmoore3standard** [MicrosoftDocs/cloud-adoption-framework#82]
This links above for 1. Implement a DMZ between Azure and your on-premises datacenter 2. Implement a DMZ between Azure and the internet , point to the same reference architecture page,( https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz ), which is exclusively pertains to use case 1.  Is there no reference architecture specifically for securing Internet access for customer facing applications scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d40b10fc-3c76-0f45-6139-5e406d23cbec
* Version Independent ID: 3a4eb3db-94be-72ed-922b-48b4d87903f5
* Content: [Perimeter networks - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/perimeter-networks#feedback)
* Content Source: [docs/ready/azure-best-practices/perimeter-networks.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-best-practices/perimeter-networks.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by JanetCThomas** [comment]
@MikeWasson - should a new RA be created for this?

**Comment by alexbuckgit** [comment]
We've added this request to our backlog for prioritization. Thanks for the feedback!
