### ISSUE TITLE
Unclear where to find policies

### ISSUE THREAD

**Issue by PulpyJuice** [MicrosoftDocs/cloud-adoption-framework#827]
Hi! I'm currently trying to adapt the CAF - Data and Analytics scenario policies to a sandbox and I've not been able to utilize the recommended policies, as they are unsearchable within the current Azure portal. The info given in "Policy name" does not correlate to either policy name, policy description nor policy ID in the Azure portal. I've also tried to look for the IDs using https://www.azadvertizer.net/, however, to no avail. The site states in an info box that "All the policies are available in our GitHub repository.", howver, no such Github repo is available. Where do I find it? 

Thanks,
Pulpy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 007e1c4c-4370-b09e-45fc-7a199ae949d0
* Version Independent ID: 007e1c4c-4370-b09e-45fc-7a199ae949d0
* Content: [Detail of policies in Azure data management and analytics scenario - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/policies)
* Content Source: [docs/scenarios/data-management/architectures/policies.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/policies.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @marvinbuss
* Microsoft Alias: **mabuss**

**Comment by v-fearam** [comment]
Hi @PulpyJuice



Sorry for the delay. 


It is not so clear your point for me.

Following the content link in the ticket, I get [Solution Accelerators Page](https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/solution-accelerators). I think the original page is not available.

Anyway, here there is a page about [Azure Policies](https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/eslz-policies).

Here there is the [Azure Policies GitHub Repository](https://github.com/Azure/azure-policy). 

For example, about storage, you can find [Azure Policy built-in definitions for Azure Storage](https://learn.microsoft.com/azure/storage/common/policy-reference), then the [policy on the GitHub Repo](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Storage/StorageEncryptionScopesShouldUseDoubleEncryption_Audit.json), and also on Azure Portal


![image](https://user-images.githubusercontent.com/62260324/200363000-d1e87e67-e0e4-49bd-9d72-17960abd6096.png)

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
