### ISSUE TITLE
Front Door firewall policy name can not have any hyphen character unlike abbreviation with a hyphen character  in given documentation 

### ISSUE THREAD

**Issue by kaganmersin** [MicrosoftDocs/cloud-adoption-framework#829]
Documentation basically shows us the abbreviation with hyphen character as shown below. (fdfp-)
![image](https://user-images.githubusercontent.com/46555755/159698231-b43dbb2f-0504-470b-956f-0737a3e333c0.png)

But if we try to create this resource with portal we see below error message

![image](https://user-images.githubusercontent.com/46555755/159698454-65c13f22-9ea6-470e-b862-ef87e7086cbb.png)

Seems like the Front Door firewall policy must be created with the name has hyphen character like any other Azure resources. But in the reality it is impossible. Either documentation or resources should be changed considering the as-is situation (I believe resource should allow)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
Thanks @kaganmersin! We recently made this change. Thanks for letting us know.
