### ISSUE TITLE
What is "Digital Rebar Provision (DRP) regimes"?

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/cloud-adoption-framework#830]
This page has a line which reads "Inventory the workflows to support in engineering, updating, and deploying your solution in normal and Digital Rebar Provision (DRP) regimes"

What is "Digital Rebar Provision (DRP) regimes"?  It's not a term I'm familiar with, and I could not find it via an internet search.

Please clarify or revise this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046cd0bc-3c54-3e86-eadc-b77a2048bd10
* Version Independent ID: 73d4b0ae-6435-a5ae-332b-d863cd660991
* Content: [Deployment option considerations for Azure Kubernetes Service (AKS) - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/aks/eslz-platform-automation-and-devops)
* Content Source: [docs/scenarios/aks/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/aks/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by larryclaman** [comment]
@BrianBlanchard  -- can you take a look?

**Comment by larryclaman** [comment]
Seems like DRP was first added in this commit https://github.com/MicrosoftDocs/cloud-adoption-framework/commit/c34584e38f651573cd42402d7a01db4d9a02f927 by @primegonzola on Sep 29, 2020

And then "Digital Rebar Provision" was added in this commit on Feb 17 2021:   https://github.com/MicrosoftDocs/cloud-adoption-framework/commit/560e2353b2f4508a89621f996ce9577970e9e594 by @v-thepet

@primegonzola  and  @v-thepet , could you add some context to what is meant by DRP?

**Comment by larryclaman** [comment]
@v-thepet thanks for the link; however, I have a concern that the term "digital rebar provision" is proprietary to Rackspace.  So I wonder if in this context, the original poster might have meant "disaster recovery plan".

In any case, I'm still confused, even substituting in that term:  "Consider the various workflows to support in engineering, updating and deploying your solution in normal and disaster recovery plan regime".   Unfortunately that's only slightly less unclear.

**Comment by v-thepet** [comment]
@larryclaman - DRP might be open-source, I can't really tell. Anyway, this Docs article is part of a series on enterprise-level Kubernetes. The [previous article in the series is about disaster recovery](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/aks/eslz-business-continuity-and-disaster-recovery). This article is about deployment options. Just trying to explain why I chose that meaning for the acronym. But I'm certainly no expert and I'm sure the content owners can provide the correct answer.

**Comment by mosabami** [comment]
hi @v-thepet , I lead the team that developed the documentation. Please change the long form to "disaster recovery plan" as that is what it is supposed to be. Thanks in advance.  cc @BrianBlanchard , @larryclaman

**Comment by v-thepet** [comment]
@BrianBlanchard @mosabami @larryclaman - I will need to get authorization from my manager to make the change as am no longer assigned on the project. Unless the content owner wants to make the change. Sorry, should have forwarded this to my manager in the first place. @marteeleigh - FYI

**Comment by mosabami** [comment]
im the content owner @v-thepet

**Comment by v-thepet** [comment]
@mosabami - Oh sorry, I meant, I myself can't make the change without permission from my manager, but the content owner (you) can make the change yourself. Thanks!

**Comment by v-thepet** [comment]
@mosabami - Just go to the published article, select Edit (pencil) at upper right, it will take you to Github where you can edit the article then select Commit and it will be pushed as a PR, reviewed and merged. I know, I could do it myself quicker than explaining it but this is best. Let me know if you have trouble.

**Comment by larryclaman** [comment]
closing per PR #3362
