### ISSUE TITLE
Advice to use kube-advisor should be removed

### ISSUE THREAD

**Issue by larryclaman** [MicrosoftDocs/cloud-adoption-framework#831]
This page says  "Regularly run the latest version of the [kube-advisor open-source tool](https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-scheduler#regularly-check-for-cluster-issues-with-kube-advisor) to detect issues in your cluster."

Kube-advisor has been deprecated and should be removed from this guidance.   see https://github.com/Azure/kube-advisor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f148bc4d-6f2b-e164-78e9-f65194cb7ebc
* Version Independent ID: 742f123f-36cb-1d07-4abb-fe88c08c0b71
* Content: [Business continuity and disaster recovery considerations for Azure Kubernetes Service - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/aks/eslz-business-continuity-and-disaster-recovery)
* Content Source: [docs/scenarios/aks/eslz-business-continuity-and-disaster-recovery.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/aks/eslz-business-continuity-and-disaster-recovery.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @jeffmitchell
* Microsoft Alias: **jemitche**

**Comment by JefferyMitchell** [comment]
> @JefferyMitchell @BrianBlanchard can you take a look? I am happy to create the PR if you agree

Thank you Larry! Let me check with the team.

**Comment by mosabami** [comment]
@BrianBlanchard  I agree with @larryclaman  please remove it

**Comment by mosabami** [comment]
@larryclaman  please create a PR and send me a link. thank you very much!

**Comment by larryclaman** [comment]
PR submitted:  https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3298

**Comment by larryclaman** [comment]
Above PR no longer works.  Created a new one:  https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3361

**Comment by RobBagby** [comment]
This was addressed 5/9. Closing.
