### ISSUE TITLE
Azure bastion diagram for virtual wan does not match the wording of the design recommendation

### ISSUE THREAD

**Issue by pagyP** [MicrosoftDocs/cloud-adoption-framework#835]
In the design recommendations the article states - "In a Virtual WAN-based network topology where remote access to Azure Virtual Machines over the internet is required, deploy Azure Bastion in each spoke VNet of the respective VMs as depicted in Figure 1 below."  

However,  figure 1 does not  fully represent this description.  Instead it shows a single virtual network with a bastion provisioned in it and other virtual networks without bastion provisioned therefore making it look like you can provision bastion in one virtual network linked to virtual wan and have the same functionality as the hub and spoke bastion model.  The diagram should really show a bastion provisioned in each virtual network to match the wording of the design recommendation.  Having a diagram that does not fully match the design recommendation could be confusing.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3530c3e-7b36-d4bc-62cf-e1662d5ed07f
* Version Independent ID: a3530c3e-7b36-d4bc-62cf-e1662d5ed07f
* Content: [Plan for virtual machine remote access - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access?WT.mc_id=linkedin)
* Content Source: [docs/ready/azure-best-practices/plan-for-virtual-machine-remote-access.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/plan-for-virtual-machine-remote-access.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @sitarant
* Microsoft Alias: **sitarant**

**Comment by BryanLa** [comment]
@pagyP - thanks for your contribution, and our apologies for the long delay in responding. 

I believe this issue has been resolved. An additional nested bullet was added to the [Virtual WAN-based network topology design recommendations](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-virtual-machine-remote-access#design-recommendations) after you filed this issue, clarifying what's depicted in figure 1:

*- You may choose to deploy a centralized Azure Bastion instance in a single spoke in your Virtual WAN topology. This 
configuration reduces the number of Azure Bastion instances to manage in your environment. This scenario requires users 
who sign in to Windows and Linux VMs via Azure Bastion to have a [reader role on the Azure Bastion resource and the 
chosen spoke virtual network](https://learn.microsoft.com/en-us/azure/bastion/bastion-faq#peering). Some 
implementations might have security or compliance considerations that restrict or prevent this.*

I've also slightly altered this text to indicate which is depicted in figure #1, which will republish tomorrow around 10am Pacific.

Please let us know if this is not sufficient and we can reopen this issue.

#please-close
