### ISSUE TITLE
Poor image quality

### ISSUE THREAD

**Issue by arntdg** [MicrosoftDocs/cloud-adoption-framework#836]
[Enter feedback here]
The image quality on this page is very poor. Even enlarging it does not clarify it. Can you please supply an SVG version and link it to the enlarge function instead of the existing image?
Also in recent other articles a new option was added to download the Visio version. This would be highly welcome here too!
Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f1fff-2485-a841-1b26-aa9601d2a121
* Version Independent ID: d8f114ec-93c2-f30b-6ac8-bfa47160813b
* Content: [Enterprise-scale for SAP on Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone)
* Content Source: [docs/scenarios/sap/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/sap/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by JefferyMitchell** [comment]
This one is assigned to @PankajMeshramCSA

**Comment by TiSaBu22** [comment]
Is that possible to add the Visio Diagram file for the Architecture. We can use it for our client projects and update existing SAP on Azure Reference Architecture diagrams.

**Comment by PankajMeshramCSA** [comment]
@TiSaBu22 - Yes this is in progress. I will update once done.

**Comment by TiSaBu22** [comment]
> @TiSaBu22 - Yes this is in progress. I will update once done.

Great! Thank you.

**Comment by hallihan** [comment]
@PankajMeshramCSA Has this been completed?

**Comment by arntdg** [comment]
The image is looking much better now. The second zoom level is really deep though.


With kind regards/Met vriendelijke groeten,

***@***.***
Arnt de Gier
Azure NetApp Files Technical Marketing Engineer
Mobile: +31613384557 – Email: ***@***.******@***.***> |  ***@***.******@***.***>

https://azure.microsoft.com/services/netapp/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fservices%2Fnetapp%2F&data=02%7C01%7Cb-gevant%40microsoft.com%7Cdc8b62206c2c43b4244008d850d64928%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637348228564525803&sdata=L8gK1JdEli7qXS4ykiX%2F2GKvHqIXM9K1ebDe8FsM%2Fd0%3D&reserved=0>
Azure NetApp Files documentation found here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fazure%2Fazure-netapp-files%2F&data=02%7C01%7Cb-gevant%40microsoft.com%7Cdc8b62206c2c43b4244008d850d64928%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637348228564525803&sdata=08XnNk9FfQSxIP2JN5Eh0Yh%2BFS09Wbu%2Bqfq6q%2F0vhIU%3D&reserved=0>
