### ISSUE TITLE
Cloud Adoption Framework/Scenarios/Data Management - Curated Zone

### ISSUE THREAD

**Issue by fddermid** [MicrosoftDocs/cloud-adoption-framework#838]
Please consider rewording "It might store data in de-normalized data marts or star schemas." to The Curated data may also be stored in de-normalized data marts or star schemas.  The distinction being "It" does qualify the object and my client read this to be data marts and star schemas can be created in storage.  Certainly folders and files can be stored, but normalization of data and schemas are more a database concept Vs storage.  

Next paragraph "Data is taken from the golden layer...", you may consider reusing the terminology introduced and change "Golden" to "Curated."

Thank you.... not being picky, but client read this and needed to reposition what storage was and was not.

**Comment by mboswell** [comment]
This is no longer in the docs.

#close-off
