### ISSUE TITLE
I have a question in part of "Operate in multiple geographic regions".

### ISSUE THREAD

**Issue by tatokamoto** [MicrosoftDocs/cloud-adoption-framework#840]
[Enter feedback here]
I have a question in part of "Operate in multiple geographic regions".
Please give me specific examples of the following items.
These items do not specifically written.

*Asset distribution
*User access profiles
*Compliance requirements 
*Regional resiliency 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b660c4be-7ac5-4d77-06e4-22fae18724ba
* Version Independent ID: b5db2093-d8dc-3a60-d1ca-553f085aa00e
* Content: [Azure regions decision guide - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/multiple-regions#operate-in-multiple-geographic-regions)
* Content Source: [docs/migrate/azure-best-practices/multiple-regions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/multiple-regions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @doodlemania2
* Microsoft Alias: **dermar**

**Comment by hallihan** [comment]
These topics are just high level categories identifying additional considerations when regions are geographically dispersed.  See https://learn.microsoft.com/azure/cloud-adoption-framework/migrate/azure-best-practices/multiple-regions#know-data-sovereignty-requirements and https://learn.microsoft.com/azure/cloud-adoption-framework/migrate/azure-best-practices/governance-or-compliance for a couple examples.
