### ISSUE TITLE
Recommended abbreviation for resource type are different on the web page Vs the AZNamingTool generator

### ISSUE THREAD

**Issue by Atul-Moghe** [MicrosoftDocs/cloud-adoption-framework#841]
There are discrepancies in [Recommended Abbreviations For Azure Resource Types](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) page and the output of AZNamingTool generator. Below are few examples.

- On recommendation page it's 'apim' for Api Management where the tool suggests to have 'apims'
- On recommendation page it's 'stapps' for Static Web App where as the tool suggests to have 'aswba'
- On recommendation page it's 'st' for Storage Account where as the tool suggests to have 'stg'

**Comment by stephen-sumner** [comment]
@Atul-Moghe  - Thanks for the feedback. We're working on resolving these. You should see closer alignment here soon.
