### ISSUE TITLE
Recommended abbreviations for regions

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/cloud-adoption-framework#844]
Would be nice to have similar page for azure regions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@yahorsi -  thank you for the suggestion! I'm going to keep this in mind as we make some updates in the future.

I'd recommend using the Azure Naming Tool. It has abbreviations for every region.

https://github.com/microsoft/CloudAdoptionFramework/blob/master/ready/AzNamingTool/README.md

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950
