### ISSUE TITLE
need updates for 20.04

### ISSUE THREAD

**Issue by Trevor-Davis** [MicrosoftDocs/cloud-adoption-framework#849]
[Enter feedback here]
This command in version 20.04 does not work.
sudo rm /etc/netplan/50-cloud-init.yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f97610-b965-bfd3-e006-0c35df0cb68a
* Version Independent ID: 412e9c54-393f-fb40-952c-f5b2a6b60e6d
* Content: [Create a VMware vSphere template for Ubuntu Server 18.04 - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/hybrid/server/best-practices/vmware-ubuntu-template?%2Fazure%2Fcloud-adoption-framework%2F_bread%2Ftoc.json=&toc=%2Fazure%2Fcloud-adoption-framework%2Fscenarios%2Fhybrid%2Ftoc.json&source=docs)
* Content Source: [docs/manage/hybrid/server/best-practices/vmware-ubuntu-template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/manage/hybrid/server/best-practices/vmware-ubuntu-template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **manage**
* GitHub Login: @likamrat
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24252 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
