### ISSUE TITLE
data-landing-zone-data-integration link

### ISSUE THREAD

**Issue by claasnic** [MicrosoftDocs/cloud-adoption-framework#850]
link to https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone-data-integration
is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a913402-aa8d-3ae7-2589-81d7bee16c09
* Version Independent ID: 5857fc40-82a4-18e2-e152-67841ca03f51
* Content: [Data landing zones - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone)
* Content Source: [docs/scenarios/data-management/architectures/data-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/architectures/data-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
This no longer exists and was removed in our new version (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/architectures/data-landing-zone).

**Comment by mboswell** [comment]
#close-off

**Comment by mboswell** [comment]
#please-close
