### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by rocavalc** [MicrosoftDocs/cloud-adoption-framework#852]
[Enter feedback here]
These two links are broken (404) on this page.

Introduction to Data management and analytics scenario - Cloud Adoption Framework
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/

Scaling data management and analytics in Azure - Cloud Adoption Framework
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42c384-f5c3-b47b-1903-9d3ae4a71247
* Version Independent ID: a6a5e0de-1d1e-af9b-2eea-c06440102b76
* Content: [Cloud-scale analytics - Microsoft Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/data-management/)
* Content Source: [docs/scenarios/data-management/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/data-management/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
Thanks for this - we are repoint all of them to cloud-scale-analytics and this should be finished in the next few days.

cc @v-andreaco

**Comment by v-andreaco** [comment]
@rocavalc 

Both of those links should be working now. If they don't work for you, try refreshing or clearing your cache. :)

Closing this. Thanks for catching this issue!
