### ISSUE TITLE
Clarification on folder structures

### ISSUE THREAD

**Issue by pottsork** [MicrosoftDocs/cloud-adoption-framework#854]
Hi!
And thanks for great documentation on Cloud-scale analytics. I have seen that you have recently updated it.

Although, i'm having issues grasping some of the things in this particular markdown. Two questions:

1. Here is an example of the Folder structure in conformance container:
![image](https://user-images.githubusercontent.com/34475134/166204703-96b568ee-d057-4f1a-88ea-353919661126.png)

Here it seems as if both a **Delta** and a **Full** folder should be included for each entity. Shouldn't it be either or?

2. In the folder structure for the Standardized and Curated container the **Sensitive** folder is intented in the markdown. (See example image) 
![image](https://user-images.githubusercontent.com/34475134/166205114-452c3d51-c269-491c-8ab2-e39444ad0ed9.png)

Shouldn't these be on the same heirarchy level? This to be able to steer the ACL's in an efficient manner.

Thanks in advance.

BR
Jesper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5307b585-f48a-c46d-bdc5-56ec5dad0112
* Version Independent ID: 5307b585-f48a-c46d-bdc5-56ec5dad0112
* Content: [Data lake zones and containers - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/best-practices/data-lake-zones)
* Content Source: [docs/scenarios/cloud-scale-analytics/best-practices/data-lake-zones.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/best-practices/data-lake-zones.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by mboswell** [comment]
This is intentional so that you can use a directory structure related to the data product but then using ACLs assign different permissions to a data product. This data product could have a general and sensitive version.

**Comment by mboswell** [comment]
#please-close
