### ISSUE TITLE
Conflicting documentation - Management Groups

### ISSUE THREAD

**Issue by reduards** [MicrosoftDocs/cloud-adoption-framework#855]
Hello,

Conflicting documentation regarding Mangement Group strutucture.

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-management-groups:

"Don't create management groups for production, testing, and development environments. If necessary, separate these groups into different subscriptions in the same management group. To review further guidance on this topic, see:"

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/organize-subscriptions:

"Do you expect your Azure environment to grow? Then create management groups for production and nonproduction now, and apply appropriate policies and access controls at the management group level. As you add new subscriptions to each management group, those subscriptions inherit the appropriate controls."

Best Regards,
Rasmus

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24464 to track and investigate the issue.

**Comment by skabou** [comment]
#please-close
