### ISSUE TITLE
Security Baseline Sample Template - old 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/cloud-adoption-framework#856]
The sample template is over 3 years old, would it be possible to get this updated to include some examples that address new security functionality that has been added since then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc89babe-12fc-bba9-f1af-00a90d2a3529Ol
* Version Independent ID: d0f4c657-ac71-b09f-f3e3-7a3b50128e8a
* Content: [Security Baseline discipline template - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/security-baseline/template)
* Content Source: [docs/govern/security-baseline/template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/security-baseline/template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @DeanGross.

This baseline template will no longer be maintained or updated, and new content will be rolling out shortly for the CAF Govern security section.

#please-close
