### ISSUE TITLE
Missing recommended abbreviations for Azure resource types

### ISSUE THREAD

**Issue by jeiesel** [MicrosoftDocs/cloud-adoption-framework#857]
Hi I was defining prefix to the resources I want to deploy at Azure and I miss some of the Resources than I am using:

- Elastic Job Agent: Microsoft.Sql/servers/jobAgents
- Elastic Pool: Microsoft.Sql/servers/elasticpool
- Private Endpoint: Microsoft.Network/privateEndpoints
- Sendgrid Account: Sendgrid.Email/accounts
- FileShare: Microsoft.Storage/storageAccounts/fileServices/shares
- Hosting environment: Microsoft.Web/hostingEnvironments
- Batch Accounts: Microsoft.Batch/batchAccounts

Thanks in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#containers)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@jeiesel - Thanks for the feedback! You should see some updates soon.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950
