### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by SeanStL** [MicrosoftDocs/cloud-adoption-framework#859]
This bullet point is duplicated: Enterprise-scale landing zones. The paragraph just below the bullets also references TWO options when there should be three. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec75f268-b2f6-6473-6eae-bf406374c618
* Version Independent ID: ce6d73e6-f293-b443-703b-3f7d90980744
* Content: [Azure landing zones for modern application platforms - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/ready)
* Content Source: [docs/scenarios/app-platform/ready.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/ready.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
It appears this has been addressed.  Please re-open with additional details if help is still needed.
