### ISSUE TITLE
Why so complicated??

### ISSUE THREAD

**Issue by Misosoppa** [MicrosoftDocs/cloud-adoption-framework#86]
Why do you have 2 sections for secure and manage? First here, and then in best practices? Same with a lot of things like TCO. It's mentioned in the ready phase, and then again in migrate. Sure, I get that it can be done in different phases, but this is CAF - Just pick the point which you find best!

I used the AWS CAF before and its so much more streamlined. A template to fill in, one page for every section and a clean interface. 
I've read the entire CAF here and it's over a 1000 pages!!! Don't get me wrong, it's good info, but nobody in my company except me will have the time or willpower to learn them. Again, simplify and streamline! Simplicity over trying to cover every single thing remotely connected to migration over and over again...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7abc9c-dee1-3bcb-311a-2bbfe4138d7f
* Version Independent ID: 0ee7bd0d-7b2e-2dd3-e9ee-ec2db258c9fd
* Content: [Secure and Manage - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-migration-guide/secure-and-manage?tabs=servicehealth#feedback)
* Content Source: [docs/migrate/azure-migration-guide/secure-and-manage.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-migration-guide/secure-and-manage.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @Matticusau
* Microsoft Alias: **mlavery**

**Comment by BrianBlanchard** [comment]
There are two challenges in this conversation...
- First, we were in a fast march to release last November, that led to some duplicated content in various sections
- Second, we heavily suggest an iterative approach to release management and decision making.  This approach suggests aligning on an initial plan during ready. But then refining that plan on a per-workload basis during each iteration.

We have been working for the last 3 months to remove duplication where possible. We will continue to address the second issue with continued refinements over the next 4 months. Please check back on the [What's New article](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/getting-started/whats-new) to see how we are addressing this simplification effort at each release.
