### ISSUE TITLE
Why is the CAF so defragmented?

### ISSUE THREAD

**Issue by Misosoppa** [MicrosoftDocs/cloud-adoption-framework#87]
Why is this section located in a completely different part of the CAF framework than migration? It is so confusing to use the CAF because you just throw in anything that might be relevant and put it anywhere it might fit. We need a more streamlined version of it.
I used the AWS CAF before and its so much more streamlined. A template to fill in, one page for every section and a clean interface. 
I've read the entire CAF here and it's over a 1000 pages!!! Don't get me wrong, it's good info, but nobody in my company except me will have the time or willpower to learn them. Again, simplify and streamline! Simplicity over trying to cover every single thing remotely connected to migration over and over again...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8000fd6f-1bb1-dc48-1fbb-94797e1ef672
* Version Independent ID: a3a2a262-5943-6018-52ce-2030048a4760
* Content: [Migration tools decision guide - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/migrate-decision-guide/#feedback)
* Content Source: [docs/decision-guides/migrate-decision-guide/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/decision-guides/migrate-decision-guide/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
Great feedback! Thank you! 

CAF is designed to be a modular framework & not a single solution. Today, there are 6 distinct methodologies within the framework, which have shared dependencies on resources like decisions guides. I would never ask a customer or partner to read the whole thing. Instead, it was designed to use a specific methodology to overcome specific blockers to adoption.

More importantly, at the root of your feedback, we are actively working on streamlining. For NDA purposes, I can’t share on GitHub. But your feedback confirms & supports some changes that we have in the works. If you’d like to see what we are thinking, I’d be very interested in your feedback on the coming efforts. Please feel free to ping me on LinkedIn, Twitter or email to go deeper.

Thanks again,
-Brian
