### ISSUE TITLE
ALB vs AAG Decision Tree Error?

### ISSUE THREAD

**Issue by LDavis-Msft** [MicrosoftDocs/cloud-adoption-framework#871]
Our standard SAP Reference Architecture always has an ALB in front of the dual Webdispatchers, which I have always considered the default position except in the scenario where the SAP Application is internet facing.  However looking at the decision tree it says if the Application is Web HTTP/HTTPS and Not Internet Facing then to use AAG.  (3rd Scenario in the tree)

This doesn't make sense and I think this is a mistake.  Can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee541725-0b3e-153c-6875-de17ea85e4b3
* Version Independent ID: 0686e67e-7908-5666-1baf-1e4ae202b11d
* Content: [Governance disciplines for SAP on Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/eslz-security-governance-and-compliance)
* Content Source: [docs/scenarios/sap/eslz-security-governance-and-compliance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/sap/eslz-security-governance-and-compliance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @deepakonics
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 24577 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
