### ISSUE TITLE
Suggestion: Adding a note to avoid IP ranges reserved for AKS cluster or Container App

### ISSUE THREAD

**Issue by cmcyrus** [MicrosoftDocs/cloud-adoption-framework#879]
[Enter feedback here]
Suggest adding a note, for potential AKS / Container App users, to avoid IP ranges that cannot be used in AKS cluster 

From doc 
"AKS clusters may not use 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, or 192.0.2.0/24 for the Kubernetes service address range, pod address range, or cluster virtual network address range."
Ref: https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#prerequisites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56d1933-3acc-c78b-68b9-db881d93c7cf
* Version Independent ID: 9fd7912b-11cf-0aed-967f-19bac23b94f9
* Content: [Plan for IP addressing - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/plan-for-ip-addressing)
* Content Source: [docs/ready/azure-best-practices/plan-for-ip-addressing.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/plan-for-ip-addressing.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
#please-close
