### ISSUE TITLE
Suggestion: SAP on Azure

### ISSUE THREAD

**Issue by ketanshethia** [MicrosoftDocs/cloud-adoption-framework#880]
I have captured the questions from the section "[Security baseline considerations](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/governance#security-baseline-considerations)". I am wondering if there is a reason to omit Microsoft Sentinel from this questions? As I think Microsoft Sentinel has capabilities (using Azure Monitor) to monitor and alert SAP application, database, and underlying infrastructure level security events.

What tools and guardrails need to be enforced across the environment as part of a security baseline?
Who might be notified when deviations are found?
Consider using Azure Policy to enforce tools (such as Microsoft Defender for Cloud, Microsoft Defender for Cloud).
Consider using Azure Policy to enforce guardrails (such as the Azure Security Benchmark).

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 24786 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
