### ISSUE TITLE
Great ref to understand ML Cloud Adoption Framework.

### ISSUE THREAD

**Issue by Shijokingo** [MicrosoftDocs/cloud-adoption-framework#881]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7974639-5516-d455-afea-110184c5c373
* Version Independent ID: 155cd67e-a5d4-b275-fe77-8915f954c9f4
* Content: [What is machine learning? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/machine-learning)
* Content Source: [docs/innovate/best-practices/machine-learning.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/innovate/best-practices/machine-learning.md)
* Service: **cloud-adoption-framework**
* Sub-service: **innovate**
* GitHub Login: @v-hanki
* Microsoft Alias: **janet**

**Comment by hallihan** [comment]
Thanks for the feedback!
