### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by akiyoshi** [MicrosoftDocs/cloud-adoption-framework#882]
It seems that SSL certification for cafbaseline.com has expired.
Would you check and renew it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7c8896-cfaa-b957-48b7-02fc9e038a12
* Version Independent ID: 01ba169e-d6f4-30e0-b081-d814392c9a68
* Content: [Assess your cloud governance journey - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/benchmark)
* Content Source: [docs/govern/benchmark.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/benchmark.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by hallihan** [comment]
This was fixed back in June.
