### ISSUE TITLE
Security Center image should be replaced by MS Defender for Cloud 

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/cloud-adoption-framework#883]
Security Cneter image should be replaced by MS Defender for Cloud at [https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/#azure-landing-zone-conceptual-architecture](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
Thank you for finding and reporting this @ezYakaEagle442!
We've just updated the diagram to replace the Security Center icon with Defender for Cloud. This change will roll out shortly. 

#please-close
