### ISSUE TITLE
AVS missing info in docs about what to do when the extra cluster is in a failed state

### ISSUE THREAD

**Issue by DWeda1** [MicrosoftDocs/cloud-adoption-framework#884]
Hi, I was reading the https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-platform-automation-and-devops
I can see information about what to do when the AVS Instance is in status Failed but what about if the AVS instance is successful but the extra cluster you want to add is in a failed status? Should I also make a support request and let MS delete the cluster because from what I have experienced I was not able to delete the extra cluster from the portal or with PowerShell, the error message told me something like I can not edit a resource in a failed state .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed4fc81d-ca72-58f0-d869-60d5e4890bd2
* Version Independent ID: 3c4680f2-d3be-b554-079f-d3de36076e77
* Content: [Enterprise-scale platform automation for Azure VMware Solution - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-platform-automation-and-devops)
* Content Source: [docs/scenarios/azure-vmware/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @ScottHolden
* Microsoft Alias: **scholden**

**Comment by ScottHolden** [comment]
Hi @DWeda1,

I'd recommend opening a Microsoft support case so support/engineering can advise on why the operation failed and look at options for remediation. Depending on the state of the Private Cloud/Cluster you may not be able to edit/modify either resource (as you mentioned).

I'll work with @prasad3017 and team to have this added to the documentation.

**Comment by v-fearam** [comment]
#please-close
