### ISSUE TITLE
Description of the reference architecture management groups online and corp does not align with the general description in management group documentation

### ISSUE THREAD

**Issue by stalejohnsen** [MicrosoftDocs/cloud-adoption-framework#885]
The description of the reference architecture management groups online and corp does not align with the general description in management group documentation: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-management-groups 

Example from Tailor the Azure landing zone architecture page:
**Online** | Workloads, such as directly publicly facing, internet, web apps. They might also have **hybrid connectivity** and peering to other virtual networks, which includes **on-premises**.

Example from Resource Organization -> Management group page:
**Online** | The dedicated management group for online landing zones. This group is for workloads that might require direct internet inbound/outbound connectivity or for workloads that might not require a virtual network.

The description in Tailor the Azure landing zone for Online archetype is confusing as it is mentioning hybrid and on-premise which is more aligned with description of Corp in Resource Organization -> Management group page:

**Corp** | The dedicated management group for corporate landing zones. This group is for workloads that require connectivity or **hybrid connectivity** with the **corporate network** via the hub in the connectivity subscription.

</body>
</html>

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc363c4-7019-3af1-08f5-39f63f9abdad
* Version Independent ID: bdc363c4-7019-3af1-08f5-39f63f9abdad
* Content: [Tailor the Azure landing zone architecture - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/tailoring-alz)
* Content Source: [docs/ready/landing-zone/tailoring-alz.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/tailoring-alz.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by v-fearam** [comment]
#please-close
