### ISSUE TITLE
Power BI File Broken - Az Resoruce SKU VM's Query

### ISSUE THREAD

**Issue by adamswbrown** [MicrosoftDocs/cloud-adoption-framework#889]
the Az resource SKU VM's query requires an account key that is not provided

![image](https://user-images.githubusercontent.com/29273106/171637806-36add451-61ba-4a0e-bbf7-70f076fc3274.png)

This causes the file to fail to load as without the key, the BI model does not load

https://raw.githubusercontent.com/microsoft/CloudAdoptionFramework/master/strategy/azure-virtual-machine-cost-estimator.pbix

**Comment by skabou** [comment]
@adamswbrown Thank you for your feedback. I was able to run the query without issue.  Is it now working for you?

**Comment by adamswbrown** [comment]
That works for me now, thanks for resolving

**Comment by skabou** [comment]
Great! I'll be closing the ticket but if you run into another issue, please feel free to reopen.
