### ISSUE TITLE
Update statement within Connectivity Resources section to be accurate based upon v2.0.0 terraform module updates.

### ISSUE THREAD

**Issue by ATuckwell** [MicrosoftDocs/cloud-adoption-framework#890]
Information within the Connectivity Resources section is outdated.

**Current Statement**:
This capability currently enables deployment of a multiple-region hub-and-spoke network topology. Azure Virtual WAN is on the product roadmap.

As Virtual WAN was released with **v2.0.0** of the updated module, suggest updating to something similar to the below:

**Suggested Update**:
This capability currently enables deployment of a multiple-region hub-and-spoke network topology, as well deployment and configuration of Virtual WAN resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b505a5-c7a1-6641-dd29-4c4e71a1b3cf
* Version Independent ID: a4759d26-4bef-be02-a553-4fbc58a814e6
* Content: [Terraform module for Azure landing zones - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/terraform-module)
* Content Source: [docs/ready/landing-zone/terraform-module.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/terraform-module.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @krowlandson
* Microsoft Alias: **brblanch**

**Comment by krowlandson** [comment]
@ATuckwell - great suggestion. Thank you for bringing this to our attention!

Just to check (and avoid duplication of effort), are you planning to raise a PR with this update, or would you like us to do this?

**Comment by v-fearam** [comment]
PR already merged.

**Comment by v-fearam** [comment]
#please-close
