### ISSUE TITLE
Event hub should be Event hub namespace

### ISSUE THREAD

**Issue by zemien** [MicrosoftDocs/cloud-adoption-framework#892]
The recommendation for Event hub should reflect the correct [hierarchy of resources](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features). One would create an 'Event hub namespace' to contain 'Event hubs'. Thus, the recommended prefix should also be **evhns**:

Asset type | Scope | Format and examples
-- | -- | --
Event hub **namespace** | Global | **evhns**-navigator-prod **evhns**-emissions-dev

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi @zemien ,

Sorry for the delay. 

The article provides only examples, it is not an expected to be a completed resource list. 

Event hub is no longer included in the current examples. 

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
