### ISSUE TITLE
Kubecost -Unable to reach your Kubecost backend with aks 

### ISSUE THREAD

**Issue by munir94** [MicrosoftDocs/cloud-adoption-framework#893]
The deployment was successful but the connection cannot be made. 

![image](https://user-images.githubusercontent.com/39366930/174055075-02962d82-152d-41a2-ac17-db411e3e707a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce9d7ab-8355-ffc0-fd04-1aa59e3749da
* Version Independent ID: f2629562-e6fe-45db-400b-05aeccffbb52
* Content: [Cost governance with Kubecost - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/aks/cost-governance-with-kubecost)
* Content Source: [docs/scenarios/app-platform/aks/cost-governance-with-kubecost.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/aks/cost-governance-with-kubecost.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi @munir94
Sorry for the delay. 
I deployed a new cluster from scratch and followed the article instructions. The kubecost was deployed correctly and I was able to access the dashboard.
I think it was something specific in your deployment. 

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
