### ISSUE TITLE
abbreviations for On-Premise data gateway & private endpoints are missing

### ISSUE THREAD

**Issue by RHooijer** [MicrosoftDocs/cloud-adoption-framework#897]
We use the abbreviations a lot, however I notices that the On-Premise data gateway and private endpoints are missing in this list. Can those be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
Thanks! Add private endpoint abbreviation. 

As for the on-prem data gateway, this is a good suggestion. I didn't add it yet since it doesn't have an Azure namespace. But we will definitely keep these types of resources under consideration.
