### ISSUE TITLE
Issues with "Connect Microsoft Project to Azure DevOps" information

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/cloud-adoption-framework#901]
The link to [Connect Microsoft Project to Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog) has a couple problems:

1. The link itself points to a broad documentation article covering "Create your product backlog in Azure Boards", not specific to Microsoft Project. The link should point directly to instructions on connecting Microsoft Project to Azure DevOps or at least provide instructions on where to locate the information on the target page.
2. The Microsoft Project add-in (Visual Studio Office Integration Tools) is not supported in Azure DevOps Server 2019 or later versions, nor in Azure DevOps Services. See [this reference](https://docs.microsoft.com/en-us/azure/devops/server/compatibility?view=azure-devops#microsoft-office-integration). The reference to the Microsoft Project integration/addon should either be removed or updated to include a note/warning that it only works with versions of Azure DevOps Server (on-prem) *prior* to version 2019 of the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad00e712-d5f6-9e6d-a3f2-ca9de10ed45b
* Version Independent ID: b71d7a12-58d8-a176-c232-e8d25bc52b7a
* Content: [Cloud adoption plan for the deployment to Azure DevOps - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/template)
* Content Source: [docs/plan/template.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/plan/template.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
#please-close
