### ISSUE TITLE
Naming Recommendation Article is incomplete. It is missing some Azure Resources

### ISSUE THREAD

**Issue by jeffwessling** [MicrosoftDocs/cloud-adoption-framework#902]
I appreciate the existence of naming recommendations; I think that can go a long way to helping people standardize on terminology. However, I was surprised to find that this article didn't include some of the Azure Resources that have been created as part of our solution (Storage Account, API Connection, Private DNS zone, Private endpoint). It also seems to recommend at least one prefix that not even Microsoft uses when automatically naming generated resources. For 'App Service Plan' the article recommends 'plan-' whereas Azure creates default App Service Plans with 'ASP-'. It would be helpful if an article like this was complete and up-to-date and new Azure resources are introduced as anything missing then allows for differences in how things are named. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by cveld** [comment]
In particular API Connection is what I need today. For now I will go for `apicon`.

**Comment by stephen-sumner** [comment]
@jeffwessling - Thanks for the feedback! You should see some updates soon. We made that changes to the app service plan.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950
