### ISSUE TITLE
Comma splice

### ISSUE THREAD

**Issue by arcesso** [MicrosoftDocs/cloud-adoption-framework#903]
The following contains a comma splice.
"Segmenting workloads in a way that differs from the [implementation options](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options) for management group hierarchy**,** can create a complex policy and access control structure to govern your environment."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9da9dea-b71c-1d66-5ed9-b9fa705f1359
* Version Independent ID: c9da9dea-b71c-1d66-5ed9-b9fa705f1359
* Content: [Azure landing zone design principles - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-principles)
* Content Source: [docs/ready/landing-zone/design-principles.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-principles.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @jtracey93
* Microsoft Alias: **jatracey**

**Comment by JanetCThomas** [comment]
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/2017694

**Comment by 19BMG00** [comment]
Comma splice removed from line 72

**Comment by 19BMG00** [comment]
@JanetCThomas -- please review this edit. Thank you.

**Comment by ckittel** [comment]
@19BMG00 -- could you please link to the PR where this edit has been made.

**Comment by CAC1127** [comment]
@ckittel - Looking at the history of the doc, he pushed a commit Dec. 31 which fixed the comma splice issue. While I can't find a PR in the repo that he's authored, the live product no longer has a comma. Are we able to consider this issue resolved?

**Comment by ckittel** [comment]
Sounds like it.  @arcesso please re-open with additional details if we miseed anything.

#please-close
