### ISSUE TITLE
Broken link to "test-driven development of landing zones"

### ISSUE THREAD

**Issue by janerikohman** [MicrosoftDocs/cloud-adoption-framework#905]
I could see that the link "[test-driven development of landing zones](https://docs.microsoft.com/en-us/docs/ready/considerations/test-driven-development)" is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e057ef85-c4d2-46a9-7e38-2ac00a68be83
* Version Independent ID: 29c8a82c-9cb0-1a99-bce3-c0cded487d07
* Content: [Expand your landing zone - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/?source=docs)
* Content Source: [docs/ready/considerations/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
It appears the broken link has been fixed.  If you still require assistance, please feel free to re-open with additional details.
