### ISSUE TITLE
AZU//api_SDK.ymsrael(1388)

### ISSUE THREAD

**Issue by AemJane** [MicrosoftDocs/cloud-adoption-framework#906]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fc9644-e505-b9d8-0062-dd75d94d37ad
* Version Independent ID: abcfe78d-2c31-9a3e-45f0-1e23da219ce6
* Content: [Prepare for cloud adoption - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/)
* Content Source: [docs/ready/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by skabou** [comment]
It is unclear what to investigate from the details provided.  Please re-open with additional details if assistance is still needed.
