### ISSUE TITLE
The ARM template will fail due to policy conflict

### ISSUE THREAD

**Issue by marcosamsj** [MicrosoftDocs/cloud-adoption-framework#909]
I have gone through a CAF Go Big deployment with a Customer, and while deploying the landing zone, the ARM template will fail due to policy conflict on the Identity Management tile.
The solution was to go through the deployment will all policies set to "no" on the Identity Management tile to deploy the resources, and the re-run the same with policies set to yes.
The customer found this process super weird and there was awkward silence because we couldn't explain why we had run this thing twice.

**Comment by skabou** [comment]
It is unclear what article this is in reference to.  Please provide a link to the article and reopen if help is still needed.
