### ISSUE TITLE
Culture eats strategy for breakfast is not a Satya quote

### ISSUE THREAD

**Issue by RichardatMS** [MicrosoftDocs/cloud-adoption-framework#91]
Just a note, Peter Drucker was the person who is famously known for this quote. Satya requotes him but I think some might misinterpret that based on how it has been written in this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 177e1dd0-2a74-31c6-4b35-569423eed9fe
* Version Independent ID: 42d247d4-86f9-fd6d-15dc-e55ec5840096
* Content: [Introduction to the operating model - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/#feedback)
* Content Source: [docs/operating-model/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/operating-model/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **overview**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
This has been corrected. Thanks!
