### ISSUE TITLE
Incorrent links at page: "Compare common cloud operating models"

### ISSUE THREAD

**Issue by vanroon** [MicrosoftDocs/cloud-adoption-framework#914]
Description:
Link button at bottom of page that should link to "Operating model terminology (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/terms)" actually links to "Compare common cloud operating models (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/compare)"

Link text at bottom of page says "Compare common cloud operating models" and refers to "https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/". Link text should be changed to "What is an Azure landing zone?"

Suggested actions
- Change link value of first "button" to: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/terms
- Change link text of sectond "button" to: "What is an Azure landing zone?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb84d9b-3890-58cc-cc5c-547247b23a1a
* Version Independent ID: 025a2790-d3bd-e25e-1c4b-3b5e4bc46797
* Content: [Review and compare common cloud operating models - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/compare)
* Content Source: [docs/operating-model/compare.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/operating-model/compare.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thanks for the suggestion.  The changes have been implemented.
