### ISSUE TITLE
Recommendation to fork for each data landing zone probably wont work in practice

### ISSUE THREAD

**Issue by ShaneOsborne** [MicrosoftDocs/cloud-adoption-framework#918]
According to the instructions when you deploy multiple data landing zones you should fork these so you can customise/change parameters config etc.  This allows you to update changes back/forward between forks and 'parent'

However the challenge with this approach is that a fork has to be in a different organisation from the parent,  if your doing multiple data landing zones within a single company then you probably wont have different github orgs for each one.

Shane

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c70c23d5-23dc-b88b-c50d-bbfe0dc23b45
* Version Independent ID: c70c23d5-23dc-b88b-c50d-bbfe0dc23b45
* Content: [Provision cloud-scale analytics platform - Cloud Adoption Framework](https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/manage-provision-platform)
* Content Source: [docs/scenarios/cloud-scale-analytics/manage-provision-platform.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/manage-provision-platform.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @abdale
* Microsoft Alias: **hamoodaleem**

**Comment by v-fearam** [comment]
Hi @ShaneOsborne

Sorry for the delay. 

It is possibly create more than one fork on github org, for example:

![image](https://user-images.githubusercontent.com/62260324/234826832-cdcda5f4-135e-429c-b1cc-dd8c428fa6d6.png)

![image](https://user-images.githubusercontent.com/62260324/234826942-bff51b83-ec88-4cee-95b6-b05e264ab000.png)

Multiple forks will only work for an organization, not a personal GitHub account.
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
