### ISSUE TITLE
duplicate text

### ISSUE THREAD

**Issue by ldeanroberts** [MicrosoftDocs/cloud-adoption-framework#92]
the Strategy and Plan phases have the same description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5beb8241-27e4-fbc0-2372-16a224dcff0c
* Version Independent ID: 65b2c7b2-5443-9f44-98f3-d831963b87b7
* Content: [Getting started on a skills readiness path - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/plan/suggested-skills#feedback)
* Content Source: [docs/plan/suggested-skills.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/plan/suggested-skills.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
Thanks for the feedback. I think that has been addressed. Please let us know if see otherwise. 
docs/strategy/suggested-skills.md
docs/plan/suggested-skills
