### ISSUE TITLE
Add Route Server naming

### ISSUE THREAD

**Issue by mergljoe** [MicrosoftDocs/cloud-adoption-framework#920]
Dear MS,

Could you add Route server naming and update this abbreviations page as well? https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations.

Thank you!

Best regards,

József Mergl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a84ce2-7a0b-4558-1e28-aeefc649b567
* Version Independent ID: 3dffb383-4087-9aca-3b33-c5f777334062
* Content: [Define your naming convention - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming#feedback)
* Content Source: [docs/ready/azure-best-practices/resource-naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@mergljoe - Thanks for the feedback! You should see some updates soon.

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3950
