### ISSUE TITLE
"Use Azure Policy to control resource provider registrations" not possible

### ISSUE THREAD

**Issue by denishol** [MicrosoftDocs/cloud-adoption-framework#921]
Hi Docs,

as stated in this article:

> Use Azure Policy to control resource provider registrations at the subscription or management group levels

it should be possible to control resource provider registrations via Azure Policy. I haven't found a way to do this via Azure Policy.
In contrast I have even found the statement https://github.com/Azure/azure-policy/issues/573#issuecomment-635488482

> There is no functionality in policy to query or ensure that a resource provider is registered.

Could you please clarify, if it is possible to control resource provider registrations via Azure Policy or not?

Thank you very much!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061d80aa-0c57-8ae8-c9ae-a2ea52dff98f
* Version Independent ID: f77eeafe-a217-7959-3d5c-6e5f5e54d908
* Content: [Azure governance design area guidance - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/governance)
* Content Source: [docs/ready/landing-zone/design-area/governance.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/governance.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by v-fearam** [comment]
Hi @denishol 
 
Sorry for the delay.

Let discuss a little about [Azure Policies](https://learn.microsoft.com/azure/governance/policy/overview)
   
Azure Policy helps to enforce organizational standards and to assess compliance at-scale. Common use cases for Azure Policy include implementing governance for resource consistency, regulatory compliance, security, cost, and management.
__Azure Policy evaluates state by examining properties on resources that are represented in Resource Manager and properties of some Resource Providers. Azure Policy ensures that resource state is compliant to your business rules__ without concern for who made the change or who has permission to make a change.
Business rules for handling non-compliant resources vary widely between organizations (Deny, audit , etc)
There is a huge set of [Built-in Policies](https://learn.microsoft.com/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/eslz-policies). Here there is the [Azure Policies GitHub Repository](https://github.com/Azure/azure-policy).
   

[Azure Resource provider](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-providers-and-types)   is a collection of REST operations that provide functionality for an Azure service. The resource provider defines the Azure resources that are available for you to deploy to your account. The name of a resource type is in the format: {resource-provider}/{resource-type}.
Before using a resource provider, your Azure subscription must be registered for the resource provider. Registration configures your subscription to work with the resource provider.
Some resource providers are registered by default. For a list of resource providers registered by default, see [Resource providers for Azure services](https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers)
Other resource providers are registered automatically when you take certain actions. When you create a resource through the portal, the resource provider is typically registered for you. When you deploy an Azure Resource Manager template or Bicep file, resource providers defined in the template are registered automatically. However, if a resource in the template creates supporting resources that aren't in the template, such as monitoring or security resources, you need to manually register those resource providers.
 

Azure Policies helps to enforce resource states, it is for implementing governance (“control” means that in this context). Azure Policies won’t do actions like enable a Resource Provider.  

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
