### ISSUE TITLE
DB Migration - SQL DB not SQL MI

### ISSUE THREAD

**Issue by kinseymd** [MicrosoftDocs/cloud-adoption-framework#925]
There is a discrepancy in this article on the type of SQL resource deployed in the solution.
The Proposed Solution calls out Azure SQL DB as the resource
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql#proposed-solution

Later in the Migration Process you note "Contoso provisions an Azure SQL managed instance". Assuming the reference architecture diagram above is correct, you're showing an Azure SQL DB and you should be stating "Contoso provisions an Azure SQL Database"
https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql#migration-process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793c08e6-c592-7530-92df-6b0a8f1a4b02
* Version Independent ID: cb833a2c-e428-732e-cce4-2b09c663c98f
* Content: [Migrate an application to Azure App Service and SQL Database - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql?ocid=eml_pg201410_gdc_comm_az&mkt_tok=MTU3LUdRRS0zODIAAAGF_mRXpxGS8y2NtGW40xFkygnFn7jX3eITmEI79iyoaVlEKatU_h8UZKw5S66dRzNPOV5CrFr0ZzK_UTiKoUmOvExN_Jt4yOG3lsZnY3ypBf12TKQwMIr3q5c#migration-process)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
#please-close
