### ISSUE TITLE
Revise guidance to align with the Azure portal

### ISSUE THREAD

**Issue by Richards706** [MicrosoftDocs/cloud-adoption-framework#93]
Does anyone else have a problem finding instructions that are current with the actual actions that are available on Azure?  It seems that every time I find an article that I think will answer my questions and fulfill my desire to build with VS and Azure, by the time I move over to the Portal, it has been changed to the point that the instruction is no longer of value.  If an article is more than just a few months old, it is no longer relevant. IE: Every search I do for development of a web app with connection to a Azure Db refers me to "Tutorial: Build an ASP.NET app in Azure with SQL Database".  In that article it instructs one to start an App Service and create a SQL Database.  That option is no longer available or it has been hidden.  When I asked a question on that page, two people answered and seemed to make fun of me for not getting it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793c08e6-c592-7530-92df-6b0a8f1a4b02
* Version Independent ID: cb833a2c-e428-732e-cce4-2b09c663c98f
* Content: [Refactor an app by migrating it to Azure App Service and Azure SQL Database - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql#feedback)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/migrate/azure-best-practices/contoso-migration-refactor-web-app-sql.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by alexbuckgit** [comment]
This article has recently been revised. Thanks for the feedback!
