### ISSUE TITLE
Network Configuration URL reference no longer valid

### ISSUE THREAD

**Issue by ksaye** [MicrosoftDocs/cloud-adoption-framework#930]
The URL for [Azure Arc network service tags and IP addresses range](https://docs.microsoft.com/en-us/azure/azure-arc/servers/agent-overview#networking-configuration) no longer points to a location that includes network configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec75e13-926c-05fc-bbe2-db857849ce1b
* Version Independent ID: 8ec75e13-926c-05fc-bbe2-db857849ce1b
* Content: [Network connectivity for Azure Arc-enabled servers - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/hybrid/arc-enabled-servers/eslz-arc-servers-connectivity)
* Content Source: [docs/scenarios/hybrid/arc-enabled-servers/eslz-arc-servers-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/hybrid/arc-enabled-servers/eslz-arc-servers-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @Welasco
* Microsoft Alias: **vsantana**

**Comment by JanetCThomas** [comment]
@likamrat - can you please look at this broken link experience.

**Comment by likamrat** [comment]
Can you please update with the following link?

/azure/azure-arc/servers/network-requirements
