### ISSUE TITLE
HTTP when using Proxy/Firewall

### ISSUE THREAD

**Issue by psinnathurai** [MicrosoftDocs/cloud-adoption-framework#932]
Is it correct that when using Proxy or Firewall the agents connects outbound using HTTP instead of HTTPs?

"If the machine uses a firewall or a proxy server to communicate over the internet, the agent connects outbound using the HTTP protocol."

**Comment by jocontr** [comment]
Thanks @psinnathurai, could you please point us to the article in question?

On a side note. A lot depends on the configuration of your proxy or firewall. Whether HTTP or HTTPS, it all depends on how the middleware is configured to handle and rely requests. Thank you.
