### ISSUE TITLE
Cloud users download the Visio file of architecture?

### ISSUE THREAD

**Issue by jiankefu** [MicrosoftDocs/cloud-adoption-framework#933]
This is a high-quality document, as a reader, I have seen a lot of network topologies in your documents, and I want to download and edit these topologies, so cloud you upload the original files of these topologies in the documents? Thanks very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3f50d-5fc4-32d7-400a-4876b83a1535
* Version Independent ID: e159e485-d2db-10a0-2615-73e78f3733f3
* Content: [Virtual WAN network topology - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/virtual-wan-network-topology?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fbread%2Ftoc.json)
* Content Source: [docs/ready/azure-best-practices/virtual-wan-network-topology.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/virtual-wan-network-topology.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @jiankefu .
The full Visio file with all network topologies and Azure Landing Zone architectures is available from this page: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas 

In the Visio file, you select the "ALZ VWAN" tab to see the correct design.

I'm making a note in the internal backlog that we'll address this on the mentioned page, too, and introduce the download link from there.
