### ISSUE TITLE
New AntiPattern?

### ISSUE THREAD

**Issue by jeremiahhoward** [MicrosoftDocs/cloud-adoption-framework#934]
We may want to consider adding an antipattern that revolves around the concept of siloed small teams that each manage different ways to engage with the cloud, common in situations where a lack of initial velocity and governance allowed teams to go rogue. These elements can be consolidated and the best of breed taken from each to create a single better product that is greater than the sum of the parts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9e8e3e-57c5-971a-c581-72868d953b1e
* Version Independent ID: 980e5123-f0cf-b7d5-ade6-47e8a0b761d1
* Content: [Cloud adoption plan antipatterns - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/antipatterns/plan-antipatterns)
* Content Source: [docs/antipatterns/plan-antipatterns.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/antipatterns/plan-antipatterns.md)
* Service: **cloud-adoption-framework**
* Sub-service: **plan**
* GitHub Login: @mahia127
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37657 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
