### ISSUE TITLE
Misleading information on Landing Zones

### ISSUE THREAD

**Issue by SharmainePopov** [MicrosoftDocs/cloud-adoption-framework#935]
"Your data management landing zone must be deployed as a separate subscription under the **corp** management group of an azure landing zone architecture. You can then control governance across your organization. The [Azure landing zone accelerator](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/) illustrates how you should approach Azure landing zones."

The Management Group/Subscription naming is not prescriptive.  You should not direct users to place this in the  "corp" subscription. "corp" and "online" are just examples of subscription names. The Data Landing Zone should be deployed as an "Application Landing Zone" type, in a dedicated Subscription, and under a Management Group with governance appropriate to protect an internal, vs a public facing, workload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28447daa-9ef3-8942-e8c2-b67803c04ab8
* Version Independent ID: 48aeb0be-8eaf-b2b3-e933-a5ff8b2ad561
* Content: [Cloud-scale analytics data management landing zone overview - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/cloud-scale-analytics/architectures/data-management-landing-zone)
* Content Source: [docs/scenarios/cloud-scale-analytics/architectures/data-management-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/cloud-scale-analytics/architectures/data-management-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @mboswell
* Microsoft Alias: **mboswell**

**Comment by v-fearam** [comment]
#please-close
