### ISSUE TITLE
Add scenarios for Azure Firewall

### ISSUE THREAD

**Issue by prasannag6** [MicrosoftDocs/cloud-adoption-framework#937]
Guidance for Network topology with Azure Firewall in the Hub vNET will be a valuable addition (current scenarios cover only NVAs). Similar to other scenarios this should cover all traffic patterns - AVS to Internet/Spoke vNETs/On-prem via Hub vNET with Azure Firewall. And optionally Azure Firewall in vWAN Hub
References - https://blog.cloudtrooper.net/2022/05/02/azure-firewalls-sidekick-to-join-the-bgp-superheroes/
youtube.com/watch?v=8CPghVFIR9Q

**Comment by hallihan** [comment]
@prasannag6 This issue is missing the template text that points to a specific article. Can you provide a URL for the article where this suggestion applies?

**Comment by hallihan** [comment]
Without details on the article the suggestion applies to, I'm going to have to close this issue.  Feel free to open a new request with more specifics. #please-close
