### ISSUE TITLE
This sections does not mention Azure HPC Cache: "Will you need to support hybrid cloud storage for on-premises high-performance computing (HPC) workloads"

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/cloud-adoption-framework#938]
See https://docs.microsoft.com/en-us/azure/hpc-cache/nfs-blob-considerations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acd2fd4-b22c-5c11-e891-cc4993d9891e
* Version Independent ID: 1acbff98-4a94-53f5-dd45-8f22637602b4
* Content: [Review your storage options - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/storage-options)
* Content Source: [docs/ready/considerations/storage-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/storage-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@pisees - thanks for your feedback. I know it's been a while since you opened this request, but you should see that update come through shortly.

**Comment by stephen-sumner** [comment]
#please-close
