### ISSUE TITLE
Azure AD Domain Services Replica Sets

### ISSUE THREAD

**Issue by marcelkmfst** [MicrosoftDocs/cloud-adoption-framework#939]
Hi,

the statement that you can´t add domain controllers to AADDS is no longer correct:

see:

https://docs.microsoft.com/en-us/azure/active-directory-domain-services/tutorial-create-replica-set 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a03e968-7a5a-26f0-0889-e8955d6b888a
* Version Independent ID: 7d1ad01a-a793-7d44-44c2-42731a6b5d65
* Content: [Identity and access management for Azure Virtual Desktop - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/wvd/eslz-identity-and-access-management)
* Content Source: [docs/scenarios/wvd/eslz-identity-and-access-management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/wvd/eslz-identity-and-access-management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @wahidsaleemi
* Microsoft Alias: **wasaleem**

**Comment by v-fearam** [comment]
#please-close
