### ISSUE TITLE
Network Assessment Tools to Measure Bandwidth Requirements

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/cloud-adoption-framework#94]
hi,
The Microsoft Azure CAF is one of the best when compared with other Cloud Providers. however, one key area which is missing is the network assessment. How to measure current bandwidth requirements to ensure you have the right pipe to Azure? This is not touched anywhere in the documentation. Based on my search, I could not find any tools from Microsoft which can do this today. 

Appreciate any pointers, as I have a large project where i need to perform network bandwidth assessment for the customer migraiton to Azure. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63badde4-b985-a969-fc40-140da14ef383
* Version Independent ID: 8f5cf934-82ca-8f8a-fcbd-801bacdfa583
* Content: [Review your network options - Cloud Adoption Framework](https://docs.microsoft.com/en-in/azure/cloud-adoption-framework/ready/considerations/networking-options#feedback)
* Content Source: [docs/ready/considerations/networking-options.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/considerations/networking-options.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by BrianBlanchard** [comment]
It would be great to include this topic. Unfortunately, I haven't found an Azure tool that can perform this task either. Movere and other assessment tools can help. Existing on-prem network monitoring tools can also help.
