### ISSUE TITLE
Why include info guaranteed by scope?

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/cloud-adoption-framework#941]
Why does this convention include info that is guaranteed by the scope of the item? It seems that tags would be better for much of this.

For example, having region, environment, division, etc. in the name is obvious for anyone in the portal account for a given environment. All that info is available for those resources - it's PART if those resources already.

Different user types will need different data, so why not include other info in the name too, such as Azure or AWS, for multi-cloud deployments? That's rhetorical, please don't do that.

For those who like the extra info in the name, then the portal should support views that show all that info. 

My experience is that in this format, the most meaningful part of the resource name ends up being limited to something like three letters. That's not helpful.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37645 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
