### ISSUE TITLE
Decision Tree Please

### ISSUE THREAD

**Issue by SharmainePopov** [MicrosoftDocs/cloud-adoption-framework#944]
This page makes it look like the "right" way to do an Azure LZ deployment is to deploy the scenario presented in the diagram with the blue button. The level of customization provided has met the needs of only 1 very tiny customer of mine. I would like to see a decision tree here, that can direct to other avenues - bicep terraform, greenfield brownfield, component level deployment (eg client would like to grab the policy set) . FYI most customers I have are now brownfield.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6c9632-28af-7abb-d244-b0d1228e4f43
* Version Independent ID: 099f2c55-6a50-01f7-ebc4-0c1f0597f48c
* Content: [What is an Azure landing zone? - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/)
* Content Source: [docs/ready/landing-zone/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
@SharmainePopov - I'm going to close this issue. Please let us know if you have any questions. We really appreciate your feedback!
