### ISSUE TITLE
Spelling mistake?

### ISSUE THREAD

**Issue by karl-petter** [MicrosoftDocs/cloud-adoption-framework#945]
Is there a spelling mistake in the section "Security - Software deployment - Can policies be enforced to control source or code integrity?" Should the "or" be removed? If not I think source integrity needs to be explained. The term code integrity I am very familiar with and also source code integrity which is just a longer version of the same expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019319d8-467d-01af-558c-3cd461c2e91a
* Version Independent ID: 019319d8-467d-01af-558c-3cd461c2e91a
* Content: [Service enablement framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/service-enablement-framework)
* Content Source: [docs/ready/landing-zone/design-area/service-enablement-framework.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/service-enablement-framework.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by Zimmergren** [comment]
Thank you for reporting this, @karl-petter. We've refreshed the article and it will roll out later today.
#please-close
