### ISSUE TITLE
Odd wording and confusing question in Service Enablement Framework

### ISSUE THREAD

**Issue by karl-petter** [MicrosoftDocs/cloud-adoption-framework#946]
In the service enablement framework the following question is kind of strange; "Identity and access management - Authentication and access control - Is Azure-to-Internet as a Service (IaaS), or service-to-virtual-network, authentication via Azure AD?". First IaaS is not generally an abbreviation of "Internet as a Service" but rather "Infrastructure as a Service" so that section is confusing. Secondly, I have never seen outbound traffic being authenticated via an AD. Generally you use an AD to authenticate access to services not network traffic. Or what is the meaning of this question?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019319d8-467d-01af-558c-3cd461c2e91a
* Version Independent ID: 019319d8-467d-01af-558c-3cd461c2e91a
* Content: [Service enablement framework - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/service-enablement-framework)
* Content Source: [docs/ready/landing-zone/design-area/service-enablement-framework.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/service-enablement-framework.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by v-fearam** [comment]
#please-close
