### ISSUE TITLE
Resource provider namespace for "App Service environment"

### ISSUE THREAD

**Issue by garylirocks** [MicrosoftDocs/cloud-adoption-framework#947]
`Microsoft.Web/sites` is showing as "Resource provider namespace/entity" for "App Service environment".

Shouldn't it be `Microsoft.Web/hostingEnvironments` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Recommended abbreviations for Azure resource types - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by stephen-sumner** [comment]
https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/3985

**Comment by stephen-sumner** [comment]
@garylirocks - Thank you so much for catching that error and let us know! I tested it, and you're absolutely correct. I've made the update, and you should see the update shortly.
