### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by sqlsolver** [MicrosoftDocs/cloud-adoption-framework#952]
The phrase on this page, 'only one management group contains a subscription' seems to directly contradict the explanation and illustration [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/subscriptions/#mix-subscription-strategies).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b24efd3-3fda-7c73-6bf6-cfed8a3e2785
* Version Independent ID: 95e455f3-674a-7554-bfd8-d43e46c60271
* Content: [Organize and manage multiple Azure subscriptions - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/organize-subscriptions)
* Content Source: [docs/ready/azure-best-practices/organize-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/organize-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by v-fearam** [comment]
Hi @sqlsolver,

Sorry for the delay. 

The sentence 'only one management group contains a subscription' is correct. Each subscription can belong to one [management group](https://learn.microsoft.com/azure/governance/management-groups/overview).

I don’t see today any [diagram in your reference](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-subscriptions#mix-subscription-strategies), and it seems that the referenced section was deleted.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close

**Comment by sqlsolver** [comment]
The semantics are still incorrect. I understand the one-to-many
relationship between a management group and the subscriptions it
contains. *What
the existing sentence, 'only one management group contains a
subscription', conveys is that among many management groups only one
contains a subscription.* You might instead say, 'a single management group
contains one or more subscriptions' or call it a one-to-many relationship.
Either would be well understood.
