### ISSUE TITLE
Visio downloadable files for the network topologies depicted

### ISSUE THREAD

**Issue by sudharsonan** [MicrosoftDocs/cloud-adoption-framework#954]
[Enter feedback here]
Hi Team,

For a customer implementation, we are discussing these network topology blueprints and it would really help to have the viso files for this? Can you please share this with me or make it available on the website for public download?

Regards
Sudharson AN
sudharson.an@avanade.com
0615123134

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa825ef-dbe1-3147-2362-812e546b8501
* Version Independent ID: bec5cea5-7688-4911-09a2-504915e0cccd
* Content: [Enterprise-scale network topology and connectivity for Azure VMware Solution - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-network-topology-connectivity)
* Content Source: [docs/scenarios/azure-vmware/eslz-network-topology-connectivity.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-network-topology-connectivity.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @rodrigosantosms
* Microsoft Alias: **janet**

**Comment by Zimmergren** [comment]
Thank you for submitting this issue, @sudharsonan. 
There's been some updates to the relevant pages since this issue was created, and the page no longer contains a visual/diagram.
