### ISSUE TITLE
Azure Stack = Azure Stack Hub

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/cloud-adoption-framework#961]
Page needs to be updated to reflect that 'Azure Stack' on this page is really referring to 'Azure Stack Hub'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab409cd9-8447-ee37-3d3e-3d2d18333b59
* Version Independent ID: 9a97e3d5-1fd1-c6a7-4301-08d944a23fb1
* Content: [Create hybrid cloud consistency - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/hybrid-consistency)
* Content Source: [docs/ready/considerations/hybrid-consistency.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/hybrid-consistency.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by v-fearam** [comment]
Hi  @aricbernard 

Sorry for the delay. 

[Azure Stack](https://azure.microsoft.com/products/azure-stack) is a portfolio of products that extend Azure services and capabilities to your environment of choice. Azure Stack Hub is a specific flavor, and the documentation references Azure Stack as a general idea. 

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
