### ISSUE TITLE
Is this management group hierarchal reference still relevant?

### ISSUE THREAD

**Issue by mikemckanna** [MicrosoftDocs/cloud-adoption-framework#962]
[Enter feedback here]
If the ESLZ hierarchal reference is the new standard as defined in - https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/faq#how-do-we-handle-devtestproduction-workload-landing-zones-in-azure-landing-zone-architecture, then does this page conflict with that standard? The most recent recommendation is TO NOT USE MGs for separating PRODUCTION & NON-PRODUCTION subscriptions, but this pages clearly shows the legacy(?) hierarchical approach.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20d70b1a-338e-6f92-8889-0abe2a0dacae
* Version Independent ID: afbbf40d-efe7-5193-7673-ac49999ef6fb
* Content: [Subscription decision guide - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/subscriptions/)
* Content Source: [docs/decision-guides/subscriptions/index.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/decision-guides/subscriptions/index.md)
* Service: **cloud-adoption-framework**
* Sub-service: **decision-guide**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **abuck**

**Comment by v-fearam** [comment]
Hi @mikemckanna

Sorry for the delay. 
Thanks for the feedback and note that the old content was deprecated and now redirects to CAF.
#please-close
