### ISSUE TITLE
Missing abbreviation / naming convention for `Azure Maps Accounts`

### ISSUE THREAD

**Issue by dsdilpreet** [MicrosoftDocs/cloud-adoption-framework#963]
Hi there, 

[This page ](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) and [this page](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming) does not have any naming convention/abbreviation defined for [Azure Maps](https://azure.microsoft.com/en-us/products/azure-maps/) resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c22eb33-2fde-55b4-021d-e229c857e51b
* Version Independent ID: 1f767675-7d50-6ea5-b798-1323cd4a63a1
* Content: [Abbreviation examples for Azure resources - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
* Content Source: [docs/ready/azure-best-practices/resource-abbreviations.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/azure-best-practices/resource-abbreviations.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @stephen-sumner
* Microsoft Alias: **ssumner**

**Comment by stephen-sumner** [comment]
Hi @dsdilpreet. Thanks so much for the input! We added an abbreviation for Azure Maps. You should see that now. We are also working on updating the naming guidance. This will take a little bit longer. Thanks again.
