### ISSUE TITLE
Clarify this use case/scenario

### ISSUE THREAD

**Issue by SharmainePopov** [MicrosoftDocs/cloud-adoption-framework#964]
Hi please clarify the scenario - starting point on prem including platform , hardware and client use case, then solution options in Azure, then decision criteria to select options being clear about which initial components are included, and final proposed solution.  In Proposed Architecture we are talking about migrating a Windows Server to Azure. Then in Solution Review we are discussing AVD Win 10 multisession hosts.  I'm confused. 

![image](https://user-images.githubusercontent.com/34690778/194123141-a3aef833-bb1e-4277-86e9-dc4fb14a7d8f.png)

![image](https://user-images.githubusercontent.com/34690778/194123405-9251778a-996a-4d76-86e2-8d66c12c8f9a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 177be313-669c-b534-575c-27eaa49b76b8
* Version Independent ID: 33169923-9568-077a-7f12-19554a9dbb94
* Content: [Move on-premises Remote Desktop Services to Azure Virtual Desktop - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/contoso-migration-rds-to-wvd)
* Content Source: [docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/migrate/azure-best-practices/contoso-migration-rds-to-wvd.md)
* Service: **cloud-adoption-framework**
* Sub-service: **migrate**
* GitHub Login: @benstegink
* Microsoft Alias: **abuck**

**Comment by v-fearam** [comment]
#please-close
