### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sqlsolver** [MicrosoftDocs/cloud-adoption-framework#968]
You have a typo in the note RE transferring subscriptions, it should say 'for' not 'or.' See existing text below.

 Note

Transferring to another Azure AD tenant is not supported or Azure Cloud Solution Provider (CSP) subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54688c3b-0c16-6490-97c6-d92446d2553c
* Version Independent ID: 54688c3b-0c16-6490-97c6-d92446d2553c
* Content: [Subscription considerations and recommendations - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-area/resource-org-subscriptions)
* Content Source: [docs/ready/landing-zone/design-area/resource-org-subscriptions.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/landing-zone/design-area/resource-org-subscriptions.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @dominicallen
* Microsoft Alias: **doalle**

**Comment by Jehan-h20220012** [comment]
Please assign me this issue

**Comment by Jehan-h20220012** [comment]
Please merge my PR and close this issue
