### ISSUE TITLE
numbers don't match up

### ISSUE THREAD

**Issue by sk-bln** [MicrosoftDocs/cloud-adoption-framework#97]
"Two common indicators are an excess of 25,000 VMs or 10,000 vCPUs."
This is not logical. You cannot have less vCPUs than VMs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019fcb5a-b1ae-f264-d2d4-e26323d9b93c
* Version Independent ID: 75ab35b8-71d4-e97f-c93f-df715e7359f0
* Content: [Deploy a migration landing zone in Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-setup-guide/migration-landing-zone#feedback)
* Content Source: [docs/ready/azure-setup-guide/migration-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/ready/azure-setup-guide/migration-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by JanetCThomas** [comment]
AB#174956 Internal Microsoft DevOps bug

**Comment by alexbuckgit** [comment]
This issue has been resolved. Thanks!
