### ISSUE TITLE
Use ALZ MG architecture as the diagram

### ISSUE THREAD

**Issue by rkuehfus** [MicrosoftDocs/cloud-adoption-framework#971]
This

![image](https://user-images.githubusercontent.com/17836524/196204042-6906e67f-3bed-4239-8e29-00523daec03e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30485ede-c850-98ec-7279-5c8d9107dc70
* Version Independent ID: 30485ede-c850-98ec-7279-5c8d9107dc70
* Content: [Management group structure guidance in the Resource Consistency discipline - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/management-group-structure?branch=pr-en-us-3888&source=docs)
* Content Source: [docs/govern/resource-consistency/management-group-structure.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/resource-consistency/management-group-structure.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
It looks like this was already addressed in the PR branch
