### ISSUE TITLE
Should we have guidance to locate ungoverned along with Orphaned resources?

### ISSUE THREAD

**Issue by rkuehfus** [MicrosoftDocs/cloud-adoption-framework#972]
The guidance for orphaned resources is good but we should also call out you may have ungoverned resources that are not orphaned just ungoverned.  

P0 - bring all subscriptions and resources into governance that are ungoverned.  Help the customer locate these.
P1 - bring all orphaned subscriptions and resources into governance or decommission them.  Help the customer locate these.  

We should define what we consider a ungoverned subscription and resource.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e12b36c-a12d-2e9c-88db-c9e6f7edecbe
* Version Independent ID: 5e12b36c-a12d-2e9c-88db-c9e6f7edecbe
* Content: [Resource consistency in the Cloud Adoption Framework for Azure - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/overview?branch=pr-en-us-3888)
* Content Source: [docs/govern/resource-consistency/overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/resource-consistency/overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37619 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
