### ISSUE TITLE
Include Organize and Secure methodologies to operating model

### ISSUE THREAD

**Issue by mikemckanna** [MicrosoftDocs/cloud-adoption-framework#974]
When discussing the CAF with customers, I've used the attached images to demonstrate how the Strategy, Plan, Ready, & Adopt methodologies are 'iterative' processes which the organization should perform with each workload migration. The 'continuous' activities are Organize, Govern, Manage, and Secure which the organization will perform regardless of the workload migration process. The second image demonstrates how the CAF methodologies align to the organizational (Business), Platform (Landing Zone), and Workload (Application/Service) domains. This approach is the basis of the new Defense CAF scenario in review for CAF publication.
Highly recommend inclusion of these concepts into the operating model discussion.
![CCx FED CAF - Operating Model 01](https://user-images.githubusercontent.com/88058048/196469072-99077233-8930-4b8e-bcf0-63ef724579de.png)
![CCx FED CAF - Operating Model 02](https://user-images.githubusercontent.com/88058048/196469077-bf74f476-3b87-4899-92dd-42d9227a4e9b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb736919-3318-849a-f18d-0ebe09936203
* Version Independent ID: 7970d251-13ec-f1e1-8102-ffdf9346b88e
* Content: [Define your cloud operating model - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/operating-model/define)
* Content Source: [docs/operating-model/define.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/operating-model/define.md)
* Service: **cloud-adoption-framework**
* Sub-service: **general**
* GitHub Login: @BrianBlanchard
* Microsoft Alias: **brblanch**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37617 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
