### ISSUE TITLE
Include WAF best practices for on-premise to Azure application traffic

### ISSUE THREAD

**Issue by smithers54** [MicrosoftDocs/cloud-adoption-framework#975]
Based on the Zero-Trust model, on-premise inbound traffic over vpn or ExR should be processed by a WAF either on-premise or in Azure. Can you please add literature that reflects this?

**Comment by hallihan** [comment]
@smithers54 This issue is missing the template text that points to a specific article. Can you provide a URL for the article where this suggestion applies?

**Comment by hallihan** [comment]
Without details on the article the suggestion applies to, I'm going to have to close this issue. Feel free to open a new request with more specifics. #please-close
