### ISSUE TITLE
Update the LZ AKS accelerator

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/cloud-adoption-framework#977]
Some concepts should be updated after the last features release by PG over the last six months

network: talk about CNI overlay or dynamic IP allocation for CNI
identity: it recommends to use pod identity which is deprecated vs workload identity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65eff0a9-95f9-6709-b4e5-93b48cfed374
* Version Independent ID: ba888d87-6a30-4916-14c8-9a9207f08442
* Content: [Identity and access management considerations for AKS - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/aks/identity-and-access-management)
* Content Source: [docs/scenarios/app-platform/aks/identity-and-access-management.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/app-platform/aks/identity-and-access-management.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @TomGeske
* Microsoft Alias: **thomasge**

**Comment by v-fearam** [comment]
#please-close
