### ISSUE TITLE
User Story 22783- Missing References To ALZ-Bicep

### ISSUE THREAD

**Issue by lachaves** [MicrosoftDocs/cloud-adoption-framework#980]
You want to use only Azure native tools. Your organization might have prior ARM template deployment experience.

Propossed: You want to use only Azure native tools. Your organization might have prior ARM or Bicep template deployment experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b81454c5-f535-1421-5e0c-d686310d10ee
* Version Independent ID: b81454c5-f535-1421-5e0c-d686310d10ee
* Content: [Infrastructure as Code - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/infrastructure-as-code)
* Content Source: [docs/ready/considerations/infrastructure-as-code.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/ready/considerations/infrastructure-as-code.md)
* Service: **cloud-adoption-framework**
* Sub-service: **ready**
* GitHub Login: @emguzman13
* Microsoft Alias: **emguzman**

**Comment by v-fearam** [comment]
#please-close
