### ISSUE TITLE
User Story 22783- Missing References To ALZ-Bicep

### ISSUE THREAD

**Issue by lachaves** [MicrosoftDocs/cloud-adoption-framework#981]
Infrastructure configuration, such as using an Azure Resource Manager template to deploy an
Azure Network Security Group and createsecurity group rules.

Propossed:
Infrastructure configuration, such as using an Azure Resource Manager or Bicep template to deploy an
Azure Network Security Group and createsecurity group rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54b5a18b-95cd-d0ea-f7fe-4dd37cda4ac5
* Version Independent ID: 54b5a18b-95cd-d0ea-f7fe-4dd37cda4ac5
* Content: [Development security strategy - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/secure/development-security-strategy-overview)
* Content Source: [docs/secure/development-security-strategy-overview.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/secure/development-security-strategy-overview.md)
* Service: **cloud-adoption-framework**
* Sub-service: **secure**
* GitHub Login: @mpvenables
* Microsoft Alias: **mas**

**Comment by v-fearam** [comment]
#please-close
