### ISSUE TITLE
Feedback request: Naming overview

### ISSUE THREAD

**Issue by Springstone** [MicrosoftDocs/cloud-adoption-framework#990]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

TODO #1. Naming convention does not help with cost recovery. Cost recovery works best at a subscription level as there are services that cannot be tagged (like Defender for Cloud, ADO, etc) - for cost recovery purposes, dedicate subscriptions to business units for example. 
It absolutely helps with management and security. Having a consistent naming convention for all resources, immediately highlights the resource "impacted", and ideally proper tagging of owners/contacts allows for rapid escalation/engagement (this one is so hard to get right, as people/owners change).
Also, resources should not need to have the environment name in them (so proper subscription naming convention and management group hierarchy is important). Separation of Prod, UAT, SomethingElse, Dev should be done at management group and subscription levels (ie, dedicated subscription for each environment). 

Helping customers define the naming convention is super, I really like and encourage wider adoption of the Azure Naming Tool.

Enforcement will be difficult (some customers will have wildly different naming conventions) but encourage a better auditing solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6847c584-e823-5a8a-d86a-282fd6718aea
* Version Independent ID: 6847c584-e823-5a8a-d86a-282fd6718aea
* Content: [Naming guidance for resources in the Resource Consistency discipline - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/naming?branch=pr-en-us-3888)
* Content Source: [docs/govern/resource-consistency/naming.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/resource-consistency/naming.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
@Springstone - looks like this was feedback on a review branch. In the future, please provide feedback via the PR comment thread. If any of these issues are still outstanding on the published article, reach out to the content author or open a new feedback item. #please-close
