### ISSUE TITLE
Feedback requested: Tagging overview

### ISSUE THREAD

**Issue by Springstone** [MicrosoftDocs/cloud-adoption-framework#991]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Generally, this content is fine, however, I would suggest for tagging we come up with a top 10 list of tags that are recommended (based on what all enterprise customers generally tag) and highlight/document/showcase whatever (ie in the portal drop down, show the recommended tags to make it clearer) to make them visible. Issues I've seen at S500s just capturing owners consistently: owner, Owner, owners, Owners, ownership, owningTeam, business owner, technical owner, etc. I would encourage making some mandatory, like owner/contact person/group from a security incident (or cost recovery) perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3f3e0d4-1160-9539-a8a0-bb81ee083966
* Version Independent ID: d3f3e0d4-1160-9539-a8a0-bb81ee083966
* Content: [Tagging guidance in the Resource Consistency discipline - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/tagging?branch=pr-en-us-3888)
* Content Source: [docs/govern/resource-consistency/tagging.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/resource-consistency/tagging.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
@Springstone - looks like this was feedback on a review branch. In the future, please provide feedback via the PR comment thread. If any of these issues are still outstanding on the published article, reach out to the content author or open a new feedback item. #please-close
