### ISSUE TITLE
Feedback requested: Business constraints

### ISSUE THREAD

**Issue by Springstone** [MicrosoftDocs/cloud-adoption-framework#992]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Redundant storage: Geo-redundant is not always required. Business data maybe, logs not so much. You may want to quantify value with cost on this topic. Needs a lot more information around use cases (LRS vs ZRS, vs GRS vs RA-GRS, etc.). Maybe require GRS for storage with a certain tag or 'prod' in the name?

For the monitoring section, the Windows and Linux rules are mis-matched. Under Linux section is Windows policies, and vice versa. (expect Windows to be first in the list :)). Also, the Linux policies don't work very well in Enterprise for various reasons - but that is not relevant).
Key point to review is security versus operations logging. Should not be the same LA workspace, different teams need access to different levels of data. I would add descriptions around operational (metrics, performance, ops) logging, and perhaps separate security logging (diagnostic settings, audits, activity logs) to another workspace that we could/should enable Sentinel on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8172a3fd-147d-3e62-3f3e-d2eb4356a452
* Version Independent ID: 8172a3fd-147d-3e62-3f3e-d2eb4356a452
* Content: [Managing business constraints in the Resource Consistency discipline - Cloud Adoption Framework](https://review.learn.microsoft.com/en-us/azure/cloud-adoption-framework/govern/resource-consistency/business-constraints?branch=pr-en-us-3888)
* Content Source: [docs/govern/resource-consistency/business-constraints.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/govern/resource-consistency/business-constraints.md)
* Service: **cloud-adoption-framework**
* Sub-service: **govern**
* GitHub Login: @RobBagby
* Microsoft Alias: **robbag**

**Comment by hallihan** [comment]
@Springstone - looks like this was feedback on a review branch. In the future, please provide feedback via the PR comment thread. If any of these issues are still outstanding on the published article, reach out to the content author or open a new feedback item. #please-close
