### ISSUE TITLE
Areas to make guidance more specific

### ISSUE THREAD

**Issue by sblair01** [MicrosoftDocs/cloud-adoption-framework#997]
Hello - While I find the content useful, I think there are opportunities to help users find consider, specific and applicable options. In its current state, this document hinders customers from finding what they need to deploy quickly and borders being "too general". I've listed some feedback below:

Second bullet under **automated deployment** talks about planning for ip-space but then takes you to the all up ESLZ Networking page which is too long to read just to address this one point. What is the recommendation to for overlapping ranges? Is there automation? If not, it may not belong in an automation section. 

That last two bullet points in this section say the what, but where do users find the how?

**Automated Connectivity**
Nothing in this section tells me how to automated connectivity. Suggestion is to simply say, you can connect automatically to a SDDC using the automation found "here" and reference the github page with networking scenarios. 

**Automated Scale**
The content here is very good, but similar feedback as above. Instead of just considerations and recommendations, maybe a third bullet for implementation where we list the options. 

**Azure Integration**
I don't understand this section. All of our design area guidance and implementation options are around integration options. While I t think it's important to have all up knowledge, that can be handled in an ALZ engagement. Pointing them to that doc doesn't help them with AVS. I would opt to remove this section altogether. 

**DevOps Approach**

"For more information, see the enterprise-scale landing zone platform automation and DevOps documentation." - This links to the section in the next line. Mine as well just say "see below"

**VMware platform automation**

Just my two cents here but I think this should be a subsection. This is the first thing I was looking for, and either had to read all the way to the bottom or scroll down. 

**Implementation Options**
There are no options for deployment anywhere. I think there is a lot of growth opportunity in this section. See the all up guide for an example: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options

Language: Documents should have more definitive language and avoid "If" and "You can."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed4fc81d-ca72-58f0-d869-60d5e4890bd2
* Version Independent ID: 3c4680f2-d3be-b554-079f-d3de36076e77
* Content: [Enterprise-scale platform automation for Azure VMware Solution - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-platform-automation-and-devops)
* Content Source: [docs/scenarios/azure-vmware/eslz-platform-automation-and-devops.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-platform-automation-and-devops.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @ScottHolden
* Microsoft Alias: **scholden**

**Comment by skabou** [comment]
Thank you for your feedback. We have created internal ticket 37593 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
