### ISSUE TITLE
Organization of page

### ISSUE THREAD

**Issue by sblair01** [MicrosoftDocs/cloud-adoption-framework#998]
The content on this page is really good and the new flow chart is a lot easier to follow. My only feedback is sometimes the content is hard to find if quickly looking for information. 

The design recommendations and considerations are fine, but there should also be a preliminary link for customers that want to go straight into implementation and read later. 

For example, the last 5 or so bullets Under Disaster Recovery recommendations are all about IP Addressing, so maybe that should be a sub-section or highlighted. 

The last bullet on the page points to ESLZ networking guidance for global reach instead of a specific page for global reach connectivity

I think there should be a summary section with a how-to get started. Some of the links like the zerto implementation are already there, but just needs to be easier to sort out the next steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db7abe28-b183-34bd-f9bf-84e135a41ad3
* Version Independent ID: c62c7e3e-8b1a-4db8-a40c-22098d28b8ed
* Content: [Enterprise-scale BCDR for Azure VMware Solution - Cloud Adoption Framework](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery#feedback)
* Content Source: [docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/main/docs/scenarios/azure-vmware/eslz-business-continuity-and-disaster-recovery.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @sonmitt
* Microsoft Alias: **janet**

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37591 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
